# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
The forward-pass guest<->host surface (submits PTIR container bytes). The WIT
surface family is named `forward*`; PTIR remains the name of the container
byte format it ships.

Layering: the guest traces a pass -> canonical PTIR container bytes
(pie_sampling_ir::ptir). WIT cannot carry closures, so the container bytes
stay the wire artifact -- but everything the author manipulates (channels,
working sets, the pass, the pipeline) crosses the boundary as a first-class
resource, mirroring the ptir tracing DSL.

THREE INTERFACES, ONE PER STATE SEMANTICS (forward_refactor.md D1):

  `forward`            paged, per-token, reversibly discardable KV only
  `forward-recurrent`  irreversibly folded recurrent state only
  `forward-hybrid`     both, in the same forward

The split is over STATE SEMANTICS, not model family: `architecture()` is an
open, fast-growing string set, while this taxonomy is closed. `model.pass-kind()`
selects the interface; constructing the wrong one errors immediately.

The split is also a CORRECTNESS GATE. Attention-only algorithms (H2O, SnapKV,
TOVA, Quest) are semantically wrong on a folded recurrent state -- evicting KV
does not undo the fold -- and until now nothing caught it. They can no longer
name a hybrid model's pass type.

All three deliberately DUPLICATE `embed` / `readout` / `program` / `submit`
and their geometry records rather than sharing a `pass-body` (D3): WIT
duplication does not force implementation duplication (the host keeps one
private `PassCore`), and full separation makes cross-kind states
unrepresentable instead of runtime-guarded. Adding a field to one interface's
record must never move another's ABI.
THIS FILE: pure attention. llama_like, gemma*, mixtral, kimi, deepseek_v4,
glm5, qwen3_vl, csm. Valid only when `model.pass-kind()` == attention.

Legal stages: prologue, on_attn_proj, on_attn, epilogue.

The resource name `forward-pass` is shared by all three interfaces: WIT
scopes resource names to their interface, so this is legal and the generated
bindings differ only by module path. That is what collapses guest migration
to a single changed `use` line.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import pipeline
from ..imports import channel
from ..imports import working_set
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter

@dataclass
class KvGeometry:
    """
    Attention geometry. Every input is an individual channel; the record
    exists so the whole group can be handled as a unit (and, in
    `forward-hybrid`, made optional as a unit). `none` on `mask` omits the
    PTIR AttnMask port; `some(mask)` binds that channel to it.
    
    Declared separately per interface ON PURPOSE (D8/D3).
    """
    readable_pages: working_set.PageSpan
    writable_pages: working_set.PageSpan
    kv_len: channel.Channel
    pages: channel.Channel
    page_indptr: channel.Channel
    w_slot: channel.Channel
    w_off: channel.Channel
    positions: channel.Channel
    mask: Optional[channel.Channel]

class ForwardPass:
    """
    A forward-pass builder. Construction is empty; descriptor resources are
    attached explicitly, then `program` supplies the traced container.
    """
    
    def __init__(self) -> None:
        raise NotImplementedError

    def attention(self, kv: working_set.KvWorkingSet, geom: KvGeometry) -> None:
        """
        State binding. REQUIRED -- a pass with no attention binding is not
        submittable.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def embed(self, tokens: channel.Channel, indptr: channel.Channel) -> None:
        """
        Bind embedding token ids and CSR row indptr. Both are channels.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def readout(self, indices: channel.Channel) -> None:
        """
        Bind an optional readout-index channel separately from embedding.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def program(self, container_bytes: bytes, channels: List[channel.Channel]) -> None:
        """
        Attach canonical PTIR bytes and channel handles in dense declaration
        order. Validation uses the engine-owned ModelProfile, and now also
        rejects any stage this interface does not admit -- see the per-file
        note on which stages are legal.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



def submit(on: pipeline.Pipeline, slots: List[Optional[ForwardPass]]) -> None:
    """
    Submit ONE FRAME on `on`: exactly `model.frame-size()` ordered slots.
    Slot i executes in wave i of the frame; the composer never moves a
    slot to another wave. `none` is a no-op for that wave. The slot list
    may repeat the same handle (a plain decode frame is the same pass in
    every slot) and may be heterogeneous (prefill chunks in the earliest
    slots, decode in the rest). A frame is one call, not a resource.
    
    Submission validation (deterministic, structural — never timing):
    - `slots` must hold exactly `frame-size()` entries with at least one
      non-no-op slot.
    - Every host-writer channel bound by the frame's non-no-op slots must
      be *staged* (it holds at least as many staged cells as the frame's
      fires will consume), *device-advanced* (the program contains an
      advance rule for it), or *latest-value* (the program only reads it —
      a control word; one committed cell suffices and host `set` may
      replace it at any time).
    - Per host-reader channel, occupancy plus cells reserved by accepted
      unsettled frames plus the cells this frame will write must fit the
      capacity — overflow is prevented here, never by back-pressure.
    
    Each non-no-op slot prepares and enqueues RUN-AHEAD in slot order,
    including passes that bind recurrent state: an RS mapping publishes at
    prepare, so slot i+1 sees slot i's decision without waiting for it to
    execute, and the state's contents are ordered by the stream. The first
    submit of a pass binds seeds; steady-state resubmits carry the
    identity hash + instance only. Staged host-writer puts coalesce into
    the slot fires in order.
    
    The result covers validation/preparation/enqueue only. A fire that
    fails AFTER submit poisons the pass's host-reader channels (surfaced
    at `take`/`read` with the fire's error) and fails the pass — further
    submits of it error with the root cause. End-of-stream is a PIPELINE
    event, not a fire attribute: call `pipeline.close` after the last
    submit.
    
    Raises: `componentize_py_types.Err(wit_world.imports.str)`
    """
    raise NotImplementedError
