# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter

class Grammar:
    """
    Describes the structure that the LLM output must conform to.
    Constructed via static factory methods for each supported format.
    """
    
    @classmethod
    def from_json_schema(cls, schema: str) -> Self:
        """
        Construct from a JSON Schema string.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    @classmethod
    def json(cls) -> Self:
        """
        Construct a built-in free-form JSON grammar (any valid JSON).
        """
        raise NotImplementedError
    @classmethod
    def from_regex(cls, pattern: str) -> Self:
        """
        Construct from a regular expression pattern.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    @classmethod
    def from_ebnf(cls, ebnf: str) -> Self:
        """
        Construct from an EBNF grammar string.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def to_string(self) -> str:
        """
        Debug representation of the grammar. Format is unspecified and
        may differ across grammar kinds; do not parse.
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class Matcher:
    """
    Stateful matcher that walks the grammar automaton as tokens are
    accepted, producing a bitmask of valid next tokens at each step.
    The host compiles and may cache the grammar when its resource is
    constructed; matcher construction reuses that compiled result.
    """
    
    def __init__(self, grammar: Grammar) -> None:
        """
        Create a new matcher from a grammar.
        """
        raise NotImplementedError

    def accept_tokens(self, token_ids: List[int]) -> None:
        """
        Accept one or more decoded tokens, advancing the matcher state.
        Returns an error if any token violates the grammar.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def mask(self) -> List[int]:
        """
        The packed allowed-token bitmask at the current position: a
        `[ceil(vocab/32)]` u32 array where bit `j` (word `j/32`, bit `j%32`)
        is 1 iff token `j` is allowed, 0 if disallowed. Applied in-program
        by the sampler's `mask-apply` op (the de-hardwired grammar mask
        channel); multiple constraints compose by word-wise bitwise-AND
        host-side. Replaces the removed BRLE `next-token-logit-mask`.
        """
        raise NotImplementedError
    def is_terminated(self) -> bool:
        """
        Check whether the matcher has reached a terminal state.
        """
        raise NotImplementedError
    def reset(self) -> None:
        """
        Reset the matcher to its initial state so it can be reused.
        """
        raise NotImplementedError
    def fork(self) -> Self:
        """
        Split off an independent matcher positioned exactly where this one
        is. The two matchers do not share state afterwards. Search
        algorithms that branch -- beam search, tree drafting, speculative
        decoding -- need one grammar state per live branch; without this,
        a branch has to be replayed token by token from a fresh matcher.
        """
        raise NotImplementedError
    def rollback(self, num_tokens: int) -> None:
        """
        Undo the last `num-tokens` accepted tokens, returning the matcher
        to the state it had before them. Values above
        `rollback-capacity` undo as much history as is retained. This is
        the reject path of speculative decoding: the drafter proposes k
        tokens, the verifier accepts j < k, and the matcher must give back
        the other k - j.
        """
        raise NotImplementedError
    def rollback_capacity(self) -> int:
        """
        How many accepted tokens `rollback` can still undo. History is
        bounded, so a caller that drafts deeply should check this rather
        than assume an unlimited undo log.
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



