# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
The pipeline is an ordering domain, not the owner of any working set
(kv_refact.md). Every command on every pipeline enters the single
per-driver sequencer queue in program order and is linearized there; a
pipeline names the ordering domain a command belongs to. Device-visible
working-set mutations (`working-set.wit`) and forward submissions
(`forward.wit`) take `borrow<pipeline>`.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter

class Pipeline:
    """
    A run-ahead ordering domain. Commands on the same pipeline execute in
    deterministic submission order; different pipelines promise nothing
    beyond the sequencer's linearization. Creating a working set on one
    pipeline and firing it from another is safe by construction.
    """
    
    def __init__(self) -> None:
        raise NotImplementedError

    def close(self) -> None:
        """
        End the stream and tear down its ordering domain. The scheduler
        stops awaiting this pipeline immediately; every fire already
        submitted (queued, preparing, or dispatched) still runs to
        settlement in submission order and its outputs remain take-able.
        Later submissions fail. Work never submitted is simply absent.
        Resource drop has exactly these semantics.
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



