"""Worker entry for the ggml driver.

Lifecycle:
  * Resolves the `pie_driver_portable` binary, the HF snapshot dir, and writes a
    startup TOML the binary consumes.
  * Spawns the binary and waits for its `READY {json}` line on stdout.
  * Reports the resulting `DriverCapabilities` to the engine via `ready_queue`.
  * Serves the control-plane RPC channel (ping / page-swap / adapter ops). The
    fast path (`fire_batch`) is served directly by the binary on `/pie_shmem`;
    pie_runtime is the client.

The binary loads HF safetensors directly (no GGUF). Page allocation is
owned by Pie's runtime — the binary honors whatever page IDs arrive in
each BPIQ request.
"""

from __future__ import annotations

import json
import os
import selectors
import shutil
import signal
import socket
import struct
import subprocess
import threading
import time
import traceback
from pathlib import Path

import msgpack

from pie._runtime import RpcServer
from pie.capabilities import DriverCapabilities

from .config import PortableDriverConfig


# =============================================================================
# Topology
# =============================================================================


def calculate_topology(world_size: int, tp_degree: int) -> list[list[int]]:
    """Server-driven helper: partition `world_size` ranks into TP groups.

    The ggml driver only supports tp_degree=1 in v1 (multi-rank lands
    post-v1). We still implement the helper so `pie/server.py` can call
    it uniformly and surface a clear error if the user asks for TP>1.
    """
    if world_size % tp_degree != 0:
        raise ValueError(
            f"world_size ({world_size}) must be divisible by tp_degree ({tp_degree})"
        )
    num_groups = world_size // tp_degree
    return [
        list(range(g * tp_degree, (g + 1) * tp_degree))
        for g in range(num_groups)
    ]


# =============================================================================
# Binary discovery
# =============================================================================


def _resolve_binary(override: str) -> Path:
    """Find `pie_driver_portable`. Checks override, env var, $PATH, then a sibling
    build tree. Raises with a useful hint if nothing works."""
    if override:
        p = Path(override).expanduser()
        if p.is_file() and os.access(p, os.X_OK):
            return p
        raise FileNotFoundError(
            f"binary_path={override!r} is not an executable file"
        )

    if env := os.environ.get("PIE_PORTABLE_DRIVER_BIN"):
        p = Path(env).expanduser()
        if p.is_file() and os.access(p, os.X_OK):
            return p

    if which := shutil.which("pie_driver_portable"):
        return Path(which)

    # Fall back to a relative search: this file lives at
    # <repo>/pie/src/pie_driver_portable/worker.py, so the build tree is at
    # <repo>/driver/portable/build/bin/pie_driver_portable.
    candidate = (Path(__file__).resolve().parents[3]
                 / "driver" / "portable" / "build" / "bin" / "pie_driver_portable")
    if candidate.is_file() and os.access(candidate, os.X_OK):
        return candidate

    raise FileNotFoundError(
        "pie_driver_portable binary not found. Build it via\n"
        "    cd driver/portable && cmake -S . -B build -G Ninja && cmake --build build\n"
        "or set $PIE_PORTABLE_DRIVER_BIN to its path."
    )


# =============================================================================
# TOML emission
# =============================================================================


def _write_startup_toml(
    *,
    driver_cfg: PortableDriverConfig,
    snapshot_dir: str,
    aux_socket_path: str,
    out_path: Path,
    group_id: int = 0,
) -> None:
    """Emit the binary's startup config. Format matches `driver/portable/dev.toml`."""
    # Per-DP-replica shmem name; mirrors runtime/src/device.rs::shmem_name
    # (`/pie_shmem_g{idx}`). Hardcoding `/pie_shmem` collides across replicas.
    shmem_name = f"/pie_shmem_g{group_id}"
    lines = [
        "# Auto-generated by pie_driver_portable; do not edit.",
        "",
        "[shmem]",
        # Must match runtime/src/device.rs SHMEM_* constants — resp_buf is
        # 4 MiB on the runtime side, not 1 MiB; mismatched sizes silently
        # break the channel and the runtime sends nothing.
        f'name = "{shmem_name}"',
        "num_slots = 8",
        "req_buf = 4194304",
        "resp_buf = 4194304",
        "spin_us = 0",
        "",
        "[model]",
        f'hf_path = "{snapshot_dir}"',
        f"n_gpu_layers = {driver_cfg.n_gpu_layers}",
        f"n_ctx = {driver_cfg.n_ctx}",
        "",
        "[batching]",
        f"kv_page_size = {driver_cfg.kv_page_size}",
        f"max_num_kv_pages = {driver_cfg.max_num_kv_pages}",
        f"max_batch_tokens = {driver_cfg.max_batch_tokens}",
        f"max_batch_size = {driver_cfg.max_batch_size}",
        f"cpu_pages = {driver_cfg.cpu_pages}",
        "",
        "[aux_ipc]",
        f'socket_path = "{aux_socket_path}"',
        "",
    ]
    out_path.write_text("\n".join(lines))


# =============================================================================
# Aux IPC client — marshal copy_* RPCs into binary commands
# =============================================================================
#
# Wire format mirrors `driver/portable/src/aux_ipc.hpp`:
#   header (24 bytes, LE):
#     u32 magic = 0x41454950 ('PIEA')
#     u32 method (1=d2h, 2=h2d, 3=d2d, 4=h2h)
#     u32 n_pages
#     u32 reserved
#     u64 req_id
#   payload: n_pages × { u32 src; u32 dst; }
#   ack (16 bytes, LE):
#     u32 magic = 0x4B414950 ('PIAK')
#     u32 status
#     u64 req_id


_AUX_MAGIC      = 0x41454950
_AUX_ACK_MAGIC  = 0x4B414950
_AUX_HDR        = struct.Struct("<IIIIQ")    # 24 bytes (magic, method, n_pages, reserved, req_id)
_AUX_PAIR       = struct.Struct("<II")       # 8 bytes
_AUX_ACK        = struct.Struct("<IIQ")      # 16 bytes (magic, status, req_id)
_AUX_LOAD_HDR   = struct.Struct("<QII")      # 16 bytes (adapter_id, path_len, reserved)
_METHOD_LOAD_ADAPTER = 5


class _AuxClient:
    """Synchronous unix-socket client for the binary's aux IPC server.
    Single-threaded — guarded by a lock since the wrapper's RPC loop may
    dispatch handlers concurrently in principle."""

    def __init__(self, socket_path: str):
        self._path = socket_path
        self._sock = None
        self._lock = threading.Lock()
        self._next_req = 1

    def call(self, method: int, pairs: list[tuple[int, int]]) -> None:
        payload = b"".join(_AUX_PAIR.pack(s, d) for (s, d) in pairs)
        self._send_command(method, payload, n_pages=len(pairs))

    def load_adapter(self, adapter_id: int, file_path: str) -> None:
        """Send a LoadAdapter command pointing at an on-disk safetensors
        file. The binary reads + parses the file and registers the
        adapter under `adapter_id`."""
        path_bytes = file_path.encode("utf-8")
        sub = _AUX_LOAD_HDR.pack(adapter_id, len(path_bytes), 0)
        self._send_command(_METHOD_LOAD_ADAPTER, sub + path_bytes, n_pages=0)

    def close(self) -> None:
        with self._lock:
            if self._sock is not None:
                try:
                    self._sock.close()
                except Exception:
                    pass
                self._sock = None

    # -------------------------------------------------------------------------
    # Internals
    # -------------------------------------------------------------------------

    def _send_command(self, method: int, payload: bytes, n_pages: int) -> None:
        """Send one aux command and read its ack. Holds `self._lock` for the
        full round-trip so concurrent callers serialize cleanly."""
        with self._lock:
            self._connect()
            req_id = self._next_req
            self._next_req += 1
            hdr = _AUX_HDR.pack(_AUX_MAGIC, method, n_pages, 0, req_id)
            self._sock.sendall(hdr + payload)
            self._read_ack(req_id)

    def _connect(self) -> None:
        if self._sock is not None:
            return
        s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        # Retry briefly: the binary's listener may take a few ms to bind.
        deadline = time.monotonic() + 5.0
        last_err = None
        while time.monotonic() < deadline:
            try:
                s.connect(self._path)
                self._sock = s
                return
            except (FileNotFoundError, ConnectionRefusedError) as e:
                last_err = e
                time.sleep(0.05)
        raise RuntimeError(f"aux IPC connect failed: {last_err}")

    def _recv_full(self, n: int) -> bytes:
        buf = bytearray()
        while len(buf) < n:
            chunk = self._sock.recv(n - len(buf))
            if not chunk:
                raise RuntimeError("aux IPC: peer closed during recv")
            buf.extend(chunk)
        return bytes(buf)

    def _read_ack(self, req_id: int) -> None:
        ack = self._recv_full(_AUX_ACK.size)
        magic, status, ack_req = _AUX_ACK.unpack(ack)
        if magic != _AUX_ACK_MAGIC:
            raise RuntimeError(f"aux IPC: bad ack magic 0x{magic:08x}")
        if ack_req != req_id:
            raise RuntimeError(
                f"aux IPC: ack req_id mismatch ({ack_req} != {req_id})")
        if status != 0:
            raise RuntimeError(f"aux IPC: command failed (status={status})")


# =============================================================================
# READY handshake
# =============================================================================


class _ReadyTimeout(RuntimeError):
    pass


def _wait_for_ready(proc: subprocess.Popen, timeout_s: float) -> dict:
    """Read lines from `proc.stdout` until a `READY {json}` arrives. Anything
    else is forwarded to stderr so the user sees binary log output during
    startup. Raises if the binary exits, times out, or emits malformed JSON."""
    if proc.stdout is None:
        raise RuntimeError("subprocess has no stdout pipe")

    sel = selectors.DefaultSelector()
    sel.register(proc.stdout, selectors.EVENT_READ)

    start = time.monotonic()

    while True:
        if proc.poll() is not None:
            raise RuntimeError(
                f"pie_driver_portable exited before READY (rc={proc.returncode})"
            )

        elapsed = time.monotonic() - start
        if elapsed > timeout_s:
            raise _ReadyTimeout(f"no READY within {timeout_s:.1f}s")

        events = sel.select(timeout=min(0.5, timeout_s - elapsed))
        if not events:
            continue

        line = proc.stdout.readline()
        if not line:
            continue
        line = line.rstrip("\n")

        if line.startswith("READY "):
            return json.loads(line[len("READY "):])

        # Pre-READY chatter — pass through so users see startup progress.
        print(f"[pie_driver_portable] {line}")


def _stream_stderr(proc: subprocess.Popen) -> None:
    """Relay the binary's stderr into our own stderr (best-effort)."""
    if proc.stderr is None:
        return
    for raw in iter(proc.stderr.readline, ""):
        if not raw:
            break
        print(f"[pie_driver_portable] {raw.rstrip()}")


# =============================================================================
# RPC dispatch (control plane only)
# =============================================================================


def _make_methods(aux: "_AuxClient | None"):
    """Returns the cold-path method table. The fast path (`fire_batch`) is
    served by the binary directly on `/pie_shmem`; we never see it here.

    `aux` is the connection to the binary's aux IPC server when M7 page
    swap is enabled. None → page-copy RPCs return success as a no-op (this
    is safe for inferlets that don't actually depend on the data being
    copied; the runtime tolerates `swap_pool_size = 0` in capabilities)."""

    def _ping(**_):
        return {"ok": True}

    def _query(**_):
        return {"driver": "portable", "implemented": False}

    def _unimplemented(name, milestone):
        def stub(**_):
            raise RuntimeError(
                f"{name!r} is not yet implemented in ggml driver "
                f"(planned for {milestone})"
            )
        return stub

    def _noop_ok(**_):
        return {"ok": True}

    # Method ID constants — must match `driver/portable/src/aux_ipc.hpp`.
    METHOD_D2H, METHOD_H2D, METHOD_D2D, METHOD_H2H = 1, 2, 3, 4

    def _load_adapter_handler(client: "_AuxClient | None"):
        """Wrapper-side load_adapter: write the LoRA bytes to a temp file
        and forward the path to the binary's adapter loader."""
        def handler(**kwargs):
            if client is None:
                raise RuntimeError(
                    "load_adapter requires the aux IPC channel — "
                    "ensure the binary supports M7 wiring")
            adapter_ptr = int(kwargs["adapter_ptr"])
            data = kwargs.get("adapter_data") or kwargs.get("data") or b""
            if isinstance(data, list):
                data = bytes(data)
            tmp_dir = Path(os.environ.get("PIE_HOME", Path.home() / ".pie"))
            tmp_dir.mkdir(parents=True, exist_ok=True)
            tmp_path = tmp_dir / f"portable-lora-{adapter_ptr}.safetensors"
            tmp_path.write_bytes(bytes(data))
            client.load_adapter(adapter_ptr, str(tmp_path))
            return {"ok": True, "adapter_ptr": adapter_ptr}
        return handler

    def _copy_via_aux(method: int, src_key: str, dst_key: str):
        """Build a handler that translates kwargs → aux IPC command."""
        def handler(**kwargs):
            if aux is None:
                # No aux IPC — accept silently (degraded mode).
                return {"ok": True}
            srcs = list(kwargs[src_key])
            dsts = list(kwargs[dst_key])
            if len(srcs) != len(dsts):
                raise ValueError(
                    f"copy: src/dst length mismatch ({len(srcs)} vs {len(dsts)})")
            aux.call(method, list(zip(srcs, dsts)))
            return {"ok": True}
        return handler

    return {
        "ping": _ping,
        "query": _query,
        "fire_batch": _unimplemented("fire_batch", "shmem fast path"),  # defensive
        "embed_image": _unimplemented("embed_image", "post-v1"),
        "initialize_adapter": _unimplemented("initialize_adapter",
                                              "post-v1 (CMAES)"),
        "update_adapter": _unimplemented("update_adapter",
                                          "post-v1 (CMAES)"),
        "save_adapter": _unimplemented("save_adapter", "post-v1"),
        "load_adapter": _load_adapter_handler(aux),
        # Page-copy / swap RPCs. When the binary's aux IPC server is up
        # (cpu_pages > 0), forward each pair-list call to it; the binary
        # executes the actual ggml_backend_tensor_get/set per page per
        # layer. swap_out/in_pages share the d2h/h2d wire — the runtime
        # uses them interchangeably in current versions.
        "copy_d2h":       _copy_via_aux(METHOD_D2H, "phys_ids",     "slots"),
        "copy_h2d":       _copy_via_aux(METHOD_H2D, "slots",        "phys_ids"),
        "copy_d2d":       _copy_via_aux(METHOD_D2D, "src_phys_ids", "dst_phys_ids"),
        "copy_h2h":       _copy_via_aux(METHOD_H2H, "src_slots",    "dst_slots"),
        "swap_out_pages": _copy_via_aux(METHOD_D2H, "phys_ids",     "slots"),
        "swap_in_pages":  _copy_via_aux(METHOD_H2D, "slots",        "phys_ids"),
    }


def _run_rpc_loop(
    server: RpcServer,
    stop_event: threading.Event,
    methods: dict,
) -> None:
    """Mirror of pie_driver's leader loop on the cold path."""
    SPIN_US = 10_000
    POLL_TIMEOUT_MS = 200

    while not stop_event.is_set():
        try:
            req = server.poll_busy(SPIN_US, POLL_TIMEOUT_MS)
        except RuntimeError as e:
            if stop_event.is_set() or "Interrupted" in str(e):
                break
            raise
        if req is None:
            continue
        request_id, method, payload, _send_walltime_us = req

        try:
            args = msgpack.unpackb(payload)
            fn = methods.get(method)
            if fn is None:
                response = msgpack.packb(f"Method not found: {method}")
                server.respond(request_id, response, 0)
                continue

            if isinstance(args, dict):
                result = fn(**args)
            elif isinstance(args, (list, tuple)):
                result = fn(*args)
            else:
                result = fn(args)

            response = msgpack.packb(result)
            server.respond(request_id, response, 0)
        except Exception as e:
            print(f"[portable RPC Error] {method}: {e}\n{traceback.format_exc()}")
            response = msgpack.packb(str(e))
            server.respond(request_id, response, 0)


# =============================================================================
# worker_main
# =============================================================================


def worker_main(
    local_rank: int,
    world_size: int,
    devices: list[str],
    master_port: int,
    model_config: dict,
    driver_config: dict,
    group_topology: list[list[int]],
    ready_queue,
):
    """Entry point invoked via `mp.spawn` from `pie/server.py`."""
    if world_size != 1 or len(group_topology) != 1 or len(group_topology[0]) != 1:
        raise NotImplementedError(
            "ggml driver supports tensor_parallel_size=1 only "
            "(multi-rank is post-v1). Use the `native` driver for TP>1."
        )

    rank = local_rank

    driver_cfg = PortableDriverConfig(**{
        k: v for k, v in driver_config.items()
        if k in PortableDriverConfig.__dataclass_fields__
    })

    binary = _resolve_binary(driver_cfg.binary_path)

    # Reuse pie_driver's HF cache helper — same logic the Python `native`
    # driver uses to resolve `hf_repo` to a snapshot directory.
    from pie_driver.hf_utils import get_hf_snapshot_dir
    hf_repo = model_config["hf_repo"]
    snapshot_dir = get_hf_snapshot_dir(hf_repo)

    pie_home = Path(os.environ.get("PIE_HOME", Path.home() / ".pie"))
    pie_home.mkdir(parents=True, exist_ok=True)
    toml_path = pie_home / f"portable-driver-{os.getpid()}.toml"
    aux_socket_path = str(pie_home / f"portable-aux-{os.getpid()}.sock")
    # Resolve our DP-replica group_id from the topology (same convention
    # as pie_driver/worker.py). Single-rank → 0; multi-replica picks per
    # rank so each replica's shmem region gets a distinct `_g{idx}` suffix.
    my_group_id = 0
    for i, grp in enumerate(group_topology):
        if rank in grp:
            my_group_id = i
            break
    _write_startup_toml(
        driver_cfg=driver_cfg,
        snapshot_dir=str(snapshot_dir),
        aux_socket_path=aux_socket_path,
        out_path=toml_path,
        group_id=my_group_id,
    )

    # Cold-path RPC server first so the ready handshake can carry its name.
    server = RpcServer.create()
    server_name = server.server_name()

    proc = subprocess.Popen(
        [str(binary), "--config", str(toml_path)],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        bufsize=1,  # line-buffered
    )

    try:
        caps_dict = _wait_for_ready(proc, driver_cfg.ready_timeout_s)
    except Exception:
        proc.kill()
        proc.wait(timeout=2)
        raise

    stderr_thread = threading.Thread(
        target=_stream_stderr, args=(proc,), daemon=True
    )
    stderr_thread.start()

    # Translate the binary's capability JSON into DriverCapabilities.
    caps = DriverCapabilities(
        total_pages=int(caps_dict.get("total_pages", driver_cfg.max_num_kv_pages)),
        kv_page_size=int(caps_dict.get("kv_page_size", driver_cfg.kv_page_size)),
        swap_pool_size=int(caps_dict.get("swap_pool_size", 0)),
        max_batch_tokens=int(caps_dict.get("max_batch_tokens", driver_cfg.max_batch_tokens)),
        max_batch_size=int(caps_dict.get("max_batch_size", driver_cfg.max_batch_size)),
        arch_name=str(caps_dict.get("arch_name", "")),
        vocab_size=int(caps_dict.get("vocab_size", 0)),
        max_model_len=int(caps_dict.get("max_model_len", 0)),
        activation_dtype=str(caps_dict.get("activation_dtype", "")),
        snapshot_dir=str(caps_dict.get("snapshot_dir") or snapshot_dir),
    )

    ready_queue.put((rank, server_name, caps))

    # Connect to the binary's aux IPC server. The binary creates the
    # socket on startup; we lazily connect on the first page-copy RPC.
    aux_client = _AuxClient(aux_socket_path)

    stop_event = threading.Event()
    methods = _make_methods(aux_client)

    def _shutdown(signum, frame):
        stop_event.set()

    signal.signal(signal.SIGTERM, _shutdown)
    signal.signal(signal.SIGINT, _shutdown)

    try:
        _run_rpc_loop(server, stop_event, methods)
    finally:
        try:
            aux_client.close()
        except Exception:
            pass
        if proc.poll() is None:
            proc.send_signal(signal.SIGTERM)
            try:
                proc.wait(timeout=driver_cfg.shutdown_timeout_s)
            except subprocess.TimeoutExpired:
                proc.kill()
                proc.wait(timeout=2)
        try:
            toml_path.unlink(missing_ok=True)
        except Exception:
            pass
