[package]
name = "inferlet"
version.workspace = true
edition = "2024"
authors = ["In Gim <in.gim@yale.edu>"]
description = "Inferlet support library for Pie"
license = "Apache-2.0"
repository = "https://github.com/pie-project/pie"
keywords = ["wasi", "wasm", "pie", "inferlet"]
categories = ["wasm"]

include = ["src/**/*", "wit/**/*"]

[dependencies]
wit-bindgen = { version = "0.59.0", features = ["async-spawn"] }
inferlet-macros = { version = "0.5.0", path = "../inferlet-macros" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
eta-dsl = { path = "../eta-dsl" }

[lints]
workspace = true
