//===-- descriptor.cpp - reading the pie.model/1 descriptor --------------===//
//
// The replacement for `parse_hf_config`. Where that one dereferences nested
// configs, probes alternate spellings, applies per-`model_type` rules and
// resolves defaults -- ~850 lines with 25 conditionals -- this reads a flat
// document whose every field is already decided.
//
// That is the whole point of `pie.model/1`: the quirks are normalized once at
// import, in Rust, and what reaches a driver is a struct written out. There is
// nothing here to disagree with the normalizer about, because there is no
// judgement left in it.
//
// `head_dim_kernel` is the one field not in the descriptor and not readable
// from one: it rounds `head_dim` up to a head dim *this driver build*
// instantiated in kernels.def, so it is recomputed here rather than carried.
//
// GENERATED by `generate.py` from `model/config.hpp`. Regenerate rather than
// edit: a field added to `HfConfig` and forgotten here would read as zero.
//
//===----------------------------------------------------------------------===//
#include "model/descriptor.hpp"

#include <stdexcept>

#include <nlohmann/json.hpp>

#include "kernels_manifest.hpp"

namespace pie_cuda_driver {

namespace {

// The descriptor is exhaustive by construction, so a missing key is a bug in
// the writer rather than a case to default around. Reading it as zero would
// turn that bug into a model that loads and answers wrongly.
template <typename T>
T need(const nlohmann::json& j, const char* key) {
    auto it = j.find(key);
    if (it == j.end()) {
        throw std::runtime_error(
            std::string("pie.model/1 descriptor: missing key '") + key + "'");
    }
    return it->get<T>();
}

HfConfig::RopeScaling rope_scaling_of(const std::string& name) {
    if (name == "none") return HfConfig::RopeScaling::None;
    if (name == "llama3") return HfConfig::RopeScaling::Llama3;
    if (name == "original_yarn") return HfConfig::RopeScaling::OriginalYaRN;
    throw std::runtime_error("pie.model/1 descriptor: unknown rope scaling " + name);
}

GemmaVisionConfig read_GemmaVisionConfig(const nlohmann::json& j) {
    GemmaVisionConfig v;
    v.hidden_size = need<int>(j, "hidden_size");
    v.intermediate_size = need<int>(j, "intermediate_size");
    v.num_hidden_layers = need<int>(j, "num_hidden_layers");
    v.num_attention_heads = need<int>(j, "num_attention_heads");
    v.num_key_value_heads = need<int>(j, "num_key_value_heads");
    v.head_dim = need<int>(j, "head_dim");
    v.patch_size = need<int>(j, "patch_size");
    v.rms_norm_eps = need<float>(j, "rms_norm_eps");
    v.rope_theta = need<float>(j, "rope_theta");
    v.pooling_kernel_size = need<int>(j, "pooling_kernel_size");
    v.soft_tokens_per_image = need<int>(j, "soft_tokens_per_image");
    v.use_clipped_linears = need<bool>(j, "use_clipped_linears");
    return v;
}

GemmaAudioConfig read_GemmaAudioConfig(const nlohmann::json& j) {
    GemmaAudioConfig v;
    v.hidden_size = need<int>(j, "hidden_size");
    v.num_attention_heads = need<int>(j, "num_attention_heads");
    v.num_hidden_layers = need<int>(j, "num_hidden_layers");
    v.conv_kernel_size = need<int>(j, "conv_kernel_size");
    v.subsampling_conv_channels0 = need<int>(j, "subsampling_conv_channels0");
    v.subsampling_conv_channels1 = need<int>(j, "subsampling_conv_channels1");
    v.output_proj_dims = need<int>(j, "output_proj_dims");
    v.attention_chunk_size = need<int>(j, "attention_chunk_size");
    v.attention_context_left = need<int>(j, "attention_context_left");
    v.attention_context_right = need<int>(j, "attention_context_right");
    v.feature_size = need<int>(j, "feature_size");
    v.attention_logit_cap = need<float>(j, "attention_logit_cap");
    v.residual_weight = need<float>(j, "residual_weight");
    v.rms_norm_eps = need<float>(j, "rms_norm_eps");
    v.use_clipped_linears = need<bool>(j, "use_clipped_linears");
    return v;
}

CsmDepthDecoderConfig read_CsmDepthDecoderConfig(const nlohmann::json& j) {
    CsmDepthDecoderConfig v;
    v.hidden_size = need<int>(j, "hidden_size");
    v.backbone_hidden_size = need<int>(j, "backbone_hidden_size");
    v.num_hidden_layers = need<int>(j, "num_hidden_layers");
    v.num_attention_heads = need<int>(j, "num_attention_heads");
    v.num_key_value_heads = need<int>(j, "num_key_value_heads");
    v.head_dim = need<int>(j, "head_dim");
    v.intermediate_size = need<int>(j, "intermediate_size");
    v.num_codebooks = need<int>(j, "num_codebooks");
    v.vocab_size = need<int>(j, "vocab_size");
    v.max_position_embeddings = need<int>(j, "max_position_embeddings");
    v.rms_norm_eps = need<float>(j, "rms_norm_eps");
    v.rope_theta = need<float>(j, "rope_theta");
    v.rope_factor = need<float>(j, "rope_factor");
    v.rope_low_freq_factor = need<float>(j, "rope_low_freq_factor");
    v.rope_high_freq_factor = need<float>(j, "rope_high_freq_factor");
    v.rope_original_max_position = need<int>(j, "rope_original_max_position");
    return v;
}

MimiCodecConfig read_MimiCodecConfig(const nlohmann::json& j) {
    MimiCodecConfig v;
    v.hidden_size = need<int>(j, "hidden_size");
    v.codebook_dim = need<int>(j, "codebook_dim");
    v.codebook_size = need<int>(j, "codebook_size");
    v.num_quantizers = need<int>(j, "num_quantizers");
    v.num_semantic_quantizers = need<int>(j, "num_semantic_quantizers");
    v.num_filters = need<int>(j, "num_filters");
    v.upsampling_ratios = need<std::vector<int>>(j, "upsampling_ratios");
    v.xf_num_attention_heads = need<int>(j, "xf_num_attention_heads");
    v.xf_num_key_value_heads = need<int>(j, "xf_num_key_value_heads");
    v.xf_head_dim = need<int>(j, "xf_head_dim");
    v.xf_intermediate_size = need<int>(j, "xf_intermediate_size");
    v.xf_num_hidden_layers = need<int>(j, "xf_num_hidden_layers");
    v.xf_sliding_window = need<int>(j, "xf_sliding_window");
    v.xf_rope_theta = need<float>(j, "xf_rope_theta");
    v.norm_eps = need<float>(j, "norm_eps");
    v.sampling_rate = need<int>(j, "sampling_rate");
    v.use_causal_conv = need<bool>(j, "use_causal_conv");
    v.upsample_groups = need<int>(j, "upsample_groups");
    v.residual_kernel_size = need<int>(j, "residual_kernel_size");
    v.kernel_size = need<int>(j, "kernel_size");
    v.last_kernel_size = need<int>(j, "last_kernel_size");
    return v;
}

CsmConfig read_CsmConfig(const nlohmann::json& j) {
    CsmConfig v;
    v.text_vocab_size = need<int>(j, "text_vocab_size");
    v.audio_vocab_size = need<int>(j, "audio_vocab_size");
    v.num_codebooks = need<int>(j, "num_codebooks");
    v.codebook_eos_token_id = need<int>(j, "codebook_eos_token_id");
    v.audio_eos_token_id = need<int>(j, "audio_eos_token_id");
    v.audio_token_id = need<int>(j, "audio_token_id");
    v.depth = read_CsmDepthDecoderConfig(need<nlohmann::json>(j, "depth"));
    v.codec = read_MimiCodecConfig(need<nlohmann::json>(j, "codec"));
    return v;
}

Qwen3VLVisionConfig read_Qwen3VLVisionConfig(const nlohmann::json& j) {
    Qwen3VLVisionConfig v;
    v.hidden_size = need<int>(j, "hidden_size");
    v.intermediate_size = need<int>(j, "intermediate_size");
    v.depth = need<int>(j, "depth");
    v.num_heads = need<int>(j, "num_heads");
    v.patch_size = need<int>(j, "patch_size");
    v.temporal_patch_size = need<int>(j, "temporal_patch_size");
    v.spatial_merge_size = need<int>(j, "spatial_merge_size");
    v.in_channels = need<int>(j, "in_channels");
    v.out_hidden_size = need<int>(j, "out_hidden_size");
    v.num_position_embeddings = need<int>(j, "num_position_embeddings");
    v.deepstack_visual_indexes = need<std::vector<int>>(j, "deepstack_visual_indexes");
    return v;
}

HfConfig read_config(const nlohmann::json& j) {
    HfConfig v;
    v.arch_name = need<std::string>(j, "arch_name");
    v.model_type = need<std::string>(j, "model_type");
    v.hidden_size = need<int>(j, "hidden_size");
    v.intermediate_size = need<int>(j, "intermediate_size");
    v.num_hidden_layers = need<int>(j, "num_hidden_layers");
    v.num_attention_heads = need<int>(j, "num_attention_heads");
    v.num_key_value_heads = need<int>(j, "num_key_value_heads");
    v.head_dim = need<int>(j, "head_dim");
    v.vocab_size = need<int>(j, "vocab_size");
    v.max_position_embeddings = need<int>(j, "max_position_embeddings");
    v.rms_norm_eps = need<float>(j, "rms_norm_eps");
    v.hidden_act = need<std::string>(j, "hidden_act");
    v.mlp_hidden_act = need<std::string>(j, "mlp_hidden_act");
    v.rope_theta = need<float>(j, "rope_theta");
    v.rope_scaling_kind = rope_scaling_of(need<std::string>(j, "rope_scaling_kind"));
    v.rope_factor = need<float>(j, "rope_factor");
    v.rope_low_freq_factor = need<float>(j, "rope_low_freq_factor");
    v.rope_high_freq_factor = need<float>(j, "rope_high_freq_factor");
    v.rope_original_max_position = need<int>(j, "rope_original_max_position");
    v.rope_beta_fast = need<float>(j, "rope_beta_fast");
    v.rope_beta_slow = need<float>(j, "rope_beta_slow");
    v.rope_attention_factor = need<float>(j, "rope_attention_factor");
    v.rope_mla_softmax_mscale = need<float>(j, "rope_mla_softmax_mscale");
    v.has_rope_scaling = need<bool>(j, "has_rope_scaling");
    v.sliding_window = need<int>(j, "sliding_window");
    v.layer_types = need<std::vector<std::string>>(j, "layer_types");
    v.rope_local_base_freq = need<float>(j, "rope_local_base_freq");
    v.tie_word_embeddings = need<bool>(j, "tie_word_embeddings");
    v.attention_bias = need<bool>(j, "attention_bias");
    v.use_qk_norm = need<bool>(j, "use_qk_norm");
    v.num_experts = need<int>(j, "num_experts");
    v.num_experts_per_tok = need<int>(j, "num_experts_per_tok");
    v.gemma4_enable_moe = need<bool>(j, "gemma4_enable_moe");
    v.gemma4_attention_k_eq_v = need<bool>(j, "gemma4_attention_k_eq_v");
    v.gemma4_num_global_key_value_heads = need<int>(j, "gemma4_num_global_key_value_heads");
    v.gemma4_global_head_dim = need<int>(j, "gemma4_global_head_dim");
    v.gemma4_double_wide_mlp = need<bool>(j, "gemma4_double_wide_mlp");
    v.swiglu_limit = need<float>(j, "swiglu_limit");
    v.mlp_has_bias = need<bool>(j, "mlp_has_bias");
    v.router_has_bias = need<bool>(j, "router_has_bias");
    v.attention_has_sinks = need<bool>(j, "attention_has_sinks");
    v.gemma_query_pre_attn_scalar = need<float>(j, "gemma_query_pre_attn_scalar");
    v.gemma_final_logit_softcap = need<float>(j, "gemma_final_logit_softcap");
    v.gemma_attn_logit_softcap = need<float>(j, "gemma_attn_logit_softcap");
    v.gemma_hidden_size_per_layer_input = need<int>(j, "gemma_hidden_size_per_layer_input");
    v.num_kv_shared_layers = need<int>(j, "num_kv_shared_layers");
    v.gemma4_use_ordered_embeddings = need<bool>(j, "gemma4_use_ordered_embeddings");
    v.gemma4_num_centroids = need<int>(j, "gemma4_num_centroids");
    v.gemma4_centroid_intermediate_top_k = need<int>(j, "gemma4_centroid_intermediate_top_k");
    v.gemma_per_layer_rope_theta = need<std::vector<float>>(j, "gemma_per_layer_rope_theta");
    v.gemma_per_layer_partial_rotary_factor = need<std::vector<float>>(j, "gemma_per_layer_partial_rotary_factor");
    v.moe_intermediate_size = need<int>(j, "moe_intermediate_size");
    v.shared_expert_intermediate_size = need<int>(j, "shared_expert_intermediate_size");
    v.routed_scaling_factor = need<float>(j, "routed_scaling_factor");
    v.n_group = need<int>(j, "n_group");
    v.topk_group = need<int>(j, "topk_group");
    v.norm_topk_prob = need<bool>(j, "norm_topk_prob");
    v.mamba_num_heads = need<int>(j, "mamba_num_heads");
    v.mamba_head_dim = need<int>(j, "mamba_head_dim");
    v.mamba_state_size = need<int>(j, "mamba_state_size");
    v.mamba_n_groups = need<int>(j, "mamba_n_groups");
    v.mamba_conv_kernel = need<int>(j, "mamba_conv_kernel");
    v.mamba_chunk_size = need<int>(j, "mamba_chunk_size");
    v.mamba_time_step_min = need<float>(j, "mamba_time_step_min");
    v.q_lora_rank = need<int>(j, "q_lora_rank");
    v.kv_lora_rank = need<int>(j, "kv_lora_rank");
    v.qk_nope_head_dim = need<int>(j, "qk_nope_head_dim");
    v.qk_rope_head_dim = need<int>(j, "qk_rope_head_dim");
    v.v_head_dim = need<int>(j, "v_head_dim");
    v.first_k_dense_replace = need<int>(j, "first_k_dense_replace");
    v.n_shared_experts = need<int>(j, "n_shared_experts");
    v.dsv4_o_lora_rank = need<int>(j, "dsv4_o_lora_rank");
    v.dsv4_o_groups = need<int>(j, "dsv4_o_groups");
    v.dsv4_index_head_dim = need<int>(j, "dsv4_index_head_dim");
    v.dsv4_index_n_heads = need<int>(j, "dsv4_index_n_heads");
    v.dsv4_index_topk = need<int>(j, "dsv4_index_topk");
    v.dsv4_hc_mult = need<int>(j, "dsv4_hc_mult");
    v.dsv4_num_hash_layers = need<int>(j, "dsv4_num_hash_layers");
    v.dsv4_sliding_window = need<int>(j, "dsv4_sliding_window");
    v.dsv4_hc_eps = need<float>(j, "dsv4_hc_eps");
    v.dsv4_compress_rope_theta = need<float>(j, "dsv4_compress_rope_theta");
    v.dsv4_compress_ratios = need<std::vector<int>>(j, "dsv4_compress_ratios");
    v.dsv4_scoring_func = need<std::string>(j, "dsv4_scoring_func");
    v.dsv4_expert_dtype = need<std::string>(j, "dsv4_expert_dtype");
    v.linear_num_value_heads = need<int>(j, "linear_num_value_heads");
    v.linear_num_key_heads = need<int>(j, "linear_num_key_heads");
    v.linear_key_head_dim = need<int>(j, "linear_key_head_dim");
    v.linear_value_head_dim = need<int>(j, "linear_value_head_dim");
    v.linear_conv_kernel_dim = need<int>(j, "linear_conv_kernel_dim");
    v.attn_output_gate = need<bool>(j, "attn_output_gate");
    v.partial_rotary_factor = need<float>(j, "partial_rotary_factor");
    v.mtp_num_hidden_layers = need<int>(j, "mtp_num_hidden_layers");
    v.mtp_use_dedicated_embeddings = need<bool>(j, "mtp_use_dedicated_embeddings");
    v.altup_num_inputs = need<int>(j, "altup_num_inputs");
    v.altup_active_idx = need<int>(j, "altup_active_idx");
    v.altup_correct_scale = need<bool>(j, "altup_correct_scale");
    v.altup_coef_clip = need<float>(j, "altup_coef_clip");
    v.laurel_rank = need<int>(j, "laurel_rank");
    v.vocab_size_per_layer_input = need<int>(j, "vocab_size_per_layer_input");
    v.gemma3n_rope_local_base_freq = need<float>(j, "gemma3n_rope_local_base_freq");
    v.gemma3n_per_layer_intermediate = need<std::vector<int>>(j, "gemma3n_per_layer_intermediate");
    v.gemma3n_activation_sparsity = need<std::vector<float>>(j, "gemma3n_activation_sparsity");
    v.kda_gate_lower_bound = need<float>(j, "kda_gate_lower_bound");
    v.kda_full_rank_gate = need<bool>(j, "kda_full_rank_gate");
    v.mla_use_nope = need<bool>(j, "mla_use_nope");
    v.mla_output_gate = need<bool>(j, "mla_output_gate");
    v.routed_expert_hidden_size = need<int>(j, "routed_expert_hidden_size");
    v.latent_moe_use_norm = need<bool>(j, "latent_moe_use_norm");
    v.attn_res_block_size = need<int>(j, "attn_res_block_size");
    v.situ_beta = need<float>(j, "situ_beta");
    v.situ_linear_beta = need<float>(j, "situ_linear_beta");
    v.moe_router_activation_func = need<std::string>(j, "moe_router_activation_func");
    v.index_topk = need<int>(j, "index_topk");
    v.index_head_dim = need<int>(j, "index_head_dim");
    v.index_n_heads = need<int>(j, "index_n_heads");
    v.indexer_types = need<std::vector<std::string>>(j, "indexer_types");
    v.torch_dtype = need<std::string>(j, "torch_dtype");
    v.quant_method = need<std::string>(j, "quant_method");
    v.quant_bits = need<int>(j, "quant_bits");
    v.quant_group_size = need<int>(j, "quant_group_size");
    v.quant_desc_act = need<bool>(j, "quant_desc_act");
    v.quant_sym = need<bool>(j, "quant_sym");
    v.quant_zero_point = need<bool>(j, "quant_zero_point");
    v.kv_cache_scheme_present = need<bool>(j, "kv_cache_scheme_present");
    v.mm_lm_strip_prefix = need<std::string>(j, "mm_lm_strip_prefix");
    v.mm_skip_prefixes = need<std::vector<std::string>>(j, "mm_skip_prefixes");
    if (const auto it = j.find("gemma_vision"); it != j.end() && !it->is_null()) {
        v.gemma_vision = read_GemmaVisionConfig(*it);
    }
    if (const auto it = j.find("gemma_audio"); it != j.end() && !it->is_null()) {
        v.gemma_audio = read_GemmaAudioConfig(*it);
    }
    if (const auto it = j.find("qwen3_vl_vision"); it != j.end() && !it->is_null()) {
        v.qwen3_vl_vision = read_Qwen3VLVisionConfig(*it);
    }
    if (const auto it = j.find("csm"); it != j.end() && !it->is_null()) {
        v.csm = read_CsmConfig(*it);
    }
    v.qwen3_vl_mrope_section = need<std::vector<int>>(j, "qwen3_vl_mrope_section");
    v.qwen3_vl_mrope_interleaved = need<bool>(j, "qwen3_vl_mrope_interleaved");
    v.qwen3_vl_image_token_id = need<int>(j, "qwen3_vl_image_token_id");
    v.qwen3_vl_vision_start_token_id = need<int>(j, "qwen3_vl_vision_start_token_id");
    v.qwen3_vl_vision_end_token_id = need<int>(j, "qwen3_vl_vision_end_token_id");
    return v;
}

}  // namespace

HfConfig parse_pie_model_descriptor(const std::string& json) {
    const auto j = nlohmann::json::parse(json);
    const auto version = need<std::string>(j, "version");
    if (version != "pie.model/1") {
        throw std::runtime_error(
            "this artifact's model descriptor is " + version +
            ", and this build reads pie.model/1; regenerate it with "
            "`pie model convert --force`");
    }
    HfConfig cfg = read_config(j);
    // Not a fact about the checkpoint: the set of instantiated head dims is a
    // property of this build (kernels.def), so it is derived here.
    cfg.head_dim_kernel = round_up_attn_head_dim(cfg.head_dim);
    return cfg;
}

}  // namespace pie_cuda_driver
