//! The CUDA runtime template every emitted kernel is prefixed with: two
//! literals checked in under `runtime/cuda/`, wrapped around an RNG preamble
//! generated by [`crate::codegen::rng`] so the device RNG cannot drift from
//! `eta_ir::rng`.

use alloc::string::String;

const PROLOGUE: &str = include_str!("../../../runtime/cuda/ptir_m1_runtime_prologue.cuh");
const BODY: &str = include_str!("../../../runtime/cuda/ptir_m1_runtime_body.cuh");

/// The `__device__` projection of the RNG contract. The leading newline is
/// part of the value, kept to match what the goldens record.
fn rng_preamble() -> String {
    let mut preamble = String::from("\n");
    preamble.push_str(&crate::codegen::rng::cuda_device_functions());
    preamble
}

/// The full CUDA runtime source: prologue, RNG preamble, then body.
pub fn singleton_runtime_source() -> String {
    let mut source = String::with_capacity(PROLOGUE.len() + BODY.len() + 4096);
    source.push_str(PROLOGUE);
    source.push_str(&rng_preamble());
    source.push_str(BODY);
    source
}

