//! Static C++ emission — rung 3 of north-star-dsl.md.
//!
//! Walks a LOWERED class trace and writes the C++ the dumb interpreter
//! would execute: one statement per op, choices already made (they were
//! made at trace time; the emitter just spells them). This is the proof
//! of "statically convertible to C++": the generated file has no op
//! dispatch, no registry, no scan — the XQA prepare appears because the
//! emitter SAW the stated launch, the rope table build is a line because
//! the trace has the op, and layer weights are spelled `w.layers[17]`.
//!
//! What still appears as `if` in the generated code is exactly what the
//! interpreter also branches on: per-fire RUNTIME inputs
//! (`has_write_desc`, compact logits) and binding availability
//! (`gate_up_proj_fused`) — inputs of the launch, not choices between
//! kernels. Every such branch is a transliteration of the corresponding
//! interpreter arm in `declared_forward.cpp`, and the three-way parity
//! gate (hand-written ≡ interpreter ≡ generated) holds them together.
//!
//! Scope: the vocabulary the qwen3-class traces contain (pre-norm,
//! unpadded head dim, per-head qk-norm, fused QKV) — at FULL fire
//! width since rung 3 completed: the masked, mixed (Peel), lora
//! (staged handle + constant-layer corrections) and hooked arms (the
//! sideband preamble, constant-layer sites, page-mask brackets,
//! capture publishes) all emit, and the generated dispatch has no
//! per-attachment exclusions. Post-norm placement and padded head
//! dims remain interpreter-only (the asserts below). Anything outside
//! the vocabulary fails loudly — an emitter that silently skipped an
//! op would be a miscompile, not a fallback.

use crate::facts::{LlamaLikeCudaFacts, LlamaLikeFacts, NormPlacement, QkNorm};
use crate::family::llama_like_cuda;
use crate::trace::{FireClass, ForwardPlan, NormVariant, OpKind, RopeKind};

/// The digest naming what a generated TU was emitted FROM. The driver
/// composes the same string from its derived facts at model load
/// (`build_llama_like_declared_plan`) and runs the generated code only on
/// exact match — a config drift falls back to the interpreter, loudly.
/// One format, two printers (this and the C++ in declared_forward.cpp);
/// the live parity gate is what holds them together.
pub fn facts_digest(facts: &LlamaLikeFacts, cuda: &LlamaLikeCudaFacts) -> String {
    format!(
        "llama_like/h{}/l{}/qh{}/kvh{}/hd{}/i{}/v{}/rope{}/nv{}/np{}/qk{}/fq{}/te{}/qb{}/xqa{}/dfp{}/rt{}/fpp{}/pad{}",
        facts.hidden,
        facts.layers,
        facts.q_heads,
        facts.kv_heads,
        facts.head_dim,
        facts.intermediate,
        facts.vocab,
        match facts.rope {
            RopeKind::Standard => 0,
            RopeKind::Yarn => 1,
        },
        match facts.norm_variant {
            NormVariant::Plain => 0,
            NormVariant::Gemma => 1,
        },
        match facts.norm_placement {
            NormPlacement::Pre => 0,
            NormPlacement::Post => 1,
        },
        match facts.qk_norm {
            QkNorm::Off => 0,
            QkNorm::PerHead => 1,
            QkNorm::Global => 2,
        },
        u8::from(facts.fused_qkv),
        u8::from(facts.tied_embeddings),
        u8::from(facts.qkv_bias),
        u8::from(cuda.xqa_decode),
        u8::from(cuda.decode_fused_post),
        u8::from(cuda.rope_table),
        u8::from(cuda.force_prefill_path),
        u8::from(cuda.head_dim_padded),
    )
}

/// Emit the committed `.inc`: both class functions plus the digest
/// constant, ready for inclusion inside `declared_forward.cpp`'s
/// anonymous namespace (it uses the helpers and includes already there).
pub fn emit_llama_like_cuda_inc(
    facts: &LlamaLikeFacts,
    cuda: &LlamaLikeCudaFacts,
    tag: &str,
) -> String {
    let decode = llama_like_cuda(facts, cuda, FireClass::Decode);
    let prefill = llama_like_cuda(facts, cuda, FireClass::Prefill);
    let digest = facts_digest(facts, cuda);
    let mut out = String::new();
    out.push_str(&format!(
        "// GENERATED by `cargo run -p pie-forward --bin emit-cuda` — DO NOT EDIT.\n\
         // The static C++ form of the lowered llama_like class traces\n\
         // (north-star-dsl.md rung 3): one statement per traced op, choices\n\
         // already made at trace time. Included by declared_forward.cpp inside\n\
         // its anonymous namespace; regenerate after any change to the\n\
         // declaration, the facts below, or the emitter, and re-run the\n\
         // three-way parity gate. One TU per deployment; the `{tag}` suffix\n\
         // keeps the symbols apart and the digest constant names the pair.\n\
         //\n\
         // Emitted from: {digest}\n\n\
         constexpr const char* kGeneratedDigest_{tag} =\n    \"{digest}\";\n\n"
    ));
    out.push_str(&emit_class_fn(
        &decode,
        facts,
        cuda,
        &format!("generated_llama_like_decode_{tag}"),
        true,
        false,
    ));
    out.push('\n');
    out.push_str(&emit_class_fn(
        &prefill,
        facts,
        cuda,
        &format!("generated_llama_like_prefill_{tag}"),
        false,
        false,
    ));
    out.push('\n');
    // The supergraph build (S2, north-star-dsl.md "The supergraph
    // directive"): the SAME decode trace emitted as a capture builder —
    // guards become conditional nodes over the fire's device predicate
    // word, Peel becomes its two endpoint conditionals, and the whole
    // union captures as ONE graph per (R, N). Score-capture and lora
    // arms stay outside this union (their machinery is host-driven and
    // throws under capture — the S4 repair list); replay eligibility
    // keeps such fires eager.
    out.push_str(&emit_class_fn(
        &decode,
        facts,
        cuda,
        &format!("generated_llama_like_decode_{tag}_supergraph_build"),
        true,
        true,
    ));
    out
}

/// The parameter list shared with `llama_like_forward_declared`, minus the
/// plan (the whole point) and the inputs the class makes irrelevant.
const PARAMS: &str = "\
    const Qwen3Weights& w,\n\
    const HfConfig& cfg,\n\
    const LlamaLikeForwardCfg& fwd_cfg,\n\
    const LlamaLikePlanState& plan_state,\n\
    Workspace& ws,\n\
    KvCache& cache,\n\
    AttentionWorkspace& attn_ws,\n\
    ops::CublasHandle& cublas,\n\
    const std::int32_t* token_ids,\n\
    const std::int32_t* positions,\n\
    const std::uint32_t* qo_indptr,\n\
    const std::uint32_t* kv_page_indices,\n\
    const std::uint32_t* kv_page_indptr,\n\
    const std::uint32_t* kv_last_page_lens,\n\
    const std::uint32_t* qo_indptr_h,\n\
    const std::uint32_t* kv_page_indptr_h,\n\
    int total_tokens,\n\
    int num_requests,\n\
    const std::int32_t* logit_row_indices_d,\n\
    int num_logit_rows,\n\
    const std::uint32_t* w_page_d,\n\
    const std::uint32_t* w_off_d,\n\
    const std::uint8_t* row_valid_d,\n\
    bool has_write_desc,\n\
    const std::uint8_t* custom_mask_d,\n\
    const std::int32_t* custom_mask_indptr_d,\n\
    const StageHooks* hooks,\n\
    const LoraTable* lora,\n\
    const std::uint32_t* peel_window_d,\n\
    std::uint32_t unmasked_prefix_rows,\n\
    const std::uint32_t* mask_suffix_qo_indptr_d,\n\
    std::uint32_t declared_max_layers,\n\
    std::uint32_t declared_full_depth_rows";

fn emit_class_fn(
    plan: &ForwardPlan,
    facts: &LlamaLikeFacts,
    cuda: &LlamaLikeCudaFacts,
    fn_name: &str,
    is_decode: bool,
    sg: bool,
) -> String {
    // (sg: the TWO-PATH supergraph build — see SgValuation.)
    // Post-norm placement (olmo2) emits since the second-deployment
    // rung: the buffer routing below mirrors the interpreter's
    // `post_norm` arms line for line.
    let mut b = Body::default();
    if sg {
        // The build fn: same inputs plus the capture builder. `stream`
        // is a MUTABLE local rebound at every body boundary, so every
        // launch line below lands on whichever graph (root or arm body)
        // is capturing — the launch text itself is identical to the
        // plain fn's.
        b.line(&format!(
            "inline void {fn_name}(\n{PARAMS},\n    batch::SupergraphBuilder& sg)\n{{"
        ));
    } else {
        b.line(&format!("inline void {fn_name}(\n{PARAMS})\n{{"));
    }
    if cuda.head_dim_padded {
        b.line("    // Locals mirror the interpreter's preamble — PADDED shape");
        b.line("    // (Phi-3's 96 -> 128): the attention consumes zero-padded");
        b.line("    // dk staging copies, the softmax keeps the real-dim scale,");
        b.line("    // and the o_proj reads the stripped logical-width output.");
    } else {
        b.line("    // Locals mirror the interpreter's preamble (unpadded shape:");
        b.line("    // the staging aliases are the plain buffers).");
    }
    b.line("    const int N = total_tokens;");
    b.line("    const int R = num_requests;");
    if plan.depth_window {
        b.line("    // STRUCTURAL S-4: the depth axis, stated by the trace");
        b.line("    // (ForwardPlan::depth_window) — per-layer scopes below");
        b.line("    // shadow N/R on tail layers; uniform truncation skips");
        b.line("    // them and the unchanged epilogue is the logit-lens head.");
        b.line("    const int depth_k =");
        b.line("        declared_max_layers != 0xffffffffu &&");
        b.line("        declared_max_layers <");
        b.line("            static_cast<std::uint32_t>(cfg.num_hidden_layers)");
        b.line("            ? static_cast<int>(declared_max_layers)");
        b.line("            : cfg.num_hidden_layers;");
        b.line("    const bool depth_union =");
        b.line("        depth_k < cfg.num_hidden_layers &&");
        b.line("        declared_full_depth_rows != 0xffffffffu;");
        b.line("    const int depth_split = depth_union");
        b.line("        ? static_cast<int>(declared_full_depth_rows)");
        b.line("        : N;");
        b.line("    if (depth_union &&");
        b.line("        (depth_split <= 0 || depth_split >= R ||");
        b.line("         !plan_state.depth_prefix_decode_plan)) {");
        b.line("        throw std::runtime_error(");
        b.line("            \"depth union (generated): planned split without \"");
        b.line("            \"a usable prefix plan (gate drift)\");");
        b.line("    }");
    }
    b.line("    const int H = cfg.hidden_size;");
    b.line("    const int Hq = cfg.num_attention_heads * cfg.head_dim;");
    b.line("    const int Hk = cfg.num_key_value_heads * cfg.head_dim;");
    b.line("    const int I = cfg.intermediate_size;");
    b.line("    const int V = cfg.vocab_size;");
    b.line("    const int d = cfg.head_dim;");
    b.line("    const int num_q_heads = cfg.num_attention_heads;");
    b.line("    const int num_kv_heads = cfg.num_key_value_heads;");
    b.line("    const float eps = cfg.rms_norm_eps;");
    if sg {
        b.line("    cudaStream_t stream = sg.stream();");
        b.line("    cublas.set_stream(stream);");
    } else {
        b.line("    cudaStream_t stream = cublas.stream();");
    }
    if cuda.head_dim_padded {
        b.line("    const int dk = cfg.head_dim_kernel;");
        b.line("    const float sm_scale_override =");
        b.line("        1.0f / std::sqrt(static_cast<float>(d));");
        b.line("    void* const attn_q = ws.q_padded.data();");
        b.line("    void* const attn_k = ws.k_padded.data();");
        b.line("    void* const attn_v = ws.v_padded.data();");
        b.line("    void* const attn_out_buf = ws.attn_out_padded.data();");
    }
    b.line("    if (std::getenv(\"PIE_DECLARED_FORWARD_TRACE\")) {");
    b.line("        std::fprintf(stderr,");
    b.line(&format!(
        "                     \"[declared-forward-generated] N=%d R=%d decode={}\\n\",",
        i32::from(is_decode)
    ));
    b.line("                     N, R);");
    b.line("    }");
    b.line("");

    // The hook sidebands (the interpreter's fire-level preamble,
    // hoisted statically): the page-mask sink the OnAttnProj sites
    // offer, the per-layer score capture the attention publishes
    // through, and the per-layer (possibly compacted) page list the
    // attention emissions consume. All argument-driven — an unhooked
    // fire constructs an inactive mask and none of it launches.
    b.line("    FirePageMask page_mask(hooks, stream);");
    b.line("    const std::uint32_t* attn_page_indices = kv_page_indices;");
    b.line("    const std::uint32_t* attn_page_indptr = kv_page_indptr;");
    b.line("    const std::uint32_t* attn_last_page_lens = kv_last_page_lens;");
    if is_decode {
        b.line("    std::optional<LayerScoreCapture> score_capture;");
    } else {
        b.line("    std::optional<LayerPrefillScoreCapture> prefill_score_capture;");
    }
    b.line("");

    // A stated lora correction obligates the fire staging: the emitter
    // saw the op, so the generated file constructs the handle (the
    // interpreter's lora_state, hoisted here statically).
    let states_lora = plan.ops.iter().any(|op| {
        matches!(&op.kind, OpKind::Launch { kernel, .. }
                 if kernel == "pie_lora_qkv_correction")
    });
    if states_lora {
        // Campaign step 3a: prefer the ENGINE-staged state (outside any
        // capture region); local staging is the fallback.
        b.line("    const LoraFireStateHandle* lora_staged =");
        b.line("        (lora != nullptr && lora->usable() &&");
        b.line("         plan_state.lora_staged_table == lora)");
        b.line("            ? plan_state.lora_staged.get() : nullptr;");
        b.line("    std::optional<LoraFireStateHandle> lora_state;");
        b.line("    if (lora != nullptr && lora->usable() &&");
        b.line("        lora_staged == nullptr) {");
        b.line("        lora_state.emplace(*lora, cfg, N, H, Hq, Hk, I,");
        // Campaign steps 1-2: the staging arena rides on the workspace,
        // and the stage phase bakes the fire-constant buffer pointers
        // (placement resolved at emission).
        let lora_qkv_in = if facts.norm_placement == NormPlacement::Post {
            "ws.y.data()"
        } else {
            "ws.norm_x.data()"
        };
        b.line("                           /*tp=*/1, stream, ws,");
        b.line(&format!("                           {lora_qkv_in},"));
        b.line("                           ws.q.data(), ws.v.data(),");
        b.line("                           ws.gate.data());");
        b.line("    }");
        b.line("");
    }

    // A stated Peel obligates the split derivation: the hook-free prefix
    // row count, the interpreter's `fast_rows` binding verbatim (a
    // runtime INPUT of the stated op, not a choice).
    let states_peel = plan
        .ops
        .iter()
        .any(|op| matches!(&op.kind, OpKind::Peel { .. }));
    if states_peel {
        b.line("    const int fast_rows = hooks == nullptr");
        b.line("        ? R");
        b.line("        : (static_cast<int>(hooks->hook_free_prefix_rows) < R");
        b.line("               ? static_cast<int>(hooks->hook_free_prefix_rows)");
        b.line("               : R);");
        b.line("");
    }

    // A stated XQA launch obligates its fire-wide prepare — resolved HERE,
    // statically: the emitter saw the op, so the generated file has the
    // call and no scan.
    let states_xqa = plan.ops.iter().any(|op| {
        matches!(&op.kind, OpKind::Launch { kernel, .. }
                 if kernel == "launch_attention_xqa_decode_bf16_prepared")
    });
    if states_xqa {
        b.line("    // The trace states the XQA attention kernel; its fire-wide");
        b.line("    // prepare is that statement's obligation.");
        b.line("    ops::prepare_attention_xqa_decode_bf16(");
        b.line("        kv_page_indices, kv_page_indptr, kv_last_page_lens,");
        b.line("        R, cache.page_size(), plan_state.xqa_max_pages_per_seq,");
        b.line("        attn_ws, stream);");
        b.line("");
    }

    if sg {
        // ONE top-level conditional (mask slot 4), TWO fully resolved
        // walks. One handle, one embedded set kernel (inside
        // open_cond), no nesting — the replay overhead the per-guard
        // form paid in ~112 single-thread arms collapses to a single
        // branch.
        b.line("    {");
        b.line("        auto __sg_mask = sg.open_cond(4, true);");
        b.line("        sg.begin_body(__sg_mask.if_body);");
        b.line("        stream = sg.stream();");
        b.line("        cublas.set_stream(stream);");
        b.line("        {");
        emit_range(
            &mut b, plan, facts, cuda, is_decode,
            Some(SgValuation { has_custom_mask: true }),
            0, plan.ops.len(), None,
        );
        b.line("        }");
        b.line("        sg.end_body();");
        b.line("        sg.begin_body(__sg_mask.else_body);");
        b.line("        stream = sg.stream();");
        b.line("        cublas.set_stream(stream);");
        b.line("        {");
        emit_range(
            &mut b, plan, facts, cuda, is_decode,
            Some(SgValuation { has_custom_mask: false }),
            0, plan.ops.len(), None,
        );
        b.line("        }");
        b.line("        sg.end_body();");
        b.line("        sg.close_cond(__sg_mask);");
        b.line("        stream = sg.stream();");
        b.line("        cublas.set_stream(stream);");
        b.line("    }");
    } else {
        emit_range_scoped(
            &mut b, plan, facts, cuda, is_decode, None, 0, plan.ops.len(),
            None, plan.depth_window,
        );
    }
    b.line("}");
    b.out
}

/// The Peel row window, threaded through region emission (A3). `None`
/// is the full-N walk. `Host` carries fixed C++ expressions for the
/// region's row start and count. The `Dev*` variants are the
/// device-window campaign's graph-path forms: the split lives in the
/// `peel_window_d` word ({tail_start, tail_len}); the prefix region is
/// [0, word[0]) and every windowed launch takes the devwin kernel at
/// the full-N grid, so a captured exec replays across row splits.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Win {
    Host {
        start: &'static str,
        len: &'static str,
    },
    DevPrefix,
    DevTail,
    /// A [`PeelWindow::UnmaskedPrefix`] peel's PREFIX region (the
    /// spatial mask split): the deployment's decode dispatch over the
    /// plain rows `[0, split)` — raw CSR base addressing, the prefix
    /// decode plan.
    MaskPrefix,
    /// Its TAIL region: the custom dispatch over the masked suffix
    /// `[split, N)` — hybrid addressing (qo[0]-relative q/o, absolute
    /// device CSR at `+split`).
    MaskTail,
}

/// Emit ops `[start, end)`: a Guard consumes its region ops into an
/// emitted `if`/`else if`/`else` — the ONLY branch the declaration wrote,
/// spelled as the fixed condition its closed predicate names. RECURSIVE
/// since A1 (the class-collapse amendment): a nested guard is an
/// ordinary op inside a region and recurses into its own chain.
/// The supergraph's emission-time predicate valuation (the TWO-PATH
/// form): within the graph-replayable union today, every predicate but
/// the mask is a CONSTANT of the graph context — eligibility requires
/// write descriptors, excludes score/lora fires, and keeps hooked rows
/// out (Peel at its all-fast endpoint) — so each conditional body is a
/// fully guard-resolved straight-line walk. When hooks/lora join the
/// union (S4), the k>1 form returns to per-guard conditionals with
/// per-slot SHARED handles (PoC-2: sibling nodes share a root handle;
/// nested bodies cannot — the flattened two-path form sidesteps both).
#[derive(Clone, Copy)]
struct SgValuation {
    has_custom_mask: bool,
}

impl SgValuation {
    fn resolve(&self, pred: &crate::trace::GuardPred) -> bool {
        use crate::trace::GuardPred;
        match pred {
            GuardPred::HasCustomMask => self.has_custom_mask,
            GuardPred::HasWriteDesc => true,
            GuardPred::WantsAttnScore => false,
            GuardPred::HasLora => false,
            other => panic!(
                "emitter: pred {other:?} outside the supergraph union"
            ),
        }
    }
}

fn emit_range(
    b: &mut Body,
    plan: &ForwardPlan,
    facts: &LlamaLikeFacts,
    cuda: &LlamaLikeCudaFacts,
    is_decode: bool,
    sg: Option<SgValuation>,
    start: usize,
    end: usize,
    win: Option<Win>,
) {
    emit_range_scoped(b, plan, facts, cuda, is_decode, sg, start, end, win, false)
}

/// STRUCTURAL S-4: `track_layers` (the ONE top-level call of a
/// depth-window trace) wraps each layer's ops in a scope that shadows
/// N/R — tail layers (static L >= runtime depth_k) run at depth_split
/// on a union fire and are skipped entirely on a uniform truncated
/// fire; the layer-untagged epilogue stays full-N (the logit-lens
/// head). Regions recurse WITHOUT tracking: they are layer-local and
/// inherit the enclosing scope.
#[allow(clippy::too_many_arguments)]
fn emit_range_scoped(
    b: &mut Body,
    plan: &ForwardPlan,
    facts: &LlamaLikeFacts,
    cuda: &LlamaLikeCudaFacts,
    is_decode: bool,
    sg: Option<SgValuation>,
    start: usize,
    end: usize,
    win: Option<Win>,
    track_layers: bool,
) {
    let mut i = start;
    let mut cur_layer: Option<u32> = None;
    let close_scope = |b: &mut Body| {
        b.stmt("}");
        b.stmt("}");
    };
    while i < end {
        let op = &plan.ops[i];
        if track_layers && op.layer != cur_layer {
            if cur_layer.is_some() {
                close_scope(b);
            }
            if let Some(l) = op.layer {
                b.stmt("{");
                b.stmt(&format!(
                    "const bool depth_tail = depth_k <= {l};"
                ));
                b.stmt("if (!depth_tail || depth_union) {");
                b.stmt(
                    "const int N = depth_tail ? depth_split : total_tokens;",
                );
                b.stmt(
                    "const int R = depth_tail ? depth_split : num_requests;",
                );
                b.stmt("(void)N; (void)R;");
            }
            cur_layer = op.layer;
        }
        if let OpKind::Peel {
            prefix_ops,
            tail_ops,
            window,
        } = &op.kind
        {
            if *window == crate::trace::PeelWindow::UnmaskedPrefix {
                // The spatial mask split, STATED (NS-4 landed in the
                // IR): the declaration's peel names the axis and the
                // two regions; this emitter only spells the window
                // plumbing — planned (prepare built both plans) runs
                // prefix then rebased tail, UNPLANNED collapses to the
                // tail full-N with fire-level addressing.
                let region = i + 1;
                let tail_lo = region + *prefix_ops as usize;
                let tail_hi = tail_lo + *tail_ops as usize;
                if sg.is_some() {
                    // The retired union's mask arm was the fire-level
                    // custom dispatch: the peel's UNPLANNED endpoint.
                    emit_range(
                        b, plan, facts, cuda, is_decode, sg, tail_lo, tail_hi, None,
                    );
                    i = tail_hi;
                    continue;
                }
                b.stmt("if (plan_state.spatial_mask_split >= 0 &&");
                b.stmt("    unmasked_prefix_rows != 0xffffffffu) {");
                b.indent += 1;
                b.stmt("const int split = plan_state.spatial_mask_split;");
                // Two domains (the mixed fire): `split` is the REQUEST
                // index (CSR/mask-indptr offsets), `split_rows` the
                // TOKEN-ROW offset (q/out pointers) — equal on
                // pure-decode fires, divergent when prefill rows share
                // the fire. The planned word is the request domain.
                b.stmt("const int split_rows =");
                b.stmt("    plan_state.spatial_mask_row_split >= 0");
                b.stmt("        ? plan_state.spatial_mask_row_split");
                b.stmt("        : split;");
                b.stmt("if (split !=");
                b.stmt("    static_cast<int>(unmasked_prefix_rows)) {");
                b.stmt("    throw std::runtime_error(");
                b.stmt("        \"spatial mask: planned/prepared split drift\");");
                b.stmt("}");
                b.stmt("if (mask_suffix_qo_indptr_d == nullptr) {");
                b.stmt("    throw std::runtime_error(");
                b.stmt("        \"spatial mask: suffix qo identity missing\");");
                b.stmt("}");
                b.stmt("if (split > 0) {");
                b.indent += 1;
                emit_range(
                    b, plan, facts, cuda, is_decode, sg, region, tail_lo,
                    Some(Win::MaskPrefix),
                );
                b.indent -= 1;
                b.stmt("}");
                emit_range(
                    b, plan, facts, cuda, is_decode, sg, tail_lo, tail_hi,
                    Some(Win::MaskTail),
                );
                b.indent -= 1;
                b.stmt("} else {");
                b.indent += 1;
                emit_range(b, plan, facts, cuda, is_decode, sg, tail_lo, tail_hi, None);
                b.indent -= 1;
                b.stmt("}");
                i = tail_hi;
                continue;
            }
            if sg.is_some() {
                // Peel, RESOLVED (two-path form): the union's graph
                // fires carry no hooked rows (eligibility), so
                // fast_rows == N and the prefix region runs FULL-WIDTH;
                // the tail region does not exist on this path. A mixed
                // fire must not replay this graph — the S4 device-window
                // campaign is what would change that.
                let region = i + 1;
                emit_range(
                    b, plan, facts, cuda, is_decode, sg, region,
                    region + *prefix_ops as usize, None,
                );
                i = region + (*prefix_ops as usize) + (*tail_ops as usize);
                continue;
            }
            // A3: both regions, complementary row ranges, empty ranges
            // skipped — the interpreter's Peel walk as fixed `if`s over
            // the derived `fast_rows` local. Device-window mode
            // (peel_window_d, hook captures only): BOTH regions emit
            // unconditionally through the devwin kernel forms, so the
            // captured exec replays across row splits.
            let mut region = i + 1;
            b.stmt("if (peel_window_d != nullptr) {");
            b.indent += 1;
            emit_range(
                b, plan, facts, cuda, is_decode, sg, region,
                region + *prefix_ops as usize, Some(Win::DevPrefix),
            );
            emit_range(
                b, plan, facts, cuda, is_decode, sg,
                region + *prefix_ops as usize,
                region + *prefix_ops as usize + *tail_ops as usize,
                Some(Win::DevTail),
            );
            b.indent -= 1;
            b.stmt("} else {");
            b.indent += 1;
            b.stmt("if (fast_rows > 0) {");
            b.indent += 1;
            emit_range(
                b, plan, facts, cuda, is_decode, sg, region, region + *prefix_ops as usize,
                Some(Win::Host { start: "0", len: "fast_rows" }),
            );
            b.indent -= 1;
            b.stmt("}");
            region += *prefix_ops as usize;
            b.stmt("if (fast_rows < N) {");
            b.indent += 1;
            emit_range(
                b, plan, facts, cuda, is_decode, sg, region, region + *tail_ops as usize,
                Some(Win::Host { start: "fast_rows", len: "(N - fast_rows)" }),
            );
            b.indent -= 1;
            b.stmt("}");
            b.indent -= 1;
            b.stmt("}");
            i = region + *tail_ops as usize;
            continue;
        }
        if let OpKind::Guard { arms, else_ops } = &op.kind {
            if let Some(v) = sg {
                // Two-path form: the valuation picks ONE region at
                // emission; the chosen arm inlines, the rest vanish.
                let mut region = i + 1;
                let mut chosen: Option<(usize, usize)> = None;
                for arm in arms.iter() {
                    if chosen.is_none() && v.resolve(&arm.pred) {
                        chosen = Some((region, region + arm.ops as usize));
                    }
                    region += arm.ops as usize;
                }
                let (lo, hi) = chosen
                    .unwrap_or((region, region + *else_ops as usize));
                emit_range(b, plan, facts, cuda, is_decode, sg, lo, hi, win);
                i = region + *else_ops as usize;
                continue;
            }
            let cond_of = |pred: &crate::trace::GuardPred| match pred {
                crate::trace::GuardPred::HasWriteDesc => "has_write_desc".to_string(),
                crate::trace::GuardPred::TokensLE(k) => format!("N <= {k}"),
                crate::trace::GuardPred::TokensGT(k) => format!("N > {k}"),
                crate::trace::GuardPred::WantsAttnScore => {
                    "hooks != nullptr && hooks->wants_attn_score".to_string()
                }
                crate::trace::GuardPred::HasCustomMask => {
                    "custom_mask_d != nullptr".to_string()
                }
                crate::trace::GuardPred::HasStageHooks => {
                    "hooks != nullptr".to_string()
                }
                crate::trace::GuardPred::HasLora => {
                    "lora != nullptr && lora->usable()".to_string()
                }
            };
            let mut region = i + 1;
            for (n, arm) in arms.iter().enumerate() {
                let kw = if n == 0 { "if" } else { "} else if" };
                b.stmt(&format!("{kw} ({}) {{", cond_of(&arm.pred)));
                b.indent += 1;
                emit_range(b, plan, facts, cuda, is_decode, sg, region, region + arm.ops as usize, win);
                b.indent -= 1;
                region += arm.ops as usize;
            }
            b.stmt("} else {");
            b.indent += 1;
            emit_range(b, plan, facts, cuda, is_decode, sg, region, region + *else_ops as usize, win);
            b.indent -= 1;
            b.stmt("}");
            i = region + *else_ops as usize;
            continue;
        }
        emit_op(
            b, op, plan, facts, cuda, is_decode, win,
            plan.depth_window && sg.is_none(),
        );
        i += 1;
    }
    if track_layers && cur_layer.is_some() {
        close_scope(b);
    }
}

#[derive(Default)]
struct Body {
    out: String,
    /// Extra indent levels while inside an emitted Guard region.
    indent: usize,
}

impl Body {
    fn line(&mut self, s: &str) {
        self.out.push_str(s);
        self.out.push('\n');
    }
    fn stmt(&mut self, s: &str) {
        for l in s.lines() {
            self.out.push_str("    ");
            for _ in 0..self.indent {
                self.out.push_str("    ");
            }
            self.out.push_str(l);
            self.out.push('\n');
        }
    }
}

/// `layer.N.field` → (N, field); panics on anything else — the emitter's
/// weight vocabulary is family.rs's, same rule as the interpreter's
/// `parse_weight_name`, enforced at emission instead of at fire.
fn split_layer_weight(name: &str) -> Option<(u32, &str)> {
    let rest = name.strip_prefix("layer.")?;
    let dot = rest.find('.')?;
    let layer = rest[..dot].parse().ok()?;
    Some((layer, &rest[dot + 1..]))
}

fn require(layer: u32, member: &str, name: &str) -> String {
    format!("require(w.layers[{layer}].{member}, \"{name}\")->data()")
}

fn emit_op(
    b: &mut Body,
    op: &crate::trace::Op,
    plan: &ForwardPlan,
    facts: &LlamaLikeFacts,
    cuda: &LlamaLikeCudaFacts,
    is_decode: bool,
    win: Option<Win>,
    depth_active: bool,
) {
    let _ = plan;
    match &op.kind {
        OpKind::Embed { weight } => {
            assert_eq!(weight, "embed");
            b.stmt("kernels::launch_embed_bf16(");
            b.stmt("    token_ids, require(w.embed, \"embed\")->data(), ws.y.data(),");
            b.stmt("    N, H, V, stream);");
        }
        OpKind::Rmsnorm { weight, variant } => {
            assert_eq!(*variant, NormVariant::Plain, "emitter: Plain only");
            if weight == "final_norm" {
                // Deferred into the LmHead epilogue, exactly the
                // interpreter's arm (gather-then-norm ≡ norm-then-gather).
                b.stmt("// final_norm: deferred into the LmHead epilogue below.");
                return;
            }
            let (layer, field) = split_layer_weight(weight)
                .unwrap_or_else(|| panic!("emitter: unknown norm weight {weight}"));
            let post = facts.norm_placement == NormPlacement::Post;
            let (input, output, width) = match field {
                // Pre-norm: norm the stream INTO the sub-layer's scratch.
                // Post-norm (olmo2): the sub-layer's OUTPUT (landed in
                // norm_x by the beta=0 projection) is normed into norm_y;
                // the following ResidualAdd lands it on the stream — the
                // interpreter's post-norm arms verbatim.
                "attn_norm" if post => ("ws.norm_x.data()", "ws.norm_y.data()", "H"),
                "attn_norm" => ("ws.y.data()", "ws.norm_x.data()", "H"),
                "mlp_norm" if post => ("ws.norm_x.data()", "ws.norm_y.data()", "H"),
                "mlp_norm" => ("ws.y.data()", "ws.norm_y.data()", "H"),
                // Global qk-norm (olmo2): ONE row RMSNorm over the
                // flattened projection, in place.
                "q_norm" => ("ws.q.data()", "ws.q.data()", "Hq"),
                "k_norm" => ("ws.k.data()", "ws.k.data()", "Hk"),
                other => panic!("emitter: row-norm field {other} out of scope"),
            };
            b.stmt(&format!("kernels::launch_rmsnorm_bf16("));
            b.stmt(&format!(
                "    {input}, {},",
                require(layer, field, weight)
            ));
            b.stmt(&format!("    {output}, N, {width}, eps, stream);"));
        }
        OpKind::AddBias { weight } => {
            // Qwen-2 family qkv biases: the hand-written `maybe_add_bias`
            // calls, target buffer and width resolved at EMISSION time
            // from the weight's field name (the interpreter dispatches on
            // the same suffix at walk time).
            let (layer, field) = split_layer_weight(weight)
                .unwrap_or_else(|| panic!("emitter: unknown bias weight {weight}"));
            let (buf, width) = match field {
                "q_bias" => ("ws.q.data()", "Hq"),
                "k_bias" => ("ws.k.data()", "Hk"),
                "v_bias" => ("ws.v.data()", "Hk"),
                other => panic!("emitter: bias field {other} out of scope"),
            };
            b.stmt("kernels::launch_add_bias_bf16(");
            b.stmt(&format!("    {buf}, {},", require(layer, field, weight)));
            b.stmt(&format!("    N, {width}, stream);"));
        }
        OpKind::Matmul {
            weight,
            beta_one,
            selector,
        } => {
            assert!(selector.is_none(), "emitter: dyn matmul out of scope");
            let (layer, field) = split_layer_weight(weight)
                .unwrap_or_else(|| panic!("emitter: unknown matmul weight {weight}"));
            match (field, *beta_one) {
                ("qkv", false) => {
                    b.stmt("ops::gemm_act_x_w(cublas.handle(),");
                    b.stmt("    ws.norm_x.data(),");
                    b.stmt(&format!(
                        "    ops::WeightView(*require(w.layers[{layer}].qkv_proj_fused, \"{weight}\")),"
                    ));
                    b.stmt("    ws.qkv_fused.data(), N, Hq + 2 * Hk, H);");
                }
                ("o_proj", true) => {
                    b.stmt("ops::gemm_act_x_w(cublas.handle(),");
                    b.stmt("    ws.attn_out.data(),");
                    b.stmt(&format!(
                        "    make_weight_view(require(w.layers[{layer}].o_proj, \"{weight}\"), w.layers[{layer}].o_proj_quant),"
                    ));
                    b.stmt("    ws.y.data(), N, H, Hq, 1.f);");
                }
                ("gate_up", false) => {
                    let mlp_in = if facts.norm_placement == NormPlacement::Post {
                        "ws.y.data()"
                    } else {
                        "ws.norm_y.data()"
                    };
                    // The binding dispatch, transliterated: fused when the
                    // deployment materialised the packed weight AND the
                    // workspace carries the buffer (the interpreter's
                    // `gate_up_used_fused`, which the Swiglu right after
                    // this reads — emitted as one combined block there).
                    b.stmt(&format!(
                        "const bool gate_up_fused_{layer} ="
                    ));
                    b.stmt(&format!(
                        "    w.layers[{layer}].gate_up_proj_fused != nullptr && !ws.gate_up_fused.empty();"
                    ));
                    b.stmt(&format!("if (gate_up_fused_{layer}) {{"));
                    b.stmt("    ops::gemm_act_x_w(cublas.handle(),");
                    b.stmt(&format!("        {mlp_in},"));
                    b.stmt(&format!(
                        "        ops::WeightView(*w.layers[{layer}].gate_up_proj_fused),"
                    ));
                    b.stmt("        ws.gate_up_fused.data(), N, 2 * I, H);");
                    b.stmt("} else {");
                    b.stmt("    ops::gemm_act_x_w(cublas.handle(),");
                    b.stmt(&format!("        {mlp_in},"));
                    b.stmt(&format!(
                        "        make_weight_view(require(w.layers[{layer}].gate_proj, \"{weight}\"), w.layers[{layer}].gate_proj_quant),"
                    ));
                    b.stmt("        ws.gate.data(), N, I, H);");
                    b.stmt("    ops::gemm_act_x_w(cublas.handle(),");
                    b.stmt(&format!("        {mlp_in},"));
                    b.stmt(&format!(
                        "        make_weight_view(require(w.layers[{layer}].up_proj, \"{weight}\"), w.layers[{layer}].up_proj_quant),"
                    ));
                    b.stmt("        ws.up.data(), N, I, H);");
                    b.stmt("}");
                }
                ("down", true) => {
                    b.stmt("ops::gemm_act_x_w(cublas.handle(),");
                    b.stmt("    ws.gate.data(),");
                    b.stmt(&format!(
                        "    make_weight_view(require(w.layers[{layer}].down_proj, \"{weight}\"), w.layers[{layer}].down_proj_quant),"
                    ));
                    b.stmt("    ws.y.data(), N, H, I, 1.f);");
                }
                // Unfused projections (olmo2/phi3 bindings): the three
                // per-projection GEMMs the interpreter's arms make. The
                // QKV input is the post-norm stream itself or the
                // pre-norm scratch (the interpreter's qkv_in).
                ("q_proj", false) | ("k_proj", false) | ("v_proj", false) => {
                    let post = facts.norm_placement == NormPlacement::Post;
                    let input = if post { "ws.y.data()" } else { "ws.norm_x.data()" };
                    let (out, width, member, quant) = match field {
                        "q_proj" => ("ws.q.data()", "Hq", "q_proj", "q_proj_quant"),
                        "k_proj" => ("ws.k.data()", "Hk", "k_proj", "k_proj_quant"),
                        _ => ("ws.v.data()", "Hk", "v_proj", "v_proj_quant"),
                    };
                    b.stmt("ops::gemm_act_x_w(cublas.handle(),");
                    b.stmt(&format!("    {input},"));
                    b.stmt(&format!(
                        "    make_weight_view(require(w.layers[{layer}].{member}, \"{weight}\"), w.layers[{layer}].{quant}),"
                    ));
                    b.stmt(&format!("    {out}, N, {width}, H);"));
                }
                // Post-norm landings (olmo2): the sub-layer output goes to
                // the norm_x scratch at beta=0; Rmsnorm + ResidualAdd land
                // it — the interpreter's post-norm arms verbatim.
                ("o_proj", false) => {
                    b.stmt("ops::gemm_act_x_w(cublas.handle(),");
                    b.stmt("    ws.attn_out.data(),");
                    b.stmt(&format!(
                        "    make_weight_view(require(w.layers[{layer}].o_proj, \"{weight}\"), w.layers[{layer}].o_proj_quant),"
                    ));
                    b.stmt("    ws.norm_x.data(), N, H, Hq, 0.f);");
                }
                ("down", false) => {
                    b.stmt("ops::gemm_act_x_w(cublas.handle(),");
                    b.stmt("    ws.gate.data(),");
                    b.stmt(&format!(
                        "    make_weight_view(require(w.layers[{layer}].down_proj, \"{weight}\"), w.layers[{layer}].down_proj_quant),"
                    ));
                    b.stmt("    ws.norm_x.data(), N, H, I, 0.f);");
                }
                (other, beta) => {
                    panic!("emitter: matmul field {other} (beta_one={beta}) out of scope")
                }
            }
        }
        OpKind::SplitQkv { .. } => {
            match win {
                Some(Win::Host { start: s, len: n }) => {
                    // A Peel region's split: the window's rows at their
                    // absolute offsets (the interpreter's windowed form).
                    b.stmt("kernels::launch_split_qkv_bf16(");
                    b.stmt(&format!(
                        "    bf16_row(ws.qkv_fused.data(), {s}, Hq + 2 * Hk),"
                    ));
                    b.stmt(&format!("    bf16_row(ws.q.data(), {s}, Hq),"));
                    b.stmt(&format!("    bf16_row(ws.k.data(), {s}, Hk),"));
                    b.stmt(&format!("    bf16_row(ws.v.data(), {s}, Hk),"));
                    b.stmt(&format!("    {n}, Hq, Hk, stream);"));
                }
                Some(Win::DevTail) => {
                    b.stmt("kernels::launch_split_qkv_bf16_devwin(");
                    b.stmt("    ws.qkv_fused.data(),");
                    b.stmt("    ws.q.data(), ws.k.data(), ws.v.data(),");
                    b.stmt("    peel_window_d, N, Hq, Hk, stream);");
                }
                Some(Win::DevPrefix) => {
                    panic!("emitter: the tail split in a Peel prefix region")
                }
                Some(Win::MaskPrefix) | Some(Win::MaskTail) => {
                    panic!("emitter: the qkv split in a mask peel region")
                }
                None => {
                    b.stmt("kernels::launch_split_qkv_bf16(");
                    b.stmt("    ws.qkv_fused.data(),");
                    b.stmt("    ws.q.data(), ws.k.data(), ws.v.data(),");
                    b.stmt("    N, Hq, Hk, stream);");
                }
            }
        }
        OpKind::Rope { kind, partial } => {
            assert!(partial.is_none(), "emitter: partial rope out of scope");
            assert_eq!(
                *kind,
                crate::trace::RopeKind::Standard,
                "emitter: only standard rope"
            );
            b.stmt("kernels::launch_rope_bf16(");
            b.stmt("    ws.q.data(), ws.k.data(), positions,");
            b.stmt("    N, num_q_heads, num_kv_heads, d,");
            b.stmt("    cfg.rope_theta, stream);");
        }
        OpKind::ResidualAdd => {
            // The post-norm landing: `y += norm_y` — the interpreter's
            // arm verbatim.
            b.stmt("kernels::launch_residual_add_bf16(");
            b.stmt("    ws.y.data(), ws.norm_y.data(),");
            b.stmt("    static_cast<std::size_t>(N) * H, stream);");
        }
        OpKind::KvAppend { layer } => {
            // Unpadded shape: no pad staging. The write mechanism is a
            // per-fire RUNTIME input (Guard's territory, see
            // declared_forward.hpp); both branches are the interpreter's.
            b.stmt(&format!("{{"));
            b.stmt(&format!(
                "    auto kv_view = cache.layer_view({layer});"
            ));
            b.stmt("    if (has_write_desc) {");
            b.stmt("        kernels::launch_write_kv_explicit_bf16(");
            b.stmt("            kv_view, ws.k.data(), ws.v.data(),");
            b.stmt("            w_page_d, w_off_d, N, stream, row_valid_d);");
            b.stmt("    } else {");
            b.stmt("        kernels::launch_write_kv_to_pages(");
            b.stmt("            kv_view, ws.k.data(), ws.v.data(),");
            b.stmt("            qo_indptr, kv_page_indices, kv_page_indptr,");
            b.stmt("            kv_last_page_lens,");
            b.stmt("            N, R, stream, row_valid_d);");
            b.stmt("    }");
            b.stmt("}");
        }
        OpKind::Swiglu { .. } => {
            // Paired with the gate_up binding dispatch emitted just above;
            // the flag name carries the layer, so nested blocks stay
            // scope-correct in the unrolled file.
            let layer = op
                .layer
                .expect("swiglu is a layer op in every llama_like trace");
            b.stmt(&format!("if (gate_up_fused_{layer}) {{"));
            b.stmt("    kernels::launch_chunked_swiglu_bf16(");
            b.stmt("        ws.gate_up_fused.data(), ws.gate.data(), N, I, stream);");
            b.stmt("} else {");
            b.stmt("    kernels::launch_swiglu_bf16(");
            b.stmt("        ws.gate.data(), ws.up.data(), ws.gate.data(),");
            b.stmt("        N * I, stream);");
            b.stmt("}");
        }
        OpKind::LmHead { weight } => {
            let member = match weight.as_str() {
                "embed" => "w.embed",
                "lm_head" => "w.lm_head",
                other => panic!("emitter: lm_head weight {other} out of scope"),
            };
            b.stmt("if (fwd_cfg.emit_logits) {");
            b.stmt("    // The hand-written epilogue, the interpreter's arm verbatim");
            b.stmt("    // (compact logits are a per-fire runtime input).");
            b.stmt("    const bool compact_logits =");
            b.stmt("        logit_row_indices_d != nullptr && num_logit_rows > 0 &&");
            b.stmt("        num_logit_rows < N;");
            b.stmt("    const void* lm_head_input = nullptr;");
            b.stmt("    int lm_head_rows = N;");
            b.stmt("    if (compact_logits) {");
            b.stmt("        kernels::launch_gather_bf16_rows(");
            b.stmt("            static_cast<const std::uint16_t*>(ws.y.data()),");
            b.stmt("            logit_row_indices_d,");
            b.stmt("            static_cast<std::uint16_t*>(ws.norm_x.data()),");
            b.stmt("            num_logit_rows, H, stream);");
            b.stmt("        kernels::launch_rmsnorm_bf16(");
            b.stmt("            ws.norm_x.data(), w.final_norm->data(),");
            b.stmt("            ws.norm_y.data(), num_logit_rows, H, eps, stream);");
            b.stmt("        lm_head_input = ws.norm_y.data();");
            b.stmt("        lm_head_rows = num_logit_rows;");
            b.stmt("    } else {");
            b.stmt("        kernels::launch_rmsnorm_bf16(");
            b.stmt("            ws.y.data(), w.final_norm->data(), ws.norm_y.data(),");
            b.stmt("            N, H, eps, stream);");
            b.stmt("        lm_head_input = ws.norm_y.data();");
            b.stmt("    }");
            b.stmt("    ops::gemm_act_x_w(cublas.handle(),");
            b.stmt(&format!(
                "        lm_head_input, ops::WeightView(*require({member}, \"{weight}\")),"
            ));
            b.stmt("        ws.logits.data(), lm_head_rows, V, H);");
            b.stmt("}");
        }
        OpKind::Launch {
            kernel,
            weights,
            state,
        } => emit_launch(
            b, kernel, weights, state.as_ref(), op, facts, cuda,
            is_decode, win, depth_active,
        ),
        OpKind::HookSite { stage, layer } => {
            // The interpreter's site handler, transliterated with the
            // stage and layer as constants. Null hooks skip everything
            // (argument no-op, zero launches).
            b.stmt("if (hooks != nullptr) {");
            match stage {
                crate::trace::HookStage::OnAttnProj => {
                    b.stmt("    attn_page_indices = kv_page_indices;");
                    b.stmt("    attn_page_indptr = kv_page_indptr;");
                    b.stmt("    attn_last_page_lens = kv_last_page_lens;");
                    b.stmt("    page_mask.begin_layer(stream);");
                    if is_decode {
                        b.stmt(&format!(
                            "    score_capture.emplace(hooks, {layer}u,"
                        ));
                        b.stmt("        static_cast<std::uint32_t>(num_q_heads),");
                        b.stmt("        /*capturable=*/true, stream);");
                    } else {
                        b.stmt(&format!(
                            "    prefill_score_capture.emplace(hooks, {layer}u,"
                        ));
                        b.stmt("        static_cast<std::uint32_t>(num_q_heads),");
                        b.stmt("        plan_state.prefill_score_window,");
                        b.stmt("        /*capturable=*/true, stream);");
                    }
                    b.stmt("    invoke_stage_hook(");
                    b.stmt("        hooks, StageHookPoint::OnAttnProj, ws.q.data(),");
                    b.stmt("        static_cast<std::uint32_t>(N),");
                    b.stmt("        static_cast<std::uint32_t>(Hq),");
                    b.stmt(&format!("        {layer}u, stream, /*query_is_f32=*/false,"));
                    b.stmt("        {.mask_sink = page_mask.sink()});");
                }
                crate::trace::HookStage::OnAttn => {
                    b.stmt("    invoke_stage_hook(");
                    b.stmt("        hooks, StageHookPoint::OnAttn, ws.q.data(),");
                    b.stmt("        static_cast<std::uint32_t>(N),");
                    b.stmt("        static_cast<std::uint32_t>(Hq),");
                    b.stmt(&format!("        {layer}u, stream, /*query_is_f32=*/false,"));
                    if is_decode {
                        b.stmt("        {.scores = score_capture ? score_capture->scores()");
                        b.stmt("                                 : nullptr});");
                    } else {
                        b.stmt("        {.scores = prefill_score_capture");
                        b.stmt("             ? prefill_score_capture->scores()");
                        b.stmt("             : nullptr});");
                    }
                }
            }
            b.stmt("}");
        }
        other => panic!("emitter: op kind {other:?} out of scope for the qwen3 classes"),
    }
}


/// The page-mask bracket the interpreter's `resolve_masked_pages` runs
/// before an attention launch, emitted with the layer constant. A
/// written mask substitutes the layer's page list into the SAME stated
/// kernel — legal only on the page-count-independent paged decode plan
/// (the hand-written contract; anything else throws).
fn emit_masked_pages_bracket(b: &mut Body, layer: u32, takes_paged_decode: bool) {
    b.stmt(&format!("if (page_mask.written_for({layer}u)) {{"));
    if takes_paged_decode {
        b.stmt("    if (!plan_state.decode_plan) {");
        b.stmt("        throw std::runtime_error(");
        b.stmt("            \"attn_page_mask was written but this layer does \"");
        b.stmt("            \"not take the paged decode path\");");
        b.stmt("    }");
        b.stmt("    if (!ops::decode_plan_is_page_count_independent(");
        b.stmt("            *plan_state.decode_plan)) {");
        b.stmt("        throw std::runtime_error(");
        b.stmt("            \"attn_page_mask requires a page-count-independent \"");
        b.stmt("            \"decode plan; this fire planned split-KV\");");
        b.stmt("    }");
        b.stmt("    page_mask.compact(");
        b.stmt("        kv_page_indices, kv_page_indptr, kv_last_page_lens,");
        b.stmt("        static_cast<std::uint32_t>(R), stream);");
        b.stmt("    attn_page_indices = page_mask.page_indices();");
        b.stmt("    attn_page_indptr = page_mask.page_indptr();");
        b.stmt("    attn_last_page_lens = page_mask.last_page_lens();");
    } else {
        b.stmt("    throw std::runtime_error(");
        b.stmt("        \"attn_page_mask was written but this layer does \"");
        b.stmt("        \"not take the paged decode path\");");
    }
    b.stmt("}");
}

fn emit_launch(
    b: &mut Body,
    kernel: &str,
    weights: &[String],
    state: Option<&crate::trace::StateRef>,
    op: &crate::trace::Op,
    facts: &LlamaLikeFacts,
    cuda: &LlamaLikeCudaFacts,
    is_decode: bool,
    win: Option<Win>,
    depth_active: bool,
) {
    // Padded head dim (Phi-3): the attention consumes the zero-padded
    // `dk` staging copies and the softmax keeps the real-dim scale —
    // all resolved AT EMISSION (the interpreter's `head_dim_padded`
    // locals become constants of this deployment's text).
    let padded = cuda.head_dim_padded;
    let q_buf = if padded { "attn_q" } else { "ws.q.data()" };
    let out_buf = if padded {
        "attn_out_buf"
    } else {
        "ws.attn_out.data()"
    };
    let scale = if padded {
        "sm_scale_override"
    } else {
        "/*sm_scale_override=*/-1.f"
    };
    // The post-attention strip (padded only): the o_proj GEMM reads the
    // logical-width ws.attn_out; every attention launch's output gets
    // stripped into it — the interpreter's name-keyed strip block.
    let strip = |b: &mut Body| {
        if padded {
            b.stmt("kernels::launch_strip_head_dim_bf16(");
            b.stmt("    attn_out_buf, ws.attn_out.data(),");
            b.stmt("    N, num_q_heads, d, dk, stream);");
        }
    };
    match kernel {
        "launch_rope_standard_table" => {
            b.stmt("if (ws.rope_table.empty()) {");
            b.stmt("    throw std::runtime_error(");
            b.stmt("        \"generated forward: no rope table in workspace\");");
            b.stmt("}");
            b.stmt("kernels::launch_rope_standard_table(");
            b.stmt("    positions,");
            b.stmt("    static_cast<float*>(ws.rope_table.data()),");
            b.stmt("    N, d, cfg.rope_theta, stream);");
        }
        "launch_qkv_decode_qk_norm_rope_write_kv_bf16" => {
            assert!(
                !padded,
                "emitter: the fused decode epilogue requires the unpadded \
                 head dim (its facts predicate); a padded emission is drift"
            );
            let layer = state.expect("fused post addresses kv state").layer;
            let (q_norm, k_norm) = (&weights[0], &weights[1]);
            let (ql, _) = split_layer_weight(q_norm).expect("q_norm layer");
            // The trace says whether the table value exists (second input).
            let table = if op.inputs.len() >= 2 {
                "static_cast<const float*>(ws.rope_table.data())"
            } else {
                "nullptr"
            };
            if matches!(win, Some(Win::DevPrefix)) {
                // Device-window capture: the prefix form — the word's
                // START is this kernel's row count.
                b.stmt("kernels::launch_qkv_decode_qk_norm_rope_write_kv_bf16_devwin(");
                b.stmt("    ws.qkv_fused.data(),");
                b.stmt("    ws.q.data(),");
                b.stmt(&format!("    cache.k({layer}), cache.v({layer}),"));
                b.stmt(&format!("    {},", require(ql, "q_norm", q_norm)));
                b.stmt(&format!("    {},", require(ql, "k_norm", k_norm)));
                b.stmt("    positions,");
                b.stmt(&format!("    {table},"));
                b.stmt("    kv_page_indices, kv_page_indptr, kv_last_page_lens,");
                b.stmt("    has_write_desc ? w_page_d : nullptr,");
                b.stmt("    has_write_desc ? w_off_d : nullptr,");
                b.stmt("    row_valid_d,");
                b.stmt("    peel_window_d,");
                b.stmt("    N, num_q_heads, num_kv_heads, d,");
                b.stmt("    cache.page_size(), cache.hnd_layout(),");
                b.stmt("    cfg.rope_theta, eps, stream);");
                return;
            }
            b.stmt("kernels::launch_qkv_decode_qk_norm_rope_write_kv_bf16(");
            b.stmt("    ws.qkv_fused.data(),");
            b.stmt("    ws.q.data(),");
            b.stmt(&format!("    cache.k({layer}), cache.v({layer}),"));
            b.stmt(&format!("    {},", require(ql, "q_norm", q_norm)));
            b.stmt(&format!("    {},", require(ql, "k_norm", k_norm)));
            b.stmt("    positions,");
            b.stmt(&format!("    {table},"));
            b.stmt("    kv_page_indices, kv_page_indptr, kv_last_page_lens,");
            b.stmt("    has_write_desc ? w_page_d : nullptr,");
            b.stmt("    has_write_desc ? w_off_d : nullptr,");
            b.stmt("    row_valid_d,");
            // Windowed (A3): a Peel's prefix region owns rows
            // [0, fast_rows); outside a peel this is R (pure decode).
            let rows = match win {
                Some(Win::Host { len, .. }) => len,
                Some(Win::DevTail) => {
                    panic!("emitter: the fused epilogue in a Peel tail region")
                }
                Some(Win::DevPrefix) => unreachable!(),
                Some(Win::MaskPrefix) | Some(Win::MaskTail) => {
                    panic!("emitter: the fused epilogue in a mask peel region")
                }
                None => "R",
            };
            b.stmt(&format!("    {rows}, num_q_heads, num_kv_heads, d,"));
            b.stmt("    cache.page_size(), cache.hnd_layout(),");
            b.stmt("    cfg.rope_theta, eps, stream);");
        }
        "launch_write_kv_explicit_bf16" => {
            let layer = state.expect("kv write addresses kv state").layer;
            if matches!(win, Some(Win::DevTail)) {
                b.stmt(&format!("{{"));
                b.stmt(&format!("    auto kv_view = cache.layer_view({layer});"));
                b.stmt("    kernels::launch_write_kv_explicit_bf16_devwin(");
                b.stmt("        kv_view, ws.k.data(), ws.v.data(),");
                b.stmt("        w_page_d, w_off_d,");
                b.stmt("        peel_window_d, N, stream, row_valid_d);");
                b.stmt("}");
                return;
            }
            let (s_, n_) = match win {
                Some(Win::Host { start, len }) => (start, len),
                None => ("0", "N"),
                Some(_) => panic!("emitter: KV write in a Peel prefix region"),
            };
            if padded {
                // A windowed write never coincides with padding (the Peel
                // exists only in the fused deployment, whose facts require
                // the unpadded head dim) — same invariant as the
                // interpreter's comment, checked at emission.
                assert!(win.is_none(), "emitter: windowed write under padding");
                b.stmt("kernels::launch_pad_head_dim_bf16(");
                b.stmt("    ws.q.data(), attn_q, N, num_q_heads, d, dk, stream);");
                b.stmt("kernels::launch_pad_head_dim_bf16(");
                b.stmt("    ws.k.data(), attn_k, N, num_kv_heads, d, dk, stream);");
                b.stmt("kernels::launch_pad_head_dim_bf16(");
                b.stmt("    ws.v.data(), attn_v, N, num_kv_heads, d, dk, stream);");
            }
            let (kbuf, vbuf) = if padded {
                ("attn_k", "attn_v")
            } else {
                ("ws.k.data()", "ws.v.data()")
            };
            b.stmt(&format!("{{"));
            b.stmt(&format!("    auto kv_view = cache.layer_view({layer});"));
            b.stmt("    kernels::launch_write_kv_explicit_bf16(");
            b.stmt("        kv_view,");
            b.stmt(&format!("        bf16_row({kbuf}, {s_}, Hk),"));
            b.stmt(&format!("        bf16_row({vbuf}, {s_}, Hk),"));
            b.stmt(&format!("        w_page_d + {s_}, w_off_d + {s_},"));
            b.stmt(&format!("        {n_}, stream,"));
            b.stmt(&format!(
                "        row_valid_d != nullptr ? row_valid_d + {s_} : nullptr);"
            ));
            b.stmt("}");
        }
        "launch_write_kv_to_pages" => {
            let layer = state.expect("kv write addresses kv state").layer;
            if padded {
                assert!(win.is_none(), "emitter: windowed write under padding");
                b.stmt("kernels::launch_pad_head_dim_bf16(");
                b.stmt("    ws.q.data(), attn_q, N, num_q_heads, d, dk, stream);");
                b.stmt("kernels::launch_pad_head_dim_bf16(");
                b.stmt("    ws.k.data(), attn_k, N, num_kv_heads, d, dk, stream);");
                b.stmt("kernels::launch_pad_head_dim_bf16(");
                b.stmt("    ws.v.data(), attn_v, N, num_kv_heads, d, dk, stream);");
            }
            let kv_bufs = if padded {
                "kv_view, attn_k, attn_v,"
            } else {
                "kv_view, ws.k.data(), ws.v.data(),"
            };
            if matches!(win, Some(Win::DevTail)) {
                b.stmt(&format!("{{"));
                b.stmt(&format!(
                    "    auto kv_view = cache.layer_view({layer});"
                ));
                b.stmt("    kernels::launch_write_kv_to_pages_bf16_devwin(");
                b.stmt(&format!("        {kv_bufs}"));
                b.stmt("        qo_indptr, kv_page_indices, kv_page_indptr,");
                b.stmt("        kv_last_page_lens,");
                b.stmt("        peel_window_d, N, R, stream, row_valid_d);");
                b.stmt("}");
                return;
            }
            b.stmt(&format!("{{"));
            b.stmt(&format!("    auto kv_view = cache.layer_view({layer});"));
            let first = match win {
                Some(Win::Host { start, .. }) => start,
                None => "0",
                Some(_) => panic!("emitter: KV write in a Peel prefix region"),
            };
            b.stmt("    kernels::launch_write_kv_to_pages(");
            b.stmt(&format!("        {kv_bufs}"));
            b.stmt("        qo_indptr, kv_page_indices, kv_page_indptr,");
            b.stmt("        kv_last_page_lens,");
            b.stmt(&format!(
                "        N, R, stream, row_valid_d, /*first_token=*/{first});"
            ));
            b.stmt("}");
        }
        "launch_qk_rmsnorm_rope_bf16" => {
            let (q_norm, k_norm) = (&weights[0], &weights[1]);
            let (ql, _) = split_layer_weight(q_norm).expect("q_norm layer");
            if matches!(win, Some(Win::DevTail)) {
                b.stmt("kernels::launch_qk_rmsnorm_rope_bf16_devwin(");
                b.stmt("    ws.q.data(), ws.k.data(),");
                b.stmt(&format!("    {},", require(ql, "q_norm", q_norm)));
                b.stmt(&format!("    {},", require(ql, "k_norm", k_norm)));
                b.stmt("    positions,");
                b.stmt("    peel_window_d, N,");
                b.stmt("    num_q_heads, num_kv_heads, d,");
                b.stmt("    cfg.rope_theta, eps, stream);");
                return;
            }
            let (s_, n_) = match win {
                Some(Win::Host { start, len }) => (start, len),
                None => ("0", "N"),
                Some(_) => {
                    panic!("emitter: qk-norm+rope in a Peel prefix region")
                }
            };
            b.stmt("kernels::launch_qk_rmsnorm_rope_bf16(");
            b.stmt(&format!("    bf16_row(ws.q.data(), {s_}, Hq),"));
            b.stmt(&format!("    bf16_row(ws.k.data(), {s_}, Hk),"));
            b.stmt(&format!("    {},", require(ql, "q_norm", q_norm)));
            b.stmt(&format!("    {},", require(ql, "k_norm", k_norm)));
            b.stmt(&format!("    positions + {s_}, {n_},"));
            b.stmt("    num_q_heads, num_kv_heads, d,");
            b.stmt("    cfg.rope_theta, eps, stream);");
        }
        "launch_attention_xqa_decode_bf16_prepared" => {
            assert!(
                !padded,
                "emitter: XQA with a padded head dim has no deployment and \
                 no hand-written reference — refuse rather than guess"
            );
            let layer = state.expect("attention addresses kv state").layer;
            emit_masked_pages_bracket(b, layer, /*takes_paged_decode=*/false);
            b.stmt(&format!("{{"));
            b.stmt(&format!(
                "    auto kv_view = cache.layer_view({layer});"
            ));
            b.stmt("    ops::launch_attention_xqa_decode_bf16_prepared(");
            b.stmt("        ws.q.data(), kv_view.k_bf16_pages, kv_view.v_bf16_pages,");
            b.stmt("        ws.attn_out.data(),");
            b.stmt("        R, num_q_heads, num_kv_heads, d,");
            b.stmt("        cache.page_size(), plan_state.xqa_max_pages_per_seq,");
            b.stmt("        attn_ws, stream, /*sm_scale_override=*/-1.f);");
            b.stmt("}");
        }
        "launch_dequant_kv_cache_layer_to_bf16_active" => {
            let layer = state.expect("dequant addresses kv state").layer;
            // In a mask peel's prefix region the staging covers the
            // PLAIN lanes' pages only — `kv_page_indptr_h[split]`.
            // Beyond the split the host CSR may be a composed-envelope
            // placeholder, and the suffix's custom dispatch takes the
            // layer view whole (no staging) anyway.
            let pages = if win == Some(Win::MaskPrefix) {
                "kv_page_indptr_h[split]"
            } else {
                "kv_page_indptr_h[R]"
            };
            b.stmt(&format!("{{"));
            b.stmt(&format!(
                "    auto kv_view = cache.layer_view({layer});"
            ));
            b.stmt("    kernels::launch_dequant_kv_cache_layer_to_bf16_active(");
            b.stmt(&format!(
                "        kv_view, kv_page_indices, {pages}, stream);"
            ));
            b.stmt("}");
        }
        "dispatch_attention_flashinfer_prefill_bf16" => {
            let layer = state.expect("attention addresses kv state").layer;
            // The class is static here: this function IS the prefill (or
            // the decode force_prefill fallback) — the plan-cache binding
            // the interpreter derives from `is_pure_decode` is a constant.
            // And on the DECODE side the whole question is static: the
            // only decode-class trace that states this launch is the
            // force_prefill arm, whose prepare deliberately builds no
            // plan (llama_like.cpp's early return) — so the generated
            // form emits the hand-written final else's PLAN-LESS
            // launcher directly, no runtime plan check at all (the
            // interpreter needs the fallback branch; the emitter does
            // not).
            if is_decode {
                b.stmt(&format!("{{"));
                b.stmt(&format!(
                    "    auto kv_view = cache.layer_view({layer});"
                ));
                b.stmt(&format!(
                    "    const int layer_window_left ="
                ));
                b.stmt(&format!(
                    "        (!fwd_cfg.per_layer_window_left.empty() &&"
                ));
                b.stmt(&format!(
                    "         {layer} < static_cast<int>(fwd_cfg.per_layer_window_left.size()))"
                ));
                b.stmt(&format!(
                    "            ? fwd_cfg.per_layer_window_left[{layer}]"
                ));
                b.stmt("            : fwd_cfg.sliding_window;");
                // A mask peel's prefix region: the plan-free launcher
                // over the plain rows — pure decode, so tokens == rows
                // == split, and every CSR's `[0, split]` head is the
                // prefix's truth (the launcher reads no further).
                let (n_rows, n_reqs) = if win == Some(Win::MaskPrefix) {
                    ("split_rows", "split")
                } else {
                    ("N", "R")
                };
                b.stmt("    ops::launch_attention_flashinfer_prefill(");
                b.stmt(&format!("        {q_buf}, kv_view, {out_buf},"));
                b.stmt("        qo_indptr, kv_page_indices, kv_page_indptr,");
                b.stmt("        kv_last_page_lens,");
                b.stmt("        qo_indptr_h, kv_page_indptr_h,");
                b.stmt(&format!(
                    "        {n_rows}, {n_reqs}, num_q_heads, attn_ws, stream,"
                ));
                b.stmt("        layer_window_left,");
                b.stmt("        /*logits_soft_cap=*/0.f,");
                b.stmt(&format!("        {scale});"));
                strip(b);
                b.stmt("}");
                return;
            }
            let plan_cache = "plan_state.prefill_plan";
            b.stmt(&format!("if (!{plan_cache}) {{"));
            b.stmt("    throw std::runtime_error(");
            b.stmt("        \"generated forward: prepare built no prefill plan\");");
            b.stmt("}");
            b.stmt(&format!("{{"));
            b.stmt(&format!(
                "    auto kv_view = cache.layer_view({layer});"
            ));
            b.stmt("    ops::dispatch_attention_flashinfer_prefill_bf16(");
            b.stmt(&format!("        *{plan_cache},"));
            b.stmt(&format!(
                "        {q_buf}, kv_view.k_bf16_pages, kv_view.v_bf16_pages,"
            ));
            b.stmt(&format!("        {out_buf},"));
            b.stmt("        qo_indptr, kv_page_indices, kv_page_indptr,");
            b.stmt("        kv_last_page_lens,");
            b.stmt("        attn_ws, stream, /*logits_soft_cap=*/0.f,");
            b.stmt(&format!("        {scale});"));
            strip(b);
            b.stmt("}");
        }
        "dispatch_attention_flashinfer_decode" => {
            let layer = state.expect("attention addresses kv state").layer;
            if win == Some(Win::MaskPrefix) {
                // The UnmaskedPrefix peel's PREFIX region (NS-4/AC-4):
                // the decode dispatch over the plain rows `[0, split)`.
                // Hooked lanes ride this prefix, so the dispatch
                // consumes the ATTN page views (hook-narrowed when
                // sites ran; raw aliases otherwise) — the bracket is
                // the interpreter's resolve_masked_pages.
                emit_masked_pages_bracket(b, layer, /*takes_paged_decode=*/true);
                b.stmt("if (!plan_state.decode_plan) {");
                b.stmt("    throw std::runtime_error(");
                b.stmt("        \"spatial mask: split active but prepare built \"");
                b.stmt("        \"no prefix decode plan\");");
                b.stmt("}");
                b.stmt(&format!("{{"));
                b.stmt(&format!(
                    "    auto kv_view = cache.layer_view({layer});"
                ));
                b.stmt(&format!(
                    "    const int layer_window_left ="
                ));
                b.stmt(&format!(
                    "        (!fwd_cfg.per_layer_window_left.empty() &&"
                ));
                b.stmt(&format!(
                    "         {layer} < static_cast<int>(fwd_cfg.per_layer_window_left.size()))"
                ));
                b.stmt(&format!(
                    "            ? fwd_cfg.per_layer_window_left[{layer}]"
                ));
                b.stmt("            : fwd_cfg.sliding_window;");
                b.stmt("    ops::dispatch_attention_flashinfer_decode(");
                b.stmt("        *plan_state.decode_plan,");
                b.stmt(&format!("        {q_buf}, kv_view, {out_buf},"));
                b.stmt("        attn_page_indices, attn_page_indptr,");
                b.stmt("        attn_last_page_lens,");
                b.stmt("        attn_ws, stream, layer_window_left,");
                b.stmt(&format!(
                    "        /*logits_soft_cap=*/0.f, {scale});"
                ));
                strip(b);
                b.stmt("}");
                return;
            }
            emit_masked_pages_bracket(b, layer, /*takes_paged_decode=*/true);
            // Per-layer window resolution is RUNTIME cfg reads
            // (per_layer_window_left / sliding_window) — placement-
            // independent, so post-norm deployments emit it unchanged.
            if depth_active {
                // STRUCTURAL S-4: a depth-tail layer's attention pairs
                // the PREFIX plan with its dedicated workspace (the
                // plan/workspace pairing rule); `depth_tail` is the
                // enclosing layer scope's static-L bool.
                b.stmt("const ops::DecodePlanCache* depth_dp = depth_tail");
                b.stmt("    ? plan_state.depth_prefix_decode_plan.get()");
                b.stmt("    : plan_state.decode_plan.get();");
                b.stmt("if (depth_dp == nullptr) {");
                b.stmt("    throw std::runtime_error(");
                b.stmt("        \"generated forward: prepare built no decode \"");
                b.stmt("        \"plan for this depth range\");");
                b.stmt("}");
            } else {
                b.stmt("if (!plan_state.decode_plan) {");
                b.stmt("    throw std::runtime_error(");
                b.stmt("        \"generated forward: prepare built no decode plan\");");
                b.stmt("}");
            }
            b.stmt(&format!("{{"));
            b.stmt(&format!(
                "    auto kv_view = cache.layer_view({layer});"
            ));
            b.stmt(&format!(
                "    const int layer_window_left ="
            ));
            b.stmt(&format!(
                "        (!fwd_cfg.per_layer_window_left.empty() &&"
            ));
            b.stmt(&format!(
                "         {layer} < static_cast<int>(fwd_cfg.per_layer_window_left.size()))"
            ));
            b.stmt(&format!(
                "            ? fwd_cfg.per_layer_window_left[{layer}]"
            ));
            b.stmt("            : fwd_cfg.sliding_window;");
            if depth_active {
                b.stmt("    ops::dispatch_attention_flashinfer_decode(");
                b.stmt("        *depth_dp,");
                b.stmt(&format!("        {q_buf}, kv_view, {out_buf},"));
                b.stmt("        attn_page_indices, attn_page_indptr,");
                b.stmt("        attn_last_page_lens,");
                b.stmt("        depth_tail ? spatial_suffix_attn_ws() : attn_ws,");
                b.stmt("        stream, layer_window_left,");
                b.stmt(&format!(
                    "        /*logits_soft_cap=*/0.f, {scale});"
                ));
            } else {
                b.stmt("    ops::dispatch_attention_flashinfer_decode(");
                b.stmt("        *plan_state.decode_plan,");
                b.stmt(&format!("        {q_buf}, kv_view, {out_buf},"));
                b.stmt("        attn_page_indices, attn_page_indptr,");
                b.stmt("        attn_last_page_lens,");
                b.stmt("        attn_ws, stream, layer_window_left,");
                b.stmt(&format!(
                    "        /*logits_soft_cap=*/0.f, {scale});"
                ));
            }
            strip(b);
            b.stmt("}");
        }
        "dispatch_attention_flashinfer_prefill_custom" => {
            // The custom-mask arm (A1): the custom dispatch takes the
            // layer view whole (no dequant), and the mask data rides as
            // runtime args of the stated kernel — the interpreter's
            // handler, minus the choosing. The plan SLOT is the class's:
            // masked pure-decode fires own `mask_decode_plan` (the
            // supergraph axiom — no mutable plan sharing across fire
            // classes), prefill-shaped masked fires keep `prefill_plan`.
            let layer = state.expect("attention addresses kv state").layer;
            // The suffix plan lives in the DEDICATED slot for every
            // planned peel tail (both classes — the mixed fire's prefill
            // slot holds the PREFIX CAUSAL plan); fire-level
            // prefill-shaped masked fires keep the prefill slot.
            let plan_cache = if is_decode || win == Some(Win::MaskTail) {
                "plan_state.mask_decode_plan"
            } else {
                "plan_state.prefill_plan"
            };
            b.stmt(&format!("if (!{plan_cache}) {{"));
            b.stmt("    throw std::runtime_error(");
            b.stmt("        \"generated forward: prepare built no custom-mask plan\");");
            b.stmt("}");
            b.stmt(&format!("{{"));
            b.stmt(&format!(
                "    auto kv_view = cache.layer_view({layer});"
            ));
            match win {
                // The UnmaskedPrefix peel's TAIL region (NS-4 in the
                // IR): the choosing is the TRACE's — this arm spells
                // only the region's addressing. Hybrid, measured live:
                // the kernel's q/o rows are plan/qo[0]-relative
                // (offset pointers + the identity qo), the KV side
                // reads the device CSR ABSOLUTELY (base indices +
                // `+split` indptr — the composed device truth, no host
                // rebase). `split` is the peel's emitted local.
                Some(Win::MaskTail) => {
                    // The workspace pairs with the PLAN's: the decode
                    // class plans the suffix into attn_ws (its prefix
                    // is a DECODE plan — no prefill-family collision),
                    // the mixed/prefill class into the dedicated
                    // suffix workspace (its prefix causal plan owns
                    // attn_ws).
                    let ws = if is_decode {
                        "attn_ws"
                    } else {
                        "spatial_suffix_attn_ws()"
                    };
                    b.stmt("    ops::dispatch_attention_flashinfer_prefill_custom(");
                    b.stmt(&format!("        *{plan_cache},"));
                    b.stmt(&format!(
                        "        bf16_row({q_buf}, split_rows, Hq), kv_view,"
                    ));
                    b.stmt(&format!(
                        "        bf16_row({out_buf}, split_rows, Hq),"
                    ));
                    b.stmt("        mask_suffix_qo_indptr_d,");
                    b.stmt("        kv_page_indices,");
                    b.stmt("        kv_page_indptr + split,");
                    b.stmt("        kv_last_page_lens + split,");
                    b.stmt("        custom_mask_d, custom_mask_indptr_d + split,");
                    b.stmt(&format!("        {ws}, stream);"));
                }
                // Fire-level: outside a peel (prefill-shaped masked
                // fires, padded/XQA deployments) and the peel's
                // UNPLANNED endpoint alike.
                None => {
                    b.stmt("    ops::dispatch_attention_flashinfer_prefill_custom(");
                    b.stmt(&format!("        *{plan_cache},"));
                    b.stmt(&format!("        {q_buf}, kv_view, {out_buf},"));
                    b.stmt("        qo_indptr, kv_page_indices, kv_page_indptr,");
                    b.stmt("        kv_last_page_lens, custom_mask_d, custom_mask_indptr_d,");
                    b.stmt("        attn_ws, stream);");
                }
                Some(_) => panic!(
                    "emitter: the custom dispatch in a foreign peel region"
                ),
            }
            strip(b);
            b.stmt("}");
        }
        "pie_lora_qkv_correction" => {
            // The §5.1 correction, statically: the layer is the op's own
            // tag (a constant here), the buffers the interpreter's.
            let layer = op
                .layer
                .expect("lora correction carries its layer tag");
            b.stmt("if (lora_staged == nullptr && !lora_state) {");
            b.stmt("    throw std::runtime_error(");
            b.stmt("        \"generated forward: lora correction stated but no \"");
            b.stmt("        \"usable lora table (guard/pred drift)\");");
            b.stmt("}");
            let qkv_in = if facts.norm_placement == NormPlacement::Post {
                "ws.y.data()"
            } else {
                "ws.norm_x.data()"
            };
            b.stmt("(lora_staged != nullptr ? *lora_staged : *lora_state)");
            b.stmt("    .apply(");
            b.stmt(&format!("    cublas.handle(), {layer}, {qkv_in},"));
            b.stmt("    H, Hq, Hk,");
            b.stmt("    ws.q.data(), ws.v.data(), ws.gate.data());");
        }
        "dispatch_attention_flashinfer_decode_capture" => {
            // The interpreter's capture-decode handler, layer constant.
            let layer = state.expect("attention addresses kv state").layer;
            b.stmt("if (!plan_state.decode_plan) {");
            b.stmt("    throw std::runtime_error(");
            b.stmt("        \"generated forward: prepare built no decode plan\");");
            b.stmt("}");
            b.stmt("if (!score_capture || !score_capture->active()) {");
            b.stmt("    throw std::runtime_error(");
            b.stmt("        \"generated forward: capture decode stated but no \"");
            b.stmt("        \"active score capture (guard/pred drift)\");");
            b.stmt("}");
            emit_masked_pages_bracket(b, layer, /*takes_paged_decode=*/true);
            b.stmt(&format!("{{"));
            b.stmt(&format!("    auto kv_view = cache.layer_view({layer});"));
            b.stmt("    ops::dispatch_attention_flashinfer_decode_capture(");
            b.stmt("        *plan_state.decode_plan,");
            b.stmt(&format!("        {q_buf}, kv_view, {out_buf},"));
            b.stmt("        attn_page_indices, attn_page_indptr,");
            b.stmt("        attn_last_page_lens,");
            b.stmt("        attn_ws, stream,");
            b.stmt("        score_capture->raw(), score_capture->indptr_d(),");
            b.stmt("        /*window_left=*/-1,");
            b.stmt(&format!(
                "        /*logits_soft_cap=*/0.f, {scale});"
            ));
            b.stmt("    score_capture->publish(");
            b.stmt("        attn_page_indptr, attn_last_page_lens,");
            b.stmt("        cache.page_size());");
            strip(b);
            b.stmt("}");
        }
        "dispatch_attention_flashinfer_prefill_capture_bf16" => {
            let layer = state.expect("attention addresses kv state").layer;
            let plan_cache = if is_decode {
                "plan_state.prefill_decode_plan"
            } else {
                "plan_state.prefill_plan"
            };
            b.stmt(&format!("if (!{plan_cache}) {{"));
            b.stmt("    throw std::runtime_error(");
            b.stmt("        \"generated forward: prepare built no prefill plan\");");
            b.stmt("}");
            b.stmt("if (!prefill_score_capture ||");
            b.stmt("    !prefill_score_capture->active()) {");
            b.stmt("    throw std::runtime_error(");
            b.stmt("        \"generated forward: capture prefill stated but no \"");
            b.stmt("        \"active score capture (guard/pred drift)\");");
            b.stmt("}");
            emit_masked_pages_bracket(b, layer, /*takes_paged_decode=*/false);
            b.stmt(&format!("{{"));
            b.stmt(&format!("    auto kv_view = cache.layer_view({layer});"));
            b.stmt("    ops::dispatch_attention_flashinfer_prefill_capture_bf16(");
            b.stmt(&format!("        *{plan_cache},"));
            b.stmt(&format!(
                "        {q_buf}, kv_view.k_bf16_pages, kv_view.v_bf16_pages,"
            ));
            b.stmt(&format!("        {out_buf},"));
            b.stmt("        qo_indptr, kv_page_indices, kv_page_indptr,");
            b.stmt("        kv_last_page_lens, attn_ws, stream,");
            b.stmt("        prefill_score_capture->raw(),");
            b.stmt("        prefill_score_capture->folded(),");
            b.stmt("        prefill_score_capture->indptr_d(),");
            b.stmt("        prefill_score_capture->window(),");
            b.stmt(&format!(
                "        /*logits_soft_cap=*/0.f, {scale});"
            ));
            b.stmt("    prefill_score_capture->publish();");
            strip(b);
            b.stmt("}");
        }
        other => panic!("emitter: stated kernel {other} out of scope"),
    }
}
