#pragma once

/* Generated by pie-loader-cbindgen (cbindgen). Do not edit by hand. Regenerate: cargo run -p pie-loader-cbindgen */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
namespace pie_loader {
struct PieLoaderPlan;
}


namespace pie_loader {

/// Sentinel for "no buffer", mirroring the C++ `numeric_limits<uint32_t>::max()`
/// default on `PieLoaderStorageInstrView::buffer_id`.
constexpr static const uint32_t PIE_LOADER_NO_BUFFER = UINT32_MAX;

/// Sentinel for "no source tensor", on the optional tensor-id fields.
constexpr static const uint32_t PIE_LOADER_NO_TENSOR = UINT32_MAX;

constexpr static const uint32_t PIE_LOADER_TILE_MAP_CAST = (1 << 0);

constexpr static const uint32_t PIE_LOADER_TILE_MAP_DECODE = (1 << 1);

constexpr static const uint32_t PIE_LOADER_TILE_MAP_ENCODE = (1 << 2);

constexpr static const uint32_t PIE_LOADER_TILE_MAP_TRANSCODE = (1 << 3);

constexpr static const uint32_t PIE_LOADER_TILE_MAP_REBLOCK = (1 << 4);

constexpr static const uint32_t PIE_LOADER_TILE_MAP_REPACK = (1 << 6);

constexpr static const uint32_t PIE_LOADER_TILE_MAP_SCALE = (1 << 7);

constexpr static const uint32_t PIE_LOADER_FUSION_FP8_TO_MXFP4 = (1 << 0);

/// `QuantSpec::channel_axis`, as a signed integer so that `-1` is "unset".
///
/// A sentinel rather than a second `bool` field keeps the struct a plain list
/// of numbers, which is what a designated initializer is good at.
constexpr static const int32_t PIE_LOADER_NO_AXIS = -1;

enum class PieLoaderStatus : uint32_t {
  Ok = 0,
  /// The request was malformed: a null pointer, a non-UTF-8 path, an
  /// out-of-range enum. The caller built the request wrong.
  InvalidRequest = 1,
  /// The checkpoint could not be read or does not say what the request claims.
  InvalidCheckpoint = 2,
  /// The plan was rejected against its contract. Only `pie_loader_verify`
  /// returns this.
  ContractViolation = 3,
  /// The compiler failed on input it should have handled. A bug in the loader.
  Internal = 4,
};

/// Which on-disk format a checkpoint file uses.
enum class PieLoaderCheckpointFormat : uint32_t {
  Safetensors = 0,
  Gguf = 1,
  Unknown = 2,
  /// Appended: adding a value in the middle would renumber `Unknown` under
  /// every driver already compiled against this header.
  Zt = 3,
  Npz = 4,
  Pt = 5,
  Hdf5 = 6,
  Onnx = 7,
};

enum class PieLoaderSeverity : uint32_t {
  /// The plan is still usable. Emitted so a compile can report a suboptimal
  /// choice without failing.
  Warning = 0,
  Error = 1,
};

enum class PieLoaderDType : uint32_t {
  F32 = 0,
  F16 = 1,
  BF16 = 2,
  F8E4M3 = 3,
  F8E5M2 = 4,
  I32 = 5,
  I16 = 6,
  I8 = 7,
  U32 = 8,
  U16 = 9,
  U8 = 10,
  Bool = 11,
  E8M0 = 12,
  I64 = 13,
  U64 = 14,
};

enum class PieLoaderEncodingKind : uint32_t {
  Raw = 0,
  Quant = 1,
};

/// Discriminants follow `pie_loader::types::QuantScheme` declaration order, which is
/// *not* the order of the hand-written C++ enum this replaces (`MlxAffineU4` is
/// eighth here and last there). The mismatch was invisible while the boundary
/// was JSON, because the C++ parser mapped by name. Now that the two sides share
/// integers, the generated header must be the only definition — deleting the
/// hand-written enum is part of the same change, not a follow-up.
enum class PieLoaderQuantScheme : uint32_t {
  None = 0,
  Fp8E4M3 = 1,
  Fp8E5M2 = 2,
  Int8Symmetric = 3,
  Int8Asymmetric = 4,
  AwqInt4 = 5,
  GptqInt4 = 6,
  Mxfp4E2M1E8M0 = 7,
  MlxAffineU4 = 8,
  GgufQ4_0 = 9,
  GgufQ4K = 10,
  GgufQ5_0 = 11,
  GgufQ5K = 12,
  GgufQ8_0 = 13,
  Int4B8 = 14,
};

/// Whether a declared tensor is bound by the driver. Mirrors [`Visibility`](pie_loader::types::Visibility).
enum class PieLoaderVisibility : uint32_t {
  /// A runtime weight, bound by name.
  Public = 0,
  /// A name the contract needed for itself: not bound, not persistent.
  Internal = 1,
};

/// `None` is the resting value for instructions that carry no tile map, so it
/// sorts after the transforms that existed when it was chosen — matching the
/// C++ enum and the default on `PieLoaderStorageInstrView::tile_kind`.
///
/// These discriminants are not the `TILE_MAP_*` capability bits and are not
/// required to agree with them: the two happen to line up below `None` and stop
/// there, because a kind added afterwards has to take a free discriminant while
/// its bit is chosen from the free bits. The loader's `TileMapKind` states the
/// pairing in one place, by name, and nothing derives one from the other.
enum class PieLoaderTileMapKind : uint32_t {
  Cast = 0,
  Decode = 1,
  Encode = 2,
  Transcode = 3,
  Reblock = 4,
  Repack = 6,
  None = 7,
  Scale = 8,
};

/// A transform chain the backend collapsed into a single kernel.
///
/// `None` is the resting value, so the driver's `switch` needs no separate
/// "is there a fusion" test.
enum class PieLoaderTransformFusion : uint32_t {
  None = 0,
  /// Encode an FP8 source straight to MXFP4, skipping the BF16 HBM
  /// round-trip. Bit-identical to the two-step path.
  Fp8ToMxfp4 = 1,
};

/// A repack's kernel, across the ABI.
///
/// `None` is the wire sentinel for a transform that ends in no kernel, the way
/// [`PieLoaderQuantScheme::None`] is for a transform that converts nothing. It
/// is deliberately *not* a member of [`RepackLayout`]: outbound it means "this
/// tile map is not a repack", and inbound — where the only reader is a contract
/// node that has already said it is one — it is rejected, because an all-zero
/// node is the shape a forgotten field has.
enum class PieLoaderRepackLayout : uint32_t {
  None = 0,
  MarlinMxfp4Weight = 1,
  MarlinMxfp4Scale = 2,
};

enum class PieLoaderBackendKind : uint32_t {
  Cuda = 0,
  Metal = 1,
  Unknown = 255,
};

/// How a scale tensor's entries map onto the tensor they scale.
enum class PieLoaderQuantGranularity : uint32_t {
  PerChannel = 0,
  PerGroup = 1,
};

/// What the driver's kernels expect a scale tensor to hold when they read it.
///
/// Not derivable from the scale tensor: its dtype says how the bytes are stored,
/// not how the kernel wants them. The driver used to infer this from
/// `group_size == 32`.
enum class PieLoaderScaleForm : uint32_t {
  /// Raw E8M0 exponent bytes, consumed as-is.
  RawE8M0 = 0,
  /// F32 multipliers; expand before the GEMM sees them.
  F32Factors = 1,
  /// BF16 multipliers paired with the zero points named by
  /// `zero_point_tensor_id`: an element is `code * scale + zero`.
  Bf16AffineFactors = 2,
};

/// A borrowed UTF-8 string. Not NUL-terminated: plan strings come from Rust
/// `String`s, and copying them only to append a NUL would double the arena for
/// no reader that needs it. C++ consumers build a `string_view` from the pair.
struct PieLoaderBytes {
  const uint8_t *ptr;
  size_t len;
};

/// One file the plan reads from. `PieLoaderSourceTensorView::file_id` indexes
/// `PieLoaderPlan::files`, so the driver no longer has to re-derive the file
/// order for itself (`architecture.md` §6).
struct PieLoaderCheckpointFileView {
  uint32_t id;
  PieLoaderBytes path;
  uint64_t size_bytes;
  PieLoaderCheckpointFormat format;
};

template<typename T>
struct PieLoaderSlice {
  const T *ptr;
  size_t len;
};

using PieLoaderCheckpointFileSlice = PieLoaderSlice<PieLoaderCheckpointFileView>;

using PieLoaderI64Slice = PieLoaderSlice<int64_t>;

/// [`pie_loader::types::QuantSpec`], flattened.
struct PieLoaderQuantSpecView {
  /// A `PieLoaderQuantScheme` value, as `uint32_t`.
  uint32_t scheme;
  /// A `PieLoaderDType` value, as `uint32_t`.
  uint32_t logical_dtype;
  /// `0` asks for the scheme's default, exactly as the Rust side does.
  uint8_t bits_per_element;
  /// `0` asks for the scheme's default.
  uint32_t group_size;
  int32_t channel_axis;
};

/// [`pie_loader::types::Encoding`], flattened. `kind` selects which half is read.
struct PieLoaderEncodingSpec {
  /// A `PieLoaderEncodingKind` value, as `uint32_t`.
  uint32_t kind;
  /// A `PieLoaderDType` value, as `uint32_t`. Read when `kind == Raw`.
  uint32_t dtype;
  /// Read when `kind == Quant`.
  PieLoaderQuantSpecView quant;
};

/// One tensor as it appears in the checkpoint.
///
/// The encoding is the full [`PieLoaderEncodingSpec`], not the flattened form
/// `PieLoaderSourceTensorView` uses: a driver reads this and writes it straight
/// back into a contract node, so a lossy summary here would be a contract that
/// cannot name what it found.
struct PieLoaderRawTensorView {
  uint32_t id;
  PieLoaderBytes name;
  uint32_t file_id;
  uint64_t file_offset;
  uint64_t span_bytes;
  /// Extents as the file declares them, before any sharding.
  PieLoaderI64Slice shape;
  PieLoaderEncodingSpec encoding;
};

struct PieLoaderRawTensorSlice {
  const PieLoaderRawTensorView *ptr;
  size_t len;
};

/// An opened checkpoint.
///
/// Freed with [`pie_loader_close_checkpoint`]. Immutable between open and
/// close, so it may be read from several threads — which is the case that
/// matters, because the ranks of a TP group compile in parallel from one
/// checkpoint.
///
/// [`pie_loader_close_checkpoint`]: crate::entry::pie_loader_close_checkpoint
struct PieLoaderCheckpoint {
  PieLoaderCheckpointFileSlice files;
  /// Every tensor in every file, in the order the reader found them.
  PieLoaderRawTensorSlice tensors;
  void *owner;
};

/// One diagnostic record.
///
/// `message` is borrowed from the owning [`PieLoaderDiagnostics`] and is valid
/// until it is released.
struct PieLoaderDiagnostic {
  PieLoaderSeverity severity;
  PieLoaderBytes message;
};

/// A flat array of diagnostics plus the storage backing their messages.
///
/// Returned through an out-param by both entry points, including on success when
/// the compile produced warnings. A null out-pointer means the caller does not
/// want them; a non-null pointer left null means there were none.
struct PieLoaderDiagnostics {
  const PieLoaderDiagnostic *items;
  size_t len;
  void *owner;
};

struct PieLoaderSourceTensorView {
  uint32_t id;
  PieLoaderBytes name;
  uint32_t file_id;
  uint64_t file_offset;
  uint64_t span_bytes;
  PieLoaderDType dtype;
  PieLoaderEncodingKind encoding_kind;
  PieLoaderQuantScheme quant_scheme;
  uint8_t quant_bits_per_element;
  uint32_t quant_group_size;
  PieLoaderI64Slice shape;
};

using PieLoaderSourceTensorSlice = PieLoaderSlice<PieLoaderSourceTensorView>;

struct PieLoaderTensorDeclView {
  uint32_t id;
  PieLoaderBytes name;
  PieLoaderDType dtype;
  PieLoaderEncodingKind encoding_kind;
  PieLoaderQuantScheme quant_scheme;
  uint8_t quant_bits_per_element;
  uint32_t quant_group_size;
  PieLoaderI64Slice shape;
  uint32_t alignment;
  PieLoaderVisibility visibility;
};

using PieLoaderTensorDeclSlice = PieLoaderSlice<PieLoaderTensorDeclView>;

struct PieLoaderBufferDeclView {
  uint32_t id;
  uint32_t tensor_id;
  bool has_tensor;
  uint64_t bytes;
  uint32_t alignment;
  bool temporary;
  bool has_persistent_offset;
  uint64_t persistent_offset;
};

using PieLoaderBufferDeclSlice = PieLoaderSlice<PieLoaderBufferDeclView>;

struct PieLoaderDimSpecView {
  int64_t count;
  int64_t src_stride;
  int64_t dst_stride;
};

using PieLoaderDimSpecSlice = PieLoaderSlice<PieLoaderDimSpecView>;

struct PieLoaderStridedExtentView {
  uint64_t base_offset;
  uint32_t element_bytes;
  PieLoaderDimSpecSlice dims;
};

struct PieLoaderSourceExtentView {
  uint32_t file_id;
  uint32_t tensor_id;
  uint64_t file_offset;
  uint64_t span_bytes;
  PieLoaderStridedExtentView stride;
  /// The type these bytes are read as. Not necessarily
  /// `PieLoaderPlan::sources[tensor_id].dtype`: a contract that reinterprets
  /// a tensor with `Transmute` -- DeepSeek-V4's E8M0 block scales are stored
  /// as `U8` -- says so here, and an executor that consulted the source
  /// table instead would undo the reinterpretation.
  PieLoaderDType dtype;
};

struct PieLoaderDestExtentView {
  uint32_t buffer_id;
  uint64_t offset;
  PieLoaderStridedExtentView stride;
};

using PieLoaderU32Slice = PieLoaderSlice<uint32_t>;

/// What an instruction does, as a tagged union carrying only that operation's
/// operands.
///
/// This mirrors `pie_loader::plan::StorageInstr` variant for variant. It was a flat
/// struct of 32 members with a `kind` tag until every reader had grown a
/// defence against the members that tag left meaningless: `if (!instr.has_source
/// || !instr.has_dest)` in three executors, `inputs.size() != 1` around a
/// `CreateView` whose input count is one by construction, and a comment in
/// `ffi::view` explaining that a resting `source` "would look like a valid
/// reference to file 0". Those are invariants a union states and a product type
/// can only apologise for.
///
/// The discriminants are the wire tag and are written out for the same reason
/// the mirror enums' are — 4 and 7 are absent because retired instructions had
/// them, and renumbering to close a gap would silently move every tag above it.
struct PieLoaderStorageOp {
  enum class Tag : uint32_t {
    Allocate = 0,
    ExtentWrite = 1,
    TileMap = 2,
    CreateView = 3,
    Finalize = 5,
    /// The destination is an offset into the persistent arena, not a buffer.
    /// The flat form had to fabricate a rank-1 `dest` extent per instruction —
    /// an arena allocation whose only content the executor ever read was
    /// `dest.offset`.
    BulkExtentWrite = 6,
    Fill = 8,
  };

  struct Allocate_Body {
    uint32_t buffer_id;
  };

  struct ExtentWrite_Body {
    PieLoaderSourceExtentView source;
    PieLoaderDestExtentView dest;
  };

  struct TileMap_Body {
    PieLoaderTileMapKind tile_kind;
    /// A tile map reads a checkpoint tensor, or transforms a buffer already
    /// on the device. `has_source` says which; the other seven operations no
    /// longer have to carry the question.
    PieLoaderSourceExtentView source;
    bool has_source;
    PieLoaderDestExtentView dest;
    bool has_dest;
    PieLoaderU32Slice input_buffers;
    PieLoaderU32Slice output_buffers;
    /// Rows of the output to transform per launch; `0` means the whole
    /// tensor in one pass.
    ///
    /// This is where the driver's `max_tile_bytes` budget ends up. The
    /// budget itself does not cross the boundary: the driver stated it in
    /// the request, the loader answered with a row count in
    /// `backend::lower`, and sending the question back alongside the answer
    /// would only invite the executor to re-derive it (`architecture.md`
    /// §8.1).
    uint32_t rows_per_tile;
    /// A transform chain the backend collapsed into one kernel.
    PieLoaderTransformFusion transform_fusion;
    PieLoaderQuantScheme transform_from;
    PieLoaderQuantScheme transform_to;
    PieLoaderRepackLayout repack_layout;
    uint32_t transform_batch;
    uint32_t transform_source_rows;
    uint32_t transform_target_rows;
    uint32_t transform_source_cols;
    uint32_t transform_target_cols;
    uint64_t transform_scratch_bytes;
    /// Source tensor holding this transform's input block scales, or
    /// [`PIE_LOADER_NO_TENSOR`].
    ///
    /// Index into `PieLoaderPlan::sources`, the same space
    /// `source.tensor_id` uses, so the executor reaches the scales' name and
    /// shape the way it reaches the payload's — instead of appending
    /// `_scale_inv` to a name and hoping the checkpoint agrees.
    uint32_t transform_metadata_source;
    /// The multiplier for a [`PieLoaderTileMapKind::Scale`], as the bit
    /// pattern of an IEEE-754 binary32; zero on every other kind.
    ///
    /// Bits rather than a `float` field so this union's layout does not
    /// depend on float ABI, and so the executor multiplies with exactly the
    /// constant the contract named — `__uint_as_float` on the CUDA side
    /// costs nothing and cannot round.
    uint32_t transform_scale_factor_bits;
    /// Elements of the operand per factor, on each axis, for a per-block
    /// [`PieLoaderTileMapKind::Scale`]; empty when the factor is the
    /// uniform constant above.
    ///
    /// Non-empty is what tells the executor to read its factors from
    /// `input_buffers[0]` — the operand the contract paired with the
    /// payload — instead of from `transform_scale_factor_bits`.
    ///
    /// One entry per axis of the destination, so a DeepSeek-style FP8
    /// checkpoint's two-dimensional block scale is `[128, 128]` and the
    /// ordinary row-wise case is `[1, 32]`. The executor already knows both
    /// shapes, so this is a statement it can check rather than one it must
    /// trust.
    PieLoaderI64Slice transform_scale_blocks;
  };

  struct CreateView_Body {
    uint32_t input_buffer;
    uint32_t output_buffer;
    PieLoaderDestExtentView view;
  };

  struct Finalize_Body {
    uint32_t buffer_id;
    PieLoaderBytes name;
  };

  struct BulkExtentWrite_Body {
    PieLoaderSourceExtentView source;
    uint64_t dest_offset;
  };

  struct Fill_Body {
    uint32_t buffer_id;
  };

  Tag tag;
  union {
    Allocate_Body allocate;
    ExtentWrite_Body extent_write;
    TileMap_Body tile_map;
    CreateView_Body create_view;
    Finalize_Body finalize;
    BulkExtentWrite_Body bulk_extent_write;
    Fill_Body fill;
  };
};

/// One entry of the plan's instruction stream: an identity, and an operation.
///
/// `id` is the schedule's handle on this instruction and is the only thing every
/// instruction has. Everything else belongs to one operation, and lives inside
/// it.
struct PieLoaderStorageInstrView {
  uint32_t id;
  PieLoaderStorageOp op;
};

using PieLoaderStorageInstrSlice = PieLoaderSlice<PieLoaderStorageInstrView>;

struct PieLoaderMemoryPlanView {
  uint64_t persistent_bytes;
  uint64_t temporary_peak_bytes;
  uint64_t transform_scratch_peak_bytes;
  uint64_t checkpoint_read_bytes;
  uint64_t device_write_bytes;
};

/// The target the plan was compiled against. The driver reads it back to assert
/// the plan it received is the plan it asked for — the same fields it supplied
/// in the request, plus the rank identity that makes a TP shard distinguishable
/// from its siblings (`architecture.md` §6.2).
struct PieLoaderTargetView {
  PieLoaderBackendKind backend;
  uint32_t tp_rank;
  uint32_t tp_size;
  uint64_t max_tile_bytes;
  uint32_t preferred_alignment;
  uint32_t tile_map_mask;
  bool native_mxfp4_moe;
  uint32_t fusion_mask;
  PieLoaderDType encode_scratch_dtype;
  uint32_t block_scale_rows;
};

/// A quantized tensor paired with the tensor holding its scales.
///
/// Both are entries in [`PieLoaderPlan::tensors`], named by `id`. The driver has
/// to know the pairing in order to attach the quant metadata its kernels read;
/// it used to rediscover it by matching name suffixes over the tensor list,
/// which guessed at something stated here.
struct PieLoaderQuantAttachmentView {
  uint32_t tensor_id;
  uint32_t scale_tensor_id;
  /// The tensor holding this weight's zero points, for an affine scheme, or
  /// [`PIE_LOADER_NO_TENSOR`] for a symmetric one. An affine weight without it
  /// cannot be dequantized, so a driver reading a `Bf16AffineFactors`
  /// attachment is entitled to treat the sentinel as a malformed plan rather
  /// than as an offset of zero.
  uint32_t zero_point_tensor_id;
  PieLoaderQuantGranularity granularity;
  uint32_t group_size;
  uint32_t channel_axis;
  PieLoaderScaleForm scale_form;
};

using PieLoaderQuantAttachmentSlice = PieLoaderSlice<PieLoaderQuantAttachmentView>;

/// Where one instruction of a group's plan reads, for one instance.
///
/// The whole of what distinguishes instance `i` from instance 0: a group did
/// not compile unless every other field of every instruction agreed across all
/// of them. `instr_id` names the instruction in
/// [`PieLoaderGroupView::plan`](PieLoaderGroupView) whose source extent these
/// three fields replace.
struct PieLoaderSourceBindingView {
  uint32_t instr_id;
  uint32_t file_id;
  uint32_t tensor_id;
  uint64_t file_offset;
};

using PieLoaderSourceBindingSlice = PieLoaderSlice<PieLoaderSourceBindingView>;

/// A set of interchangeable tensors: one plan, `arity` instances.
///
/// The driver decides what to do with it. Running `plan` `arity` times into
/// `arity` destinations makes the group resident, which is what a driver that
/// has never heard of streaming should do; running it on demand into a bounded
/// set of slots is streaming. The loader states only that the two are the same
/// program.
struct PieLoaderGroupView {
  PieLoaderBytes name;
  uint32_t arity;
  /// The program one instance runs, compiled at index 0. A whole plan, so it
  /// goes to the same executor the resident load already uses.
  const PieLoaderPlan *plan;
  /// `arity * bindings_per_instance` entries, instance-major. Instance `i`
  /// owns `[i * bindings_per_instance, (i + 1) * bindings_per_instance)`.
  PieLoaderSourceBindingSlice bindings;
  /// How many instructions of `plan` name a source. Zero only if the group's
  /// plan reads nothing, which no group does.
  size_t bindings_per_instance;
};

using PieLoaderGroupSlice = PieLoaderSlice<PieLoaderGroupView>;

/// The compiled plan, as the driver sees it.
///
/// The leading members reproduce the old `LoadPlanView` in order, so an executor
/// written against that view compiles unchanged against this struct. `target`
/// and `compiler_version` fold in the accessors `loaded_model.cpp` reached
/// through `LoadPlan` methods (`backend()`, `native_mxfp4_moe()`,
/// `preferred_alignment()`, `max_tile_bytes()`, `tile_map_mask()`,
/// `compiler_version()`), which have no method syntax to hide behind once the
/// type is POD.
///
/// `owner` is the opaque handle to the arena keeping every slice above alive. It
/// is consumed by `pie_loader_release`; the driver must not dereference it.
struct PieLoaderPlan {
  PieLoaderCheckpointFileSlice files;
  PieLoaderSourceTensorSlice sources;
  PieLoaderTensorDeclSlice tensors;
  PieLoaderBufferDeclSlice buffers;
  PieLoaderStorageInstrSlice instrs;
  PieLoaderU32Slice schedule;
  PieLoaderMemoryPlanView memory;
  uint64_t compiler_version;
  PieLoaderTargetView target;
  PieLoaderQuantAttachmentSlice attachments;
  /// The name of the materialized weights this plan produces, as 16 hex
  /// digits. Stable for as long as nothing that decides the bytes changes, so
  /// a driver can use it to key an artifact cache.
  PieLoaderBytes cache_key;
  /// One line describing the plan, for a boot log.
  PieLoaderBytes summary;
  /// The plan's counts and instruction histograms as JSON, for an operator
  /// dump. Rendered by the loader so no driver keeps a second table of
  /// instruction names to fall out of step with this one.
  PieLoaderBytes stats_json;
  /// Interchangeable tensor sets, each compiled once. Empty for a plan whose
  /// contract declared no group, which is every contract that predates them.
  PieLoaderGroupSlice groups;
  void *owner;
};

/// The device-measured half of a request.
///
/// Every field is a fact only the driver can state: what the device is, how
/// wide the TP group is, and which transforms this backend's kernels implement.
/// The loader never guesses any of it, which is what makes a plan reproducible
/// from a recorded spec on a machine with no GPU (`architecture.md` §2 P2).
///
/// `backend` and `encode_scratch_dtype` are plain `uint32_t` rather than their
/// enum types, and the same goes for every enum-valued *input* field. C++ lets a
/// caller store any integer in an enum-typed field, and reading such a field as
/// a Rust enum is undefined behaviour that happens *before* any check could
/// reject it. Assign `static_cast<uint32_t>(PieLoaderBackendKind::Cuda)`; the
/// loader validates the value and answers `PieLoaderStatus::InvalidRequest` if
/// it is not one of them.
struct PieLoaderTargetSpec {
  uint32_t backend;
  uint32_t tp_rank;
  uint32_t tp_size;
  uint64_t max_tile_bytes;
  uint32_t preferred_alignment;
  uint32_t tile_map_mask;
  bool native_mxfp4_moe;
  /// Which fused transform chains this build has kernels for
  /// (`PIE_LOADER_FUSION_*`).
  ///
  /// The opt-out that used to be `PIE_CUDA_DISABLE_FUSED_TRANSCODE`, read
  /// inside the executor. As a request field it changes the *plan*, so two
  /// settings produce two artifacts instead of one plan that runs two ways
  /// (`architecture.md` §8.1). Backends with no fused kernels pass `0`.
  uint32_t fusion_mask;
  /// The dtype this target's encode kernels dequantize through. Decides how
  /// many rows of scratch fit in `max_tile_bytes`.
  ///
  /// A `u32` for the reason [`PieLoaderTargetSpec::backend`] is: this is an
  /// *input*, so the value is whatever C++ wrote, and a Rust enum with a
  /// value outside its variants is undefined behaviour before any check can
  /// run. The output side, `PieLoaderTargetView`, keeps the enum — the loader
  /// wrote that one.
  uint32_t encode_scratch_dtype;
  /// Row granularity of this target's block scales, or `0` for none. A
  /// block-scaled source is not tiled, because a tile boundary would cut a
  /// scale block.
  uint32_t block_scale_rows;
};

/// The per-family switches, wire form. Mirrors [`FamilyKnobs`] field for
/// field; the caller reads its environment and fills these, so an author
/// never consults the environment and equal requests author equal contracts.
///
/// These two family names are the only ones in the ABI, and each is here
/// because the *forward* path reads the same environment variable. A switch
/// only the loader read would move the weights while the matmuls stayed put
/// — see [`FamilyKnobs`] for the six that went that way.
struct PieLoaderFamilyKnobs {
  bool qwen35_mtp_int8_lm_head;
  bool nemotron_tp_mamba_sharding;
};

/// Everything one authoring-and-compiling call is decided by.
struct PieLoaderModelRequest {
  /// The checkpoint, already open: authoring reads the same tensor table
  /// the compile does, which is what makes the contract and the plan
  /// provably about one parse.
  const PieLoaderCheckpoint *checkpoint;
  PieLoaderTargetSpec target;
  /// The `pie.model/1` descriptor, as the JSON bytes the caller read.
  ///
  /// This used to be ten scalars in a `PieLoaderModelFactsView` — the
  /// caller parsed `config.json`, picked out what it thought the loader
  /// needed, and sent that. The document is the request now: the facts are
  /// projected from it by `pie_model::ModelFacts::from_descriptor`, so
  /// which fields matter is a question answered where the authors live
  /// rather than in each driver, and a new fact needs no ABI change.
  ///
  /// Borrowed for the call, like every other pointer here.
  PieLoaderBytes descriptor;
  /// `Projections` wire value: 0 fused, 1 in-place.
  uint32_t projections;
  /// `Naming` wire value: 0 HF, 1 MLX.
  uint32_t naming;
  /// `RuntimeQuant` wire value, already resolved against the device:
  /// 0 none, 1 fp8, 2 int8, 3 mxfp4, 4 int4 (MLX affine, Metal's).
  uint32_t runtime_quant;
  /// `Mxfp4MoeRequest` wire value: 0 auto, 1 routed, 2 native, 3 bf16.
  uint32_t moe_request;
  /// `Component` wire value: 0 full, 1 text, 2 encode.
  uint32_t component;
  bool stream_routed_experts;
  PieLoaderFamilyKnobs knobs;
};

/// An artifact open for writing.
///
/// Freed by [`pie_loader_weight_store_publish`] or
/// [`pie_loader_weight_store_discard`]; nothing reaches the destination path
/// until the first of those succeeds.
struct PieLoaderWeightWriter {
  void *owner;
};

/// A tensor with bytes of its own, as the driver declares it.
struct PieLoaderWeightTensor {
  PieLoaderBytes name;
  /// How the bytes are stored. The payload's length is
  /// `product(shape) × width(dtype)`, and the driver's own type must agree
  /// with that or the artifact would describe something else.
  PieLoaderDType dtype;
  /// The driver's name for the type its kernels will read. Stored verbatim.
  PieLoaderBytes runtime_dtype;
  PieLoaderI64Slice shape;
};

/// A tensor that is a window into another tensor's bytes.
///
/// Reconstructed as a window, never as a copy: views are how a fused projection
/// or a stacked expert weight is addressed, and copying them back would double
/// the memory they exist to save.
struct PieLoaderWeightView {
  PieLoaderBytes name;
  /// The tensor whose bytes this window lies in. Empty for a window with no
  /// bytes at all, which a store is allowed to hold.
  PieLoaderBytes root;
  uint64_t byte_offset;
  PieLoaderDType dtype;
  PieLoaderBytes runtime_dtype;
  PieLoaderI64Slice shape;
  /// What the store records this window as cut from, which is not always the
  /// root: a view of a view names the intermediate.
  PieLoaderBytes backing;
};

/// A quantized weight's companion metadata.
struct PieLoaderWeightQuant {
  PieLoaderBytes name;
  /// The driver's name for the granularity its kernels expect. Stored verbatim.
  PieLoaderBytes kind;
  PieLoaderBytes scale;
  PieLoaderBytes zero_point;
  int32_t group_size;
  int32_t channel_axis;
};

/// A tensor as the artifact reports it back.
struct PieLoaderWeightTensorView {
  PieLoaderBytes name;
  PieLoaderBytes runtime_dtype;
  PieLoaderI64Slice shape;
  /// The payload, borrowed from the mapping. Valid until the handle closes.
  const uint8_t *data;
  uint64_t nbytes;
  /// Where the payload begins in the file. What a caller checks when it wants
  /// to know the artifact is mappable — a question the bytes cannot answer.
  uint64_t file_offset;
};

using PieLoaderWeightTensorSlice = PieLoaderSlice<PieLoaderWeightTensorView>;

using PieLoaderWeightViewSlice = PieLoaderSlice<PieLoaderWeightView>;

using PieLoaderWeightQuantSlice = PieLoaderSlice<PieLoaderWeightQuant>;

/// An opened artifact. Freed with [`pie_loader_weight_store_close`].
struct PieLoaderWeightStore {
  PieLoaderWeightTensorSlice tensors;
  PieLoaderWeightViewSlice views;
  PieLoaderWeightQuantSlice quants;
  void *owner;
};

extern "C" {

/// Open a checkpoint and read its tensor table.
///
/// The only entry point that touches the filesystem before a plan executes.
/// On success `*out` receives a handle the caller must free with
/// [`pie_loader_close_checkpoint`].
///
/// # Safety
///
/// `snapshot_dir` is a valid [`PieLoaderBytes`] live for the call. `out` is a
/// writable slot. `out_diags` is null or a writable slot.
PieLoaderStatus pie_loader_open_checkpoint(PieLoaderBytes snapshot_dir,
                                           PieLoaderCheckpoint **out,
                                           PieLoaderDiagnostics **out_diags);

/// Free a checkpoint handle.
///
/// # Safety
///
/// `checkpoint` is null, or a handle from [`pie_loader_open_checkpoint`] that
/// has not already been closed.
void pie_loader_close_checkpoint(PieLoaderCheckpoint *checkpoint);

/// Free a plan returned by [`pie_loader_compile_model`](crate::model::pie_loader_compile_model).
///
/// # Safety
///
/// `plan` is null or a pointer from
/// [`pie_loader_compile_model`](crate::model::pie_loader_compile_model) that
/// has not already been released.
void pie_loader_release(PieLoaderPlan *plan);

/// Free diagnostics returned through an out-param.
///
/// # Safety
///
/// `diags` is null or a pointer produced by this module that has not already been
/// released.
void pie_loader_release_diagnostics(PieLoaderDiagnostics *diags);

/// Author this model's contract and compile it into a plan, in one call.
///
/// `out_mxfp4_moe`, when non-null, receives the author's resolved
/// [`Mxfp4MoePolicy`] as its wire value — the answer the bind path branches
/// on, handed back rather than recomputed, because a family may override the
/// device rule.
///
/// # Safety
///
/// `req` and everything its pointers reach must be live for the call.
/// `out_plan` is a writable slot; `out_diags` and `out_mxfp4_moe` are null
/// or writable slots.
PieLoaderStatus pie_loader_compile_model(const PieLoaderModelRequest *req,
                                         PieLoaderPlan **out_plan,
                                         uint32_t *out_mxfp4_moe,
                                         PieLoaderDiagnostics **out_diags);

/// Check a plan against the contract this request authors.
///
/// The caller has no contract to hand over — a contract is loader-internal
/// IR now — so the verifier re-authors one from the same request and holds
/// the plan to it. Re-authoring is the
/// point, not a cost — the check covers the author's determinism along with
/// everything the contract verifier checks.
///
/// # Safety
///
/// `plan` must point at an unreleased plan; `req` and everything its
/// pointers reach must be live for the call. `out_diags` is null or a
/// writable slot.
PieLoaderStatus pie_loader_verify_model(const PieLoaderPlan *plan,
                                        const PieLoaderModelRequest *req,
                                        PieLoaderDiagnostics **out_diags);

/// Open an artifact for `key` at `path`.
///
/// Nothing appears at `path` until [`pie_loader_weight_store_publish`]
/// succeeds: the bytes go to a neighbouring file that is renamed into place, so
/// a run that dies mid-write leaves nothing a later boot would try to read.
///
/// # Safety
///
/// `path` and `key` are valid [`PieLoaderBytes`] live for the call. `out` is a
/// writable slot. `out_diags` is null or a writable slot.
PieLoaderStatus pie_loader_weight_store_create(PieLoaderBytes path,
                                               PieLoaderBytes key,
                                               PieLoaderWeightWriter **out,
                                               PieLoaderDiagnostics **out_diags);

/// Declare a tensor and open it for writing.
///
/// Its payload is `product(shape) × width(dtype)` bytes, delivered by
/// [`pie_loader_weight_store_write`] and closed by
/// [`pie_loader_weight_store_end_tensor`].
///
/// # Safety
///
/// `writer` is a live handle and every borrowed field of `decl` is live for the
/// call.
PieLoaderStatus pie_loader_weight_store_begin_tensor(PieLoaderWeightWriter *writer,
                                                     const PieLoaderWeightTensor *decl);

/// Append bytes to the open tensor.
///
/// # Safety
///
/// `writer` is a live handle and `data` points at `len` initialized bytes live
/// for the call.
PieLoaderStatus pie_loader_weight_store_write(PieLoaderWeightWriter *writer,
                                              const uint8_t *data,
                                              size_t len);

/// Close the open tensor, which must have received its whole payload.
///
/// # Safety
///
/// `writer` is a live handle.
PieLoaderStatus pie_loader_weight_store_end_tensor(PieLoaderWeightWriter *writer);

/// Record a window into a tensor's bytes.
///
/// # Safety
///
/// `writer` is a live handle and every borrowed field of `decl` is live for the
/// call.
PieLoaderStatus pie_loader_weight_store_add_view(PieLoaderWeightWriter *writer,
                                                 const PieLoaderWeightView *decl);

/// Record a quantized weight's companion metadata.
///
/// # Safety
///
/// `writer` is a live handle and every borrowed field of `decl` is live for the
/// call.
PieLoaderStatus pie_loader_weight_store_add_quant(PieLoaderWeightWriter *writer,
                                                  const PieLoaderWeightQuant *decl);

/// Close the artifact and move it into place.
///
/// The handle is freed either way; a failure leaves nothing at the destination.
/// On failure the message is *not* retrievable — the handle it would have lived
/// in is gone — so it is written through `out_diags` instead.
///
/// # Safety
///
/// `writer` is a live handle, not used again after this call. `out_diags` is
/// null or a writable slot.
PieLoaderStatus pie_loader_weight_store_publish(PieLoaderWeightWriter *writer,
                                                PieLoaderDiagnostics **out_diags);

/// Abandon an artifact under construction, removing the partial file.
///
/// # Safety
///
/// `writer` is null, or a live handle not used again after this call.
void pie_loader_weight_store_discard(PieLoaderWeightWriter *writer);

/// The message from whatever last failed on `writer`.
///
/// Empty when nothing has. Borrowed from the handle and valid until the next
/// failing call on it or until the handle is freed.
///
/// # Safety
///
/// `writer` is null or a live handle.
PieLoaderBytes pie_loader_weight_store_error(const PieLoaderWeightWriter *writer);

/// Open the artifact at `path`, refusing one written for another key.
///
/// A key mismatch, a schema the loader does not know, and a file that is not an
/// artifact at all are all the same answer to the caller — recompute — so they
/// share a status and differ only in the diagnostic.
///
/// # Safety
///
/// `path` and `expected_key` are valid [`PieLoaderBytes`] live for the call.
/// `out` is a writable slot. `out_diags` is null or a writable slot.
PieLoaderStatus pie_loader_weight_store_open(PieLoaderBytes path,
                                             PieLoaderBytes expected_key,
                                             PieLoaderWeightStore **out,
                                             PieLoaderDiagnostics **out_diags);

/// Whether the tensor at `index` still matches the digest written with it.
///
/// Writes 1 or 0 through `out_ok`. A mismatch is not an error status: the
/// caller's move is to recompute, the same as for an artifact that was not
/// there. The check reads the mapping, so it can run on another thread while
/// the copies to the device are in flight — which is what the driver does.
///
/// # Safety
///
/// `store` is a live handle and `out_ok` is a writable slot.
PieLoaderStatus pie_loader_weight_store_verify(const PieLoaderWeightStore *store,
                                               size_t index,
                                               bool *out_ok);

/// Free an artifact handle and unmap the file.
///
/// # Safety
///
/// `store` is null, or a handle from [`pie_loader_weight_store_open`] that has
/// not already been closed.
void pie_loader_weight_store_close(PieLoaderWeightStore *store);

}  // extern "C"

}  // namespace pie_loader
