//===-- dump_hf_config.cpp - the C++ normalizer as a golden oracle -------===//
//
// `parse_hf_config` is ~850 lines of HuggingFace-quirk normalization with 25
// `model_type` conditionals, and `pie.model/1` moves that work to import time
// in Rust. Two implementations of the same normalization is exactly the skew
// the artifact exists to kill, so the Rust port is checked against this one
// field for field rather than against a reading of the source.
//
// This is a plain C++ translation unit: `config.cpp` includes only nlohmann,
// `hf_config_json.hpp` and `kernels_manifest.hpp`, and the last of those is
// deliberately CUDA-free. So the oracle builds with a host compiler and no
// toolkit -- see `build.sh`.
//
// GENERATED by `generate.py` from `model/config.hpp`. Regenerate rather than
// edit: a field added to `HfConfig` and forgotten here would silently drop out
// of the comparison, which is the one failure this file must not have.
//
//===----------------------------------------------------------------------===//
#include <iostream>
#include <string>

#include <nlohmann/json.hpp>

#include "model/config.hpp"

namespace {

using pie_cuda_driver::HfConfig;

const char* rope_scaling_name(HfConfig::RopeScaling kind) {
    switch (kind) {
        case HfConfig::RopeScaling::None: return "none";
        case HfConfig::RopeScaling::Llama3: return "llama3";
        case HfConfig::RopeScaling::OriginalYaRN: return "original_yarn";
    }
    return "unknown";
}

nlohmann::json dump(const pie_cuda_driver::GemmaVisionConfig& v) {
    nlohmann::json j;
    j["hidden_size"] = v.hidden_size;
    j["intermediate_size"] = v.intermediate_size;
    j["num_hidden_layers"] = v.num_hidden_layers;
    j["num_attention_heads"] = v.num_attention_heads;
    j["num_key_value_heads"] = v.num_key_value_heads;
    j["head_dim"] = v.head_dim;
    j["patch_size"] = v.patch_size;
    j["rms_norm_eps"] = v.rms_norm_eps;
    j["rope_theta"] = v.rope_theta;
    j["pooling_kernel_size"] = v.pooling_kernel_size;
    j["soft_tokens_per_image"] = v.soft_tokens_per_image;
    j["use_clipped_linears"] = v.use_clipped_linears;
    return j;
}

nlohmann::json dump(const pie_cuda_driver::GemmaAudioConfig& v) {
    nlohmann::json j;
    j["hidden_size"] = v.hidden_size;
    j["num_attention_heads"] = v.num_attention_heads;
    j["num_hidden_layers"] = v.num_hidden_layers;
    j["conv_kernel_size"] = v.conv_kernel_size;
    j["subsampling_conv_channels0"] = v.subsampling_conv_channels0;
    j["subsampling_conv_channels1"] = v.subsampling_conv_channels1;
    j["output_proj_dims"] = v.output_proj_dims;
    j["attention_chunk_size"] = v.attention_chunk_size;
    j["attention_context_left"] = v.attention_context_left;
    j["attention_context_right"] = v.attention_context_right;
    j["feature_size"] = v.feature_size;
    j["attention_logit_cap"] = v.attention_logit_cap;
    j["residual_weight"] = v.residual_weight;
    j["rms_norm_eps"] = v.rms_norm_eps;
    j["use_clipped_linears"] = v.use_clipped_linears;
    return j;
}

nlohmann::json dump(const pie_cuda_driver::CsmDepthDecoderConfig& v) {
    nlohmann::json j;
    j["hidden_size"] = v.hidden_size;
    j["backbone_hidden_size"] = v.backbone_hidden_size;
    j["num_hidden_layers"] = v.num_hidden_layers;
    j["num_attention_heads"] = v.num_attention_heads;
    j["num_key_value_heads"] = v.num_key_value_heads;
    j["head_dim"] = v.head_dim;
    j["intermediate_size"] = v.intermediate_size;
    j["num_codebooks"] = v.num_codebooks;
    j["vocab_size"] = v.vocab_size;
    j["max_position_embeddings"] = v.max_position_embeddings;
    j["rms_norm_eps"] = v.rms_norm_eps;
    j["rope_theta"] = v.rope_theta;
    j["rope_factor"] = v.rope_factor;
    j["rope_low_freq_factor"] = v.rope_low_freq_factor;
    j["rope_high_freq_factor"] = v.rope_high_freq_factor;
    j["rope_original_max_position"] = v.rope_original_max_position;
    return j;
}

nlohmann::json dump(const pie_cuda_driver::MimiCodecConfig& v) {
    nlohmann::json j;
    j["hidden_size"] = v.hidden_size;
    j["codebook_dim"] = v.codebook_dim;
    j["codebook_size"] = v.codebook_size;
    j["num_quantizers"] = v.num_quantizers;
    j["num_semantic_quantizers"] = v.num_semantic_quantizers;
    j["num_filters"] = v.num_filters;
    j["upsampling_ratios"] = v.upsampling_ratios;
    j["xf_num_attention_heads"] = v.xf_num_attention_heads;
    j["xf_num_key_value_heads"] = v.xf_num_key_value_heads;
    j["xf_head_dim"] = v.xf_head_dim;
    j["xf_intermediate_size"] = v.xf_intermediate_size;
    j["xf_num_hidden_layers"] = v.xf_num_hidden_layers;
    j["xf_sliding_window"] = v.xf_sliding_window;
    j["xf_rope_theta"] = v.xf_rope_theta;
    j["norm_eps"] = v.norm_eps;
    j["sampling_rate"] = v.sampling_rate;
    j["use_causal_conv"] = v.use_causal_conv;
    j["upsample_groups"] = v.upsample_groups;
    j["residual_kernel_size"] = v.residual_kernel_size;
    j["kernel_size"] = v.kernel_size;
    j["last_kernel_size"] = v.last_kernel_size;
    return j;
}

nlohmann::json dump(const pie_cuda_driver::CsmConfig& v) {
    nlohmann::json j;
    j["text_vocab_size"] = v.text_vocab_size;
    j["audio_vocab_size"] = v.audio_vocab_size;
    j["num_codebooks"] = v.num_codebooks;
    j["codebook_eos_token_id"] = v.codebook_eos_token_id;
    j["audio_eos_token_id"] = v.audio_eos_token_id;
    j["audio_token_id"] = v.audio_token_id;
    j["depth"] = dump(v.depth);
    j["codec"] = dump(v.codec);
    return j;
}

nlohmann::json dump(const pie_cuda_driver::Qwen3VLVisionConfig& v) {
    nlohmann::json j;
    j["hidden_size"] = v.hidden_size;
    j["intermediate_size"] = v.intermediate_size;
    j["depth"] = v.depth;
    j["num_heads"] = v.num_heads;
    j["patch_size"] = v.patch_size;
    j["temporal_patch_size"] = v.temporal_patch_size;
    j["spatial_merge_size"] = v.spatial_merge_size;
    j["in_channels"] = v.in_channels;
    j["out_hidden_size"] = v.out_hidden_size;
    j["num_position_embeddings"] = v.num_position_embeddings;
    j["deepstack_visual_indexes"] = v.deepstack_visual_indexes;
    return j;
}

nlohmann::json dump(const HfConfig& v) {
    nlohmann::json j;
    j["arch_name"] = v.arch_name;
    j["model_type"] = v.model_type;
    j["hidden_size"] = v.hidden_size;
    j["intermediate_size"] = v.intermediate_size;
    j["num_hidden_layers"] = v.num_hidden_layers;
    j["num_attention_heads"] = v.num_attention_heads;
    j["num_key_value_heads"] = v.num_key_value_heads;
    j["head_dim"] = v.head_dim;
    j["head_dim_kernel"] = v.head_dim_kernel;
    j["vocab_size"] = v.vocab_size;
    j["max_position_embeddings"] = v.max_position_embeddings;
    j["rms_norm_eps"] = v.rms_norm_eps;
    j["hidden_act"] = v.hidden_act;
    j["mlp_hidden_act"] = v.mlp_hidden_act;
    j["rope_theta"] = v.rope_theta;
    j["rope_scaling_kind"] = rope_scaling_name(v.rope_scaling_kind);
    j["rope_factor"] = v.rope_factor;
    j["rope_low_freq_factor"] = v.rope_low_freq_factor;
    j["rope_high_freq_factor"] = v.rope_high_freq_factor;
    j["rope_original_max_position"] = v.rope_original_max_position;
    j["rope_beta_fast"] = v.rope_beta_fast;
    j["rope_beta_slow"] = v.rope_beta_slow;
    j["rope_attention_factor"] = v.rope_attention_factor;
    j["rope_mla_softmax_mscale"] = v.rope_mla_softmax_mscale;
    j["has_rope_scaling"] = v.has_rope_scaling;
    j["sliding_window"] = v.sliding_window;
    j["layer_types"] = v.layer_types;
    j["rope_local_base_freq"] = v.rope_local_base_freq;
    j["tie_word_embeddings"] = v.tie_word_embeddings;
    j["attention_bias"] = v.attention_bias;
    j["use_qk_norm"] = v.use_qk_norm;
    j["num_experts"] = v.num_experts;
    j["num_experts_per_tok"] = v.num_experts_per_tok;
    j["gemma4_enable_moe"] = v.gemma4_enable_moe;
    j["gemma4_attention_k_eq_v"] = v.gemma4_attention_k_eq_v;
    j["gemma4_num_global_key_value_heads"] = v.gemma4_num_global_key_value_heads;
    j["gemma4_global_head_dim"] = v.gemma4_global_head_dim;
    j["gemma4_double_wide_mlp"] = v.gemma4_double_wide_mlp;
    j["swiglu_limit"] = v.swiglu_limit;
    j["mlp_has_bias"] = v.mlp_has_bias;
    j["router_has_bias"] = v.router_has_bias;
    j["attention_has_sinks"] = v.attention_has_sinks;
    j["gemma_query_pre_attn_scalar"] = v.gemma_query_pre_attn_scalar;
    j["gemma_final_logit_softcap"] = v.gemma_final_logit_softcap;
    j["gemma_attn_logit_softcap"] = v.gemma_attn_logit_softcap;
    j["gemma_hidden_size_per_layer_input"] = v.gemma_hidden_size_per_layer_input;
    j["num_kv_shared_layers"] = v.num_kv_shared_layers;
    j["gemma4_use_ordered_embeddings"] = v.gemma4_use_ordered_embeddings;
    j["gemma4_num_centroids"] = v.gemma4_num_centroids;
    j["gemma4_centroid_intermediate_top_k"] = v.gemma4_centroid_intermediate_top_k;
    j["gemma_per_layer_rope_theta"] = v.gemma_per_layer_rope_theta;
    j["gemma_per_layer_partial_rotary_factor"] = v.gemma_per_layer_partial_rotary_factor;
    j["moe_intermediate_size"] = v.moe_intermediate_size;
    j["shared_expert_intermediate_size"] = v.shared_expert_intermediate_size;
    j["routed_scaling_factor"] = v.routed_scaling_factor;
    j["n_group"] = v.n_group;
    j["topk_group"] = v.topk_group;
    j["norm_topk_prob"] = v.norm_topk_prob;
    j["mamba_num_heads"] = v.mamba_num_heads;
    j["mamba_head_dim"] = v.mamba_head_dim;
    j["mamba_state_size"] = v.mamba_state_size;
    j["mamba_n_groups"] = v.mamba_n_groups;
    j["mamba_conv_kernel"] = v.mamba_conv_kernel;
    j["mamba_chunk_size"] = v.mamba_chunk_size;
    j["mamba_time_step_min"] = v.mamba_time_step_min;
    j["q_lora_rank"] = v.q_lora_rank;
    j["kv_lora_rank"] = v.kv_lora_rank;
    j["qk_nope_head_dim"] = v.qk_nope_head_dim;
    j["qk_rope_head_dim"] = v.qk_rope_head_dim;
    j["v_head_dim"] = v.v_head_dim;
    j["first_k_dense_replace"] = v.first_k_dense_replace;
    j["n_shared_experts"] = v.n_shared_experts;
    j["dsv4_o_lora_rank"] = v.dsv4_o_lora_rank;
    j["dsv4_o_groups"] = v.dsv4_o_groups;
    j["dsv4_index_head_dim"] = v.dsv4_index_head_dim;
    j["dsv4_index_n_heads"] = v.dsv4_index_n_heads;
    j["dsv4_index_topk"] = v.dsv4_index_topk;
    j["dsv4_hc_mult"] = v.dsv4_hc_mult;
    j["dsv4_num_hash_layers"] = v.dsv4_num_hash_layers;
    j["dsv4_sliding_window"] = v.dsv4_sliding_window;
    j["dsv4_hc_eps"] = v.dsv4_hc_eps;
    j["dsv4_compress_rope_theta"] = v.dsv4_compress_rope_theta;
    j["dsv4_compress_ratios"] = v.dsv4_compress_ratios;
    j["dsv4_scoring_func"] = v.dsv4_scoring_func;
    j["dsv4_expert_dtype"] = v.dsv4_expert_dtype;
    j["linear_num_value_heads"] = v.linear_num_value_heads;
    j["linear_num_key_heads"] = v.linear_num_key_heads;
    j["linear_key_head_dim"] = v.linear_key_head_dim;
    j["linear_value_head_dim"] = v.linear_value_head_dim;
    j["linear_conv_kernel_dim"] = v.linear_conv_kernel_dim;
    j["attn_output_gate"] = v.attn_output_gate;
    j["partial_rotary_factor"] = v.partial_rotary_factor;
    j["mtp_num_hidden_layers"] = v.mtp_num_hidden_layers;
    j["mtp_use_dedicated_embeddings"] = v.mtp_use_dedicated_embeddings;
    j["altup_num_inputs"] = v.altup_num_inputs;
    j["altup_active_idx"] = v.altup_active_idx;
    j["altup_correct_scale"] = v.altup_correct_scale;
    j["altup_coef_clip"] = v.altup_coef_clip;
    j["laurel_rank"] = v.laurel_rank;
    j["vocab_size_per_layer_input"] = v.vocab_size_per_layer_input;
    j["gemma3n_rope_local_base_freq"] = v.gemma3n_rope_local_base_freq;
    j["gemma3n_per_layer_intermediate"] = v.gemma3n_per_layer_intermediate;
    j["gemma3n_activation_sparsity"] = v.gemma3n_activation_sparsity;
    j["kda_gate_lower_bound"] = v.kda_gate_lower_bound;
    j["kda_full_rank_gate"] = v.kda_full_rank_gate;
    j["mla_use_nope"] = v.mla_use_nope;
    j["mla_output_gate"] = v.mla_output_gate;
    j["routed_expert_hidden_size"] = v.routed_expert_hidden_size;
    j["latent_moe_use_norm"] = v.latent_moe_use_norm;
    j["attn_res_block_size"] = v.attn_res_block_size;
    j["situ_beta"] = v.situ_beta;
    j["situ_linear_beta"] = v.situ_linear_beta;
    j["moe_router_activation_func"] = v.moe_router_activation_func;
    j["index_topk"] = v.index_topk;
    j["index_head_dim"] = v.index_head_dim;
    j["index_n_heads"] = v.index_n_heads;
    j["indexer_types"] = v.indexer_types;
    j["torch_dtype"] = v.torch_dtype;
    j["quant_method"] = v.quant_method;
    j["quant_bits"] = v.quant_bits;
    j["quant_group_size"] = v.quant_group_size;
    j["quant_desc_act"] = v.quant_desc_act;
    j["quant_sym"] = v.quant_sym;
    j["quant_zero_point"] = v.quant_zero_point;
    j["kv_cache_scheme_present"] = v.kv_cache_scheme_present;
    j["mm_lm_strip_prefix"] = v.mm_lm_strip_prefix;
    j["mm_skip_prefixes"] = v.mm_skip_prefixes;
    j["gemma_vision"] = v.gemma_vision ? dump(*v.gemma_vision) : nlohmann::json(nullptr);
    j["gemma_audio"] = v.gemma_audio ? dump(*v.gemma_audio) : nlohmann::json(nullptr);
    j["qwen3_vl_vision"] = v.qwen3_vl_vision ? dump(*v.qwen3_vl_vision) : nlohmann::json(nullptr);
    j["csm"] = v.csm ? dump(*v.csm) : nlohmann::json(nullptr);
    j["qwen3_vl_mrope_section"] = v.qwen3_vl_mrope_section;
    j["qwen3_vl_mrope_interleaved"] = v.qwen3_vl_mrope_interleaved;
    j["qwen3_vl_image_token_id"] = v.qwen3_vl_image_token_id;
    j["qwen3_vl_vision_start_token_id"] = v.qwen3_vl_vision_start_token_id;
    j["qwen3_vl_vision_end_token_id"] = v.qwen3_vl_vision_end_token_id;
    return j;
}

}  // namespace

// This file used to carry a `main` that dumped `parse_hf_config(argv[1])`, and
// that was the oracle: the C++ normalizer behind a JSON emitter, so the Rust
// port could be diffed against it. The port won and `config.cpp` was deleted,
// so the entry point is gone with the function it called. What is left is the
// emitter, which `dump_from_descriptor.cpp` includes to print an `HfConfig`
// the descriptor reader produced -- the same emitter, so the same output shape
// the `golden/` files were recorded in.
