use crate::shared::vocabulary::{Member, Vocab};

pub const VOCAB: Vocab = Vocab(&[

    Member::same("backbone_model.layers.{layer}.input_layernorm"),
    Member::same("backbone_model.layers.{layer}.mlp.down_proj"),
    Member::same("backbone_model.layers.{layer}.mlp.gate_proj"),
    Member::same("backbone_model.layers.{layer}.mlp.up_proj"),
    Member::same("backbone_model.layers.{layer}.post_attention_layernorm"),
    Member::same("backbone_model.layers.{layer}.self_attn.k_proj"),
    Member::same("backbone_model.layers.{layer}.self_attn.o_proj"),
    Member::same("backbone_model.layers.{layer}.self_attn.q_proj"),
    Member::same("backbone_model.layers.{layer}.self_attn.v_proj"),
    Member::same("codec_model.decoder.layers.{layer}.conv"),
    Member::same("codec_model.decoder_transformer.layers.{layer}.self_attn.q_proj"),
    Member::same("codec_model.decoder_transformer.layers.{layer}.self_attn_layer_scale.scale"),
    Member::same("codec_model.encoder.layers.{layer}.conv"),
    Member::same("codec_model.encoder_transformer.layers.{layer}.self_attn.q_proj"),
    Member::same(
        "codec_model.quantizer.acoustic_residual_vector_quantizer.layers.{layer}.codebook.embed_sum",
    ),
    Member::same(
        "codec_model.quantizer.semantic_residual_vector_quantizer.layers.{layer}.codebook.embed_sum",
    ),
    Member::same("depth_decoder.model.layers.{layer}.input_layernorm"),
    Member::same("depth_decoder.model.layers.{layer}.mlp.down_proj"),
    Member::same("depth_decoder.model.layers.{layer}.mlp.gate_proj"),
    Member::same("depth_decoder.model.layers.{layer}.mlp.up_proj"),
    Member::same("depth_decoder.model.layers.{layer}.post_attention_layernorm"),
    Member::same("depth_decoder.model.layers.{layer}.self_attn.k_proj"),
    Member::same("depth_decoder.model.layers.{layer}.self_attn.o_proj"),
    Member::same("depth_decoder.model.layers.{layer}.self_attn.q_proj"),
    Member::same("depth_decoder.model.layers.{layer}.self_attn.v_proj"),

    Member::same("backbone_model.embed_tokens.embed_audio_tokens"),
    Member::same("backbone_model.norm"),
    Member::same("codec_model.downsample.conv"),
    Member::same("codec_model.quantizer.acoustic_residual_vector_quantizer.output_proj"),
    Member::same("codec_model.quantizer.semantic_residual_vector_quantizer.input_proj"),
    Member::same("codec_model.upsample.conv"),
    Member::same("depth_decoder.codebooks_head"),
    Member::same("depth_decoder.model.embed_tokens"),
    Member::same("depth_decoder.model.inputs_embeds_projector"),
    Member::same("depth_decoder.model.norm"),
    Member::same("model.embed_text_tokens"),
    Member::same("lm_head"),
]);
