[package]
name = "controller"
version.workspace = true
edition = "2024"
authors = ["In Gim <in.gim@icloud.com>"]
description = "Distributed control plane for Pie"
license = "Apache-2.0"
repository = "https://github.com/pie-project/pie"

[lib]
name = "controller"
path = "src/lib.rs"
crate-type = ["rlib"]


[dependencies]
controller-api = { path = "../controller-api" }
ids = { path = "../ids" }
tarpc = { version = "0.37", features = [
    "serde-transport",
    "serde-transport-bincode",
    "tcp",
    "unix",
] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "time", "sync"] }
tokio-util = "0.7"
futures = "0.3"
tracing = "0.1"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
toml = "1.1"

[lints]
workspace = true
