//! Raw NIXL C-API bindings, generated by `build.rs` (bindgen over the vendored
//! `wrapper.h`) and linked against the wheel's `libnixl_capi.so`. Not used
//! directly outside this module — [`super`] wraps it in a safe [`Engine`].
//!
//! [`Engine`]: crate::core::Engine
#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]

include!(concat!(env!("OUT_DIR"), "/nixl_ffi.rs"));
