pub mod forward;
pub mod import;
pub mod media;
pub mod model;
pub mod template;
pub mod tokenizer;

use model::Model;
use model_dsl::Dtype;

/// Identification order: the first row whose import fits the checkpoint wins.
pub fn skus() -> Vec<crate::Sku> {
    crate::skus![
        (
            "qwen36-27b",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            model_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            |tp: u32| Model::d27b_undrafted(Dtype::U4g64, Dtype::Bf16, tp),
        ),
        (
            "qwen35-d0.8b",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            model_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            |tp: u32| Model::d0_8b(Dtype::U4g64, Dtype::Bf16, tp),
        ),
        (
            "qwen36-35b-a3b",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            model_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            |tp: u32| Model::a3b(Dtype::U4g64, Dtype::Bf16, tp),
        ),
        (
            "qwen36-35b-a3b-mini",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            model_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            |tp: u32| Model::a3b_mini(Dtype::U4g64, Dtype::Bf16, tp),
        ),
        (
            "qwen36-35b-a3b-mini64",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            model_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            |tp: u32| Model::a3b_mini64(Dtype::U4g64, Dtype::Bf16, tp),
        ),
        (
            "qwen36-27b",
            1,
            [Dtype::Bf16],
            Dtype::Bf16,
            model_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            |tp: u32| Model::d27b(Dtype::Bf16, Dtype::Bf16, tp),
        ),
        (
            "qwen38-27b",
            1,
            [Dtype::Bf16],
            Dtype::Bf16,
            model_dsl::trace_hybrid,
            template::chatml_interleaved,
            &tokenizer::CONTRACT_38,
            |tp: u32| Model::d27b(Dtype::Bf16, Dtype::Bf16, tp),
        ),
        (
            "qwen38-27b",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            model_dsl::trace_hybrid,
            template::chatml_interleaved,
            &tokenizer::CONTRACT_38,
            |tp: u32| Model::d27b_undrafted(Dtype::U4g64, Dtype::Bf16, tp),
        ),
        (
            "qwen35-a3b",
            1,
            [Dtype::Bf16],
            Dtype::Bf16,
            model_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            |tp: u32| Model::a3b(Dtype::Bf16, Dtype::Bf16, tp),
        ),
        (
            "qwen35-d3b",
            1,
            [Dtype::Bf16],
            Dtype::Bf16,
            model_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            |tp: u32| Model::d3b(Dtype::Bf16, Dtype::Bf16, tp),
        ),
        (
            "qwen35-d0.8b-eagle",
            1,
            [Dtype::Bf16],
            Dtype::Bf16,
            model_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            |tp: u32| Model::d0_8b_eagle(Dtype::Bf16, Dtype::Bf16, tp),
        ),
        (
            "qwen35-d0.8b",
            1,
            [Dtype::Bf16],
            Dtype::Bf16,
            model_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            |tp: u32| Model::d0_8b(Dtype::Bf16, Dtype::Bf16, tp),
        ),
        (
            "qwen35-a3b",
            2,
            [Dtype::Bf16],
            Dtype::Bf16,
            model_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            |tp: u32| Model::a3b(Dtype::Bf16, Dtype::Bf16, tp),
        ),
        (
            "qwen35-d0.8b-vision-eagle",
            1,
            [Dtype::Bf16],
            Dtype::Bf16,
            model_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT_VISION,
            |tp: u32| Model::d0_8b_vision_eagle(Dtype::Bf16, Dtype::Bf16, tp),
        ),
        (
            "qwen36-27b-vision",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            model_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT_VISION,
            |tp: u32| Model::d27b_vision_undrafted(Dtype::U4g64, Dtype::Bf16, tp),
        ),
        (
            "qwen36-27b-vision",
            1,
            [Dtype::Bf16],
            Dtype::Bf16,
            model_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT_VISION,
            |tp: u32| Model::d27b_vision(Dtype::Bf16, Dtype::Bf16, tp),
        ),
        (
            "qwen38-27b-vision",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            model_dsl::trace_hybrid,
            template::chatml_interleaved,
            &tokenizer::CONTRACT_38_VISION,
            |tp: u32| Model::d27b_vision_undrafted(Dtype::U4g64, Dtype::Bf16, tp),
        ),
        (
            "qwen38-27b-vision",
            1,
            [Dtype::Bf16],
            Dtype::Bf16,
            model_dsl::trace_hybrid,
            template::chatml_interleaved,
            &tokenizer::CONTRACT_38_VISION,
            |tp: u32| Model::d27b_vision(Dtype::Bf16, Dtype::Bf16, tp),
        ),
        (
            "qwen35-d0.8b-vision",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            model_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT_VISION,
            |tp: u32| Model::d0_8b_vision(Dtype::U4g64, Dtype::Bf16, tp),
        ),
        (
            "qwen35-d0.8b-vision",
            1,
            [Dtype::Bf16],
            Dtype::Bf16,
            model_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT_VISION,
            |tp: u32| Model::d0_8b_vision(Dtype::Bf16, Dtype::Bf16, tp),
        ),
    ]
}
