#ifndef PIE_WEIGHT_LOADER_H
#define PIE_WEIGHT_LOADER_H

#pragma once

/* Generated by cbindgen. Do not edit by hand. */

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace pie_weight_loader {

constexpr static const uint32_t STORAGE_PROGRAM_VERSION = 3;

enum class PieLoaderBackendKind {
  Cuda = 0,
  Portable = 1,
  Unknown = 255,
};

enum class PieLoaderCheckpointFormat {
  Safetensors = 0,
  Gguf = 1,
  Unknown = 255,
};

enum class PieLoaderDType {
  F32 = 0,
  F16 = 1,
  BF16 = 2,
  F8E4M3 = 3,
  F8E5M2 = 4,
  I32 = 5,
  I16 = 6,
  I8 = 7,
  U32 = 8,
  U16 = 9,
  U8 = 10,
  Bool = 11,
};

enum class PieLoaderEncodingKind {
  Raw = 0,
  Quant = 1,
};

enum class PieLoaderMxfp4MoePolicy {
  RoutedDecode = 0,
  NativeGemm = 1,
  EagerBf16 = 2,
};

enum class PieLoaderQuantScheme {
  None = 0,
  Fp8E4M3 = 1,
  Fp8E5M2 = 2,
  Int8Symmetric = 3,
  Int8Asymmetric = 4,
  AwqInt4 = 5,
  GptqInt4 = 6,
  Mxfp4E2M1E8M0 = 7,
  GgufQ4_0 = 8,
  GgufQ4K = 9,
  GgufQ5_0 = 10,
  GgufQ5K = 11,
  GgufQ8_0 = 12,
};

enum class PieLoaderRepackLayout {
  None = 0,
  MarlinMxfp4Weight = 1,
  MarlinMxfp4Scale = 2,
  DenseRowGather = 3,
};

enum class PieLoaderRowMap {
  Identity = 0,
  Even = 1,
  Odd = 2,
};

enum class PieLoaderRuntimeSourceKind {
  DirectTensor = 0,
  Semantic = 1,
  Join = 2,
  Select = 3,
  ByteSpans = 4,
};

enum class PieLoaderSemanticRole {
  DirectTensor = 0,
  TokenEmbedding = 1,
  OutputEmbedding = 2,
  AttentionQ = 3,
  AttentionK = 4,
  AttentionV = 5,
  AttentionO = 6,
  MlpGate = 7,
  MlpUp = 8,
  MlpDown = 9,
  ExpertRouter = 10,
  ExpertGate = 11,
  ExpertUp = 12,
  ExpertDown = 13,
  ExpertBias = 14,
  Norm = 15,
  QuantData = 16,
  QuantScale = 17,
  QuantZeroPoint = 18,
  QuantGroupIndex = 19,
};

enum class PieLoaderStatus {
  Ok = 0,
  NullArgument = 1,
  InvalidInput = 2,
  InternalError = 3,
};

enum class PieLoaderStorageInstrKind {
  Allocate = 0,
  ExtentWrite = 1,
  TileMap = 2,
  CreateView = 3,
  Attach = 4,
  Release = 5,
  Finalize = 6,
  BulkExtentWrite = 7,
  SlabScatter = 8,
};

enum class PieLoaderTileMapKind {
  Cast = 0,
  Decode = 1,
  Encode = 2,
  Transcode = 3,
  Reblock = 4,
  Reorder = 5,
  Repack = 6,
  None = 255,
};

struct PieLoaderProgramHandle;

struct PieLoaderBytes {
  const uint8_t *ptr;
  size_t len;
};

struct PieLoaderU32Slice {
  const uint32_t *ptr;
  size_t len;
};

struct PieLoaderI64Slice {
  const int64_t *ptr;
  size_t len;
};

struct PieLoaderDimSpecView {
  int64_t count;
  int64_t src_stride;
  int64_t dst_stride;
};

struct PieLoaderDimSpecSlice {
  const PieLoaderDimSpecView *ptr;
  size_t len;
};

struct PieLoaderBufferIdSlice {
  const uint32_t *ptr;
  size_t len;
};

struct PieLoaderStridedExtentView {
  uint64_t base_offset;
  uint32_t element_bytes;
  PieLoaderDimSpecSlice dims;
};

struct PieLoaderSourceExtentView {
  uint32_t file_id;
  uint32_t tensor_id;
  uint64_t file_offset;
  uint64_t span_bytes;
  PieLoaderStridedExtentView stride;
};

struct PieLoaderDestExtentView {
  uint32_t buffer_id;
  uint64_t offset;
  PieLoaderStridedExtentView stride;
};

struct PieLoaderCheckpointFileView {
  uint32_t id;
  PieLoaderBytes path;
  uint64_t size_bytes;
  PieLoaderCheckpointFormat format;
};

struct PieLoaderCheckpointFileSlice {
  const PieLoaderCheckpointFileView *ptr;
  size_t len;
};

struct PieLoaderCheckpointTensorView {
  uint32_t id;
  PieLoaderBytes name;
  uint32_t file_id;
  uint64_t file_offset;
  uint64_t span_bytes;
  PieLoaderDType dtype;
  PieLoaderEncodingKind encoding_kind;
  PieLoaderQuantScheme quant_scheme;
  PieLoaderI64Slice shape;
  uint8_t quant_bits_per_element;
  uint32_t quant_group_size;
  int32_t quant_channel_axis;
  bool quant_has_scale_dtype;
  PieLoaderDType quant_scale_dtype;
  bool quant_has_zero_point_dtype;
  PieLoaderDType quant_zero_point_dtype;
  PieLoaderI64Slice quant_block_shape;
};

struct PieLoaderCheckpointTensorSlice {
  const PieLoaderCheckpointTensorView *ptr;
  size_t len;
};

struct PieLoaderRuntimeByteSpanView {
  uint32_t source_tensor_id;
  uint64_t source_offset_bytes;
  uint64_t dest_offset_bytes;
  uint64_t span_bytes;
};

struct PieLoaderRuntimeByteSpanSlice {
  const PieLoaderRuntimeByteSpanView *ptr;
  size_t len;
};

struct PieLoaderRuntimeTensorContractView {
  PieLoaderBytes output_name;
  PieLoaderRuntimeSourceKind source_kind;
  uint32_t source_tensor_id;
  PieLoaderU32Slice source_tensor_ids;
  PieLoaderRuntimeByteSpanSlice byte_spans;
  PieLoaderU32Slice metadata_tensor_ids;
  uint32_t source_contract_id;
  PieLoaderSemanticRole semantic_role;
  uint32_t layer;
  bool has_layer;
  uint32_t expert;
  bool has_expert;
  int32_t axis;
  int64_t start;
  int64_t length;
  PieLoaderDType dtype;
  PieLoaderEncodingKind encoding_kind;
  PieLoaderQuantScheme quant_scheme;
  PieLoaderI64Slice shape;
  uint32_t alignment;
  int32_t shard_axis;
  uint8_t quant_bits_per_element;
  uint32_t quant_group_size;
  int32_t quant_channel_axis;
  bool quant_has_scale_dtype;
  PieLoaderDType quant_scale_dtype;
  bool quant_has_zero_point_dtype;
  PieLoaderDType quant_zero_point_dtype;
  PieLoaderI64Slice quant_block_shape;
};

struct PieLoaderRuntimeTensorContractSlice {
  const PieLoaderRuntimeTensorContractView *ptr;
  size_t len;
};

struct PieLoaderModelConfigView {
  PieLoaderBytes model_type;
  PieLoaderBytes quant_method;
  PieLoaderBytes runtime_quant;
  uint32_t num_hidden_layers;
  uint32_t num_experts;
  uint32_t num_experts_per_tok;
};

struct PieLoaderRuntimeAbiView {
  PieLoaderBytes name;
  uint32_t version;
  PieLoaderRuntimeTensorContractSlice tensors;
};

struct PieLoaderBackendTargetView {
  PieLoaderBackendKind backend;
  uint32_t tp_rank;
  uint32_t tp_size;
  uint64_t max_tile_bytes;
  uint32_t preferred_alignment;
  PieLoaderMxfp4MoePolicy mxfp4_moe;
  bool native_mxfp4_moe;
};

struct PieLoaderCompileInput {
  uint32_t version;
  PieLoaderCheckpointFileSlice files;
  PieLoaderCheckpointTensorSlice tensors;
  PieLoaderModelConfigView model;
  PieLoaderRuntimeAbiView runtime_abi;
  PieLoaderBackendTargetView target;
};

struct PieLoaderTensorDeclView {
  uint32_t id;
  PieLoaderBytes name;
  PieLoaderDType dtype;
  PieLoaderEncodingKind encoding_kind;
  PieLoaderQuantScheme quant_scheme;
  PieLoaderI64Slice shape;
  uint32_t alignment;
};

struct PieLoaderTensorDeclSlice {
  const PieLoaderTensorDeclView *ptr;
  size_t len;
};

struct PieLoaderBufferDeclView {
  uint32_t id;
  uint32_t tensor_id;
  bool has_tensor;
  uint64_t bytes;
  uint32_t alignment;
  bool temporary;
  bool has_persistent_offset;
  uint64_t persistent_offset;
};

struct PieLoaderBufferDeclSlice {
  const PieLoaderBufferDeclView *ptr;
  size_t len;
};

struct PieLoaderSlabPlacementView {
  uint64_t src_offset;
  uint64_t dest_offset;
  uint64_t bytes;
};

struct PieLoaderSlabPlacementSlice {
  const PieLoaderSlabPlacementView *ptr;
  size_t len;
};

struct PieLoaderStorageInstrView {
  uint32_t id;
  PieLoaderStorageInstrKind kind;
  uint32_t buffer_id;
  PieLoaderSourceExtentView source;
  bool has_source;
  PieLoaderDestExtentView dest;
  bool has_dest;
  PieLoaderBufferIdSlice input_buffers;
  PieLoaderBufferIdSlice output_buffers;
  PieLoaderTileMapKind tile_kind;
  uint64_t max_tile_bytes;
  PieLoaderQuantScheme transform_from;
  PieLoaderQuantScheme transform_to;
  PieLoaderRepackLayout repack_layout;
  PieLoaderRowMap row_map;
  uint32_t transform_batch;
  uint32_t transform_source_rows;
  uint32_t transform_source_row_offset;
  uint32_t transform_target_rows;
  uint32_t transform_valid_rows;
  uint32_t transform_source_stride_cols;
  uint32_t transform_source_col_offset;
  uint32_t transform_source_cols;
  uint32_t transform_target_cols;
  uint64_t transform_scratch_bytes;
  PieLoaderBytes name;
  uint32_t slab_file_id;
  uint64_t slab_file_offset;
  uint64_t slab_span_bytes;
  PieLoaderSlabPlacementSlice slab_placements;
};

struct PieLoaderStorageInstrSlice {
  const PieLoaderStorageInstrView *ptr;
  size_t len;
};

struct PieLoaderMemoryPlanView {
  uint64_t persistent_bytes;
  uint64_t temporary_peak_bytes;
  uint64_t transform_scratch_peak_bytes;
  uint64_t checkpoint_read_bytes;
  uint64_t device_write_bytes;
};

struct PieLoaderOptimizerPassStatsView {
  PieLoaderBytes name;
  uint64_t exprs_before;
  uint64_t exprs_after;
  uint64_t rewrites;
};

struct PieLoaderOptimizerPassStatsSlice {
  const PieLoaderOptimizerPassStatsView *ptr;
  size_t len;
};

struct PieLoaderOptimizerReportView {
  PieLoaderOptimizerPassStatsSlice passes;
};

struct PieLoaderStorageProgramView {
  uint32_t version;
  PieLoaderTensorDeclSlice tensors;
  PieLoaderBufferDeclSlice buffers;
  PieLoaderStorageInstrSlice instrs;
  PieLoaderU32Slice schedule;
  PieLoaderMemoryPlanView memory;
  PieLoaderOptimizerReportView optimizer;
};

struct PieLoaderError {
  PieLoaderStatus code;
  char *message;
};

}  // namespace pie_weight_loader

#endif  // PIE_WEIGHT_LOADER_H
