#pragma once

/* Generated by pie-driver-abi-cbindgen (cbindgen). Do not edit by hand. Regenerate: cargo run -p pie-driver-abi-cbindgen */

#include <stddef.h>
#include <stdint.h>

#define KV_COPY_DEVICE_TO_DEVICE (1 << 0)

#define KV_COPY_DEVICE_TO_HOST (1 << 1)

#define KV_COPY_HOST_TO_DEVICE (1 << 2)

#define KV_COPY_HOST_TO_HOST (1 << 3)

#define PIE_DEVICE_PORT_EMBED_TOKENS (1 << 0)

#define PIE_DEVICE_PORT_PAGES (1 << 1)

#define PIE_DEVICE_PORT_POSITIONS (1 << 2)

#define PIE_DEVICE_PORT_PAGE_INDPTR (1 << 3)

#define PIE_DEVICE_PORT_W_SLOT (1 << 4)

#define PIE_DEVICE_PORT_KV_LEN (1 << 5)

#define PIE_DEVICE_PORT_W_OFF (1 << 6)

/**
 * The driver resolves a dense `AttnMask` descriptor channel (device-carried
 * bool mask cells) pre-forward. Orthogonal to the geometry-class port sets:
 * a masked device-resolved pass additionally requires this bit.
 */
#define PIE_DEVICE_PORT_ATTN_MASK (1 << 7)

/**
 * Full device-resolved port mask of the `DecodeEnvelope` geometry class.
 * Driver-neutral: any backend that executes the class resolves exactly these
 * ports on device.
 */
#define PIE_DECODE_ENVELOPE_PORTS ((PIE_DEVICE_PORT_EMBED_TOKENS | PIE_DEVICE_PORT_POSITIONS) | PIE_DEVICE_PORT_KV_LEN)

/**
 * Full device-resolved port mask of the `DeviceGeometry` geometry class:
 * the program traces its complete explicit geometry in-graph and the driver
 * resolves every descriptor port from device channel cells pre-forward.
 */
#define PIE_DEVICE_GEOMETRY_PORTS ((((((PIE_DEVICE_PORT_EMBED_TOKENS | PIE_DEVICE_PORT_PAGES) | PIE_DEVICE_PORT_POSITIONS) | PIE_DEVICE_PORT_PAGE_INDPTR) | PIE_DEVICE_PORT_W_SLOT) | PIE_DEVICE_PORT_KV_LEN) | PIE_DEVICE_PORT_W_OFF)

/**
 * Current direct local ABI version.
 *
 * v14 (Project Venus): the launch unit is the sealed **frame** — one
 * [`PieFrameDesc`] carries k forward steps that the driver executes as one
 * closed system with a single completion. Frame-invariant tables (lane
 * roster, WorkingSet page translation, frame-union KV admission demand) are
 * hoisted out of the per-step sections. Admission is folded into the launch
 * call itself ([`PIE_STATUS_EXHAUSTED`] / [`PIE_STATUS_IMPOSSIBLE`]); the
 * v12 prepare/lease surface and the v13 `settle_defer` lever are deleted.
 */
#define PIE_DRIVER_ABI_VERSION 14

#define PIE_MODEL_COMPONENT_FULL 0

#define PIE_MODEL_COMPONENT_TEXT 1

#define PIE_MODEL_COMPONENT_ENCODE 2

/**
 * Success.
 */
#define PIE_STATUS_OK 0

/**
 * Descriptor validation failed synchronously.
 */
#define PIE_STATUS_INVALID_ARGUMENT -1

/**
 * ABI version or layout mismatch.
 */
#define PIE_STATUS_BAD_ABI_VERSION -2

/**
 * The requested operation is not implemented by the driver.
 */
#define PIE_STATUS_UNSUPPORTED -3

/**
 * The target object is closed or otherwise unavailable.
 */
#define PIE_STATUS_CLOSED -4

/**
 * The driver encountered an internal failure after accepting the call.
 */
#define PIE_STATUS_DRIVER_ERROR -5

/**
 * Frame admission is full right now; the frame may fit after physical
 * budget is released. The engine re-posts later.
 */
#define PIE_STATUS_EXHAUSTED -6

/**
 * The frame can never fit within the driver's physical budget ceiling.
 */
#define PIE_STATUS_IMPOSSIBLE -7

#define PIE_GEOMETRY_CLASS_HOST 0

#define PIE_GEOMETRY_CLASS_DECODE_ENVELOPE 1

#define PIE_GEOMETRY_CLASS_DEVICE_GEOMETRY 2

/**
 * Reset the recurrent-state slot before executing the request.
 */
#define PIE_RS_FLAG_RESET 1

/**
 * Fold buffered recurrent-state data into the slot after the pass.
 */
#define PIE_RS_FLAG_FOLD 2

/**
 * Concrete F32 channel element type.
 */
#define PIE_CHANNEL_DTYPE_F32 0

/**
 * Concrete I32 channel element type.
 */
#define PIE_CHANNEL_DTYPE_I32 1

/**
 * Concrete U32 channel element type.
 */
#define PIE_CHANNEL_DTYPE_U32 2

/**
 * Concrete boolean channel element type.
 */
#define PIE_CHANNEL_DTYPE_BOOL 3

/**
 * Driver-resolved activation channel element type.
 */
#define PIE_CHANNEL_DTYPE_ACT 4

/**
 * Channel has no host endpoint.
 */
#define PIE_CHANNEL_HOST_ROLE_NONE 0

/**
 * Host produces values consumed by the device program.
 */
#define PIE_CHANNEL_HOST_ROLE_WRITER 1

/**
 * Device program produces values consumed by the host.
 */
#define PIE_CHANNEL_HOST_ROLE_READER 2

/**
 * Channel is private to one bound instance.
 */
#define PIE_CHANNEL_EXTERN_NONE 0

/**
 * Bound program consumes an externally produced channel.
 */
#define PIE_CHANNEL_EXTERN_IMPORT 1

/**
 * Bound program produces an externally consumed channel.
 */
#define PIE_CHANNEL_EXTERN_EXPORT 2

#define PIE_ELASTIC_POOL_KV 0

#define PIE_ELASTIC_POOL_STATE 1

#define PIE_ELASTIC_POOL_WORKSPACE 2

#define CHANNEL_TICKET_NONE UINT64_MAX

#define RS_FLAG_RESET 1

#define RS_FLAG_FOLD 2

#define REMOTE_WIRE_VERSION 8

/**
 * Opaque embedded-driver handle.
 */
typedef void PieDriver;

/**
 * Borrowed immutable byte slice.
 *
 * `ptr` may be null only when `len == 0`.
 */
typedef struct PieBytes {
  const uint8_t *ptr;
  size_t len;
} PieBytes;

/**
 * Runtime completion callback, callable from any foreign thread.
 *
 * `ctx` is an opaque runtime-owned pointer, forwarded unchanged from
 * [`PieRuntimeCallbacks::ctx`]. Embedded drivers may invoke this callback from
 * any foreign thread after an operation has been accepted.
 */
typedef void (*PieRuntimeNotifyFn)(void *ctx, uint64_t wait_id, uint64_t epoch);

/**
 * Runtime-owned callbacks passed at driver creation time.
 */
typedef struct PieRuntimeCallbacks {
  uint32_t abi_version;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  /**
   * Opaque runtime-owned context pointer forwarded to [`PieRuntimeNotifyFn`].
   */
  void *ctx;
  /**
   * Mandatory for embedded native-driver creation.
   */
  PieRuntimeNotifyFn notify;
} PieRuntimeCallbacks;

/**
 * Driver creation descriptor.
 */
typedef struct PieDriverCreateDesc {
  uint32_t abi_version;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  struct PieBytes config_bytes;
  struct PieRuntimeCallbacks runtime;
} PieDriverCreateDesc;

/**
 * Driver-owned JSON payload returned from a cold boot call.
 */
typedef struct PieDriverCaps {
  const uint8_t *json_bytes;
  size_t json_len;
} PieDriverCaps;

/**
 * Blocking model-load descriptor.
 */
typedef struct PieModelLoadDesc {
  uint32_t abi_version;
  /**
   * One of `PIE_MODEL_COMPONENT_*`.
   */
  uint32_t component;
  /**
   * Compiler source hash expected by this runtime.
   */
  uint64_t compiler_version;
  /**
   * Serialized, versioned LoadPlan. Empty plans are invalid.
   */
  struct PieBytes load_plan_bytes;
  /**
   * UTF-8 path to the driver-local checkpoint payload root.
   */
  struct PieBytes snapshot_dir;
} PieModelLoadDesc;

/**
 * Static program registration descriptor.
 */
typedef struct PieProgramDesc {
  uint32_t abi_version;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  /**
   * Stable C3 registration/cache key; canonical bytes are only needed on first registration.
   */
  uint64_t program_hash;
  struct PieBytes canonical_bytes;
  struct PieBytes sidecar_bytes;
} PieProgramDesc;

/**
 * Borrowed immutable `u32` slice.
 *
 * `ptr` may be null only when `len == 0`.
 */
typedef struct PieU32Slice {
  const uint32_t *ptr;
  size_t len;
} PieU32Slice;

/**
 * Persistent channel endpoint registration descriptor.
 */
typedef struct PieChannelDesc {
  uint32_t abi_version;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  uint64_t channel_id;
  struct PieU32Slice shape;
  /**
   * One of `PIE_CHANNEL_DTYPE_*`.
   */
  uint8_t dtype;
  /**
   * One of `PIE_CHANNEL_HOST_ROLE_*`.
   */
  uint8_t host_role;
  /**
   * Must be 0 or 1.
   */
  uint8_t seeded;
  /**
   * One of `PIE_CHANNEL_EXTERN_*`.
   */
  uint8_t extern_dir;
  uint32_t capacity;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved1;
  uint64_t reader_wait_id;
  uint64_t writer_wait_id;
  /**
   * Canonical extern binding name. Empty for private channels.
   */
  struct PieBytes extern_name;
} PieChannelDesc;

/**
 * Stable driver-owned host endpoint returned by channel registration.
 */
typedef struct PieChannelEndpointBinding {
  uint64_t channel_id;
  uint64_t mirror_base;
  uint64_t word_base;
  uint64_t mirror_bytes;
  uint64_t word_bytes;
  uint32_t cell_bytes;
  uint32_t capacity;
  uint32_t head_word_index;
  uint32_t tail_word_index;
  uint32_t poison_word_index;
  uint32_t closed_word_index;
} PieChannelEndpointBinding;

/**
 * Borrowed immutable `u64` slice.
 *
 * `ptr` may be null only when `len == 0`.
 */
typedef struct PieU64Slice {
  const uint64_t *ptr;
  size_t len;
} PieU64Slice;

/**
 * One channel-value payload used for PTIR seeds and host puts.
 */
typedef struct PieChannelValueDesc {
  uint64_t channel_id;
  struct PieBytes bytes;
} PieChannelValueDesc;

/**
 * Borrowed immutable slice of [`PieChannelValueDesc`].
 *
 * `ptr` may be null only when `len == 0`.
 */
typedef struct PieChannelValueDescSlice {
  const struct PieChannelValueDesc *ptr;
  size_t len;
} PieChannelValueDescSlice;

/**
 * Per-instance bind descriptor.
 */
typedef struct PieInstanceDesc {
  uint32_t abi_version;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  /**
   * Runtime-derived geometry class; the driver verifies this against the
   * registered trace and echoes it in `PieInstanceBinding`.
   */
  uint32_t geometry_class;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved1;
  uint64_t program_id;
  uint64_t requested_instance_id;
  uint64_t pacing_wait_id;
  struct PieU64Slice channel_ids;
  struct PieChannelValueDescSlice seed_values;
} PieInstanceDesc;

/**
 * Driver-assigned identity returned from `*_bind_instance`.
 */
typedef struct PieInstanceBinding {
  uint64_t instance_id;
  uint32_t geometry_class;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
} PieInstanceBinding;

/**
 * Terminal completion outcome published by the native driver.
 */
typedef uint32_t PieTerminalOutcome;

/**
 * Host-visible terminal control cell.
 *
 * The `outcome` word is published with release semantics by the driver and
 * read with acquire semantics by the runtime.
 */
typedef struct PieTerminalCell {
  PieTerminalOutcome outcome;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
} PieTerminalCell;

/**
 * Borrowed immutable slice of terminal-cell pointers.
 *
 * The slice storage may be null only when `len == 0`. Each element must point
 * at a distinct, properly aligned [`PieTerminalCell`] that remains stable until
 * the corresponding accepted operation retires.
 */
typedef struct PieTerminalCellPtrSlice {
  struct PieTerminalCell *const *ptr;
  size_t len;
} PieTerminalCellPtrSlice;

/**
 * Borrowed immutable `u8` slice.
 *
 * `ptr` may be null only when `len == 0`.
 */
typedef struct PieU8Slice {
  const uint8_t *ptr;
  size_t len;
} PieU8Slice;

/**
 * Flattened mask words with request and row partitions.
 *
 * `request_indptr` partitions rows per request; `word_indptr` partitions the
 * packed `u32` words per row.
 */
typedef struct PieMaskWordsDesc {
  struct PieU32Slice request_indptr;
  struct PieU32Slice word_indptr;
  struct PieU32Slice words;
} PieMaskWordsDesc;

/**
 * One forward step of a frame: the per-step section of [`PieFrameDesc`].
 *
 * A step's batch members reference the frame's lane roster through
 * `roster_rows` and are partitioned into ordered geometry-homogeneous
 * sub-batches; sub-batch order resolves producer→consumer dependencies
 * within the step. Device-resolved (decode-envelope) sub-batches elide
 * their wire geometry exactly as in v13, so decode steps are naturally
 * small. Frame-invariant tables (roster ids, WorkingSet page translation,
 * KV admission demand) live on the frame, not the step.
 */
typedef struct PieStepDesc {
  /**
   * Indices into the frame roster (`PieFrameDesc::instance_ids`), one per
   * batch member, in sub-batch order.
   */
  struct PieU32Slice roster_rows;
  /**
   * CSR over `roster_rows`: sub-batch `b` spans members
   * `[sub_batch_indptr[b], sub_batch_indptr[b+1])`.
   */
  struct PieU32Slice sub_batch_indptr;
  /**
   * `PIE_GEOMETRY_CLASS_*` per sub-batch, parallel to the CSR segments.
   */
  struct PieU32Slice sub_batch_class;
  /**
   * Stable terminal control cell addresses, one per `roster_rows` member.
   */
  struct PieTerminalCellPtrSlice terminal_cells;
  struct PieU32Slice token_ids;
  struct PieU32Slice position_ids;
  struct PieU32Slice kv_page_indices;
  struct PieU32Slice kv_page_indptr;
  struct PieU32Slice kv_last_page_lens;
  struct PieU32Slice qo_indptr;
  /**
   * Folded recurrent-state slot per resolved `qo_indptr` row. Empty for
   * pure-attention launches; never indexed by `instance_ids`.
   */
  struct PieU32Slice rs_slot_ids;
  /**
   * Flags parallel to `rs_slot_ids`.
   */
  struct PieU8Slice rs_slot_flags;
  struct PieU32Slice rs_fold_lens;
  struct PieU32Slice rs_buffer_slot_ids;
  struct PieU32Slice rs_buffer_slot_indptr;
  struct PieMaskWordsDesc masks;
  /**
   * Model readout rows, flattened across the batch.
   */
  struct PieU32Slice sampling_indices;
  /**
   * Request → readout-row CSR parallel to the batch.
   */
  struct PieU32Slice sampling_indptr;
  struct PieU64Slice context_ids;
  /**
   * Boolean `0`/`1`; any other value is invalid.
   */
  uint8_t single_token_mode;
  /**
   * Boolean `0`/`1`; any other value is invalid.
   */
  uint8_t has_user_mask;
  /**
   * Reserved; must be zero.
   */
  uint8_t reserved_flags[2];
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  struct PieU32Slice image_indptr;
  struct PieU32Slice image_grids;
  struct PieU32Slice image_anchor_positions;
  struct PieBytes image_pixels;
  struct PieU32Slice image_pixel_indptr;
  struct PieU32Slice image_mrope_positions;
  struct PieU32Slice image_mrope_indptr;
  struct PieU32Slice image_patch_positions;
  struct PieU32Slice image_anchor_rows;
  struct PieBytes audio_features;
  struct PieU32Slice audio_feature_indptr;
  struct PieU32Slice audio_anchor_rows;
  struct PieU32Slice audio_indptr;
  struct PieBytes embed_rows;
  struct PieU32Slice embed_indptr;
  struct PieU32Slice embed_shapes;
  struct PieU8Slice embed_dtypes;
  struct PieU32Slice embed_anchor_rows;
  struct PieU32Slice embed_block_indptr;
  struct PieU32Slice kv_len;
  struct PieU64Slice kv_len_device;
  /**
   * Program → wire-request attribution CSR (`len == roster_rows.len + 1`
   * when present, else empty): step member `p` owns the wire request rows
   * `[row_indptr[p], row_indptr[p+1])` of `qo_indptr`/`kv_page_indptr`/
   * `sampling_indptr`. A device-geometry member's span is its empty
   * wire placeholder row; the driver substitutes its channel-resolved
   * geometry for that span when composing the forward batch.
   */
  struct PieU32Slice ptir_program_row_indptr;
  struct PieU64Slice ptir_kv_write_lower_bounds;
  struct PieU64Slice ptir_kv_write_upper_bounds;
  /**
   * Immutable logical-fire ids, one per `roster_rows` member.
   */
  struct PieU64Slice logical_fire_ids;
  /**
   * Dense-channel sequence tickets, CSR-partitioned per `roster_rows`
   * member.
   */
  struct PieU64Slice channel_expected_head;
  struct PieU64Slice channel_expected_tail;
  struct PieU32Slice channel_ticket_indptr;
} PieStepDesc;

/**
 * Borrowed slice of per-step sections.
 *
 * `ptr` may be null only when `len == 0`.
 */
typedef struct PieStepDescSlice {
  const struct PieStepDesc *ptr;
  size_t len;
} PieStepDescSlice;

/**
 * One sealed frame: the v14 launch unit.
 *
 * The driver executes the frame's steps as one closed system — steps chain
 * on-stream (device-resolved token feedback), data publication stays
 * per-step on-stream, and control settlement happens once at the frame
 * tail through the single launch completion. Admission is evaluated
 * against the frame-union demand at the launch call ([`PIE_STATUS_EXHAUSTED`]
 * / [`PIE_STATUS_IMPOSSIBLE`]); a frame that admits cannot fail per-lane
 * mid-frame (stream work is SUCCESS-only; deterministic compose kills latch
 * per-lane FAILED at the tail).
 */
typedef struct PieFrameDesc {
  uint32_t abi_version;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  /**
   * Lane roster: every bound instance participating in any step, in
   * scheduler order. No duplicates. Step sections reference these entries
   * by index (`PieStepDesc::roster_rows`).
   */
  struct PieU64Slice instance_ids;
  /**
   * Frame-union WorkingSet page translation, flattened across the roster:
   * entry `i` of a lane's segment is the PHYSICAL KV page id backing
   * WorkingSet-relative page index `i` for this FRAME (committed mapping
   * overlaid with ALL steps' prepared write targets). The driver maps any
   * WorkingSet-relative page reference it resolves from device channels
   * (`Pages` / `WSlot` descriptor ports) through this table; guests never
   * see physical ids. An empty segment means the lane's channel geometry
   * is already physical (legacy) or absent.
   */
  struct PieU32Slice kv_translation;
  /**
   * CSR partition of `kv_translation`, one segment per `instance_ids`
   * entry (`len == instance_ids.len + 1` when present, else empty).
   */
  struct PieU32Slice kv_translation_indptr;
  /**
   * Exclusive physical KV page high-water required after the LAST step —
   * the frame-union admission demand.
   */
  uint32_t required_kv_pages;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved1;
  /**
   * The frame's steps in execution order. Never empty.
   */
  struct PieStepDescSlice steps;
} PieFrameDesc;

/**
 * Payload-free asynchronous completion target.
 */
typedef struct PieCompletion {
  uint64_t wait_id;
  uint64_t target_epoch;
  /**
   * Stable terminal control cell for value-less operations. Frame launches
   * use the per-member `PieStepDesc::terminal_cells` instead.
   */
  struct PieTerminalCell *terminal_cell;
} PieCompletion;

typedef struct PieMutBytes {
  uint8_t *ptr;
  size_t len;
} PieMutBytes;

typedef struct PieU32MutSlice {
  uint32_t *ptr;
  size_t len;
} PieU32MutSlice;

typedef struct PieEncodeDesc {
  uint32_t abi_version;
  uint32_t reserved0;
  struct PieU32Slice image_grids;
  struct PieBytes image_pixels;
  struct PieU32Slice image_pixel_indptr;
  struct PieU32Slice image_patch_positions;
  struct PieU32Slice image_anchor_rows;
  struct PieBytes audio_features;
  struct PieU32Slice audio_feature_indptr;
  struct PieU32Slice audio_anchor_rows;
  struct PieMutBytes output_rows;
  struct PieU32MutSlice output_row_indptr;
} PieEncodeDesc;

/**
 * Memory domain tag for local KV residency copies.
 */
typedef uint32_t PieMemoryDomain;

/**
 * A single KV cell move expressed in physical page/token coordinates.
 */
typedef struct PieKvMoveCell {
  uint32_t dst_page_id;
  uint32_t dst_token_offset;
  uint32_t src_page_id;
  uint32_t src_token_offset;
} PieKvMoveCell;

/**
 * Borrowed immutable slice of [`PieKvMoveCell`].
 *
 * `ptr` may be null only when `len == 0`.
 */
typedef struct PieKvMoveCellSlice {
  const struct PieKvMoveCell *ptr;
  size_t len;
} PieKvMoveCellSlice;

/**
 * Direct KV-copy descriptor.
 *
 * Whole-page residency copies use the `src_page_ids`/`dst_page_ids` slices. The
 * optional `cells` slice carries per-token device KV moves for Design-B compaction.
 */
typedef struct PieKvCopyDesc {
  uint32_t abi_version;
  PieMemoryDomain src_domain;
  uint32_t src_device_ordinal;
  PieMemoryDomain dst_domain;
  uint32_t dst_device_ordinal;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  struct PieU32Slice src_page_ids;
  struct PieU32Slice dst_page_ids;
  struct PieKvMoveCellSlice cells;
} PieKvCopyDesc;

/**
 * One recurrent-state slot copy range.
 */
typedef struct PieStateCopyRange {
  uint32_t src_slot_id;
  uint32_t dst_slot_id;
  uint32_t src_token_offset;
  uint32_t dst_token_offset;
  uint32_t token_count;
} PieStateCopyRange;

/**
 * Borrowed immutable slice of [`PieStateCopyRange`].
 *
 * `ptr` may be null only when `len == 0`.
 */
typedef struct PieStateCopyRangeSlice {
  const struct PieStateCopyRange *ptr;
  size_t len;
} PieStateCopyRangeSlice;

/**
 * Direct recurrent-state copy descriptor.
 */
typedef struct PieStateCopyDesc {
  uint32_t abi_version;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  struct PieStateCopyRangeSlice slot_ranges;
} PieStateCopyDesc;

/**
 * One sparse pool page range to map or unmap.
 */
typedef struct PiePoolRange {
  uint64_t page_index;
  uint64_t page_count;
} PiePoolRange;

/**
 * Borrowed immutable slice of [`PiePoolRange`].
 *
 * `ptr` may be null only when `len == 0`.
 */
typedef struct PiePoolRangeSlice {
  const struct PiePoolRange *ptr;
  size_t len;
} PiePoolRangeSlice;

/**
 * Direct pool-resize descriptor.
 */
typedef struct PiePoolResizeDesc {
  uint32_t abi_version;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  uint64_t pool_id;
  uint64_t target_pages;
  struct PiePoolRangeSlice map_ranges;
  struct PiePoolRangeSlice unmap_ranges;
} PiePoolResizeDesc;

/**
 * Page-locked host memory.
 */
#define PIE_MEMORY_DOMAIN_HOST_PINNED 0

/**
 * CUDA device memory on `*_device_ordinal`.
 */
#define PIE_MEMORY_DOMAIN_CUDA_DEVICE 1

/**
 * ROCm device memory on `*_device_ordinal`.
 */
#define PIE_MEMORY_DOMAIN_ROCM_DEVICE 2

/**
 * Metal shared CPU/GPU memory.
 */
#define PIE_MEMORY_DOMAIN_METAL_SHARED 3

/**
 * Metal private device memory.
 */
#define PIE_MEMORY_DOMAIN_METAL_PRIVATE 4

/**
 * The operation has not reached a terminal state yet.
 */
#define PIE_TERMINAL_OUTCOME_PENDING 0

/**
 * The operation completed successfully.
 */
#define PIE_TERMINAL_OUTCOME_SUCCESS 1

/**
 * The operation completed unsuccessfully.
 */
#define PIE_TERMINAL_OUTCOME_FAILED 2

/**
 * The accepted work item committed no effects and must be attempted again.
 */
#define PIE_TERMINAL_OUTCOME_RETRY 3

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

extern PieDriver *pie_cuda_create(const struct PieDriverCreateDesc *desc,
                                  struct PieDriverCaps *caps);

extern int32_t pie_cuda_load_model(PieDriver *driver,
                                   const struct PieModelLoadDesc *load,
                                   struct PieDriverCaps *caps);

extern int32_t pie_cuda_register_program(PieDriver *driver,
                                         const struct PieProgramDesc *program,
                                         uint64_t *program_id);

extern int32_t pie_cuda_register_channel(PieDriver *driver,
                                         const struct PieChannelDesc *channel,
                                         struct PieChannelEndpointBinding *binding);

extern int32_t pie_cuda_bind_instance(PieDriver *driver,
                                      const struct PieInstanceDesc *instance,
                                      struct PieInstanceBinding *binding);

extern int32_t pie_cuda_launch(PieDriver *driver,
                               const struct PieFrameDesc *frame,
                               struct PieCompletion completion);

extern int32_t pie_cuda_encode(PieDriver *driver,
                               const struct PieEncodeDesc *encode,
                               struct PieCompletion completion);

extern int32_t pie_cuda_copy_kv(PieDriver *driver,
                                const struct PieKvCopyDesc *copy,
                                struct PieCompletion completion);

extern int32_t pie_cuda_copy_state(PieDriver *driver,
                                   const struct PieStateCopyDesc *copy,
                                   struct PieCompletion completion);

extern int32_t pie_cuda_resize_pool(PieDriver *driver,
                                    const struct PiePoolResizeDesc *resize,
                                    struct PieCompletion completion);

extern int32_t pie_cuda_close_instance(PieDriver *driver, uint64_t instance_id);

extern int32_t pie_cuda_close_channel(PieDriver *driver, uint64_t channel_id);

extern void pie_cuda_destroy(PieDriver *driver);

extern PieDriver *pie_metal_create(const struct PieDriverCreateDesc *desc,
                                   struct PieDriverCaps *caps);

extern int32_t pie_metal_load_model(PieDriver *driver,
                                    const struct PieModelLoadDesc *load,
                                    struct PieDriverCaps *caps);

extern int32_t pie_metal_register_program(PieDriver *driver,
                                          const struct PieProgramDesc *program,
                                          uint64_t *program_id);

extern int32_t pie_metal_register_channel(PieDriver *driver,
                                          const struct PieChannelDesc *channel,
                                          struct PieChannelEndpointBinding *binding);

extern int32_t pie_metal_bind_instance(PieDriver *driver,
                                       const struct PieInstanceDesc *instance,
                                       struct PieInstanceBinding *binding);

extern int32_t pie_metal_launch(PieDriver *driver,
                                const struct PieFrameDesc *frame,
                                struct PieCompletion completion);

extern int32_t pie_metal_encode(PieDriver *driver,
                                const struct PieEncodeDesc *encode,
                                struct PieCompletion completion);

extern int32_t pie_metal_copy_kv(PieDriver *driver,
                                 const struct PieKvCopyDesc *copy,
                                 struct PieCompletion completion);

extern int32_t pie_metal_copy_state(PieDriver *driver,
                                    const struct PieStateCopyDesc *copy,
                                    struct PieCompletion completion);

extern int32_t pie_metal_resize_pool(PieDriver *driver,
                                     const struct PiePoolResizeDesc *resize,
                                     struct PieCompletion completion);

extern int32_t pie_metal_close_instance(PieDriver *driver, uint64_t instance_id);

extern int32_t pie_metal_close_channel(PieDriver *driver, uint64_t channel_id);

extern void pie_metal_destroy(PieDriver *driver);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
