#pragma once

/* Generated by pie-driver-abi-cbindgen (cbindgen). Do not edit by hand. Regenerate: cargo run -p pie-driver-abi-cbindgen */

#include <cstddef>
#include <cstdint>

constexpr static const uint8_t PIE_REQUEST_PAYLOAD_FORWARD = 0;

constexpr static const uint8_t PIE_REQUEST_PAYLOAD_COPY = 1;

constexpr static const uint8_t PIE_REQUEST_PAYLOAD_ADAPTER = 2;

constexpr static const uint8_t PIE_REQUEST_PAYLOAD_HEALTH = 3;

constexpr static const uint8_t PIE_RESPONSE_PAYLOAD_FORWARD = 0;

constexpr static const uint8_t PIE_RESPONSE_PAYLOAD_STATUS = 1;

/// Per-slot sampler kind discriminants. Carried on the wire as the `u8`
/// elements of [`ForwardRequest::sampler_kinds`]; the value equals the
/// declaration index of the matching [`Sampler`] variant. Kept as explicit
/// `pub const`s (not a `#[repr(u8)]` enum) so cbindgen emits them verbatim as
/// the `PIE_SAMPLER_*` C consts that the driver's wire→driver kind remap
/// (`kNewToOldSamplerKind`) sources. Single source of truth for the producer
/// (`ForwardRequest::set_samplers`) and the C++ consumer.
constexpr static const uint8_t PIE_SAMPLER_MULTINOMIAL = 0;

constexpr static const uint8_t PIE_SAMPLER_TOP_K = 1;

constexpr static const uint8_t PIE_SAMPLER_TOP_P = 2;

constexpr static const uint8_t PIE_SAMPLER_MIN_P = 3;

constexpr static const uint8_t PIE_SAMPLER_TOP_K_TOP_P = 4;

constexpr static const uint8_t PIE_SAMPLER_EMBEDDING = 5;

constexpr static const uint8_t PIE_SAMPLER_DIST = 6;

constexpr static const uint8_t PIE_SAMPLER_RAW_LOGITS = 7;

constexpr static const uint8_t PIE_SAMPLER_LOGPROB = 8;

constexpr static const uint8_t PIE_SAMPLER_LOGPROBS = 9;

constexpr static const uint8_t PIE_SAMPLER_ENTROPY = 10;

/// Per-slot recurrent-state flags packed into [`ForwardRequest::rs_slot_flags`]
/// (one `u8` per request). Bit flags — combine with bitwise OR. Kept as
/// explicit `pub const`s (like the `PIE_SAMPLER_*` set) so cbindgen emits them
/// verbatim as C consts for the driver's rs_cache kernels — single source of
/// truth for the runtime producer and the driver consumer.
///
/// `RS_FLAG_RESET` (bit 0): reset the slot's recurrent state before executing
/// the request (fresh context / replay-from-zero).
constexpr static const uint8_t RS_FLAG_RESET = 1;

/// `RS_FLAG_FOLD` (bit 1): after the pass, fold buffered recurrent state into
/// the slot's folded state. The number of buffered tokens to fold is carried
/// per request in [`ForwardRequest::rs_fold_lens`]. Set by the runtime in
/// response to an explicit `inference.fold(set, n)` call.
constexpr static const uint8_t RS_FLAG_FOLD = 2;

/// Wire discriminant for a `Logits` slot.
constexpr static const uint8_t SamplingBinding_KIND_LOGITS = 0;

/// Wire discriminant for a `Tensor` slot.
constexpr static const uint8_t SamplingBinding_KIND_TENSOR = 1;

/// Wire discriminant for a `MtpLogits` (draft-logits intrinsic) slot.
constexpr static const uint8_t SamplingBinding_KIND_MTP_LOGITS = 2;

/// Wire discriminant for a `MtpDrafts` (draft-token-ids intrinsic) slot.
constexpr static const uint8_t SamplingBinding_KIND_MTP_DRAFTS = 3;

/// Copy direction for [`crate::CopyRequest`].
enum PieCopyDir : uint8_t {
  PieCopyDir_D2H,
  PieCopyDir_H2D,
  PieCopyDir_D2D,
  PieCopyDir_H2H,
};

/// Which cache a [`crate::CopyRequest`] moves.
enum PieCopyResource : uint8_t {
  PieCopyResource_Kv,
  PieCopyResource_Rs,
};

/// Adapter management op for [`crate::AdapterRequest`].
enum PieAdapterOp : uint8_t {
  PieAdapterOp_Load,
  PieAdapterOp_Save,
  PieAdapterOp_ZoInit,
  PieAdapterOp_ZoUpdate,
  PieAdapterOp_GenerateAudio,
};

struct PieBrleDesc {
  const uint32_t *buffer_ptr;
  size_t buffer_len;
  uint64_t total_size;
};

/// Per-slot adapter binding. `-1` sentinels mean "unbound" — both fields
/// are signed so the wire form matches what cuda's legacy SoA path
/// already consumes (`.as<int64_t>()`), no shim conversion needed.
struct PieAdapterBinding {
  /// `-1` means no adapter bound for this slot.
  int64_t adapter_id;
  /// `-1` means no caller-provided adapter seed.
  int64_t seed;
};

struct PieForwardRequestDesc {
  const uint32_t *token_ids_ptr;
  size_t token_ids_len;
  const uint32_t *position_ids_ptr;
  size_t position_ids_len;
  const uint32_t *kv_page_indices_ptr;
  size_t kv_page_indices_len;
  const uint32_t *kv_page_indptr_ptr;
  size_t kv_page_indptr_len;
  const uint32_t *kv_last_page_lens_ptr;
  size_t kv_last_page_lens_len;
  const uint32_t *qo_indptr_ptr;
  size_t qo_indptr_len;
  const uint32_t *rs_slot_ids_ptr;
  size_t rs_slot_ids_len;
  const uint8_t *rs_slot_flags_ptr;
  size_t rs_slot_flags_len;
  const PieBrleDesc *masks_ptr;
  size_t masks_len;
  const uint32_t *mask_indptr_ptr;
  size_t mask_indptr_len;
  const PieBrleDesc *logit_masks_ptr;
  size_t logit_masks_len;
  const uint32_t *logit_mask_indptr_ptr;
  size_t logit_mask_indptr_len;
  const uint32_t *sampling_indices_ptr;
  size_t sampling_indices_len;
  const uint32_t *sampling_indptr_ptr;
  size_t sampling_indptr_len;
  const uint8_t *sampler_kinds_ptr;
  size_t sampler_kinds_len;
  const float *sampler_temperatures_ptr;
  size_t sampler_temperatures_len;
  const uint32_t *sampler_top_k_ptr;
  size_t sampler_top_k_len;
  const float *sampler_p_ptr;
  size_t sampler_p_len;
  const uint32_t *sampler_seeds_ptr;
  size_t sampler_seeds_len;
  const uint32_t *sampler_num_tokens_ptr;
  size_t sampler_num_tokens_len;
  const uint32_t *sampler_token_ids_ptr;
  size_t sampler_token_ids_len;
  const uint32_t *sampler_token_ids_indptr_ptr;
  size_t sampler_token_ids_indptr_len;
  const uint32_t *sampler_indptr_ptr;
  size_t sampler_indptr_len;
  const PieAdapterBinding *adapter_bindings_ptr;
  size_t adapter_bindings_len;
  const uint32_t *spec_token_ids_ptr;
  size_t spec_token_ids_len;
  const uint32_t *spec_position_ids_ptr;
  size_t spec_position_ids_len;
  const uint32_t *spec_indptr_ptr;
  size_t spec_indptr_len;
  const uint8_t *output_spec_flags_ptr;
  size_t output_spec_flags_len;
  const uint64_t *context_ids_ptr;
  size_t context_ids_len;
  uint8_t single_token_mode;
  uint8_t has_user_mask;
  const uint32_t *image_indptr_ptr;
  size_t image_indptr_len;
  const uint32_t *image_grids_ptr;
  size_t image_grids_len;
  const uint32_t *image_anchor_positions_ptr;
  size_t image_anchor_positions_len;
  const uint8_t *image_pixels_ptr;
  size_t image_pixels_len;
  const uint32_t *image_pixel_indptr_ptr;
  size_t image_pixel_indptr_len;
  const uint32_t *image_mrope_positions_ptr;
  size_t image_mrope_positions_len;
  const uint32_t *image_mrope_indptr_ptr;
  size_t image_mrope_indptr_len;
  const uint32_t *image_patch_positions_ptr;
  size_t image_patch_positions_len;
  const uint32_t *image_anchor_rows_ptr;
  size_t image_anchor_rows_len;
  const uint8_t *audio_features_ptr;
  size_t audio_features_len;
  const uint32_t *audio_feature_indptr_ptr;
  size_t audio_feature_indptr_len;
  const uint32_t *audio_anchor_rows_ptr;
  size_t audio_anchor_rows_len;
  const uint32_t *audio_indptr_ptr;
  size_t audio_indptr_len;
  const uint32_t *sampling_program_indptr_ptr;
  size_t sampling_program_indptr_len;
  const uint8_t *sampling_program_bytes_ptr;
  size_t sampling_program_bytes_len;
  const uint32_t *sampling_program_bytes_indptr_ptr;
  size_t sampling_program_bytes_indptr_len;
  const uint8_t *sampling_input_blob_ptr;
  size_t sampling_input_blob_len;
  const uint32_t *sampling_input_keys_ptr;
  size_t sampling_input_keys_len;
  const uint32_t *sampling_input_offsets_ptr;
  size_t sampling_input_offsets_len;
  const uint32_t *sampling_input_lens_ptr;
  size_t sampling_input_lens_len;
  const uint32_t *sampling_input_indptr_ptr;
  size_t sampling_input_indptr_len;
  const uint32_t *sampling_late_keys_ptr;
  size_t sampling_late_keys_len;
  const uint32_t *sampling_late_indptr_ptr;
  size_t sampling_late_indptr_len;
  const uint8_t *sampling_late_blob_ptr;
  size_t sampling_late_blob_len;
  const uint32_t *sampling_late_offsets_ptr;
  size_t sampling_late_offsets_len;
  const uint32_t *sampling_late_lens_ptr;
  size_t sampling_late_lens_len;
  const uint8_t *sampling_binding_kind_ptr;
  size_t sampling_binding_kind_len;
  const uint32_t *sampling_binding_key_ptr;
  size_t sampling_binding_key_len;
  const uint32_t *sampling_binding_indptr_ptr;
  size_t sampling_binding_indptr_len;
  const uint64_t *ptir_program_hashes_ptr;
  size_t ptir_program_hashes_len;
  const uint64_t *ptir_program_instances_ptr;
  size_t ptir_program_instances_len;
  const uint8_t *ptir_program_bytes_ptr;
  size_t ptir_program_bytes_len;
  const uint32_t *ptir_program_bytes_indptr_ptr;
  size_t ptir_program_bytes_indptr_len;
  const uint8_t *ptir_program_sidecar_bytes_ptr;
  size_t ptir_program_sidecar_bytes_len;
  const uint32_t *ptir_program_sidecar_indptr_ptr;
  size_t ptir_program_sidecar_indptr_len;
  const uint64_t *ptir_program_channel_ids_ptr;
  size_t ptir_program_channel_ids_len;
  const uint32_t *ptir_program_channel_ids_indptr_ptr;
  size_t ptir_program_channel_ids_indptr_len;
  const uint64_t *ptir_program_seed_channels_ptr;
  size_t ptir_program_seed_channels_len;
  const uint8_t *ptir_program_seed_blob_ptr;
  size_t ptir_program_seed_blob_len;
  const uint32_t *ptir_program_seed_lens_ptr;
  size_t ptir_program_seed_lens_len;
  const uint32_t *ptir_program_seed_indptr_ptr;
  size_t ptir_program_seed_indptr_len;
  const uint64_t *ptir_program_host_put_channels_ptr;
  size_t ptir_program_host_put_channels_len;
  const uint8_t *ptir_program_host_put_blob_ptr;
  size_t ptir_program_host_put_blob_len;
  const uint32_t *ptir_program_host_put_lens_ptr;
  size_t ptir_program_host_put_lens_len;
  const uint32_t *ptir_program_host_put_indptr_ptr;
  size_t ptir_program_host_put_indptr_len;
  const uint64_t *ptir_release_channel_ids_ptr;
  size_t ptir_release_channel_ids_len;
  const uint64_t *ptir_release_instance_ids_ptr;
  size_t ptir_release_instance_ids_len;
  const uint32_t *rs_fold_lens_ptr;
  size_t rs_fold_lens_len;
  const uint32_t *rs_buffer_slot_ids_ptr;
  size_t rs_buffer_slot_ids_len;
  const uint32_t *rs_buffer_slot_indptr_ptr;
  size_t rs_buffer_slot_indptr_len;
  const uint64_t *sampling_output_dst_ptrs_ptr;
  size_t sampling_output_dst_ptrs_len;
  const uint32_t *sampling_output_dst_lens_ptr;
  size_t sampling_output_dst_lens_len;
  const uint32_t *sampling_output_indptr_ptr;
  size_t sampling_output_indptr_len;
  const uint64_t *sampling_late_device_ptrs_ptr;
  size_t sampling_late_device_ptrs_len;
  const uint64_t *sampling_late_device_flags_ptr;
  size_t sampling_late_device_flags_len;
  const uint32_t *sampling_late_device_lens_ptr;
  size_t sampling_late_device_lens_len;
  const uint32_t *kv_len_ptr;
  size_t kv_len_len;
  const uint64_t *kv_len_device_ptr;
  size_t kv_len_device_len;
  const uint32_t *kv_move_dst_pages_ptr;
  size_t kv_move_dst_pages_len;
  const uint32_t *kv_move_dst_offs_ptr;
  size_t kv_move_dst_offs_len;
  const uint32_t *kv_move_src_pages_ptr;
  size_t kv_move_src_pages_len;
  const uint32_t *kv_move_src_offs_ptr;
  size_t kv_move_src_offs_len;
};

struct PieCopyRequestDesc {
  PieCopyDir dir;
  const uint32_t *srcs_ptr;
  size_t srcs_len;
  const uint32_t *dsts_ptr;
  size_t dsts_len;
  PieCopyResource resource;
};

struct PieAdapterRequestDesc {
  PieAdapterOp op;
  uint64_t adapter_id;
  const uint8_t *path_ptr;
  size_t path_len;
};

struct PieRequestPayloadDesc {
  uint8_t kind;
  PieForwardRequestDesc forward;
  PieCopyRequestDesc copy;
  PieAdapterRequestDesc adapter;
};

struct PieFrameDesc {
  uint32_t driver_id;
  PieRequestPayloadDesc payload;
};

struct PieForwardResponseDesc {
  uint32_t num_requests;
  const uint32_t *tokens_indptr_ptr;
  size_t tokens_indptr_len;
  const uint32_t *tokens_ptr;
  size_t tokens_len;
  const uint32_t *dists_req_indptr_ptr;
  size_t dists_req_indptr_len;
  const uint32_t *dists_kv_indptr_ptr;
  size_t dists_kv_indptr_len;
  const uint32_t *dists_ids_ptr;
  size_t dists_ids_len;
  const float *dists_probs_ptr;
  size_t dists_probs_len;
  const uint32_t *logits_req_indptr_ptr;
  size_t logits_req_indptr_len;
  const uint32_t *logits_byte_indptr_ptr;
  size_t logits_byte_indptr_len;
  const uint8_t *logits_bytes_ptr;
  size_t logits_bytes_len;
  const uint32_t *logprobs_req_indptr_ptr;
  size_t logprobs_req_indptr_len;
  const uint32_t *logprobs_val_indptr_ptr;
  size_t logprobs_val_indptr_len;
  const float *logprobs_values_ptr;
  size_t logprobs_values_len;
  const uint32_t *entropies_indptr_ptr;
  size_t entropies_indptr_len;
  const float *entropies_ptr;
  size_t entropies_len;
  const uint32_t *spec_indptr_ptr;
  size_t spec_indptr_len;
  const uint32_t *spec_tokens_ptr;
  size_t spec_tokens_len;
  const uint32_t *spec_positions_ptr;
  size_t spec_positions_len;
  uint32_t probe_wire_parse_us;
  uint32_t probe_plan_us;
  uint32_t probe_h2d_us;
  uint32_t probe_kernel_launch_us;
  uint32_t probe_sync_us;
  uint32_t probe_response_build_us;
  uint32_t probe_device_idle_us;
  const uint32_t *program_tokens_req_indptr_ptr;
  size_t program_tokens_req_indptr_len;
  const uint32_t *program_tokens_indptr_ptr;
  size_t program_tokens_indptr_len;
  const uint32_t *program_tokens_ptr;
  size_t program_tokens_len;
};

/// Generic status response. Convention:
///   * 0 = success
///   * negative = error
///   * -1 reserved for abort sentinel (the server writes one of these
///     when a lease drops without commit; see [`crate::ResponseFrame::aborted`]).
///   * positive = method-specific
struct PieStatusResponse {
  int32_t status;
};

struct PieResponsePayloadDesc {
  uint8_t kind;
  PieForwardResponseDesc forward;
  PieStatusResponse status;
};

struct PieResponseFrameDesc {
  uint32_t driver_id;
  uint8_t aborted;
  PieResponsePayloadDesc payload;
};
