#pragma once

/* Generated by pie-driver-abi-cbindgen (cbindgen). Do not edit by hand. Regenerate: cargo run -p pie-driver-abi-cbindgen */

#include <stddef.h>
#include <stdint.h>

#define KV_COPY_DEVICE_TO_DEVICE (1 << 0)

#define KV_COPY_DEVICE_TO_HOST (1 << 1)

#define KV_COPY_HOST_TO_DEVICE (1 << 2)

#define KV_COPY_HOST_TO_HOST (1 << 3)

#define PIE_DEVICE_PORT_EMBED_TOKENS (1 << 0)

#define PIE_DEVICE_PORT_PAGES (1 << 1)

#define PIE_DEVICE_PORT_POSITIONS (1 << 2)

#define PIE_DEVICE_PORT_PAGE_INDPTR (1 << 3)

#define PIE_DEVICE_PORT_W_SLOT (1 << 4)

#define PIE_DEVICE_PORT_KV_LEN (1 << 5)

#define PIE_DEVICE_PORT_W_OFF (1 << 6)

/**
 * The driver resolves a dense `AttnMask` descriptor channel (device-carried
 * bool mask cells) pre-forward. Orthogonal to the geometry-class port sets:
 * a masked device-resolved pass additionally requires this bit.
 */
#define PIE_DEVICE_PORT_ATTN_MASK (1 << 7)

/**
 * Recurrent-state buffered-slot family. The driver resolves the buffered
 * slab CSR (`rs_buffer_pages` / `rs_buffer_indptr`), the per-row live
 * buffered length, and the buffered write descriptor from device channel
 * cells pre-forward — the RS mirror of the KV `pages` / `page-indptr` /
 * `kv-len` / `w-slot` / `w-off` set.
 *
 * Orthogonal to the geometry-class port sets below: those describe how a
 * pass resolves its ATTENTION geometry, and a recurrent-only pass has none.
 * A backend advertises these bits independently.
 */
#define PIE_DEVICE_PORT_RS_BUFFER_PAGES (1 << 8)

#define PIE_DEVICE_PORT_RS_BUFFER_INDPTR (1 << 9)

#define PIE_DEVICE_PORT_RS_BUFFER_LEN (1 << 10)

#define PIE_DEVICE_PORT_RS_W_SLOT (1 << 11)

#define PIE_DEVICE_PORT_RS_W_OFF (1 << 12)

/**
 * Full device-resolved port mask of the recurrent-state buffered-slot
 * family. A guest may bind `rs-geometry`'s channel fields only on a backend
 * advertising every one of these bits; otherwise the host rejects the
 * binding rather than silently ignoring it.
 */
#define PIE_DEVICE_RS_BUFFER_PORTS ((((PIE_DEVICE_PORT_RS_BUFFER_PAGES | PIE_DEVICE_PORT_RS_BUFFER_INDPTR) | PIE_DEVICE_PORT_RS_BUFFER_LEN) | PIE_DEVICE_PORT_RS_W_SLOT) | PIE_DEVICE_PORT_RS_W_OFF)

/**
 * Full device-resolved port mask of the `DecodeEnvelope` geometry class.
 * Driver-neutral: any backend that executes the class resolves exactly these
 * ports on device.
 */
#define PIE_DECODE_ENVELOPE_PORTS ((PIE_DEVICE_PORT_EMBED_TOKENS | PIE_DEVICE_PORT_POSITIONS) | PIE_DEVICE_PORT_KV_LEN)

/**
 * Full device-resolved port mask of the `DeviceGeometry` geometry class:
 * the program traces its complete explicit geometry in-graph and the driver
 * resolves every descriptor port from device channel cells pre-forward.
 */
#define PIE_DEVICE_GEOMETRY_PORTS ((((((PIE_DEVICE_PORT_EMBED_TOKENS | PIE_DEVICE_PORT_PAGES) | PIE_DEVICE_PORT_POSITIONS) | PIE_DEVICE_PORT_PAGE_INDPTR) | PIE_DEVICE_PORT_W_SLOT) | PIE_DEVICE_PORT_KV_LEN) | PIE_DEVICE_PORT_W_OFF)

/**
 * `"PIELPKG\0"`, little-endian.
 */
#define IMAGE_MAGIC 20067531595532624

/**
 * Current direct local ABI version.
 *
 * v14 (Project Venus): the launch unit is the sealed **frame** — one
 * [`PieFrameDesc`] carries k forward steps that the driver executes as one
 * closed system with a single completion. Frame-invariant tables (lane
 * roster, WorkingSet page translation, frame-union KV admission demand) are
 * hoisted out of the per-step sections. Admission is folded into the launch
 * call itself ([`PIE_STATUS_EXHAUSTED`] / [`PIE_STATUS_IMPOSSIBLE`]); the
 * v12 prepare/lease surface and the v13 `settle_defer` lever are deleted.
 *
 * v17 (phase 3′): `PieProgramDesc::region_analysis` — the per-region bind
 * verdicts and intrinsic side-table analysis the CUDA driver derives for
 * itself in `region_support.hpp`. Additive, and empty means "not supplied",
 * but the struct grew, so drivers and workers ship together.
 * v21: `PieLaunchDesc::rs_buffer_read_*` — the buffered prefix a fire must
 * REPLAY before its own tokens, so a recurrence can start from
 * `folded ⊕ replay(buffer)` instead of only from the folded boundary.
 * Separate from the write CSR because a write may allocate a slab and a read
 * must not. Additive, and an empty read side means "nothing to replay", but
 * the struct grew, so drivers and workers ship together.
 * v22: `PieLaunchDesc::rs_buffer_heads` — where each row's logical buffer
 * token 0 physically sits. A fold absorbs tokens off the front of the buffer
 * but can only release WHOLE covered pages, and `fold_granularity` is 1 while
 * a buffer page is the KV page size, so a fold routinely lands mid-page and
 * the survivors keep their offsets. Every buffer span the driver walks is
 * therefore `head + logical`. Zero for a buffer that was never partially
 * folded, which is why this was invisible until the replay path landed.
 * v23: `PIE_RS_FLAG_BUFFER_WRITE` — a new bit in `rs_slot_flags` marking a
 * row whose buffer span is a WRITE. Orthogonal to `PIE_RS_FLAG_FOLD`: a pass
 * may scatter its own tokens into the buffer AND fold a prefix of the result
 * in one go, and the two flags together are what tell a write-and-fold (run
 * the extended `[buffered | new]` layout, snapshot the state at
 * `rs_fold_lens[r]`) apart from a pure commit (whose rows ARE the replay).
 * No struct grew, but an older driver rejects the unknown bit, so drivers and
 * workers ship together.
 * v24: `PIE_RS_FLAG_FOLD_LEN_DEVICE` — a new bit in `rs_slot_flags` marking a
 * row whose fold length the WORKER DOES NOT KNOW. The value lives in the
 * `rs_fold_len` descriptor port, which the driver resolves at compose time,
 * so a speculative decode's accepted count never has to round-trip through
 * the host between the fire that computes it and the fire that folds it.
 * `rs_fold_lens[r]` is a placeholder for such a row and MUST be ignored; the
 * driver clamps the resolved value to the row's replay length. No struct
 * grew, but an older driver rejects the unknown bit, so drivers and workers
 * ship together.
 */
#define PIE_DRIVER_ABI_VERSION 24

#define PIE_MODEL_COMPONENT_FULL 0

#define PIE_MODEL_COMPONENT_TEXT 1

#define PIE_MODEL_COMPONENT_ENCODE 2

/**
 * MXFP4 MoE lowering request. Discriminants match `PieLoaderMxfp4MoeRequest`;
 * the driver forwards the value to the loader unchanged.
 */
#define PIE_MXFP4_MOE_AUTO 0

#define PIE_MXFP4_MOE_ROUTED_DECODE 1

#define PIE_MXFP4_MOE_NATIVE_GEMM 2

#define PIE_MXFP4_MOE_EAGER_BF16 3

/**
 * Success.
 */
#define PIE_STATUS_OK 0

/**
 * Descriptor validation failed synchronously.
 */
#define PIE_STATUS_INVALID_ARGUMENT -1

/**
 * ABI version or layout mismatch.
 */
#define PIE_STATUS_BAD_ABI_VERSION -2

/**
 * The requested operation is not implemented by the driver.
 */
#define PIE_STATUS_UNSUPPORTED -3

/**
 * The target object is closed or otherwise unavailable.
 */
#define PIE_STATUS_CLOSED -4

/**
 * The driver encountered an internal failure after accepting the call.
 */
#define PIE_STATUS_DRIVER_ERROR -5

/**
 * Frame admission is full right now; the frame may fit after physical
 * budget is released. The engine re-posts later.
 */
#define PIE_STATUS_EXHAUSTED -6

/**
 * The frame can never fit within the driver's physical budget ceiling.
 */
#define PIE_STATUS_IMPOSSIBLE -7

/**
 * Sentinel for [`PieLaunchOp::channel`] on ops that touch no channel.
 */
#define PIE_NO_CHANNEL UINT32_MAX

#define PIE_GEOMETRY_CLASS_HOST 0

#define PIE_GEOMETRY_CLASS_DECODE_ENVELOPE 1

#define PIE_GEOMETRY_CLASS_DEVICE_GEOMETRY 2

/**
 * Reset the recurrent-state slot before executing the request.
 */
#define PIE_RS_FLAG_RESET 1

/**
 * Fold buffered recurrent-state data into the slot after the pass.
 */
#define PIE_RS_FLAG_FOLD 2

/**
 * The pass SCATTERS its own tokens into the buffer. Orthogonal to `FOLD`: a
 * pass may write the buffer and fold a prefix of the result in one go, and
 * the two together are what distinguishes a write-and-fold (which runs the
 * extended `[buffered | new]` layout and snapshots the state at
 * `rs_fold_lens[r]`) from a pure commit (whose rows ARE the replay, gathered
 * straight from the slabs).
 */
#define PIE_RS_FLAG_BUFFER_WRITE 4

/**
 * This row's fold length is NOT host-known. `rs_fold_lens[r]` is a
 * placeholder and must be ignored; the real value comes from the
 * `rs_fold_len` descriptor port, which the driver resolves once the fire that
 * computes it has completed, and clamps to the row's replay length.
 */
#define PIE_RS_FLAG_FOLD_LEN_DEVICE 8

/**
 * Concrete F32 channel element type.
 */
#define PIE_CHANNEL_DTYPE_F32 0

/**
 * Concrete I32 channel element type.
 */
#define PIE_CHANNEL_DTYPE_I32 1

/**
 * Concrete U32 channel element type.
 */
#define PIE_CHANNEL_DTYPE_U32 2

/**
 * Concrete boolean channel element type.
 */
#define PIE_CHANNEL_DTYPE_BOOL 3

/**
 * Driver-resolved activation channel element type.
 */
#define PIE_CHANNEL_DTYPE_ACT 4

/**
 * Channel has no host endpoint.
 */
#define PIE_CHANNEL_HOST_ROLE_NONE 0

/**
 * Host produces values consumed by the device program.
 */
#define PIE_CHANNEL_HOST_ROLE_WRITER 1

/**
 * Device program produces values consumed by the host.
 */
#define PIE_CHANNEL_HOST_ROLE_READER 2

/**
 * Channel is private to one bound instance.
 */
#define PIE_CHANNEL_EXTERN_NONE 0

/**
 * Bound program consumes an externally produced channel.
 */
#define PIE_CHANNEL_EXTERN_IMPORT 1

/**
 * Bound program produces an externally consumed channel.
 */
#define PIE_CHANNEL_EXTERN_EXPORT 2

#define PIE_ELASTIC_POOL_KV 0

#define PIE_ELASTIC_POOL_STATE 1

#define PIE_ELASTIC_POOL_WORKSPACE 2

/**
 * What an emitted kernel is for. The driver switches on this to decide which
 * launch path a compiled entry belongs to, so it never has to re-derive from
 * the plan what the host already decided.
 */
#define PIE_KERNEL_SINGLETON 0

#define PIE_KERNEL_FUSED 1

#define PIE_KERNEL_GROUPED 2

#define PIE_KERNEL_READINESS 3

#define PIE_KERNEL_COMMIT 4

/**
 * The region can be bound as a second-party region.
 */
#define PIE_REGION_SECOND_PARTY_SUPPORTED (1 << 0)

/**
 * The region is a well-formed generated region.
 */
#define PIE_REGION_GENERATED_VALID (1 << 1)

/**
 * Where a value comes from. Mirrors `pie_ir` value sources.
 */
#define PIE_VALUE_CONST 0

#define PIE_VALUE_INTRINSIC 1

#define PIE_VALUE_CHANNEL_TAKE 2

#define PIE_VALUE_CHANNEL_READ 3

#define PIE_VALUE_OP_RESULT 4

/**
 * The channel is pre-filled with a seed cell at instantiation.
 */
#define PIE_CHANNEL_SEEDED (1 << 0)

/**
 * The host reads or writes this channel.
 */
#define PIE_CHANNEL_HOST_VISIBLE (1 << 1)

/**
 * The host is the *reader* — the channel is a program output.
 */
#define PIE_CHANNEL_HOST_READER (1 << 2)

/**
 * No op in the pass touches this channel, so a fire has nothing to wait for.
 */
#define PIE_READINESS_UNTOUCHED 0

/**
 * The first op to touch this channel in pass order takes or reads it, so a
 * fire is ready only while the ring is non-empty.
 */
#define PIE_READINESS_NEEDS_FULL 1

/**
 * The first op to touch this channel in pass order puts to it, so a fire is
 * ready only while the ring is non-full.
 */
#define PIE_READINESS_NEEDS_EMPTY 2

/**
 * The region is served by a generated kernel.
 */
#define PIE_REGION_GENERATED 0

/**
 * The region is served by a vendor or second-party library call.
 */
#define PIE_REGION_LIBRARY 1

/**
 * A dimension is a literal extent, not a symbolic one.
 */
#define PIE_EXTENT_STATIC 255

/**
 * The stage reads the `query` intrinsic.
 */
#define PIE_STAGE_REQUIRES_QUERY (1 << 0)

/**
 * The stage reads the `layer` intrinsic.
 */
#define PIE_STAGE_REQUIRES_LAYER (1 << 1)

/**
 * The stage reads the `attn_score` intrinsic.
 */
#define PIE_STAGE_REQUIRES_ATTN_SCORE (1 << 2)

/**
 * The stage names a second-party kernel.
 */
#define PIE_STAGE_REQUIRES_KERNEL_CALL (1 << 3)

/**
 * The stage writes the `attn_page_mask` sink.
 */
#define PIE_STAGE_REQUIRES_PAGE_MASK (1 << 4)

/**
 * The stage reads multi-token-prediction draft rows.
 */
#define PIE_STAGE_REQUIRES_MTP_ROWS (1 << 5)

/**
 * Every op in the stage is coverable by the grouped launch path, and its
 * intrinsics and runtime extents are ones that path supports. When clear,
 * `error` says why and the stage must take the fused path.
 */
#define PIE_STAGE_GROUPED_VALID (1 << 6)

/**
 * The stage writes the `lora` sink.
 */
#define PIE_STAGE_REQUIRES_LORA (1 << 7)

/**
 * [`PieStepDesc::region_sig`] bit: the region's members carry
 * multi-token qo windows (the ragged window class).
 */
#define PIE_REGION_SIG_MULTI_TOKEN (1 << 0)

/**
 * [`PieStepDesc::region_sig`] bit: attention-stage hook programs.
 */
#define PIE_REGION_SIG_HOOK (1 << 1)

/**
 * [`PieStepDesc::region_sig`] bit: a user (custom) attention mask.
 */
#define PIE_REGION_SIG_MASK (1 << 2)

/**
 * [`PieStepDesc::region_sig`] bit: a depth truncation (the region's k
 * is `region_k`).
 */
#define PIE_REGION_SIG_TRUNCATED (1 << 3)

/**
 * [`PieStepDesc::region_sig`] bit: a span-grouped correction (lora)
 * program. Window-free — never a seriation term — but the depth
 * split's decline rules consult it (a lane carrying BOTH correction
 * and truncation is the PQ-tree class, refused), so the table states
 * it (③b: the words' decline rules become derivable).
 */
#define PIE_REGION_SIG_LORA (1 << 4)

/**
 * `region_sig[r]` bit: the region's hook programs write the
 * `attn_page_mask` sink (Track B page substitution). Such a hook needs
 * the full-R paged decode path, so the banded-depth derivation excludes
 * it (observation-only hooks band; Track-B hooks keep the pre-band
 * servers).
 */
#define PIE_REGION_SIG_HOOK_PAGE_MASK (1 << 5)

/**
 * [`PieStepDesc::planned_hook_free_prefix_rows`]'s "no plan sent"
 * sentinel. Not zero: zero is a legitimate planned value ("no fast
 * prefix" — an all-hooked step).
 */
#define PIE_HOOK_FREE_PREFIX_UNPLANNED UINT32_MAX

/**
 * [`PieStepDesc::planned_unmasked_prefix_rows`]'s "no plan sent"
 * sentinel (zero is a legitimate planned value: an all-masked step).
 */
#define PIE_UNMASKED_PREFIX_UNPLANNED UINT32_MAX

/**
 * [`PieStepDesc::planned_max_layers`]'s "full model" sentinel (zero is
 * never a legitimate depth).
 */
#define PIE_MAX_LAYERS_FULL UINT32_MAX

/**
 * [`PieStepDesc::planned_full_depth_rows`]'s "no depth split" sentinel
 * (zero would mean an all-truncated composed fire, a legal future
 * value).
 */
#define PIE_FULL_DEPTH_UNPLANNED UINT32_MAX

#define CHANNEL_TICKET_NONE UINT64_MAX

#define RS_FLAG_RESET 1

#define RS_FLAG_FOLD 2

#define RS_FLAG_BUFFER_WRITE 4

/**
 * This row's fold length is not host-known; it comes from the `rs_fold_len`
 * descriptor port and `rs_fold_lens[r]` is a placeholder.
 */
#define RS_FLAG_FOLD_LEN_DEVICE 8

#define REMOTE_WIRE_VERSION 8

/**
 * Opaque embedded-driver handle.
 */
typedef void PieDriver;

/**
 * Borrowed immutable byte slice.
 *
 * `ptr` may be null only when `len == 0`.
 */
typedef struct PieBytes {
  const uint8_t *ptr;
  size_t len;
} PieBytes;

/**
 * Runtime completion callback, callable from any foreign thread.
 *
 * `ctx` is an opaque runtime-owned pointer, forwarded unchanged from
 * [`PieRuntimeCallbacks::ctx`]. Embedded drivers may invoke this callback from
 * any foreign thread after an operation has been accepted.
 */
typedef void (*PieRuntimeNotifyFn)(void *ctx, uint64_t wait_id, uint64_t epoch);

/**
 * Runtime-owned callbacks passed at driver creation time.
 */
typedef struct PieRuntimeCallbacks {
  uint32_t abi_version;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  /**
   * Opaque runtime-owned context pointer forwarded to [`PieRuntimeNotifyFn`].
   */
  void *ctx;
  /**
   * Mandatory for embedded native-driver creation.
   */
  PieRuntimeNotifyFn notify;
} PieRuntimeCallbacks;

/**
 * Driver creation descriptor.
 */
typedef struct PieDriverCreateDesc {
  uint32_t abi_version;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  struct PieBytes config_bytes;
  struct PieRuntimeCallbacks runtime;
} PieDriverCreateDesc;

/**
 * Driver-owned JSON payload returned from a cold boot call.
 */
typedef struct PieDriverCaps {
  const uint8_t *json_bytes;
  size_t json_len;
} PieDriverCaps;

/**
 * Blocking model-load descriptor.
 *
 * This is a *request*, not a compiled artifact: the driver compiles the load
 * plan itself from `snapshot_dir` plus the device it measured, so the runtime
 * no longer ships plan bytes across the ABI (`loader/architecture.md` §3).
 */
typedef struct PieModelLoadDesc {
  uint32_t abi_version;
  /**
   * One of `PIE_MODEL_COMPONENT_*`.
   */
  uint32_t component;
  /**
   * One of `PIE_MXFP4_MOE_*`.
   */
  uint32_t mxfp4_moe;
  /**
   * The runtime's own quantization request (e.g. `"fp8"`), not a checkpoint
   * fact. Empty means "whatever the checkpoint is".
   */
  struct PieBytes runtime_quant;
  /**
   * UTF-8 path to the driver-local checkpoint payload root.
   */
  struct PieBytes snapshot_dir;
} PieModelLoadDesc;

/**
 * One host-emitted kernel: the backend source, its entry point, and where it
 * belongs in the program.
 *
 * The host runs the code generator (`compiler/codegen`) and ships the result;
 * the driver compiles and launches it. `source.len == 0` means the host could
 * not emit this kernel, and `error` says why — that is not fatal by itself,
 * because a driver may have a slower path for the same region (a fused region
 * that exceeds a channel-binding limit falls back to one launch per op). A
 * driver MUST NOT treat a missing kernel as a reason to re-derive the source
 * itself; the whole point is that only one implementation exists.
 */
typedef struct PieEmittedKernel {
  /**
   * `PIE_KERNEL_*`.
   */
  uint32_t kind;
  /**
   * Stage index in container order.
   */
  uint32_t stage_index;
  /**
   * Region index within the stage's partition for this `kind`.
   */
  uint32_t region_index;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  /**
   * Entry-point symbol, a C identifier. Empty when `source` is empty.
   */
  struct PieBytes entry_name;
  /**
   * Backend source (CUDA C or MSL). Empty when emission failed.
   */
  struct PieBytes source;
  /**
   * Why emission failed, when `source` is empty. Empty otherwise.
   */
  struct PieBytes error;
} PieEmittedKernel;

/**
 * Borrowed view of a host-emitted kernel table.
 */
typedef struct PieEmittedKernelSlice {
  const struct PieEmittedKernel *ptr;
  size_t len;
} PieEmittedKernelSlice;

/**
 * One `argmax` in a generated region that reads a logits intrinsic's device
 * buffer directly, skipping the intrinsic materialisation and the reshapes
 * between them.
 */
typedef struct PieDirectArgmax {
  /**
   * The `argmax` node, in stage op order.
   */
  uint32_t node;
  /**
   * The value id of the intrinsic buffer it reads instead.
   */
  uint32_t source_value;
  /**
   * `PTIR_INTR_*` of that buffer.
   */
  uint16_t intrinsic;
  /**
   * Nonzero when the rewrite is only valid for a single runtime row, which
   * the driver checks per fire against the lane's descriptors.
   */
  uint8_t requires_single_row;
  /**
   * Reserved; must be zero.
   */
  uint8_t reserved0;
} PieDirectArgmax;

/**
 * Borrowed view of a direct-argmax table.
 */
typedef struct PieDirectArgmaxSlice {
  const struct PieDirectArgmax *ptr;
  size_t len;
} PieDirectArgmaxSlice;

/**
 * Borrowed immutable `u32` slice.
 *
 * `ptr` may be null only when `len == 0`.
 */
typedef struct PieU32Slice {
  const uint32_t *ptr;
  size_t len;
} PieU32Slice;

/**
 * Every per-region decision the host made about one fused region.
 *
 * Joins to `PieEmittedKernel` on `(stage_index, region_index)`. A driver that
 * reads this table does not have to look at the plan to know whether a region
 * binds, whether it can be emitted, or how its intrinsic side tables are laid
 * out (`ptir-refactor.md` §4.2).
 */
typedef struct PieRegionAnalysis {
  /**
   * Stage index in container order.
   */
  uint32_t stage_index;
  /**
   * Region index within the stage's fused partition.
   */
  uint32_t region_index;
  /**
   * `PIE_REGION_*` bits.
   */
  uint32_t flags;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  struct PieDirectArgmaxSlice direct_argmax;
  /**
   * Nodes the rewrites above make redundant, ascending.
   */
  struct PieU32Slice skipped;
} PieRegionAnalysis;

/**
 * Borrowed view of a per-region analysis table.
 */
typedef struct PieRegionAnalysisSlice {
  const struct PieRegionAnalysis *ptr;
  size_t len;
} PieRegionAnalysisSlice;

/**
 * One declared SSA value: its type and its producer.
 */
typedef struct PieLaunchValue {
  /**
   * Trace-global value id. The table is dense and ascending, so this is the
   * index, but it is carried explicitly so a driver never has to assume so.
   */
  uint32_t id;
  /**
   * `PIE_VALUE_*`.
   */
  uint8_t source;
  /**
   * Element dtype (`PTIR_DT_*`).
   */
  uint8_t dtype;
  /**
   * `PTIR_INTR_*` when `source` is `PIE_VALUE_INTRINSIC`.
   */
  uint8_t intrinsic;
  /**
   * Reserved; must be zero.
   */
  uint8_t reserved1;
  /**
   * Channel id when `source` is a channel take or read.
   */
  uint32_t channel;
  /**
   * Literal payload when `source` is `PIE_VALUE_CONST`, raw bits per dtype.
   */
  uint32_t literal_bits;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  /**
   * Row-major logical shape. Empty is scalar.
   */
  struct PieU32Slice shape;
} PieLaunchValue;

/**
 * Borrowed view of a value table.
 */
typedef struct PieLaunchValueSlice {
  const struct PieLaunchValue *ptr;
  size_t len;
} PieLaunchValueSlice;

/**
 * One channel declaration: a bounded ring of `capacity + 1` typed cells.
 */
typedef struct PieLaunchChannel {
  uint32_t id;
  /**
   * Logical capacity; the ring holds `capacity + 1` cells.
   */
  uint32_t capacity;
  /**
   * Cell element dtype (`PTIR_DT_*`).
   */
  uint8_t dtype;
  /**
   * `PIE_CHANNEL_*` bits.
   */
  uint8_t flags;
  /**
   * -1 private, 0 import, 1 export.
   */
  int8_t extern_dir;
  /**
   * `PIE_READINESS_*` — the direction the *first* op to touch this channel
   * in pass order requires.
   *
   * Not derivable from the per-stage `takes`/`reads`/`puts` sets: a channel
   * that is both taken and put (the `InPlace` shape — a counter, a beam
   * state, a DFA cursor) appears in both, and only the order says which
   * gate a fire must clear. Deriving it from the sets yields
   * `full && empty`, which a `capacity == 1` ring can never satisfy.
   */
  uint8_t readiness;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved1;
  /**
   * Cell shape.
   */
  struct PieU32Slice shape;
  /**
   * Rendezvous name when `extern_dir` is not -1.
   */
  struct PieBytes extern_name;
} PieLaunchChannel;

/**
 * Borrowed view of a channel table.
 */
typedef struct PieLaunchChannelSlice {
  const struct PieLaunchChannel *ptr;
  size_t len;
} PieLaunchChannelSlice;

/**
 * One descriptor-port binding: a forward-pass input port fed by a channel.
 */
typedef struct PieLaunchPort {
  /**
   * `PTIR_PORT_*`.
   */
  uint8_t port;
  /**
   * Nonzero when the port was const-folded and consumes no channel.
   */
  uint8_t is_const;
  /**
   * Const payload dtype when `is_const`.
   */
  uint8_t const_dtype;
  /**
   * Reserved; must be zero.
   */
  uint8_t reserved0;
  /**
   * Channel id when not const-folded.
   */
  uint32_t channel;
  /**
   * Const payload shape when `is_const`.
   */
  struct PieU32Slice const_shape;
  /**
   * Const payload bytes when `is_const`.
   */
  struct PieBytes const_data;
} PieLaunchPort;

/**
 * Borrowed view of a port table.
 */
typedef struct PieLaunchPortSlice {
  const struct PieLaunchPort *ptr;
  size_t len;
} PieLaunchPortSlice;

/**
 * Borrowed view of a table of byte strings.
 */
typedef struct PieBytesSlice {
  const struct PieBytes *ptr;
  size_t len;
} PieBytesSlice;

/**
 * One op in a stage DAG, in SSA order.
 */
typedef struct PieLaunchOp {
  /**
   * `PTIR_OP_*`.
   */
  uint16_t code;
  /**
   * SSA ids this op defines (`top_k`/`sort_desc` define two).
   */
  uint16_t result_count;
  /**
   * First SSA id this op defines.
   */
  uint32_t result_id;
  /**
   * `PTIR_INTR_*`, for `intrinsic_val`.
   */
  uint16_t intrinsic;
  /**
   * Literal dtype, for `const`.
   */
  uint8_t lit_dtype;
  /**
   * Element dtype (`PTIR_DT_*`) — the result's, or the target of a `cast`.
   */
  uint8_t dtype;
  /**
   * `pivot_threshold` predicate tag.
   */
  uint8_t pred_tag;
  /**
   * RNG kind (0 uniform, 1 gumbel).
   */
  uint8_t rng_kind;
  /**
   * Reserved; must be zero.
   */
  uint16_t reserved0;
  /**
   * Raw literal bits, for `const`.
   */
  uint32_t lit_bits;
  /**
   * `pivot_threshold` predicate payload — always a value id.
   */
  uint32_t pred_payload;
  /**
   * Channel slot for `chan_take`/`chan_read`/`chan_put`, else
   * [`PIE_NO_CHANNEL`].
   */
  uint32_t channel;
  /**
   * Name-table index for `kernel_call`/`sink_call`.
   */
  uint32_t name_index;
  /**
   * Op-specific immediates (`top_k` k, transpose axes, iota len, …).
   */
  uint32_t imm;
  uint32_t imm2;
  uint32_t imm3;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved1;
  /**
   * Operand value ids, in op-defined order.
   */
  struct PieU32Slice args;
  /**
   * Trace-known result shape (or the target shape of a broadcast/reshape).
   */
  struct PieU32Slice shape;
} PieLaunchOp;

/**
 * Borrowed view of an op table.
 */
typedef struct PieLaunchOpSlice {
  const struct PieLaunchOp *ptr;
  size_t len;
} PieLaunchOpSlice;

/**
 * A `(channel, value)` pair — a stage effect or a region's direct sink.
 */
typedef struct PieLaunchPut {
  uint32_t channel;
  uint32_t value;
} PieLaunchPut;

/**
 * Borrowed view of a put table.
 */
typedef struct PieLaunchPutSlice {
  const struct PieLaunchPut *ptr;
  size_t len;
} PieLaunchPutSlice;

/**
 * One stage program: the op DAG the driver launches, its channel effects, and
 * its declared outputs.
 */
typedef struct PieLaunchStage {
  /**
   * Attachment point: Prologue 0, OnAttnProj 1, OnAttn 2, Epilogue 3.
   */
  uint8_t kind;
  /**
   * Reserved; must be zero.
   */
  uint8_t reserved0;
  uint16_t reserved1;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved2;
  struct PieLaunchOpSlice ops;
  /**
   * Channel effects committed at pass end, in order.
   */
  struct PieLaunchPutSlice puts;
  /**
   * Channels this stage consumes — readiness needs them full.
   */
  struct PieU32Slice takes;
  /**
   * Channels this stage peeks — readiness needs them full.
   */
  struct PieU32Slice reads;
} PieLaunchStage;

/**
 * Borrowed view of a stage table.
 */
typedef struct PieLaunchStageSlice {
  const struct PieLaunchStage *ptr;
  size_t len;
} PieLaunchStageSlice;

/**
 * Borrowed immutable `u8` slice.
 *
 * `ptr` may be null only when `len == 0`.
 */
typedef struct PieU8Slice {
  const uint8_t *ptr;
  size_t len;
} PieU8Slice;

/**
 * One normalized value's type: a dtype plus a per-dimension extent, where each
 * extent is either a literal or one of the runtime extents the lane supplies.
 */
typedef struct PieLaunchPlanValue {
  /**
   * Element dtype (`PTIR_DT_*`).
   */
  uint8_t dtype;
  /**
   * Reserved; must be zero.
   */
  uint8_t reserved0;
  uint16_t reserved1;
  /**
   * Per-dimension extent kind: `PIE_EXTENT_STATIC`, or KvLen 0, PageCount
   * 1, RowCount 2, TokenCount 3, SampledRows 4, QueryLen 5, KeyLen 6.
   */
  struct PieU8Slice extents;
  /**
   * Per-dimension literal extent; meaningful where `extents` is static.
   */
  struct PieU32Slice dims;
} PieLaunchPlanValue;

/**
 * Borrowed view of a normalized value-type table.
 */
typedef struct PieLaunchPlanValueSlice {
  const struct PieLaunchPlanValue *ptr;
  size_t len;
} PieLaunchPlanValueSlice;

/**
 * One region: a contiguous run of normalized ops served by one launch.
 */
typedef struct PieLaunchRegion {
  /**
   * `PIE_REGION_GENERATED` or `PIE_REGION_LIBRARY`.
   */
  uint8_t kind;
  /**
   * Which library call, when `kind` is `PIE_REGION_LIBRARY`: NucleusSample
   * 0, TopK 1, Sort 2, Scan 3, MatMul 4, SecondParty 5.
   */
  uint8_t library;
  /**
   * Launch shape the host chose: Effects 0, OneCtaPerRow 1,
   * HierarchicalRow 2, Library 3.
   */
  uint8_t schedule;
  /**
   * Reserved; must be zero.
   */
  uint8_t reserved0;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved1;
  /**
   * Normalized op indices in this region, ascending.
   */
  struct PieU32Slice nodes;
  /**
   * Values the region reads from outside itself.
   */
  struct PieU32Slice inputs;
  /**
   * Values the region publishes.
   */
  struct PieU32Slice outputs;
  /**
   * Channel slots the region writes directly from the kernel.
   */
  struct PieLaunchPutSlice sinks;
} PieLaunchRegion;

/**
 * Borrowed view of a region table.
 */
typedef struct PieLaunchRegionSlice {
  const struct PieLaunchRegion *ptr;
  size_t len;
} PieLaunchRegionSlice;

/**
 * One lane-binding rule: normalized value `value` is bound through local
 * channel slot `local`.
 */
typedef struct PieLaunchChannelRule {
  uint32_t value;
  uint32_t local;
} PieLaunchChannelRule;

/**
 * Borrowed view of a channel-rule table.
 */
typedef struct PieLaunchChannelRuleSlice {
  const struct PieLaunchChannelRule *ptr;
  size_t len;
} PieLaunchChannelRuleSlice;

/**
 * The per-program launch plan for one stage: the normalized program the
 * emitted kernels were generated from, its region partitions, and the
 * lane-binding metadata the driver used to derive itself.
 */
typedef struct PieLaunchStagePlan {
  /**
   * Canonical signature of the normalized stage.
   */
  uint64_t signature_hash;
  /**
   * Graph-cache identity — what the driver keys a captured CUDA graph on.
   */
  uint64_t identity;
  /**
   * `PIE_STAGE_REQUIRES_*` bits.
   */
  uint32_t flags;
  /**
   * Draft rows the stage reads when `PIE_STAGE_REQUIRES_MTP_ROWS` is set.
   */
  uint32_t mtp_rows;
  /**
   * Normalized ops, in SSA order. `channel` indexes `channel_bindings`.
   */
  struct PieLaunchOpSlice ops;
  /**
   * One entry per normalized op, listing the source op positions it covers.
   */
  struct PieU32Slice source_ops;
  /**
   * `source_ops` is a flattened ragged array; this is its per-op length.
   */
  struct PieU32Slice source_op_counts;
  /**
   * One entry per normalized SSA value.
   */
  struct PieLaunchPlanValueSlice value_types;
  /**
   * Local channel slot → program-global dense channel index.
   */
  struct PieU32Slice channel_bindings;
  /**
   * Local name slot → canonical second-party kernel name.
   */
  struct PieBytesSlice names;
  /**
   * One-launch-per-op partition.
   */
  struct PieLaunchRegionSlice singleton;
  /**
   * Fused partition — what `emitted_kernels` was generated from.
   */
  struct PieLaunchRegionSlice fused;
  /**
   * Runtime extents any value in the stage depends on, ascending.
   */
  struct PieU8Slice used_extents;
  /**
   * Values bound through a channel, in normalized value order.
   */
  struct PieLaunchChannelRuleSlice channel_rules;
  /**
   * Why `PIE_STAGE_GROUPED_VALID` is clear. Empty when it is set.
   */
  struct PieBytes error;
} PieLaunchStagePlan;

/**
 * Borrowed view of a per-stage launch plan table.
 */
typedef struct PieLaunchStagePlanSlice {
  const struct PieLaunchStagePlan *ptr;
  size_t len;
} PieLaunchStagePlanSlice;

/**
 * **The launch package** — a program in the shape a driver executes it.
 *
 * This is what replaced `canonical_bytes` + `sidecar_bytes`. The compiler
 * owns what a program *is*; the driver owns firing it. Nothing here requires
 * the driver to know PTIR: there is no container, no sidecar, no wire format,
 * and no identity to re-check (`program_hash` on `PieProgramDesc` is the key).
 *
 * `stages` and `plans` are parallel arrays in attachment order — `plans[i]` is
 * the launch plan for `stages[i]`, and `(stage_index, region_index)` joins
 * both to `emitted_kernels` and to `region_analysis`.
 */
typedef struct PieLaunchPackage {
  /**
   * SSA value table, indexed by value id.
   */
  struct PieLaunchValueSlice values;
  struct PieLaunchChannelSlice channels;
  struct PieLaunchPortSlice ports;
  /**
   * Program-wide name table for second-party kernels and sinks.
   */
  struct PieBytesSlice names;
  struct PieLaunchStageSlice stages;
  /**
   * One launch plan per stage, in the same order as `stages`.
   */
  struct PieLaunchStagePlanSlice plans;
} PieLaunchPackage;

/**
 * Static program registration descriptor.
 */
typedef struct PieProgramDesc {
  uint32_t abi_version;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  /**
   * Stable C3 registration/cache key.
   */
  uint64_t program_hash;
  /**
   * Kernels the host generated for this program, in the driver's own
   * backend. Empty for a driver that has no code generation (the dummy
   * driver interprets, and the native drivers ignore the table for stages
   * they run on a prebuilt path).
   *
   * The emitter version the host built these with, so a driver's compile
   * cache keys on it: a bump must miss, not silently reuse a stale cubin.
   */
  uint32_t emitter_version;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved1;
  struct PieEmittedKernelSlice emitted_kernels;
  /**
   * Per-region bind verdicts and intrinsic side-table analysis, joined to
   * `emitted_kernels` on `(stage_index, region_index)`.
   */
  struct PieRegionAnalysisSlice region_analysis;
  /**
   * The program itself, in the shape the driver executes it.
   */
  struct PieLaunchPackage launch;
} PieProgramDesc;

/**
 * Persistent channel endpoint registration descriptor.
 */
typedef struct PieChannelDesc {
  uint32_t abi_version;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  uint64_t channel_id;
  struct PieU32Slice shape;
  /**
   * One of `PIE_CHANNEL_DTYPE_*`.
   */
  uint8_t dtype;
  /**
   * One of `PIE_CHANNEL_HOST_ROLE_*`.
   */
  uint8_t host_role;
  /**
   * Must be 0 or 1.
   */
  uint8_t seeded;
  /**
   * One of `PIE_CHANNEL_EXTERN_*`.
   */
  uint8_t extern_dir;
  uint32_t capacity;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved1;
  uint64_t reader_wait_id;
  uint64_t writer_wait_id;
  /**
   * Canonical extern binding name. Empty for private channels.
   */
  struct PieBytes extern_name;
} PieChannelDesc;

/**
 * Stable driver-owned host endpoint returned by channel registration.
 */
typedef struct PieChannelEndpointBinding {
  uint64_t channel_id;
  uint64_t mirror_base;
  uint64_t word_base;
  uint64_t mirror_bytes;
  uint64_t word_bytes;
  uint32_t cell_bytes;
  uint32_t capacity;
  uint32_t head_word_index;
  uint32_t tail_word_index;
  uint32_t poison_word_index;
  uint32_t closed_word_index;
} PieChannelEndpointBinding;

/**
 * Borrowed immutable `u64` slice.
 *
 * `ptr` may be null only when `len == 0`.
 */
typedef struct PieU64Slice {
  const uint64_t *ptr;
  size_t len;
} PieU64Slice;

/**
 * One channel-value payload used for PTIR seeds and host puts.
 */
typedef struct PieChannelValueDesc {
  uint64_t channel_id;
  struct PieBytes bytes;
} PieChannelValueDesc;

/**
 * Borrowed immutable slice of [`PieChannelValueDesc`].
 *
 * `ptr` may be null only when `len == 0`.
 */
typedef struct PieChannelValueDescSlice {
  const struct PieChannelValueDesc *ptr;
  size_t len;
} PieChannelValueDescSlice;

/**
 * Per-instance bind descriptor.
 */
typedef struct PieInstanceDesc {
  uint32_t abi_version;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  /**
   * Runtime-derived geometry class; the driver verifies this against the
   * registered trace and echoes it in `PieInstanceBinding`.
   */
  uint32_t geometry_class;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved1;
  uint64_t program_id;
  uint64_t requested_instance_id;
  uint64_t pacing_wait_id;
  struct PieU64Slice channel_ids;
  struct PieChannelValueDescSlice seed_values;
} PieInstanceDesc;

/**
 * Driver-assigned identity returned from `*_bind_instance`.
 */
typedef struct PieInstanceBinding {
  uint64_t instance_id;
  uint32_t geometry_class;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
} PieInstanceBinding;

/**
 * Terminal completion outcome published by the native driver.
 */
typedef uint32_t PieTerminalOutcome;

/**
 * Host-visible terminal control cell.
 *
 * The `outcome` word is published with release semantics by the driver and
 * read with acquire semantics by the runtime.
 */
typedef struct PieTerminalCell {
  PieTerminalOutcome outcome;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
} PieTerminalCell;

/**
 * Borrowed immutable slice of terminal-cell pointers.
 *
 * The slice storage may be null only when `len == 0`. Each element must point
 * at a distinct, properly aligned [`PieTerminalCell`] that remains stable until
 * the corresponding accepted operation retires.
 */
typedef struct PieTerminalCellPtrSlice {
  struct PieTerminalCell *const *ptr;
  size_t len;
} PieTerminalCellPtrSlice;

/**
 * Flattened mask words with request and row partitions.
 *
 * `request_indptr` partitions rows per request; `word_indptr` partitions the
 * packed `u32` words per row.
 */
typedef struct PieMaskWordsDesc {
  struct PieU32Slice request_indptr;
  struct PieU32Slice word_indptr;
  struct PieU32Slice words;
} PieMaskWordsDesc;

/**
 * One forward step of a frame: the per-step section of [`PieFrameDesc`].
 *
 * A step's batch members reference the frame's lane roster through
 * `roster_rows` and are partitioned into ordered geometry-homogeneous
 * sub-batches; sub-batch order resolves producer→consumer dependencies
 * within the step. Device-resolved (decode-envelope) sub-batches elide
 * their wire geometry exactly as in v13, so decode steps are naturally
 * small. Frame-invariant tables (roster ids, WorkingSet page translation,
 * KV admission demand) live on the frame, not the step.
 */
typedef struct PieStepDesc {
  /**
   * Indices into the frame roster (`PieFrameDesc::instance_ids`), one per
   * batch member, in sub-batch order.
   */
  struct PieU32Slice roster_rows;
  /**
   * CSR over `roster_rows`: sub-batch `b` spans members
   * `[sub_batch_indptr[b], sub_batch_indptr[b+1])`.
   */
  struct PieU32Slice sub_batch_indptr;
  /**
   * `PIE_GEOMETRY_CLASS_*` per sub-batch, parallel to the CSR segments.
   */
  struct PieU32Slice sub_batch_class;
  /**
   * Stable terminal control cell addresses, one per `roster_rows` member.
   */
  struct PieTerminalCellPtrSlice terminal_cells;
  struct PieU32Slice token_ids;
  struct PieU32Slice position_ids;
  struct PieU32Slice kv_page_indices;
  struct PieU32Slice kv_page_indptr;
  struct PieU32Slice kv_last_page_lens;
  struct PieU32Slice qo_indptr;
  /**
   * Folded recurrent-state slot per resolved `qo_indptr` row. Empty for
   * pure-attention launches; never indexed by `instance_ids`.
   */
  struct PieU32Slice rs_slot_ids;
  /**
   * Flags parallel to `rs_slot_ids`.
   */
  struct PieU8Slice rs_slot_flags;
  struct PieU32Slice rs_fold_lens;
  struct PieU32Slice rs_buffer_slot_ids;
  struct PieU32Slice rs_buffer_slot_indptr;
  /**
   * Buffered slabs the fire REPLAYS, with the row CSR (`rows + 1`), and the
   * token count to replay from each row's slabs (`rows` entries).
   *
   * Distinct from `rs_buffer_slot_ids`, which is what the fire WRITES: a
   * write may materialize or privatize a slab, a read must not, and a read
   * of a merely reserved page would gather uninitialized activations
   * straight into the recurrent state. All three are empty when no row has
   * anything buffered, which is the common case.
   */
  struct PieU32Slice rs_buffer_read_slot_ids;
  struct PieU32Slice rs_buffer_read_indptr;
  struct PieU32Slice rs_buffer_read_lens;
  struct PieU32Slice rs_buffer_heads;
  /**
   * WorkingSet-relative buffer page -> physical slot for channel-resolved
   * `rs-geometry`, concatenated over request rows. `rs_translation_indptr`
   * is the row CSR (`rows + 1`). Per ROW, unlike `kv_translation`, because
   * a pass binds one RS working set per request rather than one per pass.
   * `0xFFFF_FFFF` marks a reserved-but-unmaterialized page.
   */
  struct PieU32Slice rs_translation;
  struct PieU32Slice rs_translation_indptr;
  struct PieMaskWordsDesc masks;
  /**
   * Model readout rows, flattened across the batch.
   */
  struct PieU32Slice sampling_indices;
  /**
   * Request → readout-row CSR parallel to the batch.
   */
  struct PieU32Slice sampling_indptr;
  struct PieU64Slice context_ids;
  /**
   * Boolean `0`/`1`; any other value is invalid.
   */
  uint8_t single_token_mode;
  /**
   * Boolean `0`/`1`; any other value is invalid.
   */
  uint8_t has_user_mask;
  /**
   * Reserved; must be zero.
   */
  uint8_t reserved_flags[2];
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  struct PieU32Slice image_indptr;
  struct PieU32Slice image_grids;
  struct PieU32Slice image_anchor_positions;
  struct PieBytes image_pixels;
  struct PieU32Slice image_pixel_indptr;
  struct PieU32Slice image_mrope_positions;
  struct PieU32Slice image_mrope_indptr;
  struct PieU32Slice image_patch_positions;
  struct PieU32Slice image_anchor_rows;
  struct PieBytes audio_features;
  struct PieU32Slice audio_feature_indptr;
  struct PieU32Slice audio_anchor_rows;
  struct PieU32Slice audio_indptr;
  struct PieBytes embed_rows;
  struct PieU32Slice embed_indptr;
  struct PieU32Slice embed_shapes;
  struct PieU8Slice embed_dtypes;
  struct PieU32Slice embed_anchor_rows;
  struct PieU32Slice embed_block_indptr;
  struct PieU32Slice kv_len;
  struct PieU64Slice kv_len_device;
  /**
   * Program → wire-request attribution CSR (`len == roster_rows.len + 1`
   * when present, else empty): step member `p` owns the wire request rows
   * `[row_indptr[p], row_indptr[p+1])` of `qo_indptr`/`kv_page_indptr`/
   * `sampling_indptr`. A device-geometry member's span is its empty
   * wire placeholder row; the driver substitutes its channel-resolved
   * geometry for that span when composing the forward batch.
   */
  struct PieU32Slice ptir_program_row_indptr;
  struct PieU64Slice ptir_kv_write_lower_bounds;
  struct PieU64Slice ptir_kv_write_upper_bounds;
  /**
   * Immutable logical-fire ids, one per `roster_rows` member.
   */
  struct PieU64Slice logical_fire_ids;
  /**
   * Dense-channel sequence tickets, CSR-partitioned per `roster_rows`
   * member.
   */
  struct PieU64Slice channel_expected_head;
  struct PieU64Slice channel_expected_tail;
  struct PieU32Slice channel_ticket_indptr;
  /**
   * V2 rung ③a (north-star-dsl.md "RUNG ③ SPEC"): the region table —
   * the seriation's output stated ONCE. Region `r` spans wire rows
   * `[region_row_indptr[r], region_row_indptr[r+1])`;
   * `region_sig[r]` is the axis bitset ([`PIE_REGION_SIG_MULTI_TOKEN`]
   * etc.); `region_k[r]` is the depth operand
   * ([`PIE_MAX_LAYERS_FULL`] = full model). Empty = no table sent
   * (the words' UNPLANNED discipline). While the scalar words above
   * survive, the driver DERIVES them from a present table and
   * refuses the launch on drift — the cross-check discipline.
   */
  struct PieU32Slice region_row_indptr;
  /**
   * Axis bitset per region (see [`PieStepDesc::region_row_indptr`]).
   */
  struct PieU32Slice region_sig;
  /**
   * Depth operand per region (see
   * [`PieStepDesc::region_row_indptr`]).
   */
  struct PieU32Slice region_k;
} PieStepDesc;

/**
 * Borrowed slice of per-step sections.
 *
 * `ptr` may be null only when `len == 0`.
 */
typedef struct PieStepDescSlice {
  const struct PieStepDesc *ptr;
  size_t len;
} PieStepDescSlice;

/**
 * One sealed frame: the v14 launch unit.
 *
 * The driver executes the frame's steps as one closed system — steps chain
 * on-stream (device-resolved token feedback), data publication stays
 * per-step on-stream, and control settlement happens once at the frame
 * tail through the single launch completion. Admission is evaluated
 * against the frame-union demand at the launch call ([`PIE_STATUS_EXHAUSTED`]
 * / [`PIE_STATUS_IMPOSSIBLE`]); a frame that admits cannot fail per-lane
 * mid-frame (stream work is SUCCESS-only; deterministic compose kills latch
 * per-lane FAILED at the tail).
 */
typedef struct PieFrameDesc {
  uint32_t abi_version;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  /**
   * Lane roster: every bound instance participating in any step, in
   * scheduler order. No duplicates. Step sections reference these entries
   * by index (`PieStepDesc::roster_rows`).
   */
  struct PieU64Slice instance_ids;
  /**
   * Frame-union WorkingSet page translation, flattened across the roster:
   * entry `i` of a lane's segment is the PHYSICAL KV page id backing
   * WorkingSet-relative page index `i` for this FRAME (committed mapping
   * overlaid with ALL steps' prepared write targets). The driver maps any
   * WorkingSet-relative page reference it resolves from device channels
   * (`Pages` / `WSlot` descriptor ports) through this table; guests never
   * see physical ids. An empty segment means the lane's channel geometry
   * is already physical (legacy) or absent.
   */
  struct PieU32Slice kv_translation;
  /**
   * CSR partition of `kv_translation`, one segment per `instance_ids`
   * entry (`len == instance_ids.len + 1` when present, else empty).
   */
  struct PieU32Slice kv_translation_indptr;
  /**
   * Exclusive physical KV page high-water required after the LAST step —
   * the frame-union admission demand.
   */
  uint32_t required_kv_pages;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved1;
  /**
   * The frame's steps in execution order. Never empty.
   */
  struct PieStepDescSlice steps;
} PieFrameDesc;

/**
 * Payload-free asynchronous completion target.
 */
typedef struct PieCompletion {
  uint64_t wait_id;
  uint64_t target_epoch;
  /**
   * Stable terminal control cell for value-less operations. Frame launches
   * use the per-member `PieStepDesc::terminal_cells` instead.
   */
  struct PieTerminalCell *terminal_cell;
} PieCompletion;

typedef struct PieMutBytes {
  uint8_t *ptr;
  size_t len;
} PieMutBytes;

typedef struct PieU32MutSlice {
  uint32_t *ptr;
  size_t len;
} PieU32MutSlice;

typedef struct PieEncodeDesc {
  uint32_t abi_version;
  uint32_t reserved0;
  struct PieU32Slice image_grids;
  struct PieBytes image_pixels;
  struct PieU32Slice image_pixel_indptr;
  struct PieU32Slice image_patch_positions;
  struct PieU32Slice image_anchor_rows;
  struct PieBytes audio_features;
  struct PieU32Slice audio_feature_indptr;
  struct PieU32Slice audio_anchor_rows;
  struct PieMutBytes output_rows;
  struct PieU32MutSlice output_row_indptr;
} PieEncodeDesc;

/**
 * Memory domain tag for local KV residency copies.
 */
typedef uint32_t PieMemoryDomain;

/**
 * A single KV cell move expressed in physical page/token coordinates.
 */
typedef struct PieKvMoveCell {
  uint32_t dst_page_id;
  uint32_t dst_token_offset;
  uint32_t src_page_id;
  uint32_t src_token_offset;
} PieKvMoveCell;

/**
 * Borrowed immutable slice of [`PieKvMoveCell`].
 *
 * `ptr` may be null only when `len == 0`.
 */
typedef struct PieKvMoveCellSlice {
  const struct PieKvMoveCell *ptr;
  size_t len;
} PieKvMoveCellSlice;

/**
 * Direct KV-copy descriptor.
 *
 * Whole-page residency copies use the `src_page_ids`/`dst_page_ids` slices. The
 * optional `cells` slice carries per-token device KV moves for Design-B compaction.
 */
typedef struct PieKvCopyDesc {
  uint32_t abi_version;
  PieMemoryDomain src_domain;
  uint32_t src_device_ordinal;
  PieMemoryDomain dst_domain;
  uint32_t dst_device_ordinal;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  struct PieU32Slice src_page_ids;
  struct PieU32Slice dst_page_ids;
  struct PieKvMoveCellSlice cells;
} PieKvCopyDesc;

/**
 * One recurrent-state slot copy range.
 */
typedef struct PieStateCopyRange {
  uint32_t src_slot_id;
  uint32_t dst_slot_id;
  uint32_t src_token_offset;
  uint32_t dst_token_offset;
  uint32_t token_count;
} PieStateCopyRange;

/**
 * Borrowed immutable slice of [`PieStateCopyRange`].
 *
 * `ptr` may be null only when `len == 0`.
 */
typedef struct PieStateCopyRangeSlice {
  const struct PieStateCopyRange *ptr;
  size_t len;
} PieStateCopyRangeSlice;

/**
 * Direct recurrent-state copy descriptor.
 */
typedef struct PieStateCopyDesc {
  uint32_t abi_version;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  struct PieStateCopyRangeSlice slot_ranges;
} PieStateCopyDesc;

/**
 * One sparse pool page range to map or unmap.
 */
typedef struct PiePoolRange {
  uint64_t page_index;
  uint64_t page_count;
} PiePoolRange;

/**
 * Borrowed immutable slice of [`PiePoolRange`].
 *
 * `ptr` may be null only when `len == 0`.
 */
typedef struct PiePoolRangeSlice {
  const struct PiePoolRange *ptr;
  size_t len;
} PiePoolRangeSlice;

/**
 * Direct pool-resize descriptor.
 */
typedef struct PiePoolResizeDesc {
  uint32_t abi_version;
  /**
   * Reserved; must be zero.
   */
  uint32_t reserved0;
  uint64_t pool_id;
  uint64_t target_pages;
  struct PiePoolRangeSlice map_ranges;
  struct PiePoolRangeSlice unmap_ranges;
} PiePoolResizeDesc;

/**
 * Page-locked host memory.
 */
#define PIE_MEMORY_DOMAIN_HOST_PINNED 0

/**
 * CUDA device memory on `*_device_ordinal`.
 */
#define PIE_MEMORY_DOMAIN_CUDA_DEVICE 1

/**
 * ROCm device memory on `*_device_ordinal`.
 */
#define PIE_MEMORY_DOMAIN_ROCM_DEVICE 2

/**
 * Metal shared CPU/GPU memory.
 */
#define PIE_MEMORY_DOMAIN_METAL_SHARED 3

/**
 * Metal private device memory.
 */
#define PIE_MEMORY_DOMAIN_METAL_PRIVATE 4

/**
 * The operation has not reached a terminal state yet.
 */
#define PIE_TERMINAL_OUTCOME_PENDING 0

/**
 * The operation completed successfully.
 */
#define PIE_TERMINAL_OUTCOME_SUCCESS 1

/**
 * The operation completed unsuccessfully.
 */
#define PIE_TERMINAL_OUTCOME_FAILED 2

/**
 * The accepted work item committed no effects and must be attempted again.
 */
#define PIE_TERMINAL_OUTCOME_RETRY 3

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

extern PieDriver *pie_cuda_create(const struct PieDriverCreateDesc *desc,
                                  struct PieDriverCaps *caps);

extern int32_t pie_cuda_load_model(PieDriver *driver,
                                   const struct PieModelLoadDesc *load,
                                   struct PieDriverCaps *caps);

extern int32_t pie_cuda_register_program(PieDriver *driver,
                                         const struct PieProgramDesc *program,
                                         uint64_t *program_id);

extern int32_t pie_cuda_register_channel(PieDriver *driver,
                                         const struct PieChannelDesc *channel,
                                         struct PieChannelEndpointBinding *binding);

extern int32_t pie_cuda_bind_instance(PieDriver *driver,
                                      const struct PieInstanceDesc *instance,
                                      struct PieInstanceBinding *binding);

extern int32_t pie_cuda_launch(PieDriver *driver,
                               const struct PieFrameDesc *frame,
                               struct PieCompletion completion);

extern int32_t pie_cuda_encode(PieDriver *driver,
                               const struct PieEncodeDesc *encode,
                               struct PieCompletion completion);

extern int32_t pie_cuda_copy_kv(PieDriver *driver,
                                const struct PieKvCopyDesc *copy,
                                struct PieCompletion completion);

extern int32_t pie_cuda_copy_state(PieDriver *driver,
                                   const struct PieStateCopyDesc *copy,
                                   struct PieCompletion completion);

extern int32_t pie_cuda_resize_pool(PieDriver *driver,
                                    const struct PiePoolResizeDesc *resize,
                                    struct PieCompletion completion);

extern int32_t pie_cuda_close_instance(PieDriver *driver, uint64_t instance_id);

extern int32_t pie_cuda_close_channel(PieDriver *driver, uint64_t channel_id);

extern void pie_cuda_destroy(PieDriver *driver);

extern PieDriver *pie_metal_create(const struct PieDriverCreateDesc *desc,
                                   struct PieDriverCaps *caps);

extern int32_t pie_metal_load_model(PieDriver *driver,
                                    const struct PieModelLoadDesc *load,
                                    struct PieDriverCaps *caps);

extern int32_t pie_metal_register_program(PieDriver *driver,
                                          const struct PieProgramDesc *program,
                                          uint64_t *program_id);

extern int32_t pie_metal_register_channel(PieDriver *driver,
                                          const struct PieChannelDesc *channel,
                                          struct PieChannelEndpointBinding *binding);

extern int32_t pie_metal_bind_instance(PieDriver *driver,
                                       const struct PieInstanceDesc *instance,
                                       struct PieInstanceBinding *binding);

extern int32_t pie_metal_launch(PieDriver *driver,
                                const struct PieFrameDesc *frame,
                                struct PieCompletion completion);

extern int32_t pie_metal_encode(PieDriver *driver,
                                const struct PieEncodeDesc *encode,
                                struct PieCompletion completion);

extern int32_t pie_metal_copy_kv(PieDriver *driver,
                                 const struct PieKvCopyDesc *copy,
                                 struct PieCompletion completion);

extern int32_t pie_metal_copy_state(PieDriver *driver,
                                    const struct PieStateCopyDesc *copy,
                                    struct PieCompletion completion);

extern int32_t pie_metal_resize_pool(PieDriver *driver,
                                     const struct PiePoolResizeDesc *resize,
                                     struct PieCompletion completion);

extern int32_t pie_metal_close_instance(PieDriver *driver, uint64_t instance_id);

extern int32_t pie_metal_close_channel(PieDriver *driver, uint64_t channel_id);

extern void pie_metal_destroy(PieDriver *driver);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
