# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import model


@dataclass
class Voice_Speaker:
    value: int


@dataclass
class Voice_Named:
    value: str


Voice = Union[Voice_Speaker, Voice_Named]


@dataclass
class SpeechRequest:
    text: str
    voice: Voice
    max_duration_ms: Optional[int]


class Speech:

    @classmethod
    def generate(cls, model: model.Model, req: SpeechRequest) -> Self:
        """
        Synthesize speech on `model`.

        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def sample_rate(self) -> int:
        """
        Output sample rate in Hz.
        """
        raise NotImplementedError
    def channels(self) -> int:
        """
        Channel count.
        """
        raise NotImplementedError
    def duration_ms(self) -> int:
        """
        Duration in milliseconds.
        """
        raise NotImplementedError
    def pcm(self) -> List[float]:
        """
        Decoded PCM samples in [-1, 1].
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self

    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError
