# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
MCP client interface — lets inferlets discover and call MCP servers.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import pie_mcp_types

class Session:
    """
    An active connection to an MCP server.
    Dropping the resource closes the connection.
    """
    
    def list_tools(self) -> str:
        """
        List tools exposed by this server.
        
        Raises: `wit_world.types.Err(wit_world.imports.pie_mcp_types.Error)`
        """
        raise NotImplementedError
    def call_tool(self, name: str, args: str) -> List[pie_mcp_types.Content]:
        """
        Call a tool by name with JSON arguments.
        
        Raises: `wit_world.types.Err(wit_world.imports.pie_mcp_types.Error)`
        """
        raise NotImplementedError
    def list_resources(self) -> str:
        """
        List resources exposed by this server.
        
        Raises: `wit_world.types.Err(wit_world.imports.pie_mcp_types.Error)`
        """
        raise NotImplementedError
    def read_resource(self, uri: str) -> List[pie_mcp_types.Content]:
        """
        Read a resource by URI.
        
        Raises: `wit_world.types.Err(wit_world.imports.pie_mcp_types.Error)`
        """
        raise NotImplementedError
    def list_prompts(self) -> str:
        """
        List prompts exposed by this server.
        
        Raises: `wit_world.types.Err(wit_world.imports.pie_mcp_types.Error)`
        """
        raise NotImplementedError
    def get_prompt(self, name: str, args: str) -> str:
        """
        Render a prompt template with the given arguments.
        
        Raises: `wit_world.types.Err(wit_world.imports.pie_mcp_types.Error)`
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



def available_servers() -> List[str]:
    """
    Discover available MCP servers.
    """
    raise NotImplementedError
def connect(server_name: str) -> Session:
    """
    Connect to a named MCP server, performing the MCP handshake.
    
    Raises: `wit_world.types.Err(wit_world.imports.pie_mcp_types.Error)`
    """
    raise NotImplementedError
