# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import model
from ..imports import pie_core_types

class Context:
    
    @classmethod
    def create(cls, model: model.Model, name: str, fill: Optional[List[int]]) -> Self:
        """
        Creates a new context, optionally with a name
        
        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def destroy(self) -> None:
        raise NotImplementedError
    @classmethod
    def lookup(cls, model: model.Model, name: str) -> Optional[Self]:
        """
        Retrieves an existing context by name
        """
        raise NotImplementedError
    def fork(self, new_name: str) -> Self:
        """
        Forks this context into a new one with the given name
        
        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def acquire_lock(self) -> pie_core_types.FutureBool:
        """
        Acquires a lock on the context, returning a lock result
        """
        raise NotImplementedError
    def release_lock(self) -> None:
        """
        Releases the lock
        
        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def tokens_per_page(self) -> int:
        """
        Number of tokens per page
        """
        raise NotImplementedError
    def model(self) -> model.Model:
        raise NotImplementedError
    def committed_page_count(self) -> int:
        """
        Number of committed KV pages in the context
        """
        raise NotImplementedError
    def uncommitted_page_count(self) -> int:
        """
        Number of uncommitted KV pages in the context
        """
        raise NotImplementedError
    def commit_pages(self, page_indices: List[int]) -> None:
        """
        Commit the KV pages to the context
        
        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def reserve_pages(self, num_pages: int) -> None:
        """
        Reserve KV pages for the context
        
        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def release_pages(self, num_pages: int) -> None:
        """
        Release KV pages from the context
        """
        raise NotImplementedError
    def cursor(self) -> int:
        raise NotImplementedError
    def set_cursor(self, cursor: int) -> None:
        raise NotImplementedError
    def buffered_tokens(self) -> List[int]:
        raise NotImplementedError
    def set_buffered_tokens(self, tokens: List[int]) -> None:
        raise NotImplementedError
    def append_buffered_tokens(self, tokens: List[int]) -> None:
        raise NotImplementedError
    def last_position(self) -> Optional[int]:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



