# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
The forward-pass guest<->host surface (submits PTIR container bytes). The WIT
surface family is named `forward*`; PTIR remains the name of the container
byte format it ships.

Layering: the guest traces a pass -> canonical PTIR container bytes
(pie_sampling_ir::ptir). WIT cannot carry closures, so the container bytes
stay the wire artifact -- but everything the author manipulates (channels,
working sets, the pass, the pipeline) crosses the boundary as a first-class
resource, mirroring the ptir tracing DSL.

THREE INTERFACES, ONE PER STATE SEMANTICS (forward_refactor.md D1):

  `forward`            paged, per-token, reversibly discardable KV only
  `forward-recurrent`  irreversibly folded recurrent state only
  `forward-hybrid`     both, in the same forward

The split is over STATE SEMANTICS, not model family: `architecture()` is an
open, fast-growing string set, while this taxonomy is closed. `model.pass-kind()`
selects the interface; constructing the wrong one errors immediately.

The split is also a CORRECTNESS GATE. Attention-only algorithms (H2O, SnapKV,
TOVA, Quest) are semantically wrong on a folded recurrent state -- evicting KV
does not undo the fold -- and until now nothing caught it. They can no longer
name a hybrid model's pass type.

All three deliberately DUPLICATE `embed` / `readout` / `program` / `submit`
and their geometry records rather than sharing a `pass-body` (D3): WIT
duplication does not force implementation duplication (the host keeps one
private `PassCore`), and full separation makes cross-kind states
unrepresentable instead of runtime-guarded. Adding a field to one interface's
record must never move another's ABI.
THIS FILE: recurrent layers only, no attention layers anywhere in the model.
Valid only when `model.pass-kind()` == recurrent.

Legal stages: prologue, on_recurrent, epilogue. `on_attn_proj` / `on_attn`
are REJECTED -- there is no attention layer for them to fire on, which under
the old single-interface surface was an unexpressible (and unchecked) error.

No registered model reports this kind today: Qwen3.5 GDN and Nemotron-H
Mamba2 all interleave attention layers and so are `hybrid`. This interface
exists so that a pure-SSM model is a typed case rather than a surprise.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import pipeline
from ..imports import channel
from ..imports import working_set
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter

@dataclass
class RsGeometry:
    """
    The recurrent counterpart of `kv-geometry`: where this fire's recurrent
    state lives, and where its folded boundary lands.
    
    A linear model's context is TWO adjacent spans -- a compressed, frozen
    folded prefix `[0, F)` and an uncompressed, mutable buffer `[F, F+B)`
    holding each token's pre-recurrence activations. Reading the state means
    starting from the folded prefix and scanning the buffer; `fold` just
    moves `F` right. Folding is therefore semantically a NO-OP -- it trades
    optionality for memory and compute, and is legal exactly when the tokens
    it absorbs will never be modified again. Only the guest knows that,
    which is why this is an API rather than a runtime heuristic.
    
    The guest states POSITIONS; the runtime derives ADDRESSES. Where each
    token's activations land, which pages a row occupies, how many tokens
    are live, and how far back a replay reaches are all functions of the
    store's own occupancy, which the runtime is authoritative for -- so
    they are not on this record. They used to be, and the runtime computed
    them anyway and refused any fire whose copy disagreed: six channels of
    page arithmetic with exactly one satisfying assignment. The FOLDED
    state slot is likewise not named here -- it comes from the working-set
    handle.
    
    This rides on the STATE BINDING, not on a fold-mode method: once the
    buffer is understood as half the state, its addressing is an input to
    the recurrence itself, needed by every fire rather than by two of them.
    A plain prefill names an empty buffer and a full `fold-len`, which is
    degenerate but meaningful -- not the dummy geometry this refactor
    exists to delete.
    """
    fold_len: channel.Channel
    buffer: working_set.PageSpan

class ForwardPass:
    
    def __init__(self) -> None:
        raise NotImplementedError

    def attention(self, rs: List[working_set.RsWorkingSet], geom: RsGeometry) -> None:
        """
        State binding. REQUIRED. The mechanism is a recurrence, but the
        SLOT NAME is `attention` in all three interfaces (D6) -- the role
        inside a pass is the same regardless of mechanism; only the
        signature varies.
        
        `rs` is one working set per request, in resolved request order --
        the state's IDENTITY. `geom` is where that state lives for this
        fire and where its boundary lands. The same division as
        `attention(kv, kv-geometry)` in `forward`.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def embed(self, tokens: channel.Channel, indptr: channel.Channel) -> None:
        """
        There is deliberately NO `fold` / `buffer` / `fold-buffered` triple.
        Those were three values of one scalar -- where the folded boundary
        lands -- so they collapsed into `rs-geometry.fold-len`. An open
        enumeration of KINDS became a closed number over POSITIONS, which is
        also why folding it into a record is safe: a variant has cases to
        add, a number does not.
        
        `start-token` disappeared with them. New tokens always append at the
        buffer tail, which the runtime already tracks; letting the guest
        state a runtime-owned value is what made multi-chunk buffering
        expressible and wrong.
        Bind embedding token ids and CSR row indptr. Both are channels.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def readout(self, indices: channel.Channel) -> None:
        """
        Bind an optional readout-index channel separately from embedding.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def program(self, container_bytes: bytes, channels: List[channel.Channel]) -> None:
        """
        Attach canonical PTIR bytes and channel handles in dense declaration
        order. Validation uses the engine-owned ModelProfile, and now also
        rejects any stage this interface does not admit -- see the per-file
        note on which stages are legal.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



def submit(on: pipeline.Pipeline, slots: List[Optional[ForwardPass]]) -> None:
    """
    Submit ONE FRAME on `on`: exactly `model.frame-size()` ordered slots.
    Slot i executes in wave i of the frame; the composer never moves a
    slot to another wave. `none` is a no-op for that wave. The slot list
    may repeat the same handle (a plain decode frame is the same pass in
    every slot) and may be heterogeneous (prefill chunks in the earliest
    slots, decode in the rest). A frame is one call, not a resource.
    
    Submission validation (deterministic, structural — never timing):
    - `slots` must hold exactly `frame-size()` entries with at least one
      non-no-op slot.
    - Every host-writer channel bound by the frame's non-no-op slots must
      be *staged* (it holds at least as many staged cells as the frame's
      fires will consume), *device-advanced* (the program contains an
      advance rule for it), or *latest-value* (the program only reads it —
      a control word; one committed cell suffices and host `set` may
      replace it at any time).
    - Per host-reader channel, occupancy plus cells reserved by accepted
      unsettled frames plus the cells this frame will write must fit the
      capacity — overflow is prevented here, never by back-pressure.
    
    Each non-no-op slot prepares and enqueues RUN-AHEAD in slot order,
    including passes that bind recurrent state: an RS mapping publishes at
    prepare, so slot i+1 sees slot i's decision without waiting for it to
    execute, and the state's contents are ordered by the stream. The first
    submit of a pass binds seeds; steady-state resubmits carry the
    identity hash + instance only. Staged host-writer puts coalesce into
    the slot fires in order.
    
    The result covers validation/preparation/enqueue only. A fire that
    fails AFTER submit poisons the pass's host-reader channels (surfaced
    at `take`/`read` with the fire's error) and fails the pass — further
    submits of it error with the root cause. End-of-stream is a PIPELINE
    event, not a fire attribute: call `pipeline.close` after the last
    submit.
    
    Raises: `componentize_py_types.Err(wit_world.imports.str)`
    """
    raise NotImplementedError
