# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter

@dataclass
class Request:
    """
    A single buffered HTTP request.
    """
    method: str
    url: str
    headers: List[Tuple[str, str]]
    body: Optional[bytes]

@dataclass
class Response:
    """
    A fully-buffered HTTP response. HTTP status (incl. 4xx/5xx) is a normal
    response; `error` is reserved for transport/host failures.
    """
    status: int
    headers: List[Tuple[str, str]]
    body: bytes


async def fetch(request: Request) -> Response:
    """
    One HTTP request, host-side + async, response fully buffered. Does NOT
    follow redirects (the SDK resolves `location` and re-requests). There is
    no guest-side wasi:io pollable.
    
    Raises: `componentize_py_types.Err(wit_world.imports.str)`
    """
    raise NotImplementedError
