# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import model


class Image:

    @classmethod
    def from_bytes(cls, model: model.Model, bytes: bytes) -> Self:
        """
        Encoded still image (PNG / JPEG / ...).

        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def token_count(self) -> int:
        """
        Hidden-state rows / KV slots this visual span occupies.
        """
        raise NotImplementedError
    def position_span(self) -> int:
        """
        How far the 1-D sequence cursor advances past this span.
        """
        raise NotImplementedError
    def grid(self) -> Tuple[int, int, int]:
        """
        (t, h, w) in merged-token units.
        """
        raise NotImplementedError
    def prefix_tokens(self) -> List[int]:
        """
        Model-specific delimiter tokens placed before this span.
        """
        raise NotImplementedError
    def suffix_tokens(self) -> List[int]:
        """
        Model-specific delimiter tokens placed after this span.
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self

    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class Video:

    @classmethod
    def from_bytes(cls, model: model.Model, bytes: bytes, max_frames: int) -> Self:
        """
        Encoded animated container (for example GIF).

        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def frame_count(self) -> int:
        """
        Number of sampled frames.
        """
        raise NotImplementedError
    def frame(self, index: int) -> Image:
        """
        The `index`-th sampled frame as an owned image span.

        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def timestamp(self, index: int) -> float:
        """
        Timestamp in seconds of the `index`-th sampled frame.
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self

    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class Audio:

    @classmethod
    def from_bytes(cls, model: model.Model, bytes: bytes) -> Self:
        """
        Encoded audio (WAV / RIFF).

        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def token_count(self) -> int:
        """
        Hidden-state rows / KV slots this clip occupies.
        """
        raise NotImplementedError
    def position_span(self) -> int:
        """
        How far the 1-D sequence cursor advances past this clip.
        """
        raise NotImplementedError
    def prefix_tokens(self) -> List[int]:
        """
        Model-specific delimiter tokens placed before this span.
        """
        raise NotImplementedError
    def suffix_tokens(self) -> List[int]:
        """
        Model-specific delimiter tokens placed after this span.
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self

    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError
