# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import poll
from ..imports import pie_core_types

class Subscription:
    """
    Represents a subscription to a broadcast topic
    """
    
    def pollable(self) -> poll.Pollable:
        """
        Pollable to check for new messages on the topic
        """
        raise NotImplementedError
    def get(self) -> Optional[str]:
        """
        Retrieves a new message from the topic, if available
        """
        raise NotImplementedError
    def unsubscribe(self) -> None:
        """
        Cancels the subscription
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



def push(topic: str, message: str) -> None:
    """
    Pushes a message onto a topic queue
    """
    raise NotImplementedError
def pull(topic: str) -> pie_core_types.FutureString:
    """
    Pulls the next message from a topic queue
    """
    raise NotImplementedError
def broadcast(topic: str, message: str) -> None:
    """
    Publishes a message to a topic (broadcast to all subscribers)
    """
    raise NotImplementedError
def subscribe(topic: str) -> Subscription:
    """
    Subscribes to a topic and returns a subscription handle
    """
    raise NotImplementedError
