# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


def push(topic: str, message: str) -> None:
    """
    Pushes a message onto a topic queue
    """
    raise NotImplementedError
async def pull(topic: str) -> str:
    """
    Pulls the next message from a topic queue
    """
    raise NotImplementedError
def broadcast(topic: str, message: str) -> None:
    """
    Publishes a message to a topic (broadcast to all subscribers)
    """
    raise NotImplementedError
def subscribe(topic: str) -> StreamReader[str]:
    """
    Subscribes to a topic; the returned stream yields each broadcast
    message. Dropping the stream reader unsubscribes.
    """
    raise NotImplementedError
