# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import pie_core_types


def version() -> str:
    """
    Returns the runtime version string
    """
    raise NotImplementedError
def instance_id() -> str:
    """
    Returns a unique identifier for the running instance
    """
    raise NotImplementedError
def username() -> str:
    """
    Returns the username of the user who invoked the inferlet
    """
    raise NotImplementedError
def models() -> List[str]:
    """
    Get a list of all available model names
    """
    raise NotImplementedError
def spawn(package_name: str, args: List[str]) -> pie_core_types.FutureString:
    """
    Spawns a new inferlet with the given package name and arguments
    Returns the result of the spawned inferlet
    
    Raises: `wit_world.types.Err(wit_world.imports.str)`
    """
    raise NotImplementedError
