# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


def version() -> str:
    """
    Returns the runtime version string
    """
    raise NotImplementedError
def instance_id() -> str:
    """
    Returns a unique identifier for the running instance
    """
    raise NotImplementedError
def username() -> str:
    """
    Returns the username of the user who invoked the inferlet
    """
    raise NotImplementedError
async def sleep(duration_ns: int) -> None:
    """
    Suspends the calling inferlet for the given duration. A host-provided
    async timer: under component-model-async there is no guest-side
    pollable->future bridge for wasi:clocks, so timing lives host-side.
    """
    raise NotImplementedError
