# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import model
from ..imports import context


def price() -> float:
    """
    ── Market ─────────────────────────────────────────────────────
    Cost to produce one new KV page (constant = 1 credit).
    """
    raise NotImplementedError
def rent(ctx: context.Context) -> float:
    """
    Rent: clearing price from the last knapsack auction on this context's device.
    """
    raise NotImplementedError
def dividend(model: model.Model) -> float:
    """
    Dividend received last step (endowment-proportional share of revenue).
    """
    raise NotImplementedError
def latency(ctx: context.Context) -> float:
    """
    ── Device ─────────────────────────────────────────────────────
    Per-tick latency of this context's device (seconds), updated each tick.
    """
    raise NotImplementedError
def balance(model: model.Model) -> float:
    """
    ── Account ────────────────────────────────────────────────────
    Current credit balance (global, usable on any device).
    """
    raise NotImplementedError
