# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import pie_core_types


def send(message: str) -> None:
    """
    Sends a message to the remote user client
    """
    raise NotImplementedError
def receive() -> pie_core_types.FutureString:
    """
    Receives an incoming message from the remote user client
    """
    raise NotImplementedError
def send_file(data: bytes) -> None:
    """
    Sends a file to the remote user client
    """
    raise NotImplementedError
def receive_file() -> pie_core_types.FutureBlob:
    """
    Receives an incoming file from the remote user client
    """
    raise NotImplementedError
