# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


def encode(text: str) -> List[int]:
    """
    The tokenizer half of the former `model` interface: global functions over
    the single bound model's tokenizer (no resource handle).
    Converts input text into a list of token IDs
    """
    raise NotImplementedError
def decode(tokens: List[int]) -> str:
    """
    Converts token IDs back into a decoded string
    
    Raises: `componentize_py_types.Err(wit_world.imports.str)`
    """
    raise NotImplementedError
def vocabs() -> Tuple[List[int], List[bytes]]:
    """
    Returns the model's vocabulary as a list of byte sequences (tokens)
    """
    raise NotImplementedError
def split_regex() -> str:
    """
    Returns the split regular expression used by the tokenizer
    """
    raise NotImplementedError
def special_tokens() -> Tuple[List[int], List[bytes]]:
    """
    Returns the special tokens recognized by the model
    """
    raise NotImplementedError
