# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import inference
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter


@dataclass
class Event_Start:
    pass


@dataclass
class Event_Call:
    value: Tuple[str, str]


Event = Union[Event_Start, Event_Call]


class Decoder:
    
    def feed(self, tokens: List[int]) -> Event:
        """
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def reset(self) -> None:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



def equip(tools: List[str]) -> List[int]:
    """
    Register available tools (list of JSON schema strings)
    
    Raises: `componentize_py_types.Err(wit_world.imports.str)`
    """
    raise NotImplementedError
def answer(name: str, value: str) -> List[int]:
    """
    Provide a tool result (after a tool-call reply)
    """
    raise NotImplementedError
def create_decoder() -> Decoder:
    """
    Create a decoder to detect tool calls in generated tokens
    """
    raise NotImplementedError
def format(tools: List[str]) -> Optional[inference.Grammar]:
    """
    Returns the grammar that constrains well-formed tool-call output for
    this model and toolset, or none if the model has no enforceable format.
    """
    raise NotImplementedError
def create_matcher(tools: List[str]) -> inference.Matcher:
    """
    Create a grammar matcher to force-generate tool calls
    """
    raise NotImplementedError
