# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
import componentize_py_async_support
from componentize_py_async_support.streams import StreamReader, StreamWriter, ByteStreamReader, ByteStreamWriter
from componentize_py_async_support.futures import FutureReader, FutureWriter

@dataclass
class PageRange:
    """
    Shared by both working-set kinds. A contiguous, half-open span
    [start, start + len) of relative page slots inside a working set's dense
    ordered array. `start`/`len` are in page-slot units. The ONLY references
    that ever cross this API are these relative indices into the array —
    never physical page ids, never vpage ids.
    """
    start: int
    len: int

class KvWorkingSet:
    """
    KV working set: a dense, ordered array of KV page slots, owned by the
    inferlet. Public `u32` page references are relative indices into this
    array (see `page-range`). Token lengths, positions, replay history, and
    all semantic metadata are inferlet-owned — this resource is token-
    agnostic. Sharing (`slice`/`append`/`fork`) is lazy copy-on-write: page
    objects are shared by reference and the first divergent write copies.
    Full-page CAS sealing happens runtime-side after a forward pass writes a
    page; it never mutates other working sets' mappings.
    """
    
    def __init__(self) -> None:
        """
        Fresh, empty working set bound to `model` (and thus its device /
        unified arena). The model is captured at construction so the
        structural mutators (`alloc`/`free`/`slice`/`append`/`fork`) can
        resolve the arena without a forward pass; `slice`/`fork` inherit this
        model. In a single-model runtime every set binds to the single
        bound model.
        """
        raise NotImplementedError

    def size(self) -> int:
        """
        Current number of page slots in the array.
        """
        raise NotImplementedError
    def generation(self) -> int:
        """
        Monotonic counter bumped ONLY on `reorder`/`compact` — the operations
        that renumber slot ids (W8). Lets the SDK/inferlet detect that cached
        relative indices were invalidated by a reorder/compaction before it
        submits a forward pass. `alloc`/`alloc-slots`/`free`/`free-slots`/
        `append` do NOT bump it: slot ids are stable handles that survive
        `free` (survivors never renumber), so allocation/reclamation cannot
        invalidate a cached id. (CoW page writes do NOT bump it either.)
        NOTE: legacy dense-compaction builds (feature `ws-slot-ids` off) still
        bump on every structural mutation; the counter's meaning is strictly
        weaker only for cases it never actually protected (device-resident
        indices were never covered).
        """
        raise NotImplementedError
    def page_size(self) -> int:
        """
        Tokens per KV page for this working set's model/driver.
        """
        raise NotImplementedError
    def alloc(self, n: int) -> PageRange:
        """
        Append `n` fresh page slots to the end of the array; returns the
        contiguous relative range that was added. `alloc(0)` returns an
        empty range at the current end.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def free(self, indices: List[int]) -> None:
        """
        Remove the slots at `indices`. MIGRATION SHIM (append-only): under
        slot-id semantics (`ws-slot-ids`) this is `free-slots` — non-compacting
        tombstone; survivors keep their ids; a freed trailing run is truncated
        so a freed suffix leaves no hole. Legacy builds densely compact and
        renumber survivors. `indices` are interpreted against the array AT CALL
        TIME; all removals apply together. Out-of-range, already-freed, or
        duplicate indices return `error` (the call never traps).
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def alloc_slots(self, n: int) -> List[int]:
        """
        Stable-id allocation (W1/W2): return `n` slot ids, recycling freed ids
        (ascending) before growing. Unlike `alloc`, the returned ids need not
        be contiguous. A slot id is a stable handle that never renumbers, so it
        stays valid until passed to `free-slots`. `alloc-slots(0)` returns the
        empty list.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def free_slots(self, ids: List[int]) -> None:
        """
        Tombstone the slots at `ids` (non-compacting): survivors keep their
        ids; freed ids are recycled by a later `alloc-slots`; a freed trailing
        run is truncated so a freed suffix leaves no hole. Out-of-range or
        already-freed ids return `error` (the call never traps). Precondition:
        the freed ids are unreachable from every in-flight forward pass (the
        arena recycles the page only after the grace period).
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def reorder(self, perm: List[int]) -> None:
        """
        Reorder the array by the full bijection `perm` over `0..size`: new
        slot `i` takes old slot `perm[i]`. `perm` must list every current
        index exactly once; otherwise returns `error`.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def slice(self, start: int, len: int) -> Self:
        """
        Create a new working set whose array is the slots in
        [start, start + len), sharing those page objects by reference (lazy
        CoW; first divergent write copies). Out-of-range spans return `error`.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def append(self, other: Self) -> None:
        """
        Append the slots of `other` onto the end of this array, sharing the
        page objects by reference (lazy CoW).
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def fork(self) -> Self:
        """
        Fork into a new working set that shares all current page objects by
        reference (lazy CoW; first divergent write copies).
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class RsWorkingSet:
    """
    RS (recurrent-state) working set: required for hybrid / linear-attention
    models. Holds a folded recurrent-state object plus a mutable buffered
    suffix of page slots. NOT forced into the KV `list<page>` model. A
    forward pass may write buffered RS state WITHOUT folding it; folding is a
    separate, explicit operation (`inference.fold`). Fork is lazy CoW: the
    first fold/write on a shared folded or buffered slab copies the relevant
    object before mutation. RS CAS sharing is out of scope for v1.
    """
    
    def __init__(self) -> None:
        """
        Fresh, empty RS working set bound to `model` (device / arena),
        captured at construction so `alloc-buffer`/`fork`/`fold` resolve the
        arena without a forward pass; `fork` inherits this binding.
        """
        raise NotImplementedError

    def state_size(self) -> int:
        """
        Size in bytes of one folded recurrent-state object for this model.
        """
        raise NotImplementedError
    def buffer_size(self) -> int:
        """
        Current number of buffered page slots.
        """
        raise NotImplementedError
    def buffer_page_size(self) -> int:
        """
        Tokens per buffered RS page for this working set's model/driver.
        """
        raise NotImplementedError
    def alloc_buffer(self, n: int) -> PageRange:
        """
        Append `n` fresh buffered page slots; returns the contiguous range.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def free_buffer(self, indices: List[int]) -> None:
        """
        Remove buffered slots at `indices` and densely compact (call-time
        interpretation, same rules as `kv-working-set.free`). Invalid or
        duplicate indices return `error`.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def reorder_buffer(self, perm: List[int]) -> None:
        """
        Reorder the buffered slots by the full bijection `perm`.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def fork(self) -> Self:
        """
        Fork into a new RS working set sharing the folded state and buffered
        slabs by reference (lazy CoW; first fold/write copies).
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



