# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import inference
from ..imports import adapter


def adapter_seed(self: inference.ForwardPass, seed: int) -> None:
    raise NotImplementedError
def initialize(self: adapter.Adapter, rank: int, alpha: float, population_size: int, mu_fraction: float, initial_sigma: float) -> None:
    """
    Raises: `wit_world.types.Err(wit_world.imports.str)`
    """
    raise NotImplementedError
def update(self: adapter.Adapter, scores: List[float], seeds: List[int], max_sigma: float) -> None:
    """
    Raises: `wit_world.types.Err(wit_world.imports.str)`
    """
    raise NotImplementedError
