use std::collections::BTreeMap;
use std::fmt;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Variant {
    pub entrypoint: String,
    pub tier: crate::Capability,
    pub defines: BTreeMap<String, String>,
    pub line: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Directive {
    Include(String),
    If(String),
    Elif(String),
    Else,
    Endif,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Malformed {
    Unknown { line: usize, what: String },
    Unopened { line: usize, what: String },
    Unclosed { line: usize },
    AfterElse { line: usize },
    Uncondition { line: usize, cond: String },
    Unincluded { line: usize, path: String },
    Unnamed { line: usize },
    Untiered { line: usize, tag: String },
    Undefined { line: usize, what: String },
}

impl fmt::Display for Malformed {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unknown { line, what } => write!(f, "line {line}: unknown directive `{what}`"),
            Self::Unopened { line, what } => {
                write!(f, "line {line}: `{what}` with no `//#if` open")
            }
            Self::Unclosed { line } => write!(f, "line {line}: `//#if` is never closed"),
            Self::AfterElse { line } => write!(f, "line {line}: `//#elif` after `//#else`"),
            Self::Uncondition { line, cond } => {
                write!(
                    f,
                    "line {line}: `{cond}` is not a condition this expander reads"
                )
            }
            Self::Unincluded { line, path } => write!(f, "line {line}: no such include `{path}`"),
            Self::Unnamed { line } => {
                write!(f, "line {line}: `pie:instantiate` names no entrypoint")
            }
            Self::Untiered { line, tag } => write!(f, "line {line}: `@{tag}` is not a tier"),
            Self::Undefined { line, what } => write!(f, "line {line}: `{what}` is not `KEY=VALUE`"),
        }
    }
}

impl std::error::Error for Malformed {}

pub fn instantiations(text: &str) -> Result<Vec<Variant>, Malformed> {
    let mut out = Vec::new();
    for (at, raw) in text.lines().enumerate() {
        let line = at + 1;
        let Some(rest) = directive_body(raw, "pie:instantiate") else {
            continue;
        };
        let mut words = rest.split_whitespace();
        let Some(entrypoint) = words.next() else {
            return Err(Malformed::Unnamed { line });
        };

        let mut tier = crate::Capability::Baseline;
        let mut defines = BTreeMap::new();
        for word in words {
            if let Some(tag) = word.strip_prefix('@') {
                tier = crate::Capability::from_tag(tag).ok_or_else(|| Malformed::Untiered {
                    line,
                    tag: tag.to_owned(),
                })?;
                continue;
            }
            let Some((key, value)) = word.split_once('=') else {
                return Err(Malformed::Undefined {
                    line,
                    what: word.to_owned(),
                });
            };
            defines.insert(key.to_owned(), value.to_owned());
        }

        out.push(Variant {
            entrypoint: entrypoint.to_owned(),
            tier,
            defines,
            line,
        });
    }
    Ok(out)
}

fn directive_body<'a>(raw: &'a str, keyword: &str) -> Option<&'a str> {
    let rest = raw.trim_start().strip_prefix("//")?.trim_start();
    let rest = rest.strip_prefix(keyword)?;

    if rest.is_empty() || rest.starts_with(char::is_whitespace) {
        Some(rest.trim())
    } else {
        None
    }
}

pub fn expand(
    text: &str,
    defines: &BTreeMap<String, String>,
    includes: &dyn Fn(&str) -> Option<String>,
) -> Result<String, Malformed> {
    let mut prelude = String::new();

    prelude.push_str("// Generated by kernels-wgpu's expander. Do not edit.\n");
    for (key, value) in defines {
        if is_number(value) {
            prelude.push_str(&format!("const {key} = {value};\n"));
        } else {
            prelude.push_str(&format!(
                "// define {key}={value} (not a number: no const)\n"
            ));
        }
    }

    let mut body = String::new();
    let mut seen = Vec::new();
    splice(text, defines, includes, &mut seen, &mut body)?;

    Ok(hoist_enables(&prelude, &body))
}

fn hoist_enables(prelude: &str, body: &str) -> String {
    let mut enables: Vec<&str> = Vec::new();
    let mut rest = String::with_capacity(body.len());

    for line in body.lines() {
        if line.trim_start().starts_with("enable ") {
            let line = line.trim();
            if !enables.contains(&line) {
                enables.push(line);
            }
            continue;
        }
        rest.push_str(line);
        rest.push('\n');
    }

    let mut out = String::with_capacity(prelude.len() + rest.len() + 64);
    for enable in enables {
        out.push_str(enable);
        out.push('\n');
    }
    out.push_str(prelude);
    out.push_str(&rest);
    out
}

fn is_number(value: &str) -> bool {
    let body = value
        .trim_end_matches(['u', 'i', 'f'])
        .trim_start_matches('-');
    if let Some(hex) = body.strip_prefix("0x").or_else(|| body.strip_prefix("0X")) {
        return !hex.is_empty() && hex.chars().all(|c| c.is_ascii_hexdigit());
    }
    !body.is_empty()
        && body.chars().all(|c| c.is_ascii_digit() || c == '.')
        && body.chars().filter(|c| *c == '.').count() <= 1
        && body.chars().any(|c| c.is_ascii_digit())
}

fn splice(
    text: &str,
    defines: &BTreeMap<String, String>,
    includes: &dyn Fn(&str) -> Option<String>,
    seen: &mut Vec<String>,
    out: &mut String,
) -> Result<(), Malformed> {
    struct Frame {
        live: bool,
        taken: bool,
        elsed: bool,
        line: usize,
    }
    let mut stack: Vec<Frame> = Vec::new();

    for (at, raw) in text.lines().enumerate() {
        let line = at + 1;
        let live = stack.iter().all(|f| f.live);

        if let Some(cond) = directive_body(raw, "#if") {
            let take = live && truth(cond, defines, line)?;
            stack.push(Frame {
                live: take,
                taken: take,
                elsed: false,
                line,
            });
            continue;
        }
        if let Some(cond) = directive_body(raw, "#elif") {
            let Some(frame) = stack.last_mut() else {
                return Err(Malformed::Unopened {
                    line,
                    what: "//#elif".to_owned(),
                });
            };
            if frame.elsed {
                return Err(Malformed::AfterElse { line });
            }

            let outer = stack[..stack.len() - 1].iter().all(|f| f.live);
            let frame = stack.last_mut().expect("just checked");
            let take = outer && !frame.taken && truth(cond, defines, line)?;
            frame.live = take;
            frame.taken |= take;
            continue;
        }
        if directive_body(raw, "#else").is_some() {
            let outer = stack
                .len()
                .checked_sub(1)
                .map(|n| stack[..n].iter().all(|f| f.live));
            let Some(outer) = outer else {
                return Err(Malformed::Unopened {
                    line,
                    what: "//#else".to_owned(),
                });
            };
            let frame = stack
                .last_mut()
                .expect("outer proved the stack is not empty");
            if frame.elsed {
                return Err(Malformed::AfterElse { line });
            }
            frame.elsed = true;
            frame.live = outer && !frame.taken;
            frame.taken = true;
            continue;
        }
        if directive_body(raw, "#endif").is_some() {
            if stack.pop().is_none() {
                return Err(Malformed::Unopened {
                    line,
                    what: "//#endif".to_owned(),
                });
            }
            continue;
        }
        if let Some(path) = directive_body(raw, "#include") {
            if !live {
                continue;
            }
            let path = path.trim().trim_matches('"').to_owned();

            if seen.contains(&path) {
                continue;
            }
            let Some(body) = includes(&path) else {
                return Err(Malformed::Unincluded { line, path });
            };
            seen.push(path);
            splice(&body, defines, includes, seen, out)?;
            continue;
        }
        if let Some(what) = unknown_directive(raw) {
            return Err(Malformed::Unknown { line, what });
        }

        if live {
            out.push_str(raw);
            out.push('\n');
        }
    }

    match stack.first() {
        Some(frame) => Err(Malformed::Unclosed { line: frame.line }),
        None => Ok(()),
    }
}

fn unknown_directive(raw: &str) -> Option<String> {
    let rest = raw.trim_start().strip_prefix("//")?;
    let rest = rest.strip_prefix('#')?;
    let word: String = rest
        .chars()
        .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
        .collect();
    Some(format!("//#{word}"))
}

fn truth(cond: &str, defines: &BTreeMap<String, String>, line: usize) -> Result<bool, Malformed> {
    let mut any = false;
    for clause in cond.split("||") {
        let mut all = true;
        for term in clause.split("&&") {
            all &= term_truth(term.trim(), defines, line)?;
        }
        any |= all;
    }
    Ok(any)
}

fn term_truth(
    term: &str,
    defines: &BTreeMap<String, String>,
    line: usize,
) -> Result<bool, Malformed> {
    let uncondition = || Malformed::Uncondition {
        line,
        cond: term.to_owned(),
    };

    if let Some(rest) = term.strip_prefix('!') {
        return Ok(!term_truth(rest.trim(), defines, line)?);
    }
    if let Some(rest) = term.strip_prefix("defined") {
        let key = rest
            .trim()
            .strip_prefix('(')
            .and_then(|r| r.strip_suffix(')'))
            .ok_or_else(uncondition)?;
        return Ok(defines.contains_key(key.trim()));
    }

    for op in ["==", "!=", ">=", "<=", ">", "<"] {
        let Some((key, want)) = term.split_once(op) else {
            continue;
        };
        let key = key.trim();
        let want = want.trim();
        let Some(have) = defines.get(key) else {
            return Ok(op == "!=");
        };
        let (Ok(have), Ok(want)) = (have.trim().parse::<i64>(), want.parse::<i64>()) else {
            return match op {
                "==" => Ok(have.trim() == want),
                "!=" => Ok(have.trim() != want),
                _ => Err(uncondition()),
            };
        };
        return Ok(match op {
            "==" => have == want,
            "!=" => have != want,
            ">=" => have >= want,
            "<=" => have <= want,
            ">" => have > want,
            "<" => have < want,
            _ => unreachable!("the list above is the list matched here"),
        });
    }

    Err(uncondition())
}

