use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

#[path = "src/capability.rs"]
#[allow(dead_code)]
mod capability;

use crate::capability::Capability;

#[path = "src/preproc.rs"]
#[allow(dead_code)]
mod preproc;

fn main() {
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=src/capability.rs");
    println!("cargo::rerun-if-changed=src/preproc.rs");
    println!("cargo::rerun-if-changed=kernels");

    let root = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").expect("cargo sets this"));
    let kernels = root.join("kernels");
    let out = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets this"));

    println!("cargo::metadata=kernels_dir={}", kernels.display());
    println!(
        "cargo::metadata=include={}",
        kernels.join("common").display()
    );

    let mut sources = Vec::new();
    collect(&kernels, &kernels, &mut sources);
    sources.sort();

    check_tiers(&sources);

    let mut generated = String::new();
    generated.push_str(
        "// Generated by kernels-wgpu's build.rs. Do not edit.\n\
         /// Every `.wgsl` under `kernels/`, by its path relative to it.\n\
         pub static SOURCES: &[(&str, &str)] = &[\n",
    );
    for (rel, abs) in &sources {
        println!("cargo::rerun-if-changed={}", abs.display());
        generated.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            rel,
            abs.display().to_string()
        ));
    }
    generated.push_str("];\n");

    std::fs::write(out.join("sources.rs"), generated).expect("OUT_DIR is writable");
}

fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else if path.extension().is_some_and(|e| e == "wgsl") {
            let rel = path
                .strip_prefix(root)
                .expect("walked down from root")
                .to_string_lossy()
                .replace('\\', "/");
            out.push((rel, path));
        }
    }
}

fn check_tiers(sources: &[(String, PathBuf)]) {
    let mut baseline: BTreeSet<String> = BTreeSet::new();
    let mut tiered: BTreeMap<String, (String, usize, &'static str)> = BTreeMap::new();
    let mut seen: BTreeMap<(String, &'static str), (String, usize)> = BTreeMap::new();

    for (rel, abs) in sources {
        let text = std::fs::read_to_string(abs).expect("the file was just listed");
        let variants =
            preproc::instantiations(&text).unwrap_or_else(|why| panic!("kernels/{rel}: {why}"));

        for variant in variants {
            let tag = variant.tier.tag();
            let key = (variant.entrypoint.clone(), tag);
            if let Some((where_, line)) = seen.get(&key) {
                panic!(
                    "kernels/{rel}:{}: `{}` is already declared at tier `{tag}` \
                     by kernels/{where_}:{line}. Two variants under one name \
                     means one of them never runs, and which one is whichever \
                     the tree was walked in.",
                    variant.line, variant.entrypoint,
                );
            }
            seen.insert(key, (rel.clone(), variant.line));

            if variant.tier == capability::Capability::Baseline {
                baseline.insert(variant.entrypoint);
            } else {
                tiered.insert(variant.entrypoint, (rel.clone(), variant.line, tag));
            }
        }
    }

    let orphans: Vec<_> = tiered
        .iter()
        .filter(|(entrypoint, _)| !baseline.contains(*entrypoint))
        .map(|(entrypoint, (rel, line, tag))| {
            format!("  kernels/{rel}:{line}: `{entrypoint}` @{tag}")
        })
        .collect();

    assert!(
        orphans.is_empty(),
        "a tier is an ADDITIONAL variant of an entrypoint that already exists, \
         never a new entrypoint and never a replacement. These have no baseline \
         beneath them, so they resolve on an adapter with the feature and on no \
         other:\n{}\n",
        orphans.join("\n"),
    );
}
