//! Embed the shader tree, and refuse a tree the table does not describe.
//!
//! ## What this does NOT do
//!
//! It does not compile anything. That is the point of the backend: `naga` is a
//! Rust WGSL front end and it ships inside `wgpu`, so a module is compiled by
//! the process that dispatches it. There is no `glslc` to shell out to, no
//! `nvcc`, no `OUT_DIR/spv`, and so no `native` feature to gate any of it.
//!
//! What is left is two jobs a build script is genuinely the right place for.
//!
//! **One: put the tree in the binary.** `include_str!` needs a literal path, so
//! something has to enumerate `kernels/**/*.wgsl` and write the literals out.
//! The generated `sources.rs` is a `&[(&str, &str)]` of (path relative to
//! `kernels/`, text), which `src/source.rs` includes. A deployment then carries
//! its shaders in its binary rather than beside it — see that module's own
//! notes on why the sibling backends' directory handoff is worth not copying.
//!
//! **Two: fail the build on a tree that disagrees with itself.** Specifically
//! on an ORPHAN TIER: a `@fp16` or `@subgroup` variant of an entrypoint that
//! has no baseline. `capability.rs` states why that invariant matters — the
//! failure it prevents is an entrypoint that resolves on the author's GPU and
//! on no other — and it is enforced twice, here and in `tests/entrypoints.rs`,
//! because a build failure is what a person sees first and a test is what runs
//! on the machines that have no adapter at all.
//!
//! The directive parser is `src/preproc.rs`, pulled in with `#[path]` rather
//! than reimplemented. `kernels-vulkan` has two parsers for this — one in its
//! build script and one in a Python audit — and calls the duplication
//! intentional, on the grounds that the build and the audit must not be able to
//! disagree. They cannot disagree here because there is one of them.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

// The vocabulary the directives are written in. `#[path]` and not a dependency:
// a build script cannot depend on the crate it builds, and a second copy of
// `Capability` would be a second answer to "what tiers are there".
#[path = "src/capability.rs"]
#[allow(dead_code)]
mod capability;

// `preproc.rs` names the tier as `crate::Capability`, which is what it is
// inside the library. Re-stating it at this script's own root is what lets one
// file serve both without an `#[cfg]` in it.
use crate::capability::Capability;

#[path = "src/preproc.rs"]
#[allow(dead_code)]
mod preproc;

fn main() {
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=src/capability.rs");
    println!("cargo::rerun-if-changed=src/preproc.rs");
    println!("cargo::rerun-if-changed=kernels");

    let root = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").expect("cargo sets this"));
    let kernels = root.join("kernels");
    let out = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets this"));

    // Published for parity with the two siblings, and for a tool that wants the
    // tree on disk. Nothing in the serving path reads either.
    println!("cargo::metadata=kernels_dir={}", kernels.display());
    println!(
        "cargo::metadata=include={}",
        kernels.join("common").display()
    );

    let mut sources = Vec::new();
    collect(&kernels, &kernels, &mut sources);
    sources.sort();

    check_tiers(&sources);

    let mut generated = String::new();
    generated.push_str(
        "// Generated by kernels-wgpu's build.rs. Do not edit.\n\
         /// Every `.wgsl` under `kernels/`, by its path relative to it.\n\
         pub static SOURCES: &[(&str, &str)] = &[\n",
    );
    for (rel, abs) in &sources {
        // `rerun-if-changed=kernels` covers the directory, but a nested file
        // edited without a directory mtime change has been known to slip past
        // it on some filesystems. Naming each file is cheap and exact.
        println!("cargo::rerun-if-changed={}", abs.display());
        generated.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            rel,
            abs.display().to_string()
        ));
    }
    generated.push_str("];\n");

    std::fs::write(out.join("sources.rs"), generated).expect("OUT_DIR is writable");
}

/// Every `.wgsl` under `dir`, as (path relative to `root`, absolute path).
fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else if path.extension().is_some_and(|e| e == "wgsl") {
            let rel = path
                .strip_prefix(root)
                .expect("walked down from root")
                .to_string_lossy()
                // A generated Rust literal must not carry a Windows separator.
                .replace('\\', "/");
            out.push((rel, path));
        }
    }
}

/// Fail the build on a tier with no baseline beneath it.
///
/// Panicking is the right shape for a build script: the message is what the
/// person who added the directive reads, and it names the file and the line.
fn check_tiers(sources: &[(String, PathBuf)]) {
    let mut baseline: BTreeSet<String> = BTreeSet::new();
    let mut tiered: BTreeMap<String, (String, usize, &'static str)> = BTreeMap::new();
    let mut seen: BTreeMap<(String, &'static str), (String, usize)> = BTreeMap::new();

    for (rel, abs) in sources {
        let text = std::fs::read_to_string(abs).expect("the file was just listed");
        let variants =
            preproc::instantiations(&text).unwrap_or_else(|why| panic!("kernels/{rel}: {why}"));

        for variant in variants {
            let tag = variant.tier.tag();
            let key = (variant.entrypoint.clone(), tag);
            if let Some((where_, line)) = seen.get(&key) {
                panic!(
                    "kernels/{rel}:{}: `{}` is already declared at tier `{tag}` \
                     by kernels/{where_}:{line}. Two variants under one name \
                     means one of them never runs, and which one is whichever \
                     the tree was walked in.",
                    variant.line, variant.entrypoint,
                );
            }
            seen.insert(key, (rel.clone(), variant.line));

            if variant.tier == capability::Capability::Baseline {
                baseline.insert(variant.entrypoint);
            } else {
                tiered.insert(variant.entrypoint, (rel.clone(), variant.line, tag));
            }
        }
    }

    let orphans: Vec<_> = tiered
        .iter()
        .filter(|(entrypoint, _)| !baseline.contains(*entrypoint))
        .map(|(entrypoint, (rel, line, tag))| {
            format!("  kernels/{rel}:{line}: `{entrypoint}` @{tag}")
        })
        .collect();

    assert!(
        orphans.is_empty(),
        "a tier is an ADDITIONAL variant of an entrypoint that already exists, \
         never a new entrypoint and never a replacement. These have no baseline \
         beneath them, so they resolve on an adapter with the feature and on no \
         other:\n{}\n",
        orphans.join("\n"),
    );
}
