"""Worker entry for the cuda_native driver.

Lifecycle:
  * Resolves the `pie_driver_cuda` binary, the HF snapshot dir, and writes a
    startup TOML the binary consumes.
  * Spawns the binary and waits for its `READY {json}` line on stdout.
  * Reports the resulting `DriverCapabilities` to the engine via `ready_queue`.
  * Serves the control-plane RPC channel (ping / page-swap / adapter ops). The
    fast path (`fire_batch`) is served directly by the binary on `/pie_shmem`;
    pie_runtime is the client.

M1.1 note: the binary's READY values are config-derived stubs; model loading
and actual forward-pass execution are introduced in M1.2 / M1.3.
"""

from __future__ import annotations

import json
import os
import shutil
import signal
import socket
import struct
import subprocess
import threading

from . import control_protocol as _proto
from dataclasses import asdict
from pathlib import Path

import msgpack

from pie._runtime import RpcServer
from pie.capabilities import DriverCapabilities

from .config import CudaNativeDriverConfig


# `pie/server.py` calls `worker.calculate_topology(world_size, tp_degree)`
# during bootstrap to plan process groups. cuda_native is single-rank-only
# in M1; reuse the trivial implementation from pie_driver.
def calculate_topology(world_size: int, tp_degree: int) -> list[list[int]]:
    if world_size % tp_degree != 0:
        raise ValueError(
            f"World size ({world_size}) must be divisible by TP degree ({tp_degree})")
    num_groups = world_size // tp_degree
    return [list(range(g * tp_degree, (g + 1) * tp_degree)) for g in range(num_groups)]


# =============================================================================
# Binary discovery
# =============================================================================


def _resolve_binary(override: str) -> Path:
    """Find `pie_driver_cuda`. Checks override, env var, $PATH, then a sibling
    build tree. Raises with a useful hint if nothing works."""
    if override:
        p = Path(override).expanduser()
        if p.is_file() and os.access(p, os.X_OK):
            return p
        raise FileNotFoundError(f"binary_path={override!r} is not an executable file")

    if env := os.environ.get("PIE_CUDA_DRIVER_BIN"):
        p = Path(env).expanduser()
        if p.is_file() and os.access(p, os.X_OK):
            return p

    if which := shutil.which("pie_driver_cuda"):
        return Path(which)

    # Fall back to a relative search: this file lives at
    # <repo>/pie/src/pie_driver_cuda_native/worker.py, so the build tree is
    # at <repo>/driver/cuda/build/bin/pie_driver_cuda.
    candidate = Path(__file__).resolve().parents[3] / "driver" / "cuda" / "build" / "bin" / "pie_driver_cuda"
    if candidate.is_file() and os.access(candidate, os.X_OK):
        return candidate

    raise FileNotFoundError(
        "pie_driver_cuda binary not found. Build it via\n"
        "    cd driver/cuda && cmake -S . -B build -G Ninja && cmake --build build\n"
        "or set $PIE_CUDA_DRIVER_BIN to its path."
    )


# =============================================================================
# TOML emission
# =============================================================================


def _write_startup_toml(
    *,
    driver_cfg: CudaNativeDriverConfig,
    hf_repo: str,
    snapshot_dir: str,
    device: str,
    out_path: Path,
) -> None:
    """Emit the binary's startup config. Format matches `driver/cuda/dev.toml`."""
    # Minimal escaping — these strings are filesystem paths and HF repo IDs;
    # they don't contain double quotes in practice.
    # Shmem geometry MUST match pie/runtime/src/device.rs constants
    # (SHMEM_NAME, SHMEM_SLOTS, SHMEM_REQ_BUF, SHMEM_RESP_BUF, SHMEM_SPIN_US).
    # Mismatched stride → ShmemClient::open() returns "shmem geometry
    # mismatch", the runtime can never fire_batch into the binary, and
    # the engine reports "handled 0 requests" while the bench hangs (#109).
    # resp_buf in particular: 8 MiB is the runtime's chosen default to fit
    # full-vocab Distribution probes (≈2.6 MiB on 150K-vocab) + spec-mode
    # multi-slot tails. 4 MiB is too tight under those workloads.
    lines = [
        "# Auto-generated by pie_driver_cuda_native; do not edit.",
        "",
        "[shmem]",
        'name = "/pie_shmem"',
        "num_slots = 8",
        "req_buf = 4194304",
        "resp_buf = 8388608",
        "spin_us = 10000",
        "",
        "[model]",
        f'hf_repo = "{hf_repo}"',
        f'snapshot_dir = "{snapshot_dir}"',
        f'device = "{device}"',
        f'dtype = "{driver_cfg.weight_dtype}"',
        "",
        "[batching]",
        f"kv_page_size = {driver_cfg.kv_page_size}",
        f"max_batch_tokens = {driver_cfg.max_batch_tokens}",
        f"max_batch_size = {driver_cfg.max_batch_size}",
        f"max_num_kv_pages = {driver_cfg.max_num_kv_pages}",
        f"swap_pool_size = {driver_cfg.swap_pool_size}",
        "",
    ]
    out_path.write_text("\n".join(lines))


# =============================================================================
# READY handshake
# =============================================================================


class _ReadyTimeout(RuntimeError):
    pass


def _wait_for_ready(proc: subprocess.Popen, timeout_s: float) -> dict:
    """Read lines from `proc.stdout` until a `READY {json}` arrives. Anything
    else is forwarded to stderr so the user sees binary log output during
    startup. Raises if the binary exits, times out, or emits malformed JSON."""
    import selectors

    if proc.stdout is None:
        raise RuntimeError("subprocess has no stdout pipe")

    sel = selectors.DefaultSelector()
    sel.register(proc.stdout, selectors.EVENT_READ)

    deadline_remaining = timeout_s
    import time
    start = time.monotonic()

    while True:
        if proc.poll() is not None:
            raise RuntimeError(
                f"pie_driver_cuda exited before READY (rc={proc.returncode})"
            )

        elapsed = time.monotonic() - start
        if elapsed > timeout_s:
            raise _ReadyTimeout(f"no READY within {timeout_s:.1f}s")

        events = sel.select(timeout=min(0.5, timeout_s - elapsed))
        if not events:
            continue

        line = proc.stdout.readline()
        if not line:
            continue
        line = line.rstrip("\n")

        if line.startswith("READY "):
            return json.loads(line[len("READY "):])

        # Pass through pre-READY chatter so users see startup progress.
        print(f"[pie_driver_cuda] {line}")


def _stream_stderr(proc: subprocess.Popen) -> None:
    """Relay the binary's stderr into our own stderr (best-effort)."""
    if proc.stderr is None:
        return
    for raw in iter(proc.stderr.readline, ""):
        if not raw:
            break
        print(f"[pie_driver_cuda] {raw.rstrip()}")


# =============================================================================
# RPC dispatch (control plane only)
# =============================================================================


class _CtrlClient:
    """Wrapper-side client for the C++ binary's control socket.

    Sends `copy_d2h / copy_h2d / copy_d2d / copy_h2h` over a `SOCK_SEQPACKET`
    socketpair. Wire format and method tags live in
    `control_protocol.py` (kept in sync with `control_socket.hpp`).
    """

    # Method tags re-exported on the class for backwards-compat with
    # call sites that already use `_CtrlClient.METHOD_COPY_*`.
    METHOD_COPY_D2H = _proto.METHOD_COPY_D2H
    METHOD_COPY_H2D = _proto.METHOD_COPY_H2D
    METHOD_COPY_D2D = _proto.METHOD_COPY_D2D
    METHOD_COPY_H2H = _proto.METHOD_COPY_H2H

    def __init__(self, sock: socket.socket):
        self._sock = sock
        self._lock = threading.Lock()

    def call(self, method: int, layer: int,
             srcs: list[int], dsts: list[int]) -> int:
        if len(srcs) != len(dsts):
            raise ValueError(f"src/dst length mismatch: {len(srcs)} vs {len(dsts)}")
        n = len(srcs)
        msg = (_proto.HEADER.pack(method, layer, n, 0)
               + struct.pack(f"<{n}I", *srcs)
               + struct.pack(f"<{n}I", *dsts))
        with self._lock:
            self._sock.send(msg)
            resp = self._sock.recv(_proto.RESPONSE_SIZE)
        if len(resp) != _proto.RESPONSE_SIZE:
            raise RuntimeError(f"control socket truncated response ({len(resp)} bytes)")
        return struct.unpack("<I", resp)[0]


def _make_methods(ctrl: "_CtrlClient | None" = None):
    """Returns the cold-path method table. The fast path (`fire_batch`) is
    served by the binary; we never see it on this channel."""

    def _ping(**_):
        return {"ok": True}

    def _query(**_):
        # `pie_driver` exposes lightweight engine introspection here; for now
        # we return a placeholder until M2 wires queries through to the binary.
        return {"driver": "cuda_native", "implemented": False}

    def _unimplemented(name):
        def stub(**_):
            raise RuntimeError(
                f"{name!r} is not yet implemented in cuda_native (planned for M6+)"
            )
        return stub

    def _require_ctrl(name):
        if ctrl is None:
            raise RuntimeError(
                f"{name!r} called but cuda_native was started without a "
                "control socket — set swap_pool_size > 0 and re-spawn the "
                "driver to enable KV-page swap."
            )

    # Pie's runtime passes argument names that mirror `pie_driver`:
    #   swap_out / swap_in / copy_d2h / copy_h2d → phys_ids, slots
    #   copy_d2d                                → src_phys_ids, dst_phys_ids
    #   copy_h2h                                → src_slots, dst_slots
    # We don't pass a layer index — the binary applies copies across every
    # layer (matches Python's per-layer index_copy_ loop).
    def _swap_out(**kw):
        _require_ctrl("copy_d2h")
        srcs, dsts = list(kw["phys_ids"]), list(kw["slots"])
        s = ctrl.call(_CtrlClient.METHOD_COPY_D2H, 0, srcs, dsts)
        if s != 0: raise RuntimeError(f"copy_d2h failed: status={s}")
        return {"ok": True}

    def _swap_in(**kw):
        _require_ctrl("copy_h2d")
        # pie_driver's H2D contract: `phys_ids` are GPU destinations,
        # `slots` are CPU sources. Wire format is (src, dst) — flip.
        srcs, dsts = list(kw["slots"]), list(kw["phys_ids"])
        s = ctrl.call(_CtrlClient.METHOD_COPY_H2D, 0, srcs, dsts)
        if s != 0: raise RuntimeError(f"copy_h2d failed: status={s}")
        return {"ok": True}

    def _copy_d2d(**kw):
        _require_ctrl("copy_d2d")
        srcs = list(kw["src_phys_ids"])
        dsts = list(kw["dst_phys_ids"])
        s = ctrl.call(_CtrlClient.METHOD_COPY_D2D, 0, srcs, dsts)
        if s != 0: raise RuntimeError(f"copy_d2d failed: status={s}")
        return {"ok": True}

    def _copy_h2h(**kw):
        _require_ctrl("copy_h2h")
        srcs = list(kw.get("src_slots", kw.get("src_phys_ids", [])))
        dsts = list(kw.get("dst_slots", kw.get("dst_phys_ids", [])))
        s = ctrl.call(_CtrlClient.METHOD_COPY_H2H, 0, srcs, dsts)
        if s != 0: raise RuntimeError(f"copy_h2h failed: status={s}")
        return {"ok": True}

    return {
        "ping": _ping,
        "query": _query,
        "fire_batch": _unimplemented("fire_batch"),  # never hit; defensive
        "embed_image": _unimplemented("embed_image"),
        "initialize_adapter": _unimplemented("initialize_adapter"),
        "update_adapter": _unimplemented("update_adapter"),
        "load_adapter": _unimplemented("load_adapter"),
        "save_adapter": _unimplemented("save_adapter"),
        "swap_out_pages": _swap_out,
        "swap_in_pages":  _swap_in,
        "copy_d2h": _swap_out,
        "copy_h2d": _swap_in,
        "copy_d2d": _copy_d2d,
        "copy_h2h": _copy_h2h,
    }


def _run_rpc_loop(
    server: RpcServer,
    stop_event: threading.Event,
    methods: dict,
) -> None:
    """Mirror of pie_driver's leader loop on the cold path."""
    SPIN_US = 10_000
    POLL_TIMEOUT_MS = 200

    while not stop_event.is_set():
        try:
            req = server.poll_busy(SPIN_US, POLL_TIMEOUT_MS)
        except RuntimeError as e:
            # SIGTERM/SIGINT interrupts the underlying recv() with EINTR.
            # If shutdown was requested, treat as graceful exit; otherwise
            # re-raise so genuine IPC errors aren't swallowed.
            if stop_event.is_set() or "Interrupted" in str(e):
                break
            raise
        if req is None:
            continue
        request_id, method, payload, _send_walltime_us = req

        try:
            args = msgpack.unpackb(payload)
            fn = methods.get(method)
            if fn is None:
                response = msgpack.packb(f"Method not found: {method}")
                server.respond(request_id, response, 0)
                continue

            if isinstance(args, dict):
                result = fn(**args)
            elif isinstance(args, (list, tuple)):
                result = fn(*args)
            else:
                result = fn(args)

            response = msgpack.packb(result)
            server.respond(request_id, response, 0)
        except Exception as e:
            import traceback
            print(f"[cuda_native RPC Error] {method}: {e}\n{traceback.format_exc()}")
            response = msgpack.packb(str(e))
            server.respond(request_id, response, 0)


# =============================================================================
# worker_main
# =============================================================================


def worker_main(
    local_rank: int,
    world_size: int,
    devices: list[str],
    master_port: int,
    model_config: dict,
    driver_config: dict,
    group_topology: list[list[int]],
    ready_queue,
):
    """Entry point invoked via `mp.spawn` from `pie/server.py`."""
    if world_size != 1 or len(group_topology) != 1 or len(group_topology[0]) != 1:
        raise NotImplementedError(
            "cuda_native driver supports tensor_parallel_size=1 only "
            "(M9 will add multi-rank). Use the `native` driver for TP>1."
        )

    rank = local_rank
    device = devices[rank] if rank < len(devices) else "cuda:0"

    # Parse driver_config dict into the typed dataclass.
    driver_cfg = CudaNativeDriverConfig(**{
        k: v for k, v in driver_config.items()
        if k in CudaNativeDriverConfig.__dataclass_fields__
    })

    # Resolve binary + HF snapshot.
    binary = _resolve_binary(driver_cfg.binary_path)

    from pie_driver.hf_utils import get_hf_snapshot_dir  # reuse existing logic
    hf_repo = model_config["hf_repo"]
    snapshot_dir = get_hf_snapshot_dir(hf_repo)

    # Emit startup TOML.
    pie_home = Path(os.environ.get("PIE_HOME", Path.home() / ".pie"))
    pie_home.mkdir(parents=True, exist_ok=True)
    toml_path = pie_home / f"cuda-driver-{os.getpid()}.toml"
    _write_startup_toml(
        driver_cfg=driver_cfg,
        hf_repo=hf_repo,
        snapshot_dir=str(snapshot_dir),
        device=device,
        out_path=toml_path,
    )

    # Create the control-plane RPC server *before* spawning so we have a
    # `server_name` ready for the ready_queue handshake.
    server = RpcServer.create()
    server_name = server.server_name()

    # Set up the wrapper↔binary control socket if KV swap is enabled.
    # SOCK_SEQPACKET keeps message boundaries, which simplifies the binary's
    # serve loop (one recv = one request).
    ctrl_client = None
    binary_argv = [str(binary), "--config", str(toml_path)]
    # Optional: opt into CUDA-graph capture for the decode forward pass
    # via `PIE_CUDA_GRAPHS=1` in the driver's environment. Off by
    # default while we shake out correctness on more workloads.
    if os.environ.get("PIE_CUDA_GRAPHS") == "1":
        binary_argv.append("--cuda-graphs")
    pass_fds: tuple = ()
    wrapper_sock = None
    binary_sock = None
    if driver_cfg.swap_pool_size > 0:
        wrapper_sock, binary_sock = socket.socketpair(
            socket.AF_UNIX, socket.SOCK_SEQPACKET)
        # Make sure the binary's fd survives exec().
        os.set_inheritable(binary_sock.fileno(), True)
        binary_argv += ["--control-fd", str(binary_sock.fileno())]
        pass_fds = (binary_sock.fileno(),)
        ctrl_client = _CtrlClient(wrapper_sock)

    # Spawn the binary.
    proc = subprocess.Popen(
        binary_argv,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        bufsize=1,  # line-buffered
        pass_fds=pass_fds,
    )
    if binary_sock is not None:
        # Parent doesn't need the binary's end of the pair anymore.
        binary_sock.close()

    try:
        caps_dict = _wait_for_ready(proc, driver_cfg.ready_timeout_s)
    except Exception:
        proc.kill()
        proc.wait(timeout=2)
        raise

    # Start a thread to drain stderr for the lifetime of the process.
    stderr_thread = threading.Thread(
        target=_stream_stderr, args=(proc,), daemon=True
    )
    stderr_thread.start()

    # Translate the binary's capability JSON into DriverCapabilities. Fields
    # the binary couldn't fill in (M1.1 stub) come back as zeros / empty
    # strings; M1.2+ will populate them.
    caps = DriverCapabilities(
        total_pages=int(caps_dict.get("total_pages", 0)),
        kv_page_size=int(caps_dict.get("kv_page_size", driver_cfg.kv_page_size)),
        swap_pool_size=int(caps_dict.get("swap_pool_size", 0)),
        max_batch_tokens=int(caps_dict.get("max_batch_tokens", driver_cfg.max_batch_tokens)),
        max_batch_size=int(caps_dict.get("max_batch_size", driver_cfg.max_batch_size)),
        arch_name=str(caps_dict.get("arch_name", "")),
        vocab_size=int(caps_dict.get("vocab_size", 0)),
        max_model_len=int(caps_dict.get("max_model_len", 0)),
        activation_dtype=str(caps_dict.get("activation_dtype", driver_cfg.weight_dtype)),
        snapshot_dir=str(caps_dict.get("snapshot_dir") or snapshot_dir),
    )

    ready_queue.put((rank, server_name, caps))

    stop_event = threading.Event()
    methods = _make_methods(ctrl_client)

    def _shutdown(signum, frame):
        stop_event.set()

    signal.signal(signal.SIGTERM, _shutdown)
    signal.signal(signal.SIGINT, _shutdown)

    try:
        _run_rpc_loop(server, stop_event, methods)
    finally:
        # Close control socket so the binary's serve thread sees EOF.
        if wrapper_sock is not None:
            try:
                wrapper_sock.close()
            except Exception:
                pass
        # Tear the binary down cleanly.
        if proc.poll() is None:
            proc.send_signal(signal.SIGTERM)
            try:
                proc.wait(timeout=driver_cfg.shutdown_timeout_s)
            except subprocess.TimeoutExpired:
                proc.kill()
                proc.wait(timeout=2)
        try:
            toml_path.unlink(missing_ok=True)
        except Exception:
            pass
