//! The launch ABI, generated from the table.
//!
//! A launcher here is an authored C++ function in a nested namespace, with no
//! `extern "C"` anywhere and default arguments on several of them. None of
//! that is callable from outside C++, and the reason is not that it should be
//! — it is that the SIGNATURE was never written down. `KernelSig` carried
//! everything about a kernel except how to call it, and the argument list
//! lived only in the header and, informally, in the model bodies that call it.
//!
//! [`KernelSig::operands`] is that list. Given it, this module emits both
//! halves of a flat ABI:
//!
//! * [`emit_c_shim`] — one `extern "C"` function per row, which includes the
//!   real header and forwards to the real launcher;
//! * [`emit_rust_bindings`] — the matching `unsafe extern "C"` block.
//!
//! ## Why generating it is the proof
//!
//! The shim is not a translation layer that has to be trusted. It CALLS the
//! function it describes, with the header in scope, so C++ overload
//! resolution decides whether the row is right — arity, order, constness and
//! width, all at once, all as compile errors. A hand-written shim would need
//! a golden and a mutation suite to reach a weaker version of the same
//! claim; this needs neither, because a wrong row does not build.
//!
//! It also settles the crate's own invariant, that every symbol in the table
//! resolves to exactly one declaration and every declaration has exactly one
//! row. The first half becomes a tautology here. The second half is still a
//! count, and it is what the pilot found: `rope.hpp` declared twelve
//! launchers against ten rows.
//!
//! ## Scope
//!
//! Rows with an empty operand list are SKIPPED, not emitted as nullary. The
//! table is being filled a family at a time and an unstated row must not be
//! mistaken for a stated one — see [`KernelSig::operands`].

use kernels::KernelSig;

/// The prefix every generated entry point carries.
///
/// One underscore, not two: `__` anywhere in an identifier is reserved to the
/// implementation in C++, so the obvious `pie_k_rope__rope_bf16` spelling for
/// a `::`-joined path is not ours to use. [`entry_name`] therefore joins with
/// a single `_` and [`emit_c_shim`] rejects a collision rather than letting
/// two rows quietly share an entry point.
pub const PREFIX: &str = "pie_k_";

/// The `extern "C"` name for a row: the prefix, then the symbol with its
/// namespace separators flattened.
pub fn entry_name(symbol: &str) -> String {
    format!("{PREFIX}{}", symbol.replace("::", "_"))
}

/// The rows this module can emit — those that have stated their operands.
fn stated(table: &[&'static [KernelSig]]) -> Vec<&'static KernelSig> {
    table
        .iter()
        .flat_map(|t| t.iter())
        .filter(|k| !k.operands.is_empty())
        .collect()
}

/// The C++ namespace a symbol names, under this crate's root.
fn cpp_path(symbol: &str) -> String {
    format!("::pie_cuda_driver::kernels::{symbol}")
}

/// Emit the `extern "C"` forwarding shims for every stated row in `tables`.
///
/// `includes` are the headers the launchers are declared in, relative to
/// `csrc/src`. They are included by the generated TU, which is what makes
/// compiling it a proof of the rows.
///
/// Errors if two rows would produce the same entry point.
pub fn emit_c_shim(
    tables: &[&'static [KernelSig]],
    includes: &[&str],
) -> Result<String, String> {
    let rows = stated(tables);
    let mut seen: Vec<(String, &str)> = Vec::new();
    let mut out = String::new();

    out.push_str(
        "// GENERATED by kernels_cuda::abi::emit_c_shim -- do not edit.\n\
         //\n\
         // Each body forwards to the launcher its row describes, through a\n\
         // function pointer of the row's exact type. A function-pointer\n\
         // initialisation admits NO parameter conversions, which is why it is\n\
         // written this way rather than as a direct call: a direct call is\n\
         // checked by overload resolution, and overload resolution accepts\n\
         // `void*` where the callee takes `const void*`. That is the one\n\
         // direction a shim can be wrong in and still compile -- a row\n\
         // claiming a read-only operand is written -- and it is exactly the\n\
         // fact the table exists to carry.\n\n\
         #include <cstddef>\n\
         #include <cstdint>\n\
         #include <cstdio>\n\
         #include <cstdlib>\n\
         #include <exception>\n\
         #include <cuda_runtime.h>\n\n\
         // Every body is wrapped, and the reason is worth stating because the\n\
         // wrapper looks like belt-and-braces and is not. A launcher reports a\n\
         // capability it lacks by THROWING -- FlashInfer's dispatch macros end\n\
         // in `throw std::invalid_argument(...)` for an unsupported head dim or\n\
         // GQA group size. An exception crossing the C ABI boundary is\n\
         // undefined behaviour, and what it does in practice is unwind through\n\
         // Rust frames until the runtime aborts -- SIGABRT, no message, and a\n\
         // backtrace pointing at whatever destructor ran last. Twice that cost\n\
         // a debugger session to learn one sentence the launcher had already\n\
         // written down.\n\
         //\n\
         // So the process still dies, because these signatures have nowhere to\n\
         // put a failure -- but it dies SAYING WHY.\n\
         #define PIE_K_GUARD(expr)                                             \\\n\
             try { expr; } catch (const ::std::exception& e) {                 \\\n\
                 ::std::fprintf(stderr, \"[pie_k] %s: %s\\n\", __func__, e.what()); \\\n\
                 ::std::fflush(stderr);                                        \\\n\
                 ::std::abort();                                               \\\n\
             } catch (...) {                                                   \\\n\
                 ::std::fprintf(stderr, \"[pie_k] %s: unknown C++ exception\\n\", \\\n\
                                __func__);                                     \\\n\
                 ::std::fflush(stderr);                                        \\\n\
                 ::std::abort();                                               \\\n\
             }\n\n",
    );
    for inc in includes {
        out.push_str(&format!("#include \"{inc}\"\n"));
    }
    out.push('\n');

    for k in rows {
        let entry = entry_name(k.symbol);
        if let Some((_, other)) = seen.iter().find(|(e, _)| *e == entry) {
            return Err(format!(
                "entry point `{entry}` is claimed by both `{}` and `{other}`",
                k.symbol
            ));
        }
        seen.push((entry.clone(), k.symbol));

        let params = k
            .operands
            .iter()
            .map(|o| format!("    {} {}", o.ty.cpp(), o.name))
            .collect::<Vec<_>>()
            .join(",\n");
        let types = k
            .operands
            .iter()
            .map(|o| o.ty.cpp())
            .collect::<Vec<_>>()
            .join(", ");
        let args = k
            .operands
            .iter()
            .map(|o| o.name)
            .collect::<Vec<_>>()
            .join(", ");

        // A launcher that ANSWERS something keeps its answer: the shim
        // declares the forwarding pointer with the callee's real return
        // type, so a row that said `void` about a `bool` launcher is a
        // conversion C++ refuses rather than a value quietly dropped.
        let ret = if k.returns.is_empty() { "void" } else { k.returns };
        // The guard cannot wrap a `return` (the value would escape the
        // try block), so an answering launcher assigns first.
        let forward = if k.returns.is_empty() {
            format!("    PIE_K_GUARD(fwd({args}))")
        } else {
            format!(
                "    {ret} pie_k_answer{};\n    PIE_K_GUARD(pie_k_answer = fwd({args}))\n    return pie_k_answer;",
                ""
            )
        };
        out.push_str(&format!(
            "extern \"C\" {ret} {entry}(\n{params}) {{\n    \
             static {ret} (*const fwd)({types}) = &{};\n\
             {forward}\n}}\n\n",
            cpp_path(k.symbol),
        ));
    }
    Ok(out)
}

/// Emit the Rust `extern "C"` block matching [`emit_c_shim`].
///
/// Both sides read the same rows, so they cannot disagree with each other;
/// what the shim adds is that they cannot disagree with the C++ either.
pub fn emit_rust_bindings(tables: &[&'static [KernelSig]]) -> String {
    let mut out = String::from(
        "// GENERATED by kernels_cuda::abi::emit_rust_bindings -- do not edit.\n\
         //\n\
         // The other half of the same rows the C++ shim is generated from.\n\
         // A `nullable` operand is documented, not typed: making it an\n\
         // `Option<NonNull<_>>` here would change the calling convention of\n\
         // an `extern \"C\"` declaration for a fact the callee checks itself.\n\n\
         unsafe extern \"C\" {\n",
    );
    for k in stated(tables) {
        out.push_str(&format!("    /// `{}`\n", k.symbol));
        out.push_str(&format!("    pub unsafe fn {}(\n", entry_name(k.symbol)));
        for o in k.operands {
            let note = if o.nullable { "  // may be null" } else { "" };
            out.push_str(&format!("        {}: {},{note}\n", o.name, o.ty.rust()));
        }
        // The Rust side keeps the answer too. `bool` is the only
        // non-void return in the table and it is one byte on both
        // sides, which the layout suite already pins for `Ty::Bool`.
        if k.returns.is_empty() {
            out.push_str("    );\n");
        } else {
            let rust_ret = match k.returns {
                "bool" => "bool",
                other => panic!(
                    "abi: no Rust spelling for the return type `{other}`"
                ),
            };
            out.push_str(&format!("    ) -> {rust_ret};\n"));
        }
    }
    out.push_str("}\n");
    out
}

/// One record whose Rust mirror claims to have the C++ type's layout.
///
/// The offsets are the RUST side's, read off the mirror with `offset_of!`.
/// Nothing here is trusted: they are baked into a generated C++ file as
/// `static_assert`s and checked where both layouts are known. Neither side
/// states a number a human wrote down, so there is nothing to keep in sync.
pub struct Record {
    /// The fully-qualified C++ type.
    pub cpp: &'static str,
    /// `size_of` the Rust mirror.
    pub size: usize,
    /// `align_of` the Rust mirror.
    pub align: usize,
    /// Every field, in declaration order, with the Rust mirror's offset.
    pub fields: Vec<(&'static str, usize)>,
}

/// Build a [`Record`] from a `#[repr(C)]` mirror and the C++ type it claims.
///
/// The field list is written once, and both the offsets and the member-count
/// check are derived from it.
#[macro_export]
macro_rules! record {
    ($rust:ty => $cpp:literal { $($field:ident),* $(,)? }) => {
        $crate::abi::Record {
            cpp: $cpp,
            size: ::core::mem::size_of::<$rust>(),
            align: ::core::mem::align_of::<$rust>(),
            fields: ::std::vec![
                $((stringify!($field), ::core::mem::offset_of!($rust, $field))),*
            ],
        }
    };
}

/// Emit a translation unit that asserts each mirror's layout against the C++.
///
/// Three claims per record, and it takes all three to be exhaustive:
///
/// * `sizeof` and `alignof` — the shape of the whole;
/// * every field's `offsetof` — that each member is where the mirror puts it;
/// * a structured binding over the whole record — that there are no OTHER
///   members. This one is not decoration. A field added to the end of the C++
///   would land in the tail padding an aligned record already has, leave
///   `sizeof` unchanged, and disturb no existing offset, so the first two
///   claims would both still hold while the mirror silently stopped
///   describing the type. A structured binding names members positionally and
///   the count must match exactly, which is the only standard C++20 way to
///   say "and that is all of them".
pub fn emit_layout_assertions(records: &[Record], includes: &[&str]) -> String {
    let mut out = String::from(
        "// GENERATED by kernels_cuda::abi::emit_layout_assertions -- do not edit.\n\
         //\n\
         // The offsets are what the RUST mirrors compute for themselves. They\n\
         // are checked here because this is the only place both layouts are\n\
         // known; a mirror that disagrees does not compile.\n\n\
         #include <cstddef>\n\
         #include <cstdint>\n\n",
    );
    for inc in includes {
        out.push_str(&format!("#include \"{inc}\"\n"));
    }
    out.push('\n');

    for r in records {
        let tag = r.cpp.rsplit("::").next().unwrap_or(r.cpp);
        out.push_str(&format!(
            "static_assert(sizeof({0}) == {1},\n    \
             \"{0}: the mirror is {1} bytes\");\n\
             static_assert(alignof({0}) == {2},\n    \
             \"{0}: the mirror aligns to {2}\");\n",
            r.cpp, r.size, r.align
        ));
        for (name, off) in &r.fields {
            out.push_str(&format!(
                "static_assert(offsetof({0}, {1}) == {2},\n    \
                 \"{0}::{1} is not at {2}\");\n",
                r.cpp, name, off
            ));
        }
        let binds = r
            .fields
            .iter()
            .map(|(n, _)| format!("f_{n}"))
            .collect::<Vec<_>>();
        out.push_str(&format!(
            "\n// Exactly {} members, and no more.\nnamespace {{\ninline void \
             abi_member_count_{tag}() {{\n    {} v{{}};\n    auto& [{}] = v;\n{}}}\n}}\n\n",
            binds.len(),
            r.cpp,
            binds.join(", "),
            binds
                .iter()
                .map(|b| format!("    (void){b};\n"))
                .collect::<String>(),
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use kernels::Ty;

    /// The two emitters must describe the same operands in the same order, or
    /// the C++ side proves a signature the Rust side does not call.
    #[test]
    fn both_halves_are_emitted_from_the_same_rows() {
        let tables: &[&'static [KernelSig]] = &[crate::rope::KERNELS];
        let c = emit_c_shim(tables, &["rope/rope.hpp"]).expect("no collisions");
        let rs = emit_rust_bindings(tables);
        for k in stated(tables) {
            let entry = entry_name(k.symbol);
            assert!(c.contains(&entry), "{entry} missing from the shim");
            assert!(rs.contains(&entry), "{entry} missing from the bindings");
            for o in k.operands {
                assert!(c.contains(o.name), "{entry}: {} missing", o.name);
            }
        }
    }

    /// An unstated row is skipped rather than emitted as a nullary call.
    #[test]
    fn rows_that_have_not_stated_their_operands_are_not_emitted() {
        static UNSTATED: &[KernelSig] = &[kernels::kernel!(nothing "fam::not_yet_stated")];
        let c = emit_c_shim(&[UNSTATED], &[]).expect("no collisions");
        assert!(!c.contains("not_yet_stated"));
        assert!(!emit_rust_bindings(&[UNSTATED]).contains("not_yet_stated"));
    }

    /// `::` flattens to a single underscore -- `__` is reserved in C++.
    #[test]
    fn entry_points_avoid_the_reserved_double_underscore() {
        let name = entry_name("rope::rope_bf16");
        assert_eq!(name, "pie_k_rope_rope_bf16");
        assert!(!name.contains("__"));
    }

    /// Which makes a collision possible in principle, so it is refused.
    #[test]
    fn two_rows_may_not_claim_one_entry_point() {
        static CLASH: &[KernelSig] = &[
            kernels::kernel!(a "rope::a_b", operands = kernels::operands![stream: Stream]),
            kernels::kernel!(b "rope_a::b", operands = kernels::operands![stream: Stream]),
        ];
        let err = emit_c_shim(&[CLASH], &[]).expect_err("a collision is an error");
        assert!(err.contains("pie_k_rope_a_b"), "{err}");
    }

    /// `bool` is one byte in C++ and `int` is four. A binding that renders a
    /// flag as an `int` mis-lays every operand after it, and no compiler on
    /// either side would say so -- which is why `Bool` is its own kind.
    #[test]
    fn a_flag_stays_one_byte_wide_on_both_sides() {
        assert_eq!(Ty::Bool.cpp(), "bool");
        assert_eq!(Ty::Bool.rust(), "bool");
        assert_ne!(Ty::Bool.rust(), Ty::I32.rust());
    }
}

// ── THE GENERATED DISPATCH ─────────────────────────────────────────
//
// [`emit_c_shim`] proved a row describes its launcher. This is what the
// proof was FOR: given the types and the sources, the call itself is
// derivable, and the arm nobody has to write is the arm nobody can
// write wrong.
//
// What comes out is still a `switch`. C++ has no way to call a function
// with a dynamically built argument list without libffi or a trampoline
// per signature, and neither is worth the trade — so the switch stays
// and stops being HAND-written, which is the part that mattered. Adding
// a kernel becomes a row plus its sources; the dispatch regenerates.
//
// A row with any [`Source::Unbound`] operand is SKIPPED, on the same
// rule an unstated row is: a partial binding is not a binding, and a
// generator that filled the gaps with guesses would be the hand-written
// arm again with worse provenance.

use kernels::{Lit, Source};

// ── THE DISPATCH, GENERATED ───────────────────────────────────────────
//
// A C++ twin of this stood here and is gone with the driver it served.
// It emitted a `switch` into `model/declared/execute.hpp`; that tree is
// reference now, not running code, and a generator with no consumer is a
// second definition of the truth waiting to drift from the first.
//
// What it leaves behind is the SHAPE, which was right: one branch per row
// that states where its arguments come from, keyed by the symbol, with
// the arity the sources ask for as part of the match. A row that has not
// stated its sources is absent and belongs to a hand-written arm until it
// does — which is a row's work, not the driver's.
//
// The driver calls the FLAT entry point (`pie_k_*`), not the launcher —
// it is not C++ and cannot be, which is what `entry_name` and the
// compiled shim exist for. The shim earns its place twice over: it is
// the only way across, and compiling it is what PROVES a row, since C++
// overload resolution decides arity, order, constness and width all at
// once. Take it away and the rows become unchecked claims.
//
// `ins`/`outs`/`aux` are not three spans here. A lowered `Launch` hands
// the binder ONE run in stated order (inputs, outputs, then the weights
// the statement names), so a generated branch slices it, and the counts
// come off the op join.

/// An element count, spelled the width the row declares — or `None`,
/// which declines the whole row to a hand-written arm.
fn elem_count(e: &str, ty: kernels::Ty) -> Option<String> {
    Some(match ty {
        kernels::Ty::Usize => e.to_string(),
        kernels::Ty::I32 => format!("i32::try_from({e}).unwrap_or(0)"),
        kernels::Ty::U32 => format!("u32::try_from({e}).unwrap_or(0)"),
        kernels::Ty::I64 => format!("i64::try_from({e}).unwrap_or(0)"),
        // A count in any other width is a row this generator does not
        // understand, and the honest answer to that is the hand-written
        // arm — same rule as an unrecognised literal.
        _ => return None,
    })
}

/// The Rust expression that binds one operand.
///
/// `n_in` names the local holding the input count, so the slicing reads
/// the same in every branch. The casts mirror [`bind_expr`]'s and exist
/// for its reason: a slot is opaque and the entry point's parameter is
/// the row's declared width, so a substitution is a compile error rather
/// than a stride bug.
fn rust_bind_expr(op: &kernels::Operand) -> Option<String> {
    let e = match op.source {
        Source::Unbound => return None,
        Source::In(i) => format!("b.args[{i}].ptr"),
        Source::Out(i) => format!("b.args[n_in + {i}].ptr"),
        Source::Weight(i) => format!("b.args[n_in + n_out + {i}].ptr"),
        // Resolved ONCE before the match, so the guard below can test it
        // and so a branch does not re-look-up a name per launch.
        Source::WeightNamed => "w_named".to_string(),
        Source::Param(i) => format!("i32::try_from(spec.params[{i}]).unwrap_or(0)"),
        Source::ParamF32(i) => format!("f32::from_bits(spec.params[{i}])"),
        // Rows times a param — the MoE aligned path's route count, and
        // the one product that is neither an operand's extent nor a
        // load-time number.
        Source::RoutesOfParam(i) => format!(
            "rows.saturating_mul(i32::try_from(spec.params[{i}]).unwrap_or(0))"
        ),
        Source::Rows => "rows".to_string(),
        Source::OutRows(i) => format!("rows_of(b, n_in + {i}, rows)"),
        Source::InRows(i) => format!("rows_of(b, {i}, rows)"),
        Source::OutWidth(i) => format!("width_of(b, n_in + {i})"),
        Source::InWidth(i) => format!("width_of(b, {i})"),
        // The `max(1)` is inside `width_over`, on the driver's side, for
        // the reason `is_set` is: the row states which value's width to
        // read and what to divide it by, and what a zero divisor means is
        // the fire's business. The guard below refuses the branch outright
        // when the field is unset, so the `max(1)` is belt to that braces.
        Source::OutWidthOver(i, f) => format!("width_over(b, n_in + {i}, ctx.{f})"),
        Source::InWidthOver(i, f) => format!("width_over(b, {i}, ctx.{f})"),
        Source::OutWidthOverIn(o, i) => {
            format!("width_over(b, n_in + {o}, width_of(b, {i}))")
        }
        // An ACCESSOR, not a field: the driver decides whether its
        // per-layer vector falls back, filters or refuses, and the
        // generator's claim is only that the statement's layer is the
        // index.
        Source::CtxByLayer(f) => format!("ctx.{f}(b.layers.start as usize)"),
        // An element COUNT is a `usize` here and the row decides how wide
        // the launcher wants it — some spell `std::size_t`, some `int`.
        // The C++ emitter can cast unconditionally because C++ narrows
        // silently; this one has to ask the row, which is the better of
        // the two behaviours to have been forced into.
        Source::OutElements(i) => {
            elem_count(&format!("elems_of(b, n_in + {i}, rows)"), op.ty)?
        }
        Source::InElements(i) => {
            elem_count(&format!("elems_of(b, {i}, rows)"), op.ty)?
        }
        // A DIM is the plan's, not the binder's: an arg carries its row
        // width and nothing about the shape behind it. The join could
        // carry it, and until it does these rows stay hand-written —
        // which is the same rule `Source::Unbound` gets, for the same
        // reason (a partial binding is not a binding).
        Source::InDim(..) | Source::OutDim(..) => return None,
        // The fire's positions, which are TOKEN-ROWED like a value: a
        // rectangle starting partway in would rotate its own rows against
        // another rectangle's positions. Safe under the whole-fire guard
        // below, same as `In`/`Out`.
        Source::Positions => "ctx.positions".to_string(),
        // The enclosing guard's value, when a REGION launch declares no
        // result of its own. Which value that is depends on where the
        // statement SITS, and the Rust join does not carry the guard's
        // value yet — so these rows decline, like `InDim` does, and stay
        // with the arm that knows.
        Source::ResultOrRegion(..) => return None,
        // The KV pages are a Metal spelling. CUDA's launchers take a
        // `KvCacheLayerView` by value rather than two pointers, so a row that
        // states these is not one this emitter can generate — and saying so
        // is better than emitting a call that binds the wrong thing.
        Source::KvKeys | Source::KvValues => return None,
        // The fire's own tables, likewise a Metal spelling: CUDA's launchers
        // take them through a plan cache or a `KvCacheLayerView` rather than
        // as loose pointers.
        Source::TokenIds
        | Source::RequestOfToken
        | Source::KvPageIndices
        | Source::KvPageIndptr
        | Source::AttentionMask
        | Source::AttentionMaskEnabled
        | Source::KvHeadStride
        | Source::KvSeqStride
        | Source::KvPageSize
        | Source::KvWritePage
        | Source::KvWriteOffset
        | Source::RopeFrequencies => return None,
        // NOT in the decline above, and the difference is the launcher's
        // signature rather than the source's kind. The epilogue's gather
        // takes `const int32_t* row_indices` LOOSE — it is the one CUDA
        // launcher that wants a fire table as a bare pointer — so the
        // driver holds the pair on the ctx exactly as it holds
        // `peel_window`, and the row can say so.
        Source::SamplingIndices => "ctx.sampling_indices".to_string(),
        Source::RequestCount => "ctx.sampled_rows".to_string(),
        Source::Ctx(f) | Source::CtxNonZero(f) => format!("ctx.{f}"),
        // `g_of` is the driver's unwrap, and the guard below is what
        // makes it total: a branch binding a GDN field is emitted with
        // `gdn.is_some()` in its guard, so the only way here is through
        // that test.
        Source::Gdn(f) => format!("g_of(gdn).{f}"),
        // Both total by the same construction `g_of` is: the guard below
        // proves the context is there, and `kv_view` also proves the
        // layer is in range.
        Source::Attn(f) | Source::AttnNonZero(f) => format!("a_of(attn).{f}"),
        Source::KvLayerView => "kv_view(attn, b.layers.start as usize)".to_string(),
        // A NULL is returned fully typed and skips the cast step below:
        // that step turns a slot into the row's pointee, and a null has
        // no slot to turn. `null_mut().cast::<i32>()` leaves the original
        // `T` for an inference with nothing to work from, so the row's
        // own declared type produces the pointer directly.
        Source::Lit(Lit::Null) => {
            let rust = op.ty.rust();
            return Some(match rust.strip_prefix("*mut ") {
                Some(p) => format!("core::ptr::null_mut::<{p}>()"),
                None => format!("core::ptr::null::<{}>()", rust.strip_prefix("*const ")?),
            });
        }
        // The rest are values, and spelling a value is not parsing one.
        // A short-lived version of this function had a miniature C++
        // literal parser here, because the row held `"1.702f"` — which
        // is what a vocabulary looks like when it speaks one consumer's
        // language. The row holds `Lit::F32(1.702)` now and there is
        // nothing to parse.
        Source::Lit(Lit::Bool(v)) => v.to_string(),
        Source::Lit(Lit::F32(v)) => format!("{v}f32"),
        Source::Lit(Lit::I32(v)) => format!("{v}i32"),
    };
    Some(match op.ty {
        kernels::Ty::Buf => format!("({e}).cast_const()"),
        kernels::Ty::BufMut => e,
        kernels::Ty::I32s => format!("({e}).cast_const().cast::<i32>()"),
        kernels::Ty::U32s => format!("({e}).cast_const().cast::<u32>()"),
        kernels::Ty::U8s => format!("({e}).cast_const().cast::<u8>()"),
        kernels::Ty::I64s => format!("({e}).cast_const().cast::<i64>()"),
        kernels::Ty::F32s => format!("({e}).cast_const().cast::<f32>()"),
        kernels::Ty::I32sMut => format!("({e}).cast::<i32>()"),
        kernels::Ty::U32sMut => format!("({e}).cast::<u32>()"),
        kernels::Ty::U8sMut => format!("({e}).cast::<u8>()"),
        kernels::Ty::F32sMut => format!("({e}).cast::<f32>()"),
        kernels::Ty::U16s => format!("({e}).cast_const().cast::<u16>()"),
        kernels::Ty::U16sMut => format!("({e}).cast::<u16>()"),
        // An ARRAY OF DEVICE POINTERS: the bank of per-expert addresses
        // the routed GEMVs index. The bind is the same as a scalar
        // pointer's — the arg holds the bank's address — and only the
        // pointee type differs, which is a cast the row already states.
        // Spelled out rather than left to `_` because a `*mut c_void`
        // reaching a `*const *const i32` parameter is a compile error,
        // and the whole reason these casts are here is that the error is
        // better than a stride bug.
        kernels::Ty::BufArray => format!("({e}).cast_const().cast::<*const ::core::ffi::c_void>()"),
        kernels::Ty::BufArrayMut => format!("({e}).cast_const().cast::<*mut ::core::ffi::c_void>()"),
        kernels::Ty::BufArrayOut => format!("({e}).cast::<*const ::core::ffi::c_void>()"),
        kernels::Ty::BufArrayOutMut => format!("({e}).cast::<*mut ::core::ffi::c_void>()"),
        kernels::Ty::U8Array => format!("({e}).cast_const().cast::<*const u8>()"),
        kernels::Ty::I32Array => format!("({e}).cast_const().cast::<*const i32>()"),
        _ => e,
    })
}

/// One `match` arm per row whose operands are fully sourced, for the Rust
/// driver's `dispatch`.
///
/// Emitted as the body of a function returning `bool` — `true` when a
/// branch ran. A symbol with no generated branch, or one whose guard the
/// statement does not satisfy, returns `false` and the caller falls
/// through to the hand-written arm that knows the other spelling. That
/// fallthrough is the whole reason the guards are here rather than in the
/// arm: a generated branch must decline loudly, never guess.
pub fn emit_rust_dispatch(tables: &[&'static [KernelSig]]) -> String {
    let mut out = String::from(
        "// GENERATED by `kernels_cuda::abi::emit_rust_dispatch` — DO NOT EDIT.\n\
         //\n\
         // One branch per kernel! row that states both its operand types\n\
         // and where each argument comes from. A row missing either is\n\
         // absent here and belongs to a hand-written arm until it states\n\
         // them — which is a row's work, not the driver's.\n\
         //\n\
         // Keyed by the SYMBOL, like the C++ twin: the statement carries\n\
         // it, so there is no derived handle for the two to disagree on.\n\
         //\n\
         // A whole `match` EXPRESSION, not a run of arms: `include!` takes\n\
         // an expression or an item and never a pattern, so a file of bare\n\
         // arms has nowhere to be included from.\n\
         match b.kernel {\n",
    );
    for k in stated(tables) {
        let binds: Option<Vec<String>> =
            k.operands.iter().map(rust_bind_expr).collect();
        let Some(binds) = binds else { continue };

        // THE ARITY THE SOURCES ASK FOR, as part of the match — the C++
        // twin's reasoning verbatim. A branch that indexes `outs[1]` must
        // not run on a statement with one result; here the cost of not
        // checking is worse than a wrong answer, because the flat run
        // means an over-index reads the NEXT operand rather than faulting.
        let (mut need_in, mut need_out, mut need_w, mut need_ps) = (0u8, 0u8, 0u8, 0u8);
        for o in k.operands {
            match o.source {
                Source::In(i)
                | Source::InRows(i)
                | Source::InElements(i)
                | Source::InWidthOver(i, _)
                | Source::InWidth(i) => need_in = need_in.max(i + 1),
                Source::Out(i)
                | Source::OutRows(i)
                | Source::OutWidth(i)
                | Source::OutWidthOver(i, _)
                | Source::OutElements(i) => need_out = need_out.max(i + 1),
                Source::OutWidthOverIn(o, i) => {
                    need_out = need_out.max(o + 1);
                    need_in = need_in.max(i + 1);
                }
                Source::Weight(i) => need_w = need_w.max(i + 1),
                Source::Param(i) | Source::ParamF32(i) | Source::RoutesOfParam(i) => {
                    need_ps = need_ps.max(i + 1);
                }
                _ => {}
            }
        }
        // AN IN-PLACE ROW IS STAGED, and the staging is the row's too.
        //
        // `in_place = &[(0, 0)]` says result 0 aliases operand 0 — a fact
        // about the KERNEL, which reads and writes one buffer. The
        // lowering honours it where it can, and where it cannot (the
        // operand is live elsewhere) it assigns distinct buffers and
        // SOMETHING has to copy before the launch. That something used to
        // be a hand-written arm, and the row was skipped here for exactly
        // that reason.
        //
        // It is a convention, not a decision: `stage_d2d` is a no-op when
        // the two already alias, so emitting it is right in both the
        // honoured and the un-honoured case, and the driver owns what a
        // copy costs. Which is what makes this generatable at all —
        // nothing about WHICH buffers alias is knowable here, and nothing
        // about it needs to be.
        //
        // THE PAIR IS ARITY-DEPENDENT, and the runtime test is `lower.rs`'s
        // verbatim: *"a pair outside this statement's arity is not an
        // error: one symbol serves a q-only site and a q/k pair, and the
        // row states the widest form."* `mlp::chunked_swiglu_bf16` is that
        // case — `swiglu_aligned` states the block-major staging buffer as
        // its second operand and the activation must land on it, while
        // plain `swiglu` states one operand and there is nothing to alias.
        // So the indices are tested and not asserted, which is also why
        // they must NOT raise the arity guard: a row that demanded its
        // widest form would decline the narrow site outright.
        //
        // This is what the qwen3_5 A/B caught and gemma-4's did not:
        // `norm::residual_add_bf16` is in every layer of both, and the
        // difference was only whether that fire's buffer assignment
        // happened to alias. A bug whose reproduction depends on an
        // allocator is one to make structurally impossible, which is what
        // staging every in-place row from the row does.
        let mut stage = String::new();
        for (out, inp) in k.in_place {
            stage.push_str(&format!(
                "    if n_in > {inp} && n_out > {out} {{\n        \
                 stage_d2d(ctx, &b.rows, b.args[n_in + {out}], b.args[{inp}]);\n    }}\n"
            ));
        }
        // THE RECTANGLE, and the guard that is no longer here.
        //
        // `In`/`Out`/`Positions` used to bind a value's BASE, which is the
        // whole of the value only when the rectangle is the whole fire. A
        // peel splits a layer body in two and the second region starts at
        // `win_start`, so a launch over it must address rows `[win_start,
        // win_start + rows)`; at the base it wrote the PREFIX region's
        // rows, both regions wrote the same range, and the later one won.
        //
        // So every generated branch carried ` if b.rows.start == 0` and a
        // windowed rectangle fell through to a hand arm. That was the
        // honest answer and it was also the wrong shape: the hand arms had
        // the SAME bug and no guard, so the fallthrough was not a safety
        // net, it was a hiding place. Nothing noticed until a fire finally
        // peeled.
        //
        // The binder carries the window now (`resolve_arg_windowed`), and
        // it applies to the op join's placements as well as to the stated
        // args — one place, so a launch cannot read at the window and
        // write at the base. The C++ twin answered the same question by
        // putting the row in its context (`ArmCtx::row`); this answers it
        // one layer lower, where both consumers already meet.
        let mut guard = String::new();
        guard.push_str(&format!(
            " if n_in >= {need_in} && n_out >= {need_out} \
             && b.args.len() >= n_in + n_out + {need_w}"
        ));
        if need_ps > 0 {
            guard.push_str(&format!(" && spec.params.len() >= {need_ps}"));
        }
        // A NAME THE STORE LACKS IS DRIFT, not absence, and the right
        // answer is the hand arm's `UnknownWeight` rather than a null
        // bound into a kernel. So the branch declines and says nothing;
        // the fallthrough is what reports.
        if k.operands.iter().any(|o| o.source == Source::WeightNamed) {
            guard.push_str(" && !w_named.is_null()");
        }
        // A FIRE WITH NO RECURRENT LAYERS CARRIES NO GDN CONTEXT, so a
        // row reading one declines rather than reading a default. This
        // is what makes `g_of`'s unwrap total.
        if k.operands.iter().any(|o| matches!(o.source, Source::Gdn(_))) {
            guard.push_str(" && gdn.is_some()");
        }
        // A FIRE WITH NO ATTENTION CARRIES NO ATTENTION CONTEXT, and a
        // statement may name a layer the fire holds no cache for. Both
        // are tested here so `a_of` and `kv_view` are total.
        if k
            .operands
            .iter()
            .any(|o| matches!(o.source, Source::Attn(_) | Source::AttnNonZero(_)))
        {
            guard.push_str(" && attn.is_some()");
        }
        // AFTER `attn.is_some()`, and that order is load-bearing: `&&`
        // short-circuits left to right, so `a_of` is only reached once
        // the context is known to be there.
        for o in k.operands {
            if let Source::AttnNonZero(f) = o.source {
                guard.push_str(&format!(" && is_set(a_of(attn).{f})"));
            }
        }
        if k.operands.iter().any(|o| o.source == Source::KvLayerView) {
            guard.push_str(" && has_kv_layer(attn, b.layers.start as usize)");
        }
        // A field a family zeroes to say "not mine" — and a divisor,
        // which is the same test for a different reason: a width divided
        // by an unset field is not a smaller answer, it is a meaningless
        // one, and the two arms this replaced refused explicitly on it.
        //
        // DEDUPED, because two operands may divide by the same field —
        // `qk_rmsnorm_rope` reads a q head count and a kv head count off
        // one `head_dim` — and `is_set(x) && is_set(x)` is a guard that
        // makes a reader look for the difference.
        let mut guarded: Vec<&str> = Vec::new();
        for o in k.operands {
            if let Source::CtxNonZero(f)
            | Source::OutWidthOver(_, f)
            | Source::InWidthOver(_, f) = o.source
            {
                if guarded.contains(&f) {
                    continue;
                }
                guarded.push(f);
                // `is_set` rather than `!= 0`: the emitter does not know
                // the field's TYPE, and Rust will not compare an `f32` to
                // an integer literal. The driver implements it for the
                // kinds a context field can be, which puts the one thing
                // the generator cannot know on the side that knows it.
                guard.push_str(&format!(" && is_set(ctx.{f})"));
            }
        }

        out.push_str(&format!(
            "\"{}\"{} => {{\n{}    unsafe {{ {}(\n        {},\n    ) }};\n    true\n}}\n",
            k.symbol,
            guard,
            stage,
            format!("crate::launch::ffi::{}", entry_name(k.symbol)),
            binds.join(",\n        "),
        ));
    }
    // The fallthrough IS the answer for every symbol with no branch, and
    // it is spelled here rather than at the include site so that what
    // lands on disk is a complete expression — which `include!` requires,
    // and which also means the file can be read on its own.
    out.push_str("_ => false,\n}\n");
    out
}
