#!/usr/bin/env python3
"""Regenerates `src/schema.rs` from the driver's `model/config.hpp`.

The Rust normalizer has to produce the same 134 fields the C++ one does, under
the same names, with the same defaults — that is what makes the differential
test in `tests/differential.rs` a comparison rather than a coincidence. Writing
those declarations by hand once would be tedious; keeping them in step with a
header that gains fields every time an architecture lands would not happen.

So the struct is derived from the header, exactly as the C++ side's oracle
emitter is (`driver/cuda/tests/hf_config_dump/generate.py`), and both refuse to
run if a declaration goes uncaptured.

    python3 model/config/generate_schema.py
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
HEADER = ROOT / "driver" / "cuda" / "src" / "model" / "config.hpp"
OUT = pathlib.Path(__file__).with_name("src") / "schema.rs"

# One parser for both sides. It used to be copied here, and the same two bugs
# had to be found and fixed twice — see `hfconfig.py`.
sys.path.insert(0, str(ROOT / "driver" / "cuda" / "tests" / "hf_config_dump"))
from hfconfig import SIMPLE, parse as parse_structs  # noqa: E402

RUST_TYPE = {
    "int": "i32",
    "float": "f32",
    "bool": "bool",
    "std::string": "String",
    "std::vector<int>": "Vec<i32>",
    "std::vector<float>": "Vec<f32>",
    "std::vector<std::string>": "Vec<String>",
}

# C++ literal -> Rust literal, for in-class member initializers.
LITERAL = {
    "true": "true",
    "false": "false",
    "RopeScaling::None": "RopeScaling::None",
}


def rust_default(cxx_type, init):
    if init is None:
        # No in-class initializer. `parse_hf_config` assigns every such field
        # on every path (checked with -ftrivial-auto-var-init=pattern over the
        # whole corpus), so zero is a safe and reproducible baseline.
        return {
            "i32": "0",
            "f32": "0.0",
            "bool": "false",
            "String": "String::new()",
        }.get(cxx_type, "Vec::new()")
    init = init.strip()
    if init in LITERAL:
        return LITERAL[init]
    # C++ float suffixes: `32.f`, `1e-6f`, `1.f`.
    m = re.fullmatch(r"([0-9.eE+-]+)f", init)
    if m:
        value = m.group(1)
        return value if ("." in value or "e" in value.lower()) else value + ".0"
    if re.fullmatch(r"-?\d+", init):
        return init
    # Brace-initialized vectors: `{5, 11, 17}`, `{8, 6, 5, 4}`.
    m = re.fullmatch(r"\{([^}]*)\}", init)
    if m:
        items = [x.strip() for x in m.group(1).split(",") if x.strip()]
        return "vec![" + ", ".join(items) + "]"
    raise SystemExit(f"unhandled initializer {init!r}")


def render(structs, name):
    lines = [
        "#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]",
        f"pub struct {name} {{",
    ]
    defaults = []
    for f in structs[name]:
        cxx, field, init = f.type, f.name, f.init
        if cxx in RUST_TYPE:
            ty = RUST_TYPE[cxx]
        elif cxx == "RopeScaling":
            ty = "RopeScaling"
        elif cxx.startswith("std::optional<"):
            ty = f"Option<{cxx[len('std::optional<'):-1]}>"
        elif cxx in structs:
            ty = cxx
        else:
            raise SystemExit(f"unhandled type {cxx!r} for {name}.{field}")

        if ty.startswith("Option<"):
            default = "None"
        elif ty in structs:
            default = f"{ty}::default()"
        else:
            default = rust_default(ty, init)
        lines.append(f"    pub {field}: {ty},")
        defaults.append(f"            {field}: {default},")
    lines.append("}\n")
    lines.append(f"impl Default for {name} {{")
    lines.append("    fn default() -> Self {")
    lines.append("        Self {")
    lines.extend(defaults)
    lines.append("        }")
    lines.append("    }")
    lines.append("}\n")
    return "\n".join(lines)


PROLOGUE = '''//! The normalized shape of a HuggingFace `config.json`.
//!
//! Field for field the same as `pie_cuda_driver::HfConfig`
//! (`driver/cuda/src/model/config.hpp`), under the same names, because the
//! Rust normalizer in [`normalize`](crate::normalize) has to be checkable
//! against the C++ one it replaces. `tests/differential.rs` compares the two
//! over 55 real and synthetic configs; equality of these names is what lets
//! that comparison be mechanical.
//!
//! GENERATED by `generate_schema.py`. Regenerate rather than edit — a field
//! that drifts from the header drifts out of the comparison silently.
//!
//! Defaults match the header's in-class initializers where it has them, and
//! are zero otherwise. Zero is safe rather than arbitrary: `parse_hf_config`
//! assigns every field lacking an initializer on every path, checked over the
//! whole corpus with `-ftrivial-auto-var-init=pattern`.

use serde::{Deserialize, Serialize};

/// Which RoPE scaling rule a config selects, if any.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RopeScaling {
    #[default]
    None,
    Llama3,
    OriginalYarn,
}
'''


def main():
    structs, order = parse_structs(HEADER.read_text())
    parts = [PROLOGUE]
    for name in order:
        parts.append(render(structs, name))
    OUT.write_text("\n".join(parts))
    total = sum(len(f) for f in structs.values())
    print(f"{OUT.relative_to(ROOT)}: {total} fields across {len(structs)} structs")


if __name__ == "__main__":
    main()
