//! §45's parity gate: the four cuBLAS launchers, in Rust, byte for byte.
//!
//! # What is being compared, and why a hash of bytes is the whole of it
//!
//! `gemm/gemm.cpp` held four host launchers that contain no `__global__` and
//! never did. Each is an argument tuple handed to cuBLAS:
//! `act_x_wt_bf16_out_fp32` is one `cublasGemmEx`, `grouped_act_x_wt_bf16`
//! one `cublasGemmGroupedBatchedEx`, and the two MLA absorptions one
//! `cublasGemmStridedBatchedEx` each. §45 moved those tuples to
//! `bind::service`.
//!
//! So the arithmetic is not in question — the same library on the same device
//! does it either way. What IS in question is the tuple, and the failure this
//! kind of port makes is a transposition: an `lda` that should have been `K`,
//! a `strideA` that should have been the FULL bank pitch and not the slice's,
//! a `wv` offset counted in bytes where the C++ counted `__nv_bfloat16`. Each
//! of those produces a matrix full of entirely plausible numbers.
//!
//! That is why this compares the OUTPUT BYTES and nothing else. Not a norm,
//! not a relative error, not a cell count: FNV-1a over the whole output
//! buffer, per shape, against a transcript produced by
//! `tests/oracle/gemm_service/oracle.cu` — which is the four bodies **as they
//! were**, copied out of `git show 06074cbf3:.../gemm/gemm.cpp` and edited
//! only where they closed over a symbol that is not in the oracle. This
//! codebase has measured seven times that a wrong arm produces 99.83% of the
//! right answer, and that 34,273 of 55,200 cells can agree while the result
//! is a permutation. A tolerance would pass every one of those.
//!
//! # The inputs are hostile on purpose
//!
//! `env-audit` measured that benign inputs showed ZERO difference everywhere
//! while wide exponents exposed real ones and flipped two verdicts. The
//! generator below spreads the EXPONENT over 2^-17..2^18 with a uniform sign,
//! which is the regime where accumulation order decides the low bits, and
//! forces every seventeenth element to exact zero so the sparsity a real
//! activation has is represented. It is spelled identically in the oracle;
//! `the_generator_is_the_oracles` pins the first values it produces so the
//! two cannot drift apart silently and agree about nothing.
//!
//! # And the shapes vary in every axis, including a degenerate one
//!
//! A single shape certifies a near miss — a wrong 16x RMSNorm grid once wrote
//! 491,520 values past the rectangle with 0 differing inside it. So: M, N and
//! K each move independently, `N=1` and `K=1` are their own rows, `M=0` is
//! the empty rectangle, `group_count=0` and `tokens=0` and `heads=0` are the
//! three early returns the archive made before any launch and the port keeps,
//! and `beta != 0` is the accumulate form, which reads the output buffer and
//! therefore pins `ldc` as well as everything else.
//!
//! # Regenerating
//!
//! `tests/oracle/gemm_service/run.sh`. cuBLAS picks its kernel from the
//! device, so the transcript belongs to the GPU that made it; `build.rs`
//! compiles this tree for `sm_89` and nothing else, so that is not a new
//! constraint. A mismatch on the SAME GPU is a port bug, and the assertion
//! says which shape and shows both hashes.

#![allow(clippy::too_many_arguments)]

use std::ffi::c_void;

use cudarc::cublas::sys::{cublasContext, cublasCreate_v2, cublasDestroy_v2};
use cudarc::runtime::sys::{
    cudaDeviceSynchronize, cudaFree, cudaMalloc, cudaMemcpy, cudaMemcpyKind,
};
use driver_cuda::bind::{DispatchCtx, service};

/// The oracle's transcript, generated by `tests/oracle/gemm_service/run.sh`.
const GOLDEN: &str = include_str!("oracle/gemm_service/golden.txt");

// ── the generator, spelled as the oracle spells it ─────────────────────────

fn xs(s: &mut u64) -> u64 {
    *s ^= *s >> 12;
    *s ^= *s << 25;
    *s ^= *s >> 27;
    s.wrapping_mul(0x2545_F491_4F6C_DD1D)
}

/// bf16 with a WIDE exponent and a uniform sign. See the module header.
fn fill_bf16(n: usize, seed: u64) -> Vec<u16> {
    let mut s = seed | 1;
    let mut v = Vec::with_capacity(n);
    for i in 0..n {
        let u = xs(&mut s);
        if i % 17 == 16 {
            v.push(0);
            continue;
        }
        let sign = ((u >> 31) & 1) as u16;
        let exp = (110 + ((u >> 17) % 36)) as u16;
        let mant = ((u >> 3) & 0x7f) as u16;
        v.push((sign << 15) | (exp << 7) | mant);
    }
    v
}

fn fnv1a(bytes: &[u8]) -> u64 {
    let mut h = 0xcbf2_9ce4_8422_2325u64;
    for b in bytes {
        h = (h ^ u64::from(*b)).wrapping_mul(0x100_0000_01b3);
    }
    h
}

// ── device scratch ─────────────────────────────────────────────────────────

struct Dev(*mut c_void);

impl Dev {
    fn from_u16(host: &[u16]) -> Self {
        Self::raw(host.as_ptr().cast(), host.len() * 2)
    }
    fn from_f32(host: &[f32]) -> Self {
        Self::raw(host.as_ptr().cast(), host.len() * 4)
    }
    fn raw(src: *const c_void, bytes: usize) -> Self {
        let mut p: *mut c_void = std::ptr::null_mut();
        // SAFETY: `p` is a live out-parameter; `bytes.max(16)` keeps a
        // zero-length allocation legal so a degenerate shape still has a
        // distinct, freeable pointer to hand cuBLAS.
        unsafe {
            assert_eq!(cudaMalloc(&raw mut p, bytes.max(16)), cudaError::cudaSuccess);
            if bytes > 0 {
                assert_eq!(
                    cudaMemcpy(p, src, bytes, cudaMemcpyKind::cudaMemcpyHostToDevice),
                    cudaError::cudaSuccess
                );
            }
        }
        Self(p)
    }
    fn back_u16(&self, out: &mut [u16]) {
        self.back(out.as_mut_ptr().cast(), out.len() * 2);
    }
    fn back_f32(&self, out: &mut [f32]) {
        self.back(out.as_mut_ptr().cast(), out.len() * 4);
    }
    fn back(&self, dst: *mut c_void, bytes: usize) {
        if bytes == 0 {
            return;
        }
        // SAFETY: `dst` is the caller's live buffer of `bytes`, and `self.0`
        // was allocated with at least that many.
        unsafe {
            assert_eq!(
                cudaMemcpy(dst, self.0, bytes, cudaMemcpyKind::cudaMemcpyDeviceToHost),
                cudaError::cudaSuccess
            );
        }
    }
}

impl Drop for Dev {
    fn drop(&mut self) {
        // SAFETY: `self.0` came from `cudaMalloc` and is freed exactly once.
        unsafe {
            cudaFree(self.0);
        }
    }
}

use cudarc::runtime::sys::cudaError;

fn sync() {
    // SAFETY: no preconditions.
    unsafe {
        assert_eq!(cudaDeviceSynchronize(), cudaError::cudaSuccess);
    }
}

/// A `DispatchCtx` carrying nothing but the handle.
///
/// The four ports read `ctx.cublas` and no other field, which is the point of
/// injecting `ctx` uniformly: the emitter cannot know which arm wants what,
/// so it passes the fire's context and the arm takes what it needs. Every
/// other field here is the value that means "not stated".
fn ctx_of(cublas: *mut c_void) -> DispatchCtx {
    DispatchCtx {
        sampling_indices: std::ptr::null(),
        sampled_rows: 0,
        stream: std::ptr::null_mut(),
        cublas,
        eps: 0.0,
        rope_theta: 0.0,
        rope_theta_by_layer: Vec::new(),
        rotary_by_layer: Vec::new(),
        head_dim: 0,
        num_q_heads: 0,
        num_kv_heads: 0,
        vocab: 0,
        gate_second: false,
        rope_interleaved: false,
        token_ids: std::ptr::null_mut(),
        positions: std::ptr::null_mut(),
        final_logit_softcap: 0.0,
        ple_dim: 0,
        scales: std::collections::BTreeMap::new(),
        moe_norm_topk: false,
        moe_routed_scaling: 1.0,
        experts_per_token: 0,
        yarn: [0.0; 4],
        yarn_original_max: 0,
        glu_limit: 0.0,
        glu_alpha: 0.0,
        situ_beta: 0.0,
        situ_linear_beta: 0.0,
        wna16_group_size: 0,
        altup_streams: 0,
        altup_active: 0,
        altup_std_mult_by_layer: Vec::new(),
        lora: None,
        peel_window: std::ptr::null(),
        rows_total: 0,
        moe_ptrs: std::cell::Cell::new(None),
        moe_ptrs: std::cell::Cell::new(None),
    }
}

// ── the shape table, spelled as the oracle spells it ───────────────────────

const DENSE: &[(i32, i32, i32)] = &[
    (1, 1, 1),
    (1, 64, 128),
    (7, 33, 17),
    (64, 64, 64),
    (128, 1, 256),
    (3, 5, 1),
    (0, 64, 64),
    (33, 129, 65),
];

const GROUPED: &[(&[i32], i32, i32, f32)] = &[
    (&[1], 16, 32, 0.0),
    (&[1, 4, 9], 32, 48, 0.0),
    (&[1, 4, 9], 32, 48, 1.0),
    (&[2, 7, 1, 16], 17, 33, 0.0),
    (&[1, 1, 1, 1, 1, 1], 5, 7, 0.5),
    (&[], 8, 8, 0.0),
];

/// `(tokens, heads, qk_nope_dim, v_head_dim, kv_lora_rank)`.
const MLA: &[(i32, i32, i32, i32, i32)] = &[
    (1, 1, 1, 1, 1),
    (2, 4, 8, 16, 8),
    (5, 3, 7, 9, 11),
    (1, 16, 128, 128, 512),
    (0, 4, 8, 16, 8),
    (3, 0, 8, 16, 8),
    (9, 2, 3, 5, 7),
];

/// Builds the same transcript the oracle prints, from `bind::service`.
fn transcript() -> Vec<String> {
    let mut handle: *mut cublasContext = std::ptr::null_mut();
    // SAFETY: live out-parameter.
    unsafe {
        assert_eq!(
            cublasCreate_v2(&raw mut handle) as i32,
            0,
            "cublasCreate failed; is there a device?"
        );
    }
    let ctx = ctx_of(handle.cast());
    let mut rows = Vec::new();

    for &(m, n, k) in DENSE {
        let act = fill_bf16(
            (m * k) as usize,
            0x9E37_79B9_7F4A_7C15 ^ ((m as u64) << 32 | (n as u64) << 16 | k as u64),
        );
        let w = fill_bf16(
            (n * k) as usize,
            0xD1B5_4A32_D192_ED03 ^ ((k as u64) << 32 | (n as u64) << 16 | m as u64),
        );
        let mut y = vec![-1.0f32; (m * n) as usize];
        let dact = Dev::from_u16(&act);
        let dw = Dev::from_u16(&w);
        let dy = Dev::from_f32(&y);
        // SAFETY: every buffer above is live and at least the size the row
        // states, and nothing frees them before the sync below.
        unsafe {
            // §5 step 5 moved the body to `kernels_cuda_new::x::gemm`, where
            // it takes the handle directly instead of reading `ctx.cublas`.
            // The bytes this test hashes are the same bytes.
            let gctx = kernels_cuda_new::jit::Ctx::on(std::ptr::null_mut()).with_cublas(ctx.cublas);
            kernels_cuda_new::x::gemm::act_x_wt_bf16_out_fp32(
                &gctx,
                dact.0,
                dw.0,
                dy.0.cast(),
                m,
                n,
                k,
            )
            .ok()
            .expect("out_fp32 declines only on an empty extent");
        }
        sync();
        dy.back_f32(&mut y);
        let bytes: Vec<u8> = y.iter().flat_map(|v| v.to_ne_bytes()).collect();
        rows.push(format!("out_fp32 m={m} n={n} k={k} {:016x} {}", fnv1a(&bytes), bytes.len()));
    }

    for &(ms, n, k, beta) in GROUPED {
        let groups = ms.len() as i32;
        let total: usize = ms.iter().map(|m| (*m * n) as usize).sum();
        let mut yhost = fill_bf16(total, 0x27D4_EB2F_1656_67C5 ^ groups as u64);
        let mut off = 0usize;
        let mut keep: Vec<Dev> = Vec::new();
        let mut actp: Vec<*const c_void> = Vec::new();
        let mut wp: Vec<*const c_void> = Vec::new();
        let mut yp: Vec<*mut c_void> = Vec::new();
        for (i, &mi) in ms.iter().enumerate() {
            let a = fill_bf16(
                (mi * k) as usize,
                0x94D0_49BB_1331_11EB ^ ((i as u64) << 40) ^ ((n as u64) << 8) ^ k as u64,
            );
            let w = fill_bf16(
                (n * k) as usize,
                0xBF58_476D_1CE4_E5B9 ^ ((i as u64) << 40) ^ ((k as u64) << 8) ^ n as u64,
            );
            let da = Dev::from_u16(&a);
            let dw = Dev::from_u16(&w);
            let dy = Dev::from_u16(&yhost[off..off + (mi * n) as usize]);
            actp.push(da.0);
            wp.push(dw.0);
            yp.push(dy.0);
            keep.push(da);
            keep.push(dw);
            keep.push(dy);
            off += (mi * n) as usize;
        }
        // SAFETY: the three arrays are `groups` long and outlive the call;
        // `ms` is the host row-count array the row declares.
        unsafe {
            let gctx =
                kernels_cuda_new::jit::Ctx::on(std::ptr::null_mut()).with_cublas(handle.cast());
            kernels_cuda_new::x::gemm::grouped_act_x_wt_bf16(
                &gctx,
                actp.as_ptr(),
                wp.as_ptr(),
                yp.as_ptr(),
                ms.as_ptr(),
                groups,
                n,
                k,
                beta,
            )
            .ok()
            .expect("the grouped call declines only on group_count <= 0");
        }
        sync();
        let mut off = 0usize;
        for (gi, &mi) in ms.iter().enumerate() {
            let len = (mi * n) as usize;
            keep[gi * 3 + 2].back_u16(&mut yhost[off..off + len]);
            off += len;
        }
        let bytes: Vec<u8> = yhost.iter().flat_map(|v| v.to_ne_bytes()).collect();
        rows.push(format!(
            "grouped g={groups} n={n} k={k} beta={} {:016x} {}",
            fmt_g(beta),
            fnv1a(&bytes),
            bytes.len()
        ));
    }

    for &(tokens, heads, nope, vhead, lora) in MLA {
        let bank = (heads * (nope + vhead) * lora) as usize;
        let kvb = fill_bf16(
            bank.max(1),
            0x2545_F491_4F6C_DD1D ^ ((heads as u64) << 32) ^ ((nope as u64) << 16) ^ lora as u64,
        );
        {
            let q = fill_bf16(
                (tokens * heads * nope) as usize,
                0x9E37_79B1_85EB_CA87 ^ ((tokens as u64) << 32) ^ heads as u64,
            );
            let ob = (tokens * heads * lora) as usize;
            let mut out = vec![0xBEEFu16; ob.max(1)];
            let dq = Dev::from_u16(&q);
            let dk = Dev::from_u16(&kvb);
            let dout = Dev::from_u16(&out);
            // SAFETY: `kvb` is the whole bank, `q` and `out` the sizes the
            // doc comment states, all live across the sync below.
            unsafe {
                service::gemm_mla_absorb_q_to_latent_bf16(
                    &ctx, dq.0, dk.0, dout.0, tokens, heads, nope, vhead, lora,
                );
            }
            sync();
            dout.back_u16(&mut out);
            let bytes: Vec<u8> = out[..ob].iter().flat_map(|v| v.to_ne_bytes()).collect();
            rows.push(format!(
                "absorb_q t={tokens} h={heads} nope={nope} v={vhead} lora={lora} {:016x} {}",
                fnv1a(&bytes),
                bytes.len()
            ));
        }
        {
            let lat = fill_bf16(
                (tokens * heads * lora) as usize,
                0xFF51_AFD7_ED55_8CCD ^ ((tokens as u64) << 32) ^ lora as u64,
            );
            let ob = (tokens * heads * vhead) as usize;
            let mut out = vec![0xBEEFu16; ob.max(1)];
            let dl = Dev::from_u16(&lat);
            let dk = Dev::from_u16(&kvb);
            let dout = Dev::from_u16(&out);
            // SAFETY: as above, with the latent in place of `q_nope`.
            unsafe {
                service::gemm_mla_absorb_latent_to_v_bf16(
                    &ctx, dl.0, dk.0, dout.0, tokens, heads, nope, vhead, lora,
                );
            }
            sync();
            dout.back_u16(&mut out);
            let bytes: Vec<u8> = out[..ob].iter().flat_map(|v| v.to_ne_bytes()).collect();
            rows.push(format!(
                "absorb_v t={tokens} h={heads} nope={nope} v={vhead} lora={lora} {:016x} {}",
                fnv1a(&bytes),
                bytes.len()
            ));
        }
    }

    // SAFETY: created above, destroyed once.
    unsafe {
        cublasDestroy_v2(handle);
    }
    rows
}

/// `%g`, for the three betas in the table. Spelled out rather than derived so
/// the transcript's shape is visible in this file.
fn fmt_g(v: f32) -> String {
    if v == 0.0 {
        "0".into()
    } else if v == 1.0 {
        "1".into()
    } else {
        format!("{v}")
    }
}

/// The generator has not drifted from the oracle's.
///
/// Two files spelling the same recurrence is the one thing that can make
/// every other assertion here vacuous — if both sides computed on all-zeros
/// they would agree perfectly and prove nothing. So the first values are
/// pinned, and one of them is the forced zero.
#[test]
fn the_generator_is_the_oracles() {
    let v = fill_bf16(20, 0x9E37_79B9_7F4A_7C15);
    assert_eq!(v.len(), 20);
    assert_eq!(v[16], 0, "every 17th element is exactly zero");
    let nonzero = v.iter().filter(|x| **x != 0).count();
    assert_eq!(nonzero, 19, "only the forced zero is zero");
    // The exponent field must actually spread; a generator that emitted one
    // exponent would be the benign input `env-audit` measured as blind.
    let mut exps: Vec<u16> = v.iter().map(|x| (x >> 7) & 0xff).collect();
    exps.retain(|e| *e != 0);
    exps.sort_unstable();
    exps.dedup();
    assert!(
        exps.len() >= 10 && exps[0] <= 115 && *exps.last().unwrap() >= 140,
        "the exponents must be WIDE, got {exps:?}"
    );
}

/// The shape table exercises every axis the tuples are built from.
#[test]
fn the_shapes_are_not_one_shape() {
    let ms: std::collections::BTreeSet<i32> = DENSE.iter().map(|d| d.0).collect();
    let ns: std::collections::BTreeSet<i32> = DENSE.iter().map(|d| d.1).collect();
    let ks: std::collections::BTreeSet<i32> = DENSE.iter().map(|d| d.2).collect();
    assert!(ms.len() >= 5 && ns.len() >= 5 && ks.len() >= 5, "M, N and K each move");
    assert!(ms.contains(&0), "M=0 is the empty rectangle");
    assert!(ns.contains(&1) && ks.contains(&1), "N=1 and K=1 are degenerate axes");
    assert!(GROUPED.iter().any(|g| g.0.is_empty()), "group_count=0 is the archive's early return");
    assert!(GROUPED.iter().any(|g| g.3 != 0.0), "beta != 0 reads the output and so pins ldc");
    assert!(
        MLA.iter().any(|m| m.0 == 0) && MLA.iter().any(|m| m.1 == 0),
        "tokens=0 and heads=0 are both halves of the absorbs' early return"
    );
    assert!(
        MLA.iter().any(|m| m.2 != m.3 && m.3 != m.4 && m.2 != m.4 && m.0 != m.1),
        "at least one MLA shape has no two dims equal, so a swapped stride cannot hide"
    );
}

/// The four ports write the bytes the C++ wrote. Nothing else is checked.
#[test]
fn the_moved_cublas_calls_write_the_archives_bytes() {
    let want: Vec<&str> = GOLDEN.lines().filter(|l| !l.trim().is_empty()).collect();
    let got = transcript();
    assert_eq!(
        got.len(),
        want.len(),
        "the transcript has {} rows and the oracle's has {}; a truncated sweep \
         must not be able to pass",
        got.len(),
        want.len()
    );
    let mut bad = Vec::new();
    for (g, w) in got.iter().zip(&want) {
        if g != w {
            bad.push(format!("  rust: {g}\n  c++ : {w}"));
        }
    }
    assert!(
        bad.is_empty(),
        "{} of {} shapes disagree with the archive, BYTE FOR BYTE:\n{}\n\n\
         Each line is `<shape> <fnv1a64 of the output buffer> <bytes>`. Equal \
         byte counts with different hashes is a PERMUTATION -- a transposed \
         `lda`, a stride that took the slice pitch instead of the bank's, or \
         an offset counted in elements where the archive counted bytes. \
         Regenerate the right-hand side with tests/oracle/gemm_service/run.sh \
         only if the DEVICE changed.",
        bad.len(),
        want.len(),
        bad.join("\n")
    );
}

/// The one BEHAVIOURAL change §45 makes, and the measurement that says it
/// costs no answer.
///
/// `gemm::act_x_wt_bias_bf16` had a fused arm at `M == 1`: the warp-per-row
/// GEMV with the bias in its epilogue, one launch instead of two. The Rust
/// composition cannot take it — its steps are `gemm::act_x_wt_bf16` and then
/// `norm::add_bias_bf16` — so that launch is gone.
///
/// `gemv.hpp:25-28` claimed this costs nothing, because the epilogue computes
/// `out[n] = bf16(bf16(dot) + bias[n])` and *"the double rounding is
/// intentional"*. That was prose. `tests/oracle/gemm_service/bias_fold.cu`
/// runs the archive's own `gemv_bf16` both ways out of the real archive, on
/// hostile input, and this reads the RECORDED result — `bias_fold.txt` is
/// `include_str!`'d, so this test does not need the archive and still passes.
///
/// **The recorder no longer runs, and that is not this test failing.** §45.5
/// deleted `gemm/gemv.cu` and `gemm/gemv.hpp`: the kernels are now
/// `kernels-cuda-new/csrc/src/gemm/gemv.cuh`, carrying that same sentence at
/// both epilogues, and the host half is `driver_cuda::fire::gemv::gemv_bf16`.
/// Re-recording `bias_fold.txt` means rewriting `bias_fold.cu` against the
/// JIT unit — which is a Rust program now, not a `.cu`. The recorded bytes
/// stand until then; the kernels they came from were carried verbatim.
///
/// A refusal is recorded, not skipped: `gemv_bf16` returned `false` on a shape
/// or alignment it does not support and enqueued nothing (the Rust answers
/// `Gemv::Declined` with the reason named), and the two unsupported K here
/// (7 and 129, neither a multiple of 8) must be refused by BOTH sides or the
/// two paths have already diverged before any arithmetic.
#[test]
fn the_lost_bias_fusion_cost_no_answer() {
    const FOLD: &str = include_str!("oracle/gemm_service/bias_fold.txt");
    let rows: Vec<&str> = FOLD.lines().filter(|l| !l.trim().is_empty()).collect();
    assert!(rows.len() >= 8, "the fold sweep is {} rows", rows.len());
    let mut launched = 0usize;
    let mut values = 0usize;
    for r in &rows {
        if r.contains("REFUSED-BOTH") {
            continue;
        }
        assert!(
            !r.contains("REFUSAL-DISAGREES"),
            "one path launched and the other refused, which is a divergence \
             before any arithmetic: {r}"
        );
        let fused = r.split("fused=").nth(1).and_then(|s| s.split(' ').next());
        let split = r.split("split=").nth(1).and_then(|s| s.split(' ').next());
        assert_eq!(
            fused, split,
            "the fused epilogue and `gemv_bf16` + `add_bias_bf16` wrote \
             DIFFERENT BYTES: {r}\n`gemv.cuh`'s two epilogues say they are \
             bit-identical, and the composition in `bind::service` is built \
             on that sentence."
        );
        let differing: usize = r
            .split("differing=")
            .nth(1)
            .and_then(|s| s.split(' ').next())
            .and_then(|s| s.parse().ok())
            .expect("differing= count");
        assert_eq!(differing, 0, "{differing} cells differ: {r}");
        let n: usize = r.split("of ").nth(1).and_then(|s| s.trim().parse().ok()).expect("of <n>");
        launched += 1;
        values += n;
    }
    assert!(
        launched >= 5 && values >= 10_000,
        "only {launched} shapes launched over {values} values; a transcript \
         where everything refused would agree about nothing"
    );
}
