//! §45's parity gate: the four cuBLAS launchers, in Rust, byte for byte.
//!
//! # What is being compared, and why a hash of bytes is the whole of it
//!
//! `gemm/gemm.cpp` held four host launchers that contain no `__global__` and
//! never did. Each is an argument tuple handed to cuBLAS:
//! `act_x_wt_bf16_out_fp32` is one `cublasGemmEx`, `grouped_act_x_wt_bf16`
//! one `cublasGemmGroupedBatchedEx`, and the two MLA absorptions one
//! `cublasGemmStridedBatchedEx` each. §45 moved those tuples to
//! `bind::service`.
//!
//! So the arithmetic is not in question — the same library on the same device
//! does it either way. What IS in question is the tuple, and the failure this
//! kind of port makes is a transposition: an `lda` that should have been `K`,
//! a `strideA` that should have been the FULL bank pitch and not the slice's,
//! a `wv` offset counted in bytes where the C++ counted `__nv_bfloat16`. Each
//! of those produces a matrix full of entirely plausible numbers.
//!
//! That is why this compares the OUTPUT BYTES and nothing else. Not a norm,
//! not a relative error, not a cell count: FNV-1a over the whole output
//! buffer, per shape, against a transcript produced by
//! `tests/oracle/gemm_service/oracle.cu` — which is the four bodies **as they
//! were**, copied out of `git show 06074cbf3:.../gemm/gemm.cpp` and edited
//! only where they closed over a symbol that is not in the oracle. This
//! codebase has measured seven times that a wrong arm produces 99.83% of the
//! right answer, and that 34,273 of 55,200 cells can agree while the result
//! is a permutation. A tolerance would pass every one of those.
//!
//! # The inputs are hostile on purpose
//!
//! `env-audit` measured that benign inputs showed ZERO difference everywhere
//! while wide exponents exposed real ones and flipped two verdicts. The
//! generator below spreads the EXPONENT over 2^-17..2^18 with a uniform sign,
//! which is the regime where accumulation order decides the low bits, and
//! forces every seventeenth element to exact zero so the sparsity a real
//! activation has is represented. It is spelled identically in the oracle;
//! `the_generator_is_the_oracles` pins the first values it produces so the
//! two cannot drift apart silently and agree about nothing.
//!
//! # And the shapes vary in every axis, including a degenerate one
//!
//! A single shape certifies a near miss — a wrong 16x RMSNorm grid once wrote
//! 491,520 values past the rectangle with 0 differing inside it. So: M, N and
//! K each move independently, `N=1` and `K=1` are their own rows, `M=0` is
//! the empty rectangle, `group_count=0` and `tokens=0` and `heads=0` are the
//! three early returns the archive made before any launch and the port keeps,
//! and `beta != 0` is the accumulate form, which reads the output buffer and
//! therefore pins `ldc` as well as everything else.
//!
//! # Regenerating
//!
//! `tests/oracle/gemm_service/run.sh`. cuBLAS picks its kernel from the
//! device, so the transcript belongs to the GPU that made it; `build.rs`
//! compiles this tree for `sm_89` and nothing else, so that is not a new
//! constraint. A mismatch on the SAME GPU is a port bug, and the assertion
//! says which shape and shows both hashes.

#![allow(clippy::too_many_arguments)]

mod common;

use kernels::routine::Unbound;
use std::ffi::c_void;

use cudarc::cublas::sys::{cublasContext, cublasCreate_v2, cublasDestroy_v2};
use cudarc::runtime::sys::{
    cudaDeviceSynchronize, cudaFree, cudaMalloc, cudaMemcpy, cudaMemcpyKind,
};
// `service` WAS imported here. `bind::service`'s two `gemm_mla_absorb_*`
// entry points are gone -- their bodies are `gemm::absorb`'s now, called
// directly below -- and the import outlived them because a test target is not
// built by `cargo check`.
use driver_cuda::bind::DispatchCtx;
use kernels::routine::{Bank, In, Out, Weight};

/// The oracle's transcript, generated by `tests/oracle/gemm_service/run.sh`.
/// The archive's transcript from the card that first recorded it: **sm_89**.
const GOLDEN: &str = include_str!("oracle/gemm_service/golden.txt");

/// The same archive, same sweep, recorded on **sm_120** / CUDA 13.
///
/// Not a second opinion -- the same `oracle.cu`, rebuilt and re-run. cuBLAS
/// picks its kernel from the device, which this file's header has always
/// said, and two of the twenty-eight rows are where that shows: the two
/// `out_fp32` shapes big enough for cuBLAS to choose differently. The other
/// twenty-six are byte-identical across the two architectures.
///
/// Measured, not assumed. The archive on sm_120 answers
/// `d589370c91b26e7c` and `f79a364c99517d33` for those two, which is exactly
/// what `kernels_cuda::gemm` answers -- so the port is byte-faithful and the
/// disagreement is entirely between the two CARDS.
const GOLDEN_SM120: &str = include_str!("oracle/gemm_service/golden.sm120.txt");

/// The transcript recorded on the running device, and what it is called.
///
/// A golden per architecture rather than a tolerance or an exclusion list:
/// the rows that move are not approximately right, they are a different
/// legal summation order, and the only honest reference for a device is a
/// run of the archive ON that device. `run.sh` records one.
///
/// A device with no golden of its own falls back to sm_89's and says so, so
/// the twenty-six architecture-independent rows still get checked and the
/// failure names the two that cannot be.
fn golden_for_device() -> (&'static str, String, bool) {
    let cc = driver_cuda::device::Device::bind(0)
        .and_then(|d| d.compute_capability())
        .ok();
    match cc {
        Some((12, 0)) => (GOLDEN_SM120, "golden.sm120.txt (this device)".into(), true),
        Some((8, 9)) => (GOLDEN, "golden.txt (this device, sm_89)".into(), true),
        Some((a, b)) => (
            GOLDEN,
            format!("golden.txt -- recorded on sm_89, and this is sm_{a}{b}"),
            false,
        ),
        None => (GOLDEN, "golden.txt (device capability unreadable)".into(), false),
    }
}

// ── the generator, spelled as the oracle spells it ─────────────────────────

fn xs(s: &mut u64) -> u64 {
    *s ^= *s >> 12;
    *s ^= *s << 25;
    *s ^= *s >> 27;
    s.wrapping_mul(0x2545_F491_4F6C_DD1D)
}

/// bf16 with a WIDE exponent and a uniform sign. See the module header.
fn fill_bf16(n: usize, seed: u64) -> Vec<u16> {
    let mut s = seed | 1;
    let mut v = Vec::with_capacity(n);
    for i in 0..n {
        let u = xs(&mut s);
        if i % 17 == 16 {
            v.push(0);
            continue;
        }
        let sign = ((u >> 31) & 1) as u16;
        let exp = (110 + ((u >> 17) % 36)) as u16;
        let mant = ((u >> 3) & 0x7f) as u16;
        v.push((sign << 15) | (exp << 7) | mant);
    }
    v
}

fn fnv1a(bytes: &[u8]) -> u64 {
    let mut h = 0xcbf2_9ce4_8422_2325u64;
    for b in bytes {
        h = (h ^ u64::from(*b)).wrapping_mul(0x100_0000_01b3);
    }
    h
}

// ── device scratch ─────────────────────────────────────────────────────────

struct Dev(*mut c_void);

impl Dev {
    /// A device copy of a host array of DEVICE addresses.
    ///
    /// The array itself has to be on the device; what it holds already is.
    fn from_ptrs<T>(host: &[T]) -> Self {
        Self::raw(host.as_ptr().cast(), std::mem::size_of_val(host))
    }

    fn from_u16(host: &[u16]) -> Self {
        Self::raw(host.as_ptr().cast(), host.len() * 2)
    }
    fn from_f32(host: &[f32]) -> Self {
        Self::raw(host.as_ptr().cast(), host.len() * 4)
    }
    fn raw(src: *const c_void, bytes: usize) -> Self {
        let mut p: *mut c_void = std::ptr::null_mut();
        // SAFETY: `p` is a live out-parameter; `bytes.max(16)` keeps a
        // zero-length allocation legal so a degenerate shape still has a
        // distinct, freeable pointer to hand cuBLAS.
        unsafe {
            assert_eq!(cudaMalloc(&raw mut p, bytes.max(16)), cudaError::cudaSuccess);
            if bytes > 0 {
                assert_eq!(
                    cudaMemcpy(p, src, bytes, cudaMemcpyKind::cudaMemcpyHostToDevice),
                    cudaError::cudaSuccess
                );
            }
        }
        Self(p)
    }
    fn back_u16(&self, out: &mut [u16]) {
        self.back(out.as_mut_ptr().cast(), out.len() * 2);
    }
    fn back_f32(&self, out: &mut [f32]) {
        self.back(out.as_mut_ptr().cast(), out.len() * 4);
    }
    fn back(&self, dst: *mut c_void, bytes: usize) {
        if bytes == 0 {
            return;
        }
        // SAFETY: `dst` is the caller's live buffer of `bytes`, and `self.0`
        // was allocated with at least that many.
        unsafe {
            assert_eq!(
                cudaMemcpy(dst, self.0, bytes, cudaMemcpyKind::cudaMemcpyDeviceToHost),
                cudaError::cudaSuccess
            );
        }
    }
}

impl Drop for Dev {
    fn drop(&mut self) {
        // SAFETY: `self.0` came from `cudaMalloc` and is freed exactly once.
        unsafe {
            cudaFree(self.0);
        }
    }
}

use cudarc::runtime::sys::cudaError;

fn sync() {
    // SAFETY: no preconditions.
    unsafe {
        assert_eq!(cudaDeviceSynchronize(), cudaError::cudaSuccess);
    }
}

/// A `DispatchCtx` carrying nothing but the handle.
///
/// The four ports read `ctx.cublas` and no other field, which is the point of
/// injecting `ctx` uniformly: the emitter cannot know which arm wants what,
/// so it passes the fire's context and the arm takes what it needs. Every
/// other field here is the value that means "not stated".
fn ctx_of(cublas: *mut c_void) -> DispatchCtx {
    DispatchCtx {
        sampling_indices: std::ptr::null(),
        sampled_rows: 0,
        stream: std::ptr::null_mut(),
        cublas,
        eps: 0.0,
        rope_theta: 0.0,
        rope_theta_by_layer: Vec::new(),
        rotary_by_layer: Vec::new(),
        head_dim: 0,
        num_q_heads: 0,
        num_kv_heads: 0,
        vocab: 0,
        gate_second: false,
        rope_interleaved: false,
        token_ids: std::ptr::null_mut(),
        positions: std::ptr::null_mut(),
        final_logit_softcap: 0.0,
        ple_dim: 0,
        scales: std::collections::BTreeMap::new(),
        moe_norm_topk: false,
        moe_routed_scaling: 1.0,
        experts_per_token: 0,
        yarn: [0.0; 4],
        yarn_original_max: 0,
        glu_limit: 0.0,
        glu_alpha: 0.0,
        situ_beta: 0.0,
        situ_linear_beta: 0.0,
        wna16_group_size: 0,
        altup_streams: 0,
        altup_active: 0,
        altup_std_mult_by_layer: Vec::new(),
        lora: None,
        peel_window: std::ptr::null(),
        rows_total: 0,
        moe_ptrs: std::cell::Cell::new(None),
    }
}

// ── the shape table, spelled as the oracle spells it ───────────────────────

const DENSE: &[(i32, i32, i32)] = &[
    (1, 1, 1),
    (1, 64, 128),
    (7, 33, 17),
    (64, 64, 64),
    (128, 1, 256),
    (3, 5, 1),
    (0, 64, 64),
    (33, 129, 65),
];

const GROUPED: &[(&[i32], i32, i32, f32)] = &[
    (&[1], 16, 32, 0.0),
    (&[1, 4, 9], 32, 48, 0.0),
    (&[1, 4, 9], 32, 48, 1.0),
    (&[2, 7, 1, 16], 17, 33, 0.0),
    (&[1, 1, 1, 1, 1, 1], 5, 7, 0.5),
    (&[], 8, 8, 0.0),
];

/// `(tokens, heads, qk_nope_dim, v_head_dim, kv_lora_rank)`.
const MLA: &[(i32, i32, i32, i32, i32)] = &[
    (1, 1, 1, 1, 1),
    (2, 4, 8, 16, 8),
    (5, 3, 7, 9, 11),
    (1, 16, 128, 128, 512),
    (0, 4, 8, 16, 8),
    (3, 0, 8, 16, 8),
    (9, 2, 3, 5, 7),
];

/// Builds the same transcript the oracle prints, from `bind::service`.
fn transcript() -> Vec<String> {
    let mut handle: *mut cublasContext = std::ptr::null_mut();
    // SAFETY: live out-parameter.
    unsafe {
        assert_eq!(
            cublasCreate_v2(&raw mut handle) as i32,
            0,
            "cublasCreate failed; is there a device?"
        );
    }
    let ctx = ctx_of(handle.cast());
    // The absorb pair crossed to `x::gemm::absorb` and take the kernels
    // crate's `Ctx`, which carries the cuBLAS handle rather than a
    // `DispatchCtx`. Same handle and the same null stream, so the oracle
    // below compares the same work it always did.
    // SAFETY: the null stream is always live, and `handle` outlives this fn.
    let jit = unsafe {
        kernels_cuda::jit::Ctx::on(std::ptr::null_mut()).with_cublas(handle.cast())
    };
    let mut rows = Vec::new();

    for &(m, n, k) in DENSE {
        let act = fill_bf16(
            (m * k) as usize,
            0x9E37_79B9_7F4A_7C15 ^ ((m as u64) << 32 | (n as u64) << 16 | k as u64),
        );
        let w = fill_bf16(
            (n * k) as usize,
            0xD1B5_4A32_D192_ED03 ^ ((k as u64) << 32 | (n as u64) << 16 | m as u64),
        );
        let mut y = vec![-1.0f32; (m * n) as usize];
        let dact = Dev::from_u16(&act);
        let dw = Dev::from_u16(&w);
        let dy = Dev::from_f32(&y);
        // SAFETY: every buffer above is live and at least the size the row
        // states, and nothing frees them before the sync below.
        unsafe {
            // §5 step 5 moved the body to `kernels_cuda::gemm`, where
            // it takes the handle directly instead of reading `ctx.cublas`.
            // The bytes this test hashes are the same bytes.
            let gctx = kernels_cuda::jit::Ctx::on(std::ptr::null_mut()).with_cublas(ctx.cublas);
            kernels_cuda::gemm::act_x_wt_bf16_out_fp32(
                &gctx,
                // THE THREE EXTENTS ARE NOW TWO RECTANGLES, which is Stage 3
                // in one call site. `m`, `n` and `k` used to ride behind the
                // pointers as loose `i32`s that this test could pair up any
                // way it liked; the row's own shape says which is which now,
                // and a GEMM is exactly where getting that wrong is easiest
                // to do and hardest to see. `act` is m by k, the weight is n
                // by k, the result is m by n -- so `k` is the shared inner
                // extent and appears as the INPUT's width, while `n` appears
                // as the OUTPUT's. Swapping them once compiled.
                In { ptr: dact.0, rows: m, width: k },
                // `Weight(..)`, because the launcher's `w` is
                // `Weight<*const c_void>` now. This test hands over a
                // device buffer it filled itself rather than a bank out of
                // a fire, so the wrapper carries no information here -- what
                // it does carry is the fact that the row CROSSED, and this
                // call site is where a revert of that would first be felt.
                //
                // It stays shapeless while its neighbours gained rectangles,
                // and that is the same distinction `bind/table.rs:1265` draws
                // when it declines to mint a region for `Source::Slot(Kind::Weight, n)`:
                // *"a weight's shape is a fact about the MODEL that the
                // statement does not restate"*. n and k describe this buffer
                // perfectly well and neither of them is the statement's to
                // tell.
                kernels::routine::Weight { ptr: dw.0 },
                Out { ptr: dy.0.cast(), rows: m, width: n },
            )
            .ok()
            .expect(
                "out_fp32 declines only for a context with no cuBLAS handle, \
                 and this one has one -- the M=0 row is a legal empty \
                 rectangle that reaches cuBLAS and hashes zero bytes",
            );
        }
        sync();
        dy.back_f32(&mut y);
        let bytes: Vec<u8> = y.iter().flat_map(|v| v.to_ne_bytes()).collect();
        rows.push(format!("out_fp32 m={m} n={n} k={k} {:016x} {}", fnv1a(&bytes), bytes.len()));
    }

    for &(ms, n, k, beta) in GROUPED {
        let groups = ms.len() as i32;
        let total: usize = ms.iter().map(|m| (*m * n) as usize).sum();
        let mut yhost = fill_bf16(total, 0x27D4_EB2F_1656_67C5 ^ groups as u64);
        let mut off = 0usize;
        let mut keep: Vec<Dev> = Vec::new();
        let mut actp: Vec<*const c_void> = Vec::new();
        let mut wp: Vec<*const c_void> = Vec::new();
        let mut yp: Vec<*mut c_void> = Vec::new();
        for (i, &mi) in ms.iter().enumerate() {
            let a = fill_bf16(
                (mi * k) as usize,
                0x94D0_49BB_1331_11EB ^ ((i as u64) << 40) ^ ((n as u64) << 8) ^ k as u64,
            );
            let w = fill_bf16(
                (n * k) as usize,
                0xBF58_476D_1CE4_E5B9 ^ ((i as u64) << 40) ^ ((k as u64) << 8) ^ n as u64,
            );
            let da = Dev::from_u16(&a);
            let dw = Dev::from_u16(&w);
            let dy = Dev::from_u16(&yhost[off..off + (mi * n) as usize]);
            actp.push(da.0);
            wp.push(dw.0);
            yp.push(dy.0);
            keep.push(da);
            keep.push(dw);
            keep.push(dy);
            off += (mi * n) as usize;
        }
        // The pointer arrays go to the DEVICE. cuBLAS dereferences
        // `Aarray`/`Barray`/`Carray` on the device for the grouped form, as
        // for every other batched form, and this file used to hand it the
        // host `Vec`s -- which is `cudaErrorIllegalAddress` at the sync
        // below, not a wrong number. The scalar arrays (`ms`, and the
        // dimensions and leading dimensions the port builds) stay on the
        // host, which is where cuBLAS really does read those.
        let dactp = Dev::from_ptrs(&actp);
        let dwp = Dev::from_ptrs(&wp);
        let dyp = Dev::from_ptrs(&yp);
        // SAFETY: the three device arrays are `groups` long and outlive the
        // call; `ms` is the host row-count array the row declares.
        unsafe {
            let gctx =
                kernels_cuda::jit::Ctx::on(std::ptr::null_mut()).with_cublas(handle.cast());
            let fired = kernels_cuda::gemm::grouped_act_x_wt_bf16(
                &gctx,
                Unbound { ptr: dactp.0.cast::<*const c_void>().cast_const() },
                Unbound { ptr: dwp.0.cast::<*const c_void>().cast_const() },
                Unbound { ptr: dyp.0.cast::<*mut c_void>() },
                Unbound { ptr: ms.as_ptr() },
                groups,
                n,
                k,
                beta,
            )
;
            // The last `GROUPED` row is `&[]`, and the golden records it as
            // a hash of zero bytes: the archive's `if (group_count <= 0)
            // return;`, which launched nothing and reported nothing.
            //
            // It is a legal NO-OP, not a refusal. This asserted
            // `Refusal::Empty { what: "group_count" }` -- a contract nothing
            // states and nothing implements. `lora.rs` takes all three
            // grouped calls with `?`, so making an empty batch an error
            // would turn a legal one into a failed load. The assertion was
            // written against a target that did not compile, so it had never
            // run to be wrong out loud.
            //
            // `grouped_act_x_wt_bf16`'s `# Errors` says this now. It used to
            // say nothing, and neither did the other three bf16 wrappers,
            // which is how this file came to guess two contracts and get
            // both wrong -- see `the_empty_rectangle_reads_the_same_with_a_
            // bias_and_without`.
            //
            // What makes the row check something is not which variant comes
            // back: it is that the call reports success having launched
            // nothing, that the sync below stays clean, and that the row
            // still hashes zero bytes.
            match (groups, fired) {
                (0, Err(why)) => panic!(
                    "an empty group list is the archive's early return, not a \
                     refusal, and it answered {why:?}"
                ),
                (_, answer) => {
                    answer.unwrap_or_else(|why| panic!("the grouped call refused: {why:?}"))
                }
            }
        }
        sync();
        let mut off = 0usize;
        for (gi, &mi) in ms.iter().enumerate() {
            let len = (mi * n) as usize;
            keep[gi * 3 + 2].back_u16(&mut yhost[off..off + len]);
            off += len;
        }
        let bytes: Vec<u8> = yhost.iter().flat_map(|v| v.to_ne_bytes()).collect();
        rows.push(format!(
            "grouped g={groups} n={n} k={k} beta={} {:016x} {}",
            fmt_g(beta),
            fnv1a(&bytes),
            bytes.len()
        ));
    }

    for &(tokens, heads, nope, vhead, lora) in MLA {
        let bank = (heads * (nope + vhead) * lora) as usize;
        let kvb = fill_bf16(
            bank.max(1),
            0x2545_F491_4F6C_DD1D ^ ((heads as u64) << 32) ^ ((nope as u64) << 16) ^ lora as u64,
        );
        {
            let q = fill_bf16(
                (tokens * heads * nope) as usize,
                0x9E37_79B1_85EB_CA87 ^ ((tokens as u64) << 32) ^ heads as u64,
            );
            let ob = (tokens * heads * lora) as usize;
            let mut out = vec![0xBEEFu16; ob.max(1)];
            let dq = Dev::from_u16(&q);
            let dk = Dev::from_u16(&kvb);
            let dout = Dev::from_u16(&out);
            // NO `unsafe` BLOCK, and its absence is the crossing's receipt: this call
            // was `ffi::pie_k_gemm_mla_absorb_q_to_latent_bf16` taking raw pointers,
            // and `gemm::absorb`'s host program is a safe `fn` that derives its own
            // extents. `Dev::from_u16` still hands it device pointers; what changed
            // is who is answerable for them.
            let fired = kernels_cuda::gemm::absorb::mla_absorb_q_to_latent_bf16(
                &jit,
                In { ptr: dq.0.cast_const(), rows: 0, width: 0 },
                Bank { ptr: dk.0.cast_const() },
                Out { ptr: dout.0, rows: 0, width: 0 },
                // The fourth typed caller class: a test that holds no
                // `Fire` and calls the launcher directly. `kernels::keys` is
                // reachable from here for exactly the reason the key exists
                // -- the value type is declared once, beside the source.
                <kernels::keys::Rows as kernels::keys::Fact>::env(tokens),
                heads,
                nope,
                vhead,
                lora,
            );
            // The `MLA` table's `t=0` and `h=0` rows are the degenerate
            // ones and the golden records both as a hash of zero bytes, so
            // an empty output is the REFUSAL case here exactly as it is
            // for the empty group list above. Which refusal is not pinned:
            // `tokens` and `heads` are separate guards and the row varies
            // which one trips.
            if ob == 0 {
                assert!(
                    matches!(fired, Err(kernels::Refusal::Empty { .. })),
                    "a degenerate absorb answered {fired:?} instead of declining"
                );
            } else {
                fired.expect("the absorb fires");
            }
        
            sync();
            dout.back_u16(&mut out);
            let bytes: Vec<u8> = out[..ob].iter().flat_map(|v| v.to_ne_bytes()).collect();
            rows.push(format!(
                "absorb_q t={tokens} h={heads} nope={nope} v={vhead} lora={lora} {:016x} {}",
                fnv1a(&bytes),
                bytes.len()
            ));
        }
        {
            let lat = fill_bf16(
                (tokens * heads * lora) as usize,
                0xFF51_AFD7_ED55_8CCD ^ ((tokens as u64) << 32) ^ lora as u64,
            );
            let ob = (tokens * heads * vhead) as usize;
            let mut out = vec![0xBEEFu16; ob.max(1)];
            let dl = Dev::from_u16(&lat);
            let dk = Dev::from_u16(&kvb);
            let dout = Dev::from_u16(&out);
            // Safe for the reason the call above states — the same crossing moved both
            // halves of the absorb pair.
            let fired = kernels_cuda::gemm::absorb::mla_absorb_latent_to_v_bf16(
                &jit,
                In { ptr: dl.0.cast_const(), rows: 0, width: 0 },
                Bank { ptr: dk.0.cast_const() },
                Out { ptr: dout.0, rows: 0, width: 0 },
                // The fourth typed caller class: a test that holds no
                // `Fire` and calls the launcher directly. `kernels::keys` is
                // reachable from here for exactly the reason the key exists
                // -- the value type is declared once, beside the source.
                <kernels::keys::Rows as kernels::keys::Fact>::env(tokens),
                heads,
                nope,
                vhead,
                lora,
            );
            // The `MLA` table's `t=0` and `h=0` rows are the degenerate
            // ones and the golden records both as a hash of zero bytes, so
            // an empty output is the REFUSAL case here exactly as it is
            // for the empty group list above. Which refusal is not pinned:
            // `tokens` and `heads` are separate guards and the row varies
            // which one trips.
            if ob == 0 {
                assert!(
                    matches!(fired, Err(kernels::Refusal::Empty { .. })),
                    "a degenerate absorb answered {fired:?} instead of declining"
                );
            } else {
                fired.expect("the absorb fires");
            }
        
            sync();
            dout.back_u16(&mut out);
            let bytes: Vec<u8> = out[..ob].iter().flat_map(|v| v.to_ne_bytes()).collect();
            rows.push(format!(
                "absorb_v t={tokens} h={heads} nope={nope} v={vhead} lora={lora} {:016x} {}",
                fnv1a(&bytes),
                bytes.len()
            ));
        }
    }

    // SAFETY: created above, destroyed once.
    unsafe {
        cublasDestroy_v2(handle);
    }
    rows
}

/// `%g`, for the three betas in the table. Spelled out rather than derived so
/// the transcript's shape is visible in this file.
fn fmt_g(v: f32) -> String {
    if v == 0.0 {
        "0".into()
    } else if v == 1.0 {
        "1".into()
    } else {
        format!("{v}")
    }
}

/// The generator has not drifted from the oracle's.
///
/// Two files spelling the same recurrence is the one thing that can make
/// every other assertion here vacuous — if both sides computed on all-zeros
/// they would agree perfectly and prove nothing. So the first values are
/// pinned, and one of them is the forced zero.
#[test]
fn the_generator_is_the_oracles() {
    let v = fill_bf16(20, 0x9E37_79B9_7F4A_7C15);
    assert_eq!(v.len(), 20);
    assert_eq!(v[16], 0, "every 17th element is exactly zero");
    let nonzero = v.iter().filter(|x| **x != 0).count();
    assert_eq!(nonzero, 19, "only the forced zero is zero");
    // The exponent field must actually spread; a generator that emitted one
    // exponent would be the benign input `env-audit` measured as blind.
    let mut exps: Vec<u16> = v.iter().map(|x| (x >> 7) & 0xff).collect();
    exps.retain(|e| *e != 0);
    exps.sort_unstable();
    exps.dedup();
    assert!(
        exps.len() >= 10 && exps[0] <= 115 && *exps.last().unwrap() >= 140,
        "the exponents must be WIDE, got {exps:?}"
    );
}

/// The shape table exercises every axis the tuples are built from.
#[test]
fn the_shapes_are_not_one_shape() {
    let ms: std::collections::BTreeSet<i32> = DENSE.iter().map(|d| d.0).collect();
    let ns: std::collections::BTreeSet<i32> = DENSE.iter().map(|d| d.1).collect();
    let ks: std::collections::BTreeSet<i32> = DENSE.iter().map(|d| d.2).collect();
    assert!(ms.len() >= 5 && ns.len() >= 5 && ks.len() >= 5, "M, N and K each move");
    assert!(ms.contains(&0), "M=0 is the empty rectangle");
    assert!(ns.contains(&1) && ks.contains(&1), "N=1 and K=1 are degenerate axes");
    assert!(GROUPED.iter().any(|g| g.0.is_empty()), "group_count=0 is the archive's early return");
    assert!(GROUPED.iter().any(|g| g.3 != 0.0), "beta != 0 reads the output and so pins ldc");
    assert!(
        MLA.iter().any(|m| m.0 == 0) && MLA.iter().any(|m| m.1 == 0),
        "tokens=0 and heads=0 are both halves of the absorbs' early return"
    );
    assert!(
        MLA.iter().any(|m| m.2 != m.3 && m.3 != m.4 && m.2 != m.4 && m.0 != m.1),
        "at least one MLA shape has no two dims equal, so a swapped stride cannot hide"
    );
}

/// The four ports write the bytes the C++ wrote. Nothing else is checked.
#[test]
fn the_moved_cublas_calls_write_the_archives_bytes() {
    // Every other GPU-touching test in this crate takes this guard; this one
    // reaches `cudaMalloc` and `cublasCreate_v2` directly and never did, so on
    // a machine with no CUDA it panicked inside `cudarc`'s loader instead of
    // skipping. It still RUNS, and still fails, wherever a device exists.
    let Some(_dev) = common::device_or_skip("the moved cuBLAS calls") else {
        return;
    };
    let _serialised = common::gpu_guard();
    let (golden, which, own_device) = golden_for_device();
    let want: Vec<&str> = golden.lines().filter(|l| !l.trim().is_empty()).collect();
    let got = transcript();
    assert_eq!(
        got.len(),
        want.len(),
        "the transcript has {} rows and the oracle's has {}; a truncated sweep \
         must not be able to pass",
        got.len(),
        want.len()
    );
    let mut bad = Vec::new();
    for (g, w) in got.iter().zip(&want) {
        if g != w {
            bad.push(format!("  rust: {g}\n  c++ : {w}"));
        }
    }
    assert!(
        bad.is_empty(),
        "{} of {} shapes disagree with the archive, BYTE FOR BYTE:\n{}\n\n\
         Each line is `<shape> <fnv1a64 of the output buffer> <bytes>`. Equal \
         byte counts with different hashes is a PERMUTATION -- a transposed \
         `lda`, a stride that took the slice pitch instead of the bank's, or \
         an offset counted in elements where the archive counted bytes. \
         The right-hand side is {}.{}",
        bad.len(),
        want.len(),
        bad.join("\n"),
        which,
        if own_device {
            " Same device, so a disagreement is a PORT bug."
        } else {
            " That is NOT this device. cuBLAS picks its kernel from the card, \
             and two of these rows are known to move between sm_89 and \
             sm_120 while the other twenty-six do not -- so check the shapes \
             above against that before reading this as a port bug, and \
             record a golden for this device with \
             tests/oracle/gemm_service/run.sh."
        }
    );
}

/// The one BEHAVIOURAL change §45 makes, and the measurement that says it
/// costs no answer.
///
/// `gemm::act_x_wt_bias_bf16` had a fused arm at `M == 1`: the warp-per-row
/// GEMV with the bias in its epilogue, one launch instead of two. The Rust
/// composition cannot take it — its steps are `gemm::act_x_wt_bf16` and then
/// `norm::add_bias_bf16` — so that launch is gone.
///
/// `gemv.hpp:25-28` claimed this costs nothing, because the epilogue computes
/// `out[n] = bf16(bf16(dot) + bias[n])` and *"the double rounding is
/// intentional"*. That was prose. `tests/oracle/gemm_service/bias_fold.cu`
/// runs the archive's own `gemv_bf16` both ways out of the real archive, on
/// hostile input, and this reads the RECORDED result — `bias_fold.txt` is
/// `include_str!`'d, so this test does not need the archive and still passes.
///
/// **The recorder no longer runs, and that is not this test failing.** §45.5
/// deleted `gemm/gemv.cu` and `gemm/gemv.hpp`: the kernels are now
/// `kernels-cuda/kernels/gemm/gemv.cuh`, carrying that same sentence at
/// both epilogues, and the host half is `driver_cuda::fire::gemv::gemv_bf16`.
/// Re-recording `bias_fold.txt` means rewriting `bias_fold.cu` against the
/// JIT unit — which is a Rust program now, not a `.cu`. The recorded bytes
/// stand until then; the kernels they came from were carried verbatim.
///
/// A refusal is recorded, not skipped: `gemv_bf16` returned `false` on a shape
/// or alignment it does not support and enqueued nothing (the Rust answers
/// `Gemv::Declined` with the reason named), and the two unsupported K here
/// (7 and 129, neither a multiple of 8) must be refused by BOTH sides or the
/// two paths have already diverged before any arithmetic.
#[test]
fn the_lost_bias_fusion_cost_no_answer() {
    const FOLD: &str = include_str!("oracle/gemm_service/bias_fold.txt");
    let rows: Vec<&str> = FOLD.lines().filter(|l| !l.trim().is_empty()).collect();
    assert!(rows.len() >= 8, "the fold sweep is {} rows", rows.len());
    let mut launched = 0usize;
    let mut values = 0usize;
    for r in &rows {
        if r.contains("REFUSED-BOTH") {
            continue;
        }
        assert!(
            !r.contains("REFUSAL-DISAGREES"),
            "one path launched and the other refused, which is a divergence \
             before any arithmetic: {r}"
        );
        let fused = r.split("fused=").nth(1).and_then(|s| s.split(' ').next());
        let split = r.split("split=").nth(1).and_then(|s| s.split(' ').next());
        assert_eq!(
            fused, split,
            "the fused epilogue and `gemv_bf16` + `add_bias_bf16` wrote \
             DIFFERENT BYTES: {r}\n`gemv.cuh`'s two epilogues say they are \
             bit-identical, and the composition in `bind::service` is built \
             on that sentence."
        );
        let differing: usize = r
            .split("differing=")
            .nth(1)
            .and_then(|s| s.split(' ').next())
            .and_then(|s| s.parse().ok())
            .expect("differing= count");
        assert_eq!(differing, 0, "{differing} cells differ: {r}");
        let n: usize = r.split("of ").nth(1).and_then(|s| s.trim().parse().ok()).expect("of <n>");
        launched += 1;
        values += n;
    }
    assert!(
        launched >= 5 && values >= 10_000,
        "only {launched} shapes launched over {values} values; a transcript \
         where everything refused would agree about nothing"
    );
}

/// One operation must not answer twice, and `act_x_wt_bias_bf16` did.
///
/// The composition is `gemm::act_x_wt_bf16` and then `norm::add_bias`, and
/// its own comment says the two are "one operation" because the bias add
/// reads exactly what the GEMM wrote, on the same stream. For the empty
/// rectangle they disagreed: the GEMM reports success -- the archive's dense
/// body had no early return, so `M == 0` reaches cuBLAS and launches nothing,
/// which is what `DENSE`'s `(0, 64, 64)` row above already measures -- while
/// `norm::add_bias` builds its grid with `route_rows(m, n)` and `Ctx::launch`
/// answers `Refusal::Empty { what: "the grid" }` for a zero axis.
///
/// So an empty fire was `Ok(())` on a projection with no bias and `Err` on
/// one with a bias. `act_x_wt_bias_bf16` is a `routine!` (`model-dsl`'s
/// `cuda::base`), fired from a trace with `m` = the token count, and its
/// callers take it with `?`; the archive's `add_bias_bf16` launched a
/// zero-row grid and CUDA no-opped it.
///
/// The `m > 0` half is not decoration: without it this test would pass on a
/// body that refused everything.
#[test]
fn the_empty_rectangle_reads_the_same_with_a_bias_and_without() {
    let mut handle: *mut cublasContext = std::ptr::null_mut();
    // SAFETY: live out-parameter.
    unsafe {
        assert_eq!(
            cublasCreate_v2(&raw mut handle) as i32,
            0,
            "cublasCreate failed; is there a device?"
        );
    }
    // SAFETY: the null stream is always live, and `handle` outlives this fn.
    let jit =
        unsafe { kernels_cuda::jit::Ctx::on(std::ptr::null_mut()).with_cublas(handle.cast()) };
    for &(m, n, k) in &[(0i32, 64i32, 64i32), (2, 64, 64)] {
        let act = fill_bf16((m * k) as usize, 0x51ED_270B_2AFD_B4E1 ^ m as u64);
        let w = fill_bf16((n * k) as usize, 0x2545_F491_4F6C_DD1D ^ k as u64);
        let bias = fill_bf16(n as usize, 0x1405_7B7E_F767_814F);
        let dact = Dev::from_u16(&act);
        let dw = Dev::from_u16(&w);
        let db = Dev::from_u16(&bias);
        let dy = Dev::from_u16(&vec![0u16; (m * n) as usize]);
        // These take raw pointers and document a `# Safety` contract without
        // being `unsafe fn`: every buffer is live and at least the size the
        // row states, and nothing frees them before the sync below.
        let (bare, biased) = (
            kernels_cuda::gemm::act_x_wt_bias_bf16(
                &jit,
                In { ptr: dact.0, rows: m, width: k },
                Weight { ptr: dw.0 },
                Weight { ptr: std::ptr::null() },
                Out { ptr: dy.0, rows: m, width: n },
                0.0,
            ),
            kernels_cuda::gemm::act_x_wt_bias_bf16(
                &jit,
                In { ptr: dact.0, rows: m, width: k },
                Weight { ptr: dw.0 },
                Weight { ptr: db.0 },
                Out { ptr: dy.0, rows: m, width: n },
                0.0,
            ),
        );
        sync();
        assert!(
            bare.is_ok(),
            "m={m}: the no-bias arm is `act_x_wt_bf16` and cannot refuse a \
             context that has a handle, and it answered {bare:?}"
        );
        assert!(
            biased.is_ok(),
            "m={m}: the same rectangle answered {biased:?} with a bias and \
             {bare:?} without. The bias add reads what the GEMM wrote, so \
             when the GEMM writes nothing there is nothing to refuse."
        );
    }
}
