use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=kernels");

    let kernels = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("kernels");

    println!("cargo:kernels_dir={}", kernels.display());

    emit_entrypoints(&kernels);

    if std::env::var_os("CARGO_FEATURE_NATIVE").is_none() {
        return;
    }

    stage_rng_preamble(&kernels);
}

struct Stamp {
    params: Vec<String>,
    body: String,
}

fn emit_entrypoints(kernels: &Path) {
    let mut files: Vec<PathBuf> = Vec::new();
    walk(kernels, &mut files);
    files.sort();

    let mut found: BTreeSet<(String, String)> = BTreeSet::new();
    for path in &files {
        println!("cargo:rerun-if-changed={}", path.display());
        let rel = path
            .strip_prefix(kernels)
            .expect("walked from kernels")
            .to_string_lossy()
            .replace('\\', "/");
        let text = std::fs::read_to_string(path).unwrap_or_default();
        for name in expand(&text, &rel) {
            found.insert((rel.clone(), name));
        }
    }

    let mut generated = String::from(
        "// GENERATED by build.rs, by expanding the shader tree's `instantiate_*`\n\
         // macros. Do not edit.\n\
         /// Every `(file, entrypoint)` the `.metal` tree stamps.\n\
         pub static STAMPED: &[(&str, &str)] = &[\n",
    );
    for (file, name) in &found {
        generated.push_str(&format!("    ({file:?}, {name:?}),\n"));
    }
    generated.push_str("];\n");

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets this"));
    std::fs::write(out.join("entrypoints.rs"), generated).expect("OUT_DIR is writable");
}

fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.filter_map(Result::ok) {
        let path = entry.path();
        if path.is_dir() {
            walk(&path, out);
        } else if matches!(
            path.extension().and_then(|e| e.to_str()),
            Some("metal" | "h")
        ) {
            out.push(path);
        }
    }
}

fn expand(text: &str, file: &str) -> Vec<String> {
    let joined = text.replace("\\\n", " ");
    let mut names = Vec::new();
    let mut stamps: BTreeMap<String, Stamp> = BTreeMap::new();

    for line in joined.lines() {
        let trimmed = line.trim_start();
        let Some(rest) = trimmed.strip_prefix("#define ") else {
            continue;
        };
        let Some((head, body)) = rest.split_once(')') else {
            continue;
        };
        let Some((name, params)) = head.split_once('(') else {
            continue;
        };
        if !name.starts_with("instantiate_") {
            continue;
        }
        stamps.insert(
            name.trim().to_owned(),
            Stamp {
                params: params.split(',').map(|p| p.trim().to_owned()).collect(),
                body: body.to_owned(),
            },
        );
    }

    for (at, _) in joined
        .match_indices("kernel]] void ")
        .chain(joined.match_indices("kernel void "))
    {
        let line_start = joined[..at].rfind('\n').map_or(0, |i| i + 1);
        let line_head = joined[line_start..at].trim_start();
        if line_head.starts_with('#') {
            continue;
        }
        let before = joined[..at].trim_end();
        if before.ends_with("host_name")
            || before.contains("host_name(") && {
                before
                    .rfind("host_name(")
                    .is_some_and(|h| h > line_start.saturating_sub(1))
            }
        {
            continue;
        }

        if line_head.starts_with("template") || preceded_by_template(&joined[..line_start]) {
            continue;
        }
        let after = joined[at..]
            .split_once(" void ")
            .map(|(_, t)| t)
            .unwrap_or("");
        if let Some((name, _)) = after.split_once('(') {
            let name = name.trim();
            if !name.is_empty() && name.chars().all(|c| c.is_alphanumeric() || c == '_') {
                names.push(name.to_owned());
            }
        }
    }

    for line in joined.lines() {
        if line.trim_start().starts_with('#') {
            continue;
        }
        names.extend(literal_host_names(line));
    }

    let mut calls: Vec<(String, Vec<String>)> =
        joined.lines().filter_map(call_at_column_zero).collect();
    for _ in 0..8 {
        if calls.is_empty() {
            break;
        }
        let mut next = Vec::new();
        for (name, args) in calls {
            let Some(stamp) = stamps.get(&name) else {
                panic!(
                    "{file}: `{name}(..)` names no `#define` in this file, so the entrypoints \
                     it stamps cannot be read. A name that silently leaves the set is what \
                     this expansion exists to prevent."
                );
            };
            assert!(
                stamp.params.len() == args.len(),
                "{file}: `{name}` takes {} argument(s) and is called with {}",
                stamp.params.len(),
                args.len(),
            );
            let sub: BTreeMap<&str, &str> = stamp
                .params
                .iter()
                .map(String::as_str)
                .zip(args.iter().map(String::as_str))
                .collect();
            for pattern in host_name_patterns(&stamp.body) {
                if let Some(name) = compose(&pattern, &sub) {
                    names.push(name);
                }
            }
            for (inner, inner_args) in nested_calls(&stamp.body) {
                next.push((
                    inner,
                    inner_args
                        .into_iter()
                        .map(|a| sub.get(a.as_str()).map_or(a.clone(), |v| (*v).to_owned()))
                        .collect(),
                ));
            }
        }
        calls = next;
    }
    names
}

fn preceded_by_template(head: &str) -> bool {
    let mut depth = 0i32;
    for line in head.lines().rev() {
        let line = line.trim();
        if line.is_empty() || line.starts_with("//") {
            continue;
        }
        depth += line.matches('>').count() as i32 - line.matches('<').count() as i32;
        if line.starts_with("template") {
            return true;
        }

        if depth <= 0 || line.ends_with(';') || line.ends_with('}') {
            return false;
        }
    }
    false
}

fn literal_host_names(line: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut rest = line;
    while let Some(at) = rest.find("host_name(\"") {
        rest = &rest[at + "host_name(\"".len()..];
        let Some((name, tail)) = rest.split_once('"') else {
            break;
        };
        out.push(name.to_owned());
        rest = tail;
    }
    out
}

fn host_name_patterns(body: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut rest = body;
    while let Some(at) = rest.find("host_name(") {
        rest = &rest[at + "host_name(".len()..];
        let mut depth = 1usize;
        let mut end = rest.len();
        for (i, ch) in rest.char_indices() {
            match ch {
                '(' => depth += 1,
                ')' => {
                    depth -= 1;
                    if depth == 0 {
                        end = i;
                        break;
                    }
                }
                _ => {}
            }
        }
        out.push(rest[..end].to_owned());
        rest = &rest[end..];
    }
    out
}

fn compose(pattern: &str, sub: &BTreeMap<&str, &str>) -> Option<String> {
    let bytes = pattern.as_bytes();
    let mut out = String::new();
    let mut i = 0usize;
    while i < bytes.len() {
        let ch = bytes[i] as char;
        if ch == '"' {
            let rest = &pattern[i + 1..];
            let end = rest.find('"')?;
            out.push_str(&rest[..end]);
            i += 1 + end + 1;
        } else if ch == '#' {
            let rest = &pattern[i + 1..];
            let end = rest
                .find(|c: char| !c.is_alphanumeric() && c != '_')
                .unwrap_or(rest.len());
            out.push_str(sub.get(&rest[..end])?.trim_matches('"'));
            i += 1 + end;
        } else if ch.is_alphanumeric() || ch == '_' {
            let rest = &pattern[i..];
            let end = rest
                .find(|c: char| !c.is_alphanumeric() && c != '_')
                .unwrap_or(rest.len());
            let value = sub.get(&rest[..end])?;

            if !value.starts_with('"') {
                return None;
            }
            out.push_str(value.trim_matches('"'));
            i += end;
        } else {
            i += 1;
        }
    }
    (!out.is_empty()).then_some(out)
}

fn call_at_column_zero(line: &str) -> Option<(String, Vec<String>)> {
    let trimmed = line.trim();
    if trimmed.starts_with('#') || !trimmed.starts_with("instantiate_") {
        return None;
    }
    let (name, rest) = trimmed.split_once('(')?;
    let args = rest.rsplit_once(')')?.0;
    Some((name.trim().to_owned(), split_args(args)))
}

fn nested_calls(body: &str) -> Vec<(String, Vec<String>)> {
    let mut out = Vec::new();
    let mut rest = body;
    while let Some(at) = rest.find("instantiate_") {
        rest = &rest[at..];
        let Some((name, tail)) = rest.split_once('(') else {
            break;
        };
        if !name.chars().all(|c| c.is_alphanumeric() || c == '_') {
            rest = &rest["instantiate_".len()..];
            continue;
        }
        let Some((args, after)) = tail.split_once(')') else {
            break;
        };
        out.push((name.to_owned(), split_args(args)));
        rest = after;
    }
    out
}

fn split_args(args: &str) -> Vec<String> {
    args.split(',')
        .map(|a| a.trim().to_owned())
        .filter(|a| !a.is_empty())
        .collect()
}

fn stage_rng_preamble(kernels: &Path) {
    let src = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("crates/kernels-metal has a parent")
        .join("tensor-compiler/include/ptir_rng.generated.metal");
    println!("cargo:rerun-if-changed={}", src.display());

    let dst = kernels.join("ptir").join("ptir_rng.generated.metal");
    let text = std::fs::read(&src).unwrap_or_else(|e| {
        panic!(
            "cannot read the generated RNG preamble at {}: {e}. It is emitted \
             by tensor-compiler and committed there.",
            src.display()
        )
    });

    if std::fs::read(&dst).ok().as_deref() != Some(text.as_slice()) {
        std::fs::write(&dst, &text)
            .unwrap_or_else(|e| panic!("cannot stage {}: {e}", dst.display()));
    }
}
