#!/usr/bin/env python3
"""A source file where NOTHING runs.

## Why this exists

`crates/model` carried three files that no test could reach, because no
caller existed to reach them from: `emissions.rs` and the two
`forward/emit.rs` under it, 3,108 lines that wrote committed C++ `.inc`
files. The commit that retired the `emit-cuda` binary and its check said
so plainly -- they targeted "a tree that no longer exists" -- and deleted
the writer and the checker while leaving the library behind. The text
they emitted still opened "GENERATED by `cargo run -p pie-forward --bin
emit-cuda`", naming a crate the workspace no longer has, and there were
zero `.inc` files anywhere in it.

Every gate we had was green on that:

* `cargo test` passed. Nothing tested it.
* `cargo clippy -D warnings` passed. `dead_code` does not fire on `pub`
  items -- a public function is assumed to have callers outside the crate.
* `mod-reachability-audit.py` reported zero orphans, correctly: the files
  were reachable, from a `pub mod` that nothing called.
* `cfg-feature-audit.py` had nothing to say; no `cfg` was involved.

Coverage saw it in one line: three files at exactly 0.00%, holding 2,208
of the crate's 4,305 uncovered lines. That is the gap this fills. Dead
code that is `pub` and `mod`-reachable is invisible to every static check
here and unmistakable to a dynamic one.

## What it checks

That no file has ZERO covered lines. Not a percentage floor -- a floor
invites the argument about what the number should be, and would fail on
honest gaps like an `unwrap` arm nothing provokes. Zero is different in
kind: it means the file did not participate in the test run at all, which
is either dead code or an untested module, and both want a name.

Deleting the emission took `crates/model` from 83.98% to 92.06% purely by
subtraction, and left no file at zero -- so this passes today and the
entry to add when it fails is a test or a deletion, not an exception.

## What it does not check

The percentage. The remaining 1,947 uncovered lines in `model` are real
gaps worth closing, and a coverage number is the wrong tool for making
that happen: it can be raised by testing whatever is cheapest. This asks
one question that has a right answer.

## Cost

It rebuilds the crate instrumented, into its own target directory --
`-C instrument-coverage` changes codegen, so sharing `target/` with the
other gates would make every one of them rebuild afterwards.
"""

import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Crates measured, and why each is worth the instrumented rebuild.
CRATES = {
    "model": (
        "the catalog: every model's identity, load contract, forward trace "
        "and chat template. It is the crate the rest of the workspace asks "
        "about a checkpoint, and the one where a file nothing runs is a "
        "family nobody serves."
    ),
}

# Files allowed to have zero covered lines, and why. Empty on purpose:
# the emission's deletion cleared the last one. An entry here should be
# rarer than a fix -- if a file runs in no test, that is usually the
# finding rather than the exception.
ALLOWED_ZERO: dict[str, str] = {}


def toolchain_bin() -> Path:
    """Where `llvm-profdata`/`llvm-cov` live for the PINNED toolchain.

    Not `which llvm-cov`: a system LLVM is a different major version, and
    a profraw written by rustc's LLVM will not merge with it. This box has
    LLVM 18 on PATH against rustc's 22, which fails with a version error
    rather than a wrong number -- but only because they are far apart.
    """
    sysroot = subprocess.run(
        ["rustc", "--print", "sysroot"], capture_output=True, text=True, check=True
    ).stdout.strip()
    host = subprocess.run(
        ["rustc", "-vV"], capture_output=True, text=True, check=True
    ).stdout
    triple = next(l.split()[1] for l in host.splitlines() if l.startswith("host:"))
    return Path(sysroot) / "lib" / "rustlib" / triple / "bin"


def measure(crate: str, bindir: Path, target: Path) -> list[dict]:
    """Run `crate`'s tests instrumented and return its own files' summaries."""
    profdir = target / "prof"
    profdir.mkdir(parents=True, exist_ok=True)
    env = os.environ | {
        "RUSTFLAGS": "-C instrument-coverage",
        "LLVM_PROFILE_FILE": str(profdir / f"{crate}-%p-%m.profraw"),
        "CARGO_TARGET_DIR": str(target),
    }
    test = subprocess.run(
        ["cargo", "test", "-p", crate, "--all-features", "--no-fail-fast"],
        env=env,
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    if test.returncode != 0:
        print(test.stdout[-4000:], file=sys.stderr)
        sys.exit(f"coverage-audit: `cargo test -p {crate}` failed; fix that first.")

    raws = sorted(profdir.glob("*.profraw"))
    if not raws:
        sys.exit(f"coverage-audit: {crate} produced no profraw files.")
    merged = target / f"{crate}.profdata"
    subprocess.run(
        [str(bindir / "llvm-profdata"), "merge", "-sparse", *map(str, raws), "-o", str(merged)],
        check=True,
        capture_output=True,
    )

    objects: list[str] = []
    for f in (target / "debug" / "deps").iterdir():
        if f.is_file() and os.access(f, os.X_OK) and f.suffix not in (".so", ".d", ".rlib"):
            objects += ["--object", str(f)]
    export = subprocess.run(
        [
            str(bindir / "llvm-cov"),
            "export",
            *objects,
            f"--instr-profile={merged}",
            "--summary-only",
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    marker = f"/crates/{crate}/src/"
    return [f for f in json.loads(export.stdout)["data"][0]["files"] if marker in f["filename"]]


def main() -> int:
    bindir = toolchain_bin()
    if not (bindir / "llvm-cov").exists():
        sys.exit(
            "coverage-audit: no llvm-cov in the pinned toolchain. "
            "`rust-toolchain.toml` declares the `llvm-tools` component, so this "
            "means rustup has not installed it yet -- run any cargo command first."
        )

    problems: list[str] = []
    for crate, why in CRATES.items():
        with tempfile.TemporaryDirectory(prefix=f"cov-{crate}-") as tmp:
            files = measure(crate, bindir, Path(tmp))
        if not files:
            problems.append(f"{crate}: measured no files of its own ({why})")
            continue

        total = sum(f["summary"]["lines"]["count"] for f in files)
        covered = sum(f["summary"]["lines"]["covered"] for f in files)
        zero = [
            f["filename"]
            for f in files
            if f["summary"]["lines"]["count"] > 0 and f["summary"]["lines"]["covered"] == 0
        ]
        for path in sorted(zero):
            rel = path.split(f"/crates/{crate}/")[-1]
            if rel in ALLOWED_ZERO:
                continue
            problems.append(
                f"{crate}: `{rel}` has zero covered lines -- nothing in the test "
                f"run reaches it. Either it is dead (delete it) or it is untested "
                f"(test it); if neither, add it to ALLOWED_ZERO with the reason."
            )
        pct = 100 * covered / total if total else 0.0
        print(
            f"coverage-audit: {crate} {covered}/{total} lines ({pct:.2f}%), "
            f"{len(files)} files, none at zero."
            if not zero
            else f"coverage-audit: {crate} {covered}/{total} lines ({pct:.2f}%), "
            f"{len(files)} files, {len(zero)} at zero."
        )

    if problems:
        print("\ncoverage-audit: FAILED", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
