interface context {

    use wasi:io/poll@0.2.4.{pollable};
    use types.{error, future-bool};
    use model.{model};

    type page-id = u32;

    resource context {

        // Creates a new context, optionally with a name
        create: static func(model:borrow<model>, name: string, fill: option<list<u32>>) -> result<context, error>;

        destroy: func() -> result<_, error>;

        // Retrieves an existing context by name
        get: static func(model:borrow<model>, name: string) -> option<context>;

        // Forks this context into a new one with the given name
        fork: func(new-name: string) -> result<context, error>;

        // Merges another context into this one
        join: func(other: borrow<context>) -> result<_, error>;

        // Acquires a lock on the context, returning a lock result
        lock: func() -> future-bool;

        // Releases the lock
        unlock: func() -> result<_, error>;

        page-size: func() -> u32;

        // Number of committed KV pages in the context
        num-total-pages: func() -> u32;

        num-total-tokens: func() -> u32;

        // Commit the KV pages to the context
        commit-pages: func(indices: list<u32>) -> result<_, error>;

        allocate-pages: func(num-pages: u32) -> result<_, error>;

        free-pages: func(num-pages: u32) -> result<_, error>;

        pointer: func() -> u32;

        set-pointer: func(pointer: u32) -> result<_, error>;

        staged-tokens: func() -> list<u32>;

        set-staged-tokens: func(tokens: list<u32>) -> result<_, error>;

    }

}
