[package]
name = "model"
version = "0.1.0"
edition = "2024"
authors = ["In Gim <in.gim@yale.edu>"]
license = "Apache-2.0"
repository = "https://github.com/pie-project/pie"

[lib]
name = "model"
path = "src/lib.rs"

[dependencies]
model-dsl = { path = "../model-dsl" }
model-ir = { path = "../model-ir" }
serde_json = "1"
tokenizer = { path = "../tokenizer" }
