use crate::shared::vocabulary::{Member, Vocab};

pub const VOCAB: Vocab = Vocab(&[
    Member::same("model.layers.{layer}.block_sparse_moe.gate"),
    Member::same("model.layers.{layer}.block_sparse_moe.shared_expert.gate_proj"),
    Member::same("model.layers.{layer}.input_layernorm"),
    Member::same("model.layers.{layer}.mlp.down_proj"),
    Member::same("model.layers.{layer}.mlp.gate_proj"),
    Member::same("model.layers.{layer}.post_attention_layernorm"),
    Member::same("model.layers.{layer}.self_attention_res_norm"),
    Member::same("model.layers.{layer}.self_attention_res_proj"),
    Member::same("model.layers.{layer}.self_attn.A_log"),
    Member::same("model.layers.{layer}.self_attn.b_proj"),
    Member::same("model.layers.{layer}.self_attn.f_a_proj"),
    Member::same("model.layers.{layer}.self_attn.f_b_proj"),
    Member::same("model.layers.{layer}.self_attn.g_proj"),
    Member::same("model.layers.{layer}.self_attn.k_proj"),
    Member::same("model.layers.{layer}.self_attn.kv_a_layernorm"),
    Member::same("model.layers.{layer}.self_attn.kv_a_proj_with_mqa"),
    Member::same("model.layers.{layer}.self_attn.kv_b_proj"),
    Member::same("model.layers.{layer}.self_attn.o_norm"),
    Member::same("model.layers.{layer}.self_attn.o_proj"),
    Member::same("model.layers.{layer}.self_attn.q_a_layernorm"),
    Member::same("model.layers.{layer}.self_attn.q_a_proj"),
    Member::same("model.layers.{layer}.self_attn.q_b_proj"),
    Member::same("model.layers.{layer}.self_attn.q_proj"),
    Member::same("model.layers.{layer}.self_attn.v_proj"),
    Member::same("model.embed_tokens"),
    Member::same("lm_head"),
    Member::same("model.norm"),
]);
