"""
`inferlet.eta` — the ETA authoring surface for Python inferlets: the tracing
eDSL (`Tensor` + ops), the container encoder, and the WIT bridge
(`Channel`, `WorkingSet`, `ForwardPass`, `Pipeline`, `run_ahead`).

A stage body is an ordinary Python function traced once at first submit::

    from inferlet.eta import *

    tok_out = Channel([1], dtype.i32).named("tok_out")

    @fwd.epilogue
    def _():
        tok_out.put(reshape(reduce_argmax(intrinsics.logits()), [1]))

The emitted container bytes are identical to the Rust SDK's for the same
program, so a Python and a Rust inferlet share the host's program cache.
"""

from __future__ import annotations

from . import diffusion, intrinsics
from .bridge import (
    TOKEN_PAD,
    Channel,
    ForwardKind,
    ForwardPass,
    InferletError,
    KvBinding,
    KvGeometry,
    PageDecl,
    PageGrant,
    PageRange,
    Pipeline,
    RsGeometry,
    RsWorkingSet,
    WorkingSet,
    channel_capacity,
    frame_size,
    kv_page_size,
    max_embed_length,
    mm,
    pad_tokens,
    prefill_chunk_hint,
    prefill_chunks,
    run_ahead,
    scale,
    submit_deadline_us,
    submit_frame,
    unpad_tokens,
)
from .ir import Dtype, Port, Stage, dtype
from .trace import TraceError
from .value import (
    ConstData,
    Tensor,
    abs_,
    add,
    and_,
    broadcast,
    cast,
    causal_mask,
    constant,
    cummass_le,
    cumprod,
    cumsum,
    div,
    entropy,
    entropy_from_logprobs,
    eq,
    exp,
    gather,
    gather_row,
    ge,
    gt,
    gumbel,
    gumbel_max,
    indptr,
    iota,
    l2norm,
    le,
    log,
    log_softmax,
    lt,
    mask_apply,
    masked_argmax,
    matmul,
    max_elem,
    min_elem,
    mul,
    ne,
    neg,
    not_,
    nucleus_sample,
    or_,
    pivot_threshold,
    prob_ge,
    rank_le,
    recip,
    reduce_argmax,
    reduce_max,
    reduce_min,
    reduce_sum,
    rem,
    reshape,
    rng,
    row_membership,
    scalar_gather,
    scatter_add,
    scatter_set,
    select,
    sign,
    sink_window_mask,
    sliding_window_mask,
    softmax,
    sort_desc,
    sub,
    top_k,
    transpose,
)

__all__ = [
    # bridge
    "TOKEN_PAD",
    "Channel",
    "ForwardKind",
    "ForwardPass",
    "InferletError",
    "KvBinding",
    "KvGeometry",
    "PageDecl",
    "PageGrant",
    "PageRange",
    "Pipeline",
    "RsGeometry",
    "RsWorkingSet",
    "WorkingSet",
    "channel_capacity",
    "frame_size",
    "kv_page_size",
    "max_embed_length",
    "mm",
    "pad_tokens",
    "prefill_chunk_hint",
    "prefill_chunks",
    "run_ahead",
    "scale",
    "submit_deadline_us",
    "submit_frame",
    "unpad_tokens",
    # ir
    "Dtype",
    "Port",
    "Stage",
    "dtype",
    "TraceError",
    "diffusion",
    "intrinsics",
    # value
    "ConstData",
    "Tensor",
    "abs_",
    "add",
    "and_",
    "broadcast",
    "cast",
    "causal_mask",
    "constant",
    "cummass_le",
    "cumprod",
    "cumsum",
    "div",
    "entropy",
    "entropy_from_logprobs",
    "eq",
    "exp",
    "gather",
    "gather_row",
    "ge",
    "gt",
    "gumbel",
    "gumbel_max",
    "indptr",
    "iota",
    "l2norm",
    "le",
    "log",
    "log_softmax",
    "lt",
    "mask_apply",
    "masked_argmax",
    "matmul",
    "max_elem",
    "min_elem",
    "mul",
    "ne",
    "neg",
    "not_",
    "nucleus_sample",
    "or_",
    "pivot_threshold",
    "prob_ge",
    "rank_le",
    "recip",
    "reduce_argmax",
    "reduce_max",
    "reduce_min",
    "reduce_sum",
    "rem",
    "reshape",
    "rng",
    "row_membership",
    "scalar_gather",
    "scatter_add",
    "scatter_set",
    "select",
    "sign",
    "sink_window_mask",
    "sliding_window_mask",
    "softmax",
    "sort_desc",
    "sub",
    "top_k",
    "transpose",
]
