//! **GEMMA-4'S PREPROCESSING ARITHMETIC, PINNED**, beside the arithmetic it
//! pins (`models::gemma_4::media`); the whole-pipe PNG gate rides in
//! `runtime`'s `media_pipe_is_the_pinned_preprocessing`, where the codec is.
//!
//! ```text
//! cargo test -p models --test gemma4_media_is_the_pinned_arithmetic
//! ```
//!
//! The gates are qwen's at `k = 3` and with two things swapped: the resize
//! rounds DOWN rather than to nearest (which is where the no-edge proof lives —
//! multimodal §7.4), and the position stream is a FACTORIZATION rather than a
//! resample, so its two taps carry weight 1 each and interpolate nothing.

use models::gemma_4::media::GemmaVisionConfig;
use models::media::Budget;

/// A ramp that makes every pixel of a small image distinct, so a golden can
/// name which source pixel it expects in which patch lane. The same rule the
/// whole-pipe gate's hand-written PNG uses in `runtime`'s
/// `media_pipe_is_the_pinned_preprocessing`.
mod common {
    #[must_use]
    pub fn ramp(x: u32, y: u32) -> [u8; 3] {
        [
            ((x * 7 + y * 13) % 251) as u8,
            ((x * 31 + y * 3) % 251) as u8,
            ((x + y * 97) % 251) as u8,
        ]
    }
}

/// **`get_aspect_ratio_preserving_size`'S OWN ANSWERS**, generated by running
/// `transformers.models.gemma4.image_processing_gemma4.get_aspect_ratio_preserving_size`
/// at `patch_size = 16`, `pooling_kernel_size = 3` and the two budgets, and
/// transcribed as `(h, w, still_h, still_w, frame_h, frame_w)`.
///
/// The spread covers the ordinary case, both zero-side rescues (`7000 x 20`
/// and `2 x 3000` reach them), and the extreme ratios where the cap bites.
const RESIZE: &[(u32, u32, u32, u32, u32, u32)] = &[
    (64, 64, 768, 768, 384, 384),
    (224, 224, 768, 768, 384, 384),
    (100, 50, 1104, 528, 528, 240),
    (1, 1, 768, 768, 384, 384),
    (33, 97, 432, 1344, 192, 672),
    (768, 1024, 672, 912, 336, 432),
    (5000, 4000, 864, 672, 432, 336),
    (7000, 20, 13440, 48, 3360, 48),
    (480, 640, 672, 912, 336, 432),
    (1080, 1920, 576, 1056, 288, 528),
    (31, 31, 768, 768, 384, 384),
    (2, 3000, 48, 13440, 48, 3360),
    (3000, 2, 13440, 48, 3360, 48),
    (256, 256, 768, 768, 384, 384),
    (1, 10000, 48, 13440, 48, 3360),
];

#[test]
fn the_resize_answers_the_reference_processors_own_table() {
    let c = GemmaVisionConfig::default();
    for &(h, w, sh, sw, fh, fw) in RESIZE {
        assert_eq!(
            c.aspect_ratio_preserving_size(h, w, Budget::Still)
                .expect("a still resizes"),
            (sh, sw),
            "a {h} x {w} still"
        );
        assert_eq!(
            c.aspect_ratio_preserving_size(h, w, Budget::VideoFrame)
                .expect("a frame resizes"),
            (fh, fw),
            "a {h} x {w} video frame"
        );
    }
}

/// **ROUNDING DOWN IS THE NO-EDGE PROOF** (multimodal §7.4). Every image's
/// patch grid is a whole number of `k × k` blocks on BOTH axes, so whole-block
/// runs laid end to end never put a block across an image boundary — which is
/// what lets `layout.pool_rows` read no geometry: no indptr, no per-image grid
/// width, no atomics.
///
/// And the run length never exceeds the budget, which is the other half of
/// what rounding down buys.
#[test]
fn rounding_down_keeps_every_block_inside_one_image_and_inside_the_budget() {
    let c = GemmaVisionConfig::default();
    let k = c.pooling_kernel_size;
    for h in [1u32, 3, 17, 64, 255, 480, 1080, 4001, 7000] {
        for w in [1u32, 2, 50, 97, 256, 640, 1921, 5000] {
            for budget in [Budget::Still, Budget::VideoFrame] {
                let (th, tw) = c
                    .aspect_ratio_preserving_size(h, w, budget)
                    .expect("every one of these resizes");
                let (gh, gw) = (th / c.patch_size, tw / c.patch_size);
                assert_eq!(
                    (gh % k, gw % k),
                    (0, 0),
                    "a {h} x {w} image resized to a {gh} x {gw} patch grid, which puts a \
                     {k} x {k} pooling block across the edge"
                );
                assert!(gh > 0 && gw > 0);
                let tokens = gh * gw / (k * k);
                assert!(
                    tokens <= c.soft_tokens(budget),
                    "a {h} x {w} image occupies {tokens} soft tokens and the budget is {}",
                    c.soft_tokens(budget)
                );
            }
        }
    }
}

/// **280 IS A CEILING AND NOT A LENGTH.** `Gemma4Processor.replace_image_token`
/// repeats `image_token` exactly `patches // k²` times, which reaches the
/// budget only when the resize landed on it — a square image does, a 16:9 one
/// does not.
#[test]
fn the_run_is_the_grids_own_length_and_the_budget_is_its_ceiling() {
    let c = GemmaVisionConfig::default();
    let tokens = |h: u32, w: u32, b: Budget| -> u32 {
        let (th, tw) = c.aspect_ratio_preserving_size(h, w, b).expect("resizes");
        (th / c.patch_size) * (tw / c.patch_size) / (c.pooling_kernel_size * c.pooling_kernel_size)
    };
    assert_eq!(tokens(256, 256, Budget::Still), 256, "a square lands at 256");
    assert_eq!(
        tokens(1080, 1920, Budget::Still),
        264,
        "a 16:9 frame lands at 264, short of the 280 budget"
    );
    assert_eq!(tokens(7000, 20, Budget::Still), 280, "the cap is reachable");
    assert_eq!(tokens(256, 256, Budget::VideoFrame), 64);
    assert_eq!(tokens(7000, 20, Budget::VideoFrame), 70);
}

/// The pool-block-major order, written out here independently of `patchify`'s
/// loop nest.
fn expected_order(gh: usize, gw: usize, k: usize) -> Vec<(usize, usize)> {
    let mut out = Vec::with_capacity(gh * gw);
    for ib_r in 0..gh / k {
        for ib_c in 0..gw / k {
            for ir in 0..k {
                for ic in 0..k {
                    out.push((ib_r * k + ir, ib_c * k + ic));
                }
            }
        }
    }
    out
}

/// **THE STATUTE AT `k = 3`** — the same sentence qwen's merge already writes
/// (multimodal §8.4), which is what turns the 2-D pool into a 1-D reduction.
/// Upstream emits RASTER order and builds the pool as an `O(patches²)` one-hot
/// matmul at run time; reordering here is what makes it `O(patches)`.
#[test]
fn the_patch_rows_come_out_pool_block_major() {
    let c = GemmaVisionConfig::default();
    let (gh, gw) = (6usize, 9usize);
    let (h, w) = (gh * 16, gw * 16);
    let rgb = vec![0u8; h * w * 3];
    #[allow(clippy::cast_possible_truncation)]
    let (_, positions) = c.patchify(&rgb, h as u32, w as u32);

    let want = expected_order(gh, gw, c.pooling_kernel_size as usize);
    assert_eq!(positions.len(), want.len() * 2);
    for (at, &(row, col)) in want.iter().enumerate() {
        assert_eq!(
            (positions[2 * at] as usize, positions[2 * at + 1] as usize),
            (row, col),
            "patch row {at} should be grid cell ({row}, {col}) under the pool-block statute"
        );
    }
    // Raster and pool-block agree until row 3; assert they part there, so the
    // gate is not satisfied by the ordering it exists to rule out.
    assert_eq!(want[3], (1usize, 0usize), "row 3 is where the two orders part");
}

/// **EVERY `k²` CONSECUTIVE ROWS ARE ONE POOLING BLOCK** — the property
/// `layout.pool_rows` reads instead of geometry.
#[test]
fn every_nine_consecutive_rows_are_one_block_of_the_grid() {
    let c = GemmaVisionConfig::default();
    let k = c.pooling_kernel_size as usize;
    let (gh, gw) = (9usize, 6usize);
    let rgb = vec![0u8; gh * 16 * gw * 16 * 3];
    #[allow(clippy::cast_possible_truncation)]
    let (_, positions) = c.patchify(&rgb, (gh * 16) as u32, (gw * 16) as u32);

    for block in 0..(gh / k) * (gw / k) {
        let rows: Vec<(u32, u32)> = (0..k * k)
            .map(|i| {
                let at = block * k * k + i;
                (positions[2 * at], positions[2 * at + 1])
            })
            .collect();
        let (r0, c0) = rows[0];
        for (i, &(r, cc)) in rows.iter().enumerate() {
            assert_eq!(
                (r, cc),
                (r0 + (i / k) as u32, c0 + (i % k) as u32),
                "block {block} row {i} left its own {k} x {k} square"
            );
        }
        assert_eq!(
            (r0 % k as u32, c0 % k as u32),
            (0, 0),
            "block {block} does not start on a block boundary"
        );
    }
}

/// **THE PER-PATCH VECTOR**: row, then column, then CHANNEL —
/// `convert_image_to_patches`' `permute(1, 3, 2, 4, 0)`, HWC inside the patch,
/// which is the opposite of qwen's channel-major layout. And the values are a
/// plain `v / 255`: `do_normalize` is False and `image_mean`/`image_std` are
/// 0 and 1.
#[test]
fn a_patch_row_is_row_then_column_then_channel_and_rescaled_only() {
    let c = GemmaVisionConfig::default();
    let p = c.patch_size as usize;
    let k = c.pooling_kernel_size as usize;
    let (gh, gw) = (k, k);
    let (h, w) = (gh * p, gw * p);

    let mut rgb = vec![0u8; h * w * 3];
    for y in 0..h {
        for x in 0..w {
            for ch in 0..3 {
                rgb[(y * w + x) * 3 + ch] = common::ramp(x as u32, y as u32)[ch];
            }
        }
    }
    #[allow(clippy::cast_possible_truncation)]
    let (pix, positions) = c.patchify(&rgb, h as u32, w as u32);

    let pd = c.patch_width();
    assert_eq!(pd, 3 * p * p, "C · P² — gemma's patch has no temporal axis");
    assert_eq!(pix.len(), gh * gw * pd);

    for at in 0..gh * gw {
        let (pr, pc) = (positions[2 * at] as usize, positions[2 * at + 1] as usize);
        for r in 0..p {
            for col in 0..p {
                for ch in 0..3 {
                    let lane = (r * p + col) * 3 + ch;
                    let src = common::ramp((pc * p + col) as u32, (pr * p + r) as u32)[ch];
                    let want = f32::from(src) / 255.0;
                    assert!(
                        (pix[at * pd + lane] - want).abs() < 1e-6,
                        "patch row {at} lane {lane} (row {r}, column {col}, channel {ch}) should \
                         hold source pixel ({}, {}) channel {ch} rescaled",
                        pc * p + col,
                        pr * p + r
                    );
                }
            }
        }
    }
    assert!(
        pix.iter().all(|v| (0.0..=1.0).contains(v)),
        "a rescale-only pipeline never leaves [0, 1]"
    );
}

/// **THE SEPARABLE TABLE'S TWO TAPS, EACH AT WEIGHT ONE.**
///
/// `_position_embeddings` is `embedding(ids[..., 0], table[0]) +
/// embedding(ids[..., 1], table[1])` over a `[2, 10240, hidden]` parameter, so
/// flattened to `[2 · 10240, hidden]` the two taps are `x` and `10240 + y` and
/// the sum is `embed_weighted` with both weights 1. Gemma interpolates
/// nothing: qwen's four taps carry a bilinear RESAMPLE, gemma's two carry a
/// FACTORIZATION, and one op serves both.
#[test]
fn the_position_taps_are_the_two_planes_of_the_separable_table() {
    let c = GemmaVisionConfig::default();
    let plane = c.position_embedding_size;
    let (gh, gw) = (6usize, 9usize);
    let rgb = vec![0u8; gh * 16 * gw * 16 * 3];
    #[allow(clippy::cast_possible_truncation)]
    let (_, positions) = c.patchify(&rgb, (gh * 16) as u32, (gw * 16) as u32);
    let (ids, weights) = c.pos_embed_taps(&positions);

    assert_eq!(ids.len(), gh * gw * 2, "two taps per patch row");
    assert_eq!(weights.len(), ids.len());
    assert!(
        weights.iter().all(|&w| (w - 1.0).abs() < f32::EPSILON),
        "both taps of a factorization carry weight one"
    );
    for at in 0..gh * gw {
        let (y, x) = (positions[2 * at], positions[2 * at + 1]);
        assert_eq!(
            (ids[2 * at], ids[2 * at + 1]),
            (x as i32, (plane + y) as i32),
            "patch row {at} at grid ({y}, {x}) should read plane 0 at its COLUMN and plane 1 at \
             its ROW — `pixel_position_ids[..., 0]` is x and `[..., 1]` is y"
        );
    }
}
