use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::Command;

#[path = "src/capability.rs"]
#[allow(dead_code)]
mod capability;
use capability::Capability;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    println!("cargo:rerun-if-changed=src/capability.rs");
    println!("cargo:rerun-if-changed=kernels");
    println!("cargo:rerun-if-changed=include");

    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let kernels = root.join("kernels");
    let include = root.join("include");

    println!("cargo:include={}", include.display());
    println!("cargo:kernels_dir={}", kernels.display());

    let out = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"));

    let variants = collect(&kernels);
    assert!(
        !variants.is_empty(),
        "no `// pie:instantiate` directive under {} — the shader tree cannot \
         be empty and the directive is how a variant is declared",
        kernels.display()
    );
    emit_census(&out, &variants);

    emit_sources(&out, &kernels);

    if std::env::var_os("CARGO_FEATURE_NATIVE").is_none() {
        emit_table(&out, &BTreeMap::new(), Path::new(""));
        return;
    }

    let spv = out.join("spv");
    std::fs::create_dir_all(&spv).expect("create the SPIR-V output directory");

    let slangc = slangc();

    for ((entrypoint, _), variant) in &variants {
        compile_slang(&slangc, &kernels, &spv, entrypoint, variant);
    }

    emit_table(&out, &variants, &spv);

    println!("cargo:spv_dir={}", spv.display());

    println!(
        "cargo::rustc-env=PIE_KERNELS_VULKAN_SPV_DIR={}",
        spv.display()
    );
}

fn emit_census(out: &Path, variants: &BTreeMap<(String, Capability), Variant>) {
    let mut names: Vec<&str> = variants.keys().map(|(name, _)| name.as_str()).collect();
    names.sort_unstable();
    names.dedup();

    let mut generated = String::from(
        "// Generated by build.rs from the tree's `// pie:instantiate` lines.\n\
         pub static CENSUS: &[&str] = &[\n",
    );
    for name in names {
        generated.push_str(&format!("    {name:?},\n"));
    }
    generated.push_str("];\n");

    std::fs::write(out.join("census.rs"), generated).expect("OUT_DIR is writable");
}

fn emit_sources(out: &Path, kernels: &Path) {
    let mut files = Vec::new();
    walk_slang(kernels, kernels, &mut files);
    files.sort();
    assert!(
        !files.is_empty(),
        "no `.slang` source under {} — `runtime` compiles from these",
        kernels.display()
    );

    let mut generated = String::from(
        "// Generated by build.rs by walking the `.slang` tree.\n\
         pub static SOURCES: &[(&str, &str)] = &[\n",
    );
    for rel in &files {
        generated.push_str(&format!(
            "    ({rel:?}, include_str!(concat!({:?}, \"/\", {rel:?}))),\n",
            kernels.display().to_string()
        ));
    }
    generated.push_str("];\n");

    std::fs::write(out.join("sources.rs"), generated).expect("OUT_DIR is writable");
}

fn walk_slang(root: &Path, dir: &Path, out: &mut Vec<String>) {
    let entries =
        std::fs::read_dir(dir).unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()));
    for entry in entries {
        let path = entry.expect("a readable directory entry").path();
        if path.is_dir() {
            walk_slang(root, &path, out);
        } else if path.extension().is_some_and(|e| e == "slang") {
            let rel = path
                .strip_prefix(root)
                .expect("walked from `root`")
                .to_string_lossy()
                .replace('\\', "/");
            out.push(rel);
        }
    }
}

fn emit_table(out: &Path, variants: &BTreeMap<(String, Capability), Variant>, spv: &Path) {
    let mut rows: Vec<(String, PathBuf)> = variants
        .iter()
        .map(|((entrypoint, _), variant)| {
            let file = variant.tier.module(entrypoint);
            let stem = file
                .strip_suffix(".spv")
                .expect("`Capability::module` names a `.spv`")
                .to_string();
            (stem, spv.join(&file))
        })
        .collect();
    rows.sort();

    let mut generated = String::from(
        "// Generated by build.rs. Every compiled SPIR-V module, keyed by file stem.\n\
         pub static MODULES: &[(&str, &[u8])] = &[\n",
    );
    for (stem, path) in &rows {
        let path = path.to_string_lossy().replace('\\', "/");
        generated.push_str(&format!("    ({stem:?}, include_bytes!({path:?})),\n"));
    }
    generated.push_str("];\n");

    std::fs::write(out.join("modules.rs"), generated).expect("OUT_DIR is writable");
}

struct Variant {
    file: PathBuf,
    tier: Capability,
    defines: Vec<(String, String)>,
}

fn collect(kernels: &Path) -> BTreeMap<(String, Capability), Variant> {
    let mut out: BTreeMap<(String, Capability), Variant> = BTreeMap::new();
    let mut files = Vec::new();
    walk(kernels, &mut files);
    files.sort();

    for path in files {
        let text = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
        let rel = path
            .strip_prefix(kernels)
            .expect("walk yields paths under kernels/")
            .to_path_buf();

        for (lineno, line) in text.lines().enumerate() {
            let Some(rest) = directive(line) else {
                continue;
            };
            let mut words = rest.split_whitespace().peekable();
            let entrypoint = words
                .next()
                .unwrap_or_else(|| {
                    panic!(
                        "{}:{}: a `pie:instantiate` names an entrypoint first",
                        rel.display(),
                        lineno + 1
                    )
                })
                .to_string();

            let tier = match words.peek().and_then(|w| w.strip_prefix('@')) {
                Some(tag) => {
                    let cap = Capability::from_tag(tag).unwrap_or_else(|| {
                        panic!(
                            "{}:{}: `@{tag}` is not a capability tier; expected \
                             one of baseline, fp16, coopmat",
                            rel.display(),
                            lineno + 1
                        )
                    });
                    words.next();
                    cap
                }
                None => Capability::Baseline,
            };

            let defines = words
                .map(|w| {
                    let (k, v) = w.split_once('=').unwrap_or_else(|| {
                        panic!(
                            "{}:{}: `{w}` is not a `KEY=VALUE` define",
                            rel.display(),
                            lineno + 1
                        )
                    });
                    (k.to_string(), v.to_string())
                })
                .collect();

            if let Some(prior) = out.insert(
                (entrypoint.clone(), tier),
                Variant {
                    file: rel.clone(),
                    tier,
                    defines,
                },
            ) {
                panic!(
                    "`{entrypoint}` is instantiated twice at tier `{}`: {} and {}",
                    tier.tag(),
                    prior.file.display(),
                    rel.display()
                );
            }
        }
    }

    for (entrypoint, tier) in out.keys() {
        assert!(
            *tier == Capability::Baseline
                || out.contains_key(&(entrypoint.clone(), Capability::Baseline)),
            "`{entrypoint}` is instantiated at tier `{}` with no baseline; every \
             entrypoint must resolve on a device with no optional features",
            tier.tag()
        );
    }
    out
}

fn slangc() -> PathBuf {
    println!("cargo:rerun-if-env-changed=PIE_SLANGC");
    std::env::var_os("PIE_SLANGC").map_or_else(|| PathBuf::from("slangc"), PathBuf::from)
}

fn directive(line: &str) -> Option<&str> {
    let line = line.trim_start();
    let rest = line.strip_prefix("//")?.trim_start();
    rest.strip_prefix("pie:instantiate").map(str::trim)
}

fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("cannot read the directory {}: {e}", dir.display()));
    for entry in entries {
        let path = entry.expect("a readable directory entry").path();
        if path.is_dir() {
            walk(&path, out);
        } else if path.extension().is_some_and(|e| e == "slang") {
            out.push(path);
        }
    }
}

fn compile_slang(slangc: &Path, kernels: &Path, spv: &Path, entrypoint: &str, variant: &Variant) {
    let src = kernels.join(&variant.file);
    let dst = spv.join(variant.tier.module(entrypoint));

    let mut cmd = Command::new(slangc);
    cmd.arg("-target")
        .arg("spirv")
        .arg("-stage")
        .arg("compute")
        .arg("-entry")
        .arg("main")
        .arg("-fvk-use-entrypoint-name")
        .arg("-emit-spirv-directly")
        .arg("-allow-glsl")
        .arg("-I")
        .arg(kernels)
        .arg(format!("-DPIE_ENTRYPOINT={entrypoint}"));
    if variant.tier == Capability::Coopmat {
        cmd.arg("-O0");
    } else {
        cmd.arg("-O2");
    }
    for (k, v) in &variant.defines {
        cmd.arg(format!("-D{k}={v}"));
    }
    cmd.arg("-o").arg(&dst).arg(&src);

    let status = cmd.status().unwrap_or_else(|e| {
        panic!(
            "cannot run `{}` (set PIE_SLANGC, or put slangc on PATH — see \
             `slangc()` for the release this tree is measured against): {e}",
            slangc.display()
        )
    });
    assert!(
        status.success(),
        "slangc failed for `{entrypoint}` at tier `{}` ({}): {status}",
        variant.tier.tag(),
        variant.file.display()
    );
}
