//! **QWEN3.5'S PREPROCESSING, PINNED** — the campaign's goldens carried down to
//! where they run without a GPU.
//!
//! ```text
//! cargo test -p media-frontend --test qwen3_5_is_the_pinned_preprocessing
//! ```
//!
//! Three of these claims already existed in this tree and are carried rather
//! than re-derived:
//!
//! * **(a) THE RESAMPLE IS THE RESAMPLE** — `kernels-cuda/tests/tower_pos_embed.rs`'s
//!   first gate, which fires the taps against a TEXTBOOK `align_corners`
//!   bilinear resample written without reference to the helper. Up there it
//!   also proved the CUDA kernel; here it proves only the host arithmetic,
//!   which is the half this crate owns and the half that runs on any machine.
//! * **(b) THE NATIVE GRID DEGENERATES** — the same file's second gate, which
//!   is what makes multimodal §11.3's cheap path a fact about the arithmetic
//!   rather than a special case in a branch.
//! * **the merge-block-major order** — `qwen_patchify_hwc`'s loop nest, which
//!   `engine-cuda/tests/a_vision_sku_loads_and_fires_an_image.rs` transcribed a
//!   second time to build its own streams. Here it is asserted against an
//!   order written out independently below.
//!
//! The rest is new and pinned against `transformers` v5.15.1 directly:
//! `smart_resize`'s own table, the per-patch vector layout, the grid
//! arithmetic, and one real PNG through the whole pipe.

mod common;

use media_frontend::qwen3_5::{QwenVisionConfig, Qwen35Vision, axis_taps, interp};
use media_frontend::{Budget, EncodedSpan, Fault, VisionFrontEnd};

/// `int(2304 ** 0.5)` — `Qwen3_5VisionModel.__init__`'s `num_grid_per_side`.
const SIDE: usize = 48;

/// **THE REFERENCE PROCESSOR'S OWN ANSWERS**, generated by running
/// `transformers.models.qwen2_vl.image_processing_qwen2_vl.smart_resize` at
/// the checkpoint's `factor = 32`, `min_pixels = 65536`,
/// `max_pixels = 16777216`, and transcribed here as
/// `(h, w, h_bar, w_bar, token_count, position_span)`.
///
/// The spread is deliberate: below `min_pixels` (scale up), between the two
/// bounds (round only), above `max_pixels` (scale down), and the near-
/// degenerate ratios where the branches interact — `2 x 400` and `20 x 4000`
/// sit exactly ON the aspect-ratio limit of 200, which is where a round to
/// zero meets a rescue.
const SMART_RESIZE: &[(u32, u32, u32, u32, u32, u32)] = &[
    (64, 64, 256, 256, 64, 8),
    (224, 224, 256, 256, 64, 8),
    (100, 50, 384, 192, 72, 12),
    (1, 1, 256, 256, 64, 8),
    (33, 97, 160, 448, 70, 14),
    (768, 1024, 768, 1024, 768, 32),
    (5000, 4000, 4576, 3648, 16302, 143),
    (480, 640, 480, 640, 300, 20),
    (1080, 1920, 1088, 1920, 2040, 60),
    (31, 31, 256, 256, 64, 8),
    (256, 256, 256, 256, 64, 8),
    (2, 400, 32, 3648, 114, 114),
    (400, 2, 3648, 32, 114, 114),
    (3, 600, 32, 3648, 114, 114),
    (20, 4000, 32, 4000, 125, 125),
    (4096, 4096, 4096, 4096, 16384, 128),
    (5000, 5000, 4096, 4096, 16384, 128),
];

/// **WHAT UPSTREAM REFUSES**, and it is its own first statement:
/// `if max(h, w) / min(h, w) > 200: raise`. Gemma has no such rule and serves
/// every one of these, which is the sharpest difference between the two
/// policies and worth a gate of its own.
const REFUSED_RATIO: &[(u32, u32)] = &[(20, 4001), (7000, 20), (2, 3000), (1, 10000)];

#[test]
fn smart_resize_answers_the_reference_processors_own_table() {
    let c = QwenVisionConfig::default();
    for &(h, w, h_bar, w_bar, _, _) in SMART_RESIZE {
        assert_eq!(
            c.smart_resize(h, w).expect("this ratio is servable"),
            (h_bar, w_bar),
            "a {h} x {w} image: `smart_resize` answers {h_bar} x {w_bar}"
        );
    }
}

/// The ratio refusal, by name — and the boundary is exact: 200 serves and
/// 200.05 does not.
#[test]
fn an_absolute_aspect_ratio_past_two_hundred_is_refused() {
    let c = QwenVisionConfig::default();
    for &(h, w) in REFUSED_RATIO {
        let fault = c
            .smart_resize(h, w)
            .expect_err("a strip this thin has no grid");
        assert_eq!(fault.name(), "Empty", "{fault}");
        assert!(
            fault.to_string().contains("aspect ratio"),
            "the refusal should say what it refused: {fault}"
        );
    }
    assert!(
        c.smart_resize(20, 4000).is_ok(),
        "exactly 200 is served — the rule is `> 200`"
    );
    assert!(c.smart_resize(4000, 20).is_ok());
}

#[test]
fn the_run_length_and_the_cursor_advance_are_the_checkpoints() {
    let c = QwenVisionConfig::default();
    for &(h, w, _, _, tokens, span) in SMART_RESIZE {
        let (gh, gw) = c.patch_grid(h, w).expect("servable");
        assert_eq!(
            c.token_count(gh, gw),
            tokens,
            "a {h} x {w} image occupies {tokens} token rows"
        );
        assert_eq!(
            c.position_span(gh, gw),
            span,
            "a {h} x {w} image advances the 1-D cursor by {span}"
        );
    }
}

/// **THE NO-EDGE PROOF, QWEN'S HALF.** `smart_resize` rounds to a multiple of
/// `patch · merge`, so every image's patch grid is a whole number of 2 × 2
/// merge blocks on BOTH axes — which is what lets `layout.merge_rows` read no
/// geometry and what makes `scatter_live_rows`' tail a property of the fold
/// and not of the image (multimodal §7.4, §8.6).
#[test]
fn every_resized_grid_is_a_whole_number_of_merge_blocks() {
    let c = QwenVisionConfig::default();
    for h in [1u32, 7, 33, 64, 255, 256, 719, 1080, 4001] {
        for w in [1u32, 3, 50, 97, 256, 640, 1921, 5000] {
            let Ok((gh, gw)) = c.patch_grid(h, w) else {
                continue; // the ratio refusal, gated on its own above
            };
            assert_eq!(
                (gh % c.merge_size, gw % c.merge_size),
                (0, 0),
                "a {h} x {w} image resized to a {gh} x {gw} patch grid, which puts a merge \
                 block across the edge"
            );
            assert!(gh > 0 && gw > 0, "a {h} x {w} image resized to no patches");
        }
    }
}

/// The merge-block-major order, written out here independently of
/// `qwen_patchify_hwc`'s loop nest: block row, block column, then row and
/// column inside the block.
fn expected_order(gh: usize, gw: usize, m: usize) -> Vec<(usize, usize)> {
    let mut out = Vec::with_capacity(gh * gw);
    for ih_blk in 0..gh / m {
        for iw_blk in 0..gw / m {
            for ih in 0..m {
                for iw in 0..m {
                    out.push((ih_blk * m + ih, iw_blk * m + iw));
                }
            }
        }
    }
    out
}

/// **THE STATUTE**: one ordering serves the pos-embed gather, the merge and the
/// pool (multimodal §11.4). Assert it on the positions the patchifier answers.
#[test]
fn the_patch_rows_come_out_merge_block_major() {
    let c = QwenVisionConfig::default();
    let (gh, gw) = (6usize, 4usize);
    let (h, w) = (gh * 16, gw * 16);
    let rgb = vec![0u8; h * w * 3];
    #[allow(clippy::cast_possible_truncation)]
    let (_, positions) = c.patchify(&rgb, h as u32, w as u32);

    let want = expected_order(gh, gw, c.merge_size as usize);
    assert_eq!(positions.len(), want.len() * 2);
    for (at, &(row, col)) in want.iter().enumerate() {
        assert_eq!(
            (positions[2 * at] as usize, positions[2 * at + 1] as usize),
            (row, col),
            "patch row {at} should be grid cell ({row}, {col}); the statute is block row, \
             block column, then row and column inside the 2 x 2 block"
        );
    }
    // Raster order would agree on row 0 and disagree by row 2 — so the
    // assertion above is not vacuously satisfied by the easy ordering.
    assert_ne!(
        (want[2].0, want[2].1),
        (0usize, 2usize),
        "the expected order collapsed to raster, and this gate proves nothing"
    );
}

/// **THE PER-PATCH VECTOR**: channel, then temporal, then row, then column —
/// `Qwen2VLImageProcessor.patchify`'s `permute(0, 2, 5, 3, 6, 1, 4, 7)` with
/// the temporal axis `unsqueeze`d in after the channel. And the normalization
/// is `(v / 255 − 0.5) / 0.5`, the checkpoint's mean and std of 0.5.
#[test]
fn a_patch_row_is_channel_then_temporal_then_row_then_column() {
    let c = QwenVisionConfig::default();
    let p = c.patch_size as usize;
    let (gh, gw) = (2usize, 2usize);
    let (h, w) = (gh * p, gw * p);

    // Every source pixel distinct, so a lane that read the wrong one shows up.
    let mut rgb = vec![0u8; h * w * 3];
    for y in 0..h {
        for x in 0..w {
            for ch in 0..3 {
                rgb[(y * w + x) * 3 + ch] = common::ramp(x as u32, y as u32)[ch];
            }
        }
    }
    #[allow(clippy::cast_possible_truncation)]
    let (pix, positions) = c.patchify(&rgb, h as u32, w as u32);

    let pd = c.patch_width();
    assert_eq!(pd, 3 * 2 * p * p, "C · T · P² is the patch width");
    assert_eq!(pix.len(), gh * gw * pd);

    let tp = c.temporal_patch_size as usize;
    for at in 0..gh * gw {
        let (pr, pc) = (positions[2 * at] as usize, positions[2 * at + 1] as usize);
        for ch in 0..3 {
            for t in 0..tp {
                for r in 0..p {
                    for col in 0..p {
                        let lane = ((ch * tp + t) * p + r) * p + col;
                        let src = common::ramp((pc * p + col) as u32, (pr * p + r) as u32)[ch];
                        let want = ((f32::from(src) / 255.0) - 0.5) / 0.5;
                        assert!(
                            (pix[at * pd + lane] - want).abs() < 1e-6,
                            "patch row {at} lane {lane} (channel {ch}, frame {t}, row {r}, \
                             column {col}) should hold source pixel ({}, {}) channel {ch}",
                            pc * p + col,
                            pr * p + r
                        );
                    }
                }
            }
        }
    }
}

/// A still image repeats itself across the temporal axis — upstream's
/// `unsqueeze(6).expand(…)`, and the reason a `temporal_patch_size` of 2
/// doubles the patch width without a second frame existing.
#[test]
fn a_still_image_repeats_itself_across_the_temporal_axis() {
    let c = QwenVisionConfig::default();
    let p = c.patch_size as usize;
    let (h, w) = (2 * p, 2 * p);
    let mut rgb = vec![0u8; h * w * 3];
    for (i, byte) in rgb.iter_mut().enumerate() {
        *byte = (i % 251) as u8;
    }
    #[allow(clippy::cast_possible_truncation)]
    let (pix, _) = c.patchify(&rgb, h as u32, w as u32);
    let pd = c.patch_width();
    let plane = p * p;
    for at in 0..4 {
        for ch in 0..3 {
            let base = at * pd + ch * 2 * plane;
            assert_eq!(
                pix[base..base + plane],
                pix[base + plane..base + 2 * plane],
                "patch row {at} channel {ch}: the two temporal frames of a still image differ"
            );
        }
    }
}

/// **TEXTBOOK `align_corners = True` BILINEAR**, carried from
/// `tower_pos_embed.rs`: written without reference to `axis_taps`, so the two
/// can disagree.
fn textbook_bilinear(
    table: &[f32],
    side: usize,
    grid_h: usize,
    grid_w: usize,
    hidden: usize,
) -> Vec<f32> {
    let mut out = vec![0.0f32; grid_h * grid_w * hidden];
    for i in 0..grid_h {
        for j in 0..grid_w {
            #[allow(clippy::cast_precision_loss)]
            let y = i as f32 * (side as f32 - 1.0) / (grid_h.saturating_sub(1).max(1)) as f32;
            #[allow(clippy::cast_precision_loss)]
            let x = j as f32 * (side as f32 - 1.0) / (grid_w.saturating_sub(1).max(1)) as f32;
            let (y0, x0) = (y.floor(), x.floor());
            let (dy, dx) = (y - y0, x - x0);
            #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
            let (y0, x0) = (y0 as usize, x0 as usize);
            let y1 = (y0 + 1).min(side - 1);
            let x1 = (x0 + 1).min(side - 1);
            let at = (i * grid_w + j) * hidden;
            for hh in 0..hidden {
                let corner = |r: usize, c: usize| table[(r * side + c) * hidden + hh];
                out[at + hh] = (1.0 - dy) * (1.0 - dx) * corner(y0, x0)
                    + (1.0 - dy) * dx * corner(y0, x1)
                    + dy * (1.0 - dx) * corner(y1, x0)
                    + dy * dx * corner(y1, x1);
            }
        }
    }
    out
}

/// **(a) THE RESAMPLE IS THE RESAMPLE** — carried from
/// `kernels-cuda/tests/tower_pos_embed.rs`. The taps and weights the
/// submission ships, gathered by hand, equal an independently written
/// `align_corners` bilinear resample of the same table.
#[test]
fn the_taps_gather_a_bilinear_resample_of_the_position_table() {
    const HIDDEN: usize = 8;
    // A table a golden can print: deterministic, and every row distinct.
    #[allow(clippy::cast_precision_loss)]
    let table: Vec<f32> = (0..SIDE * SIDE * HIDDEN)
        .map(|i| ((i * 37 % 1009) as f32 / 1009.0) - 0.5)
        .collect();

    // One grid finer than the table and one coarser, so the gate is not about
    // one direction of resampling.
    for (grid_h, grid_w) in [(6usize, 4usize), (60usize, 80usize)] {
        let want = textbook_bilinear(&table, SIDE, grid_h, grid_w, HIDDEN);
        for i in 0..grid_h {
            for j in 0..grid_w {
                let (ids, weights) = interp(i, j, grid_h, grid_w, SIDE);
                for hh in 0..HIDDEN {
                    let got: f32 = (0..4)
                        .map(|t| weights[t] * table[ids[t] as usize * HIDDEN + hh])
                        .sum();
                    let expected = want[(i * grid_w + j) * HIDDEN + hh];
                    assert!(
                        (got - expected).abs() < 1e-5,
                        "{grid_h}x{grid_w} patch ({i}, {j}) lane {hh}: the taps gathered {got}, \
                         textbook bilinear says {expected}"
                    );
                }
            }
        }
    }
}

/// **(b) THE NATIVE GRID DEGENERATES** — carried from the same file. All the
/// weight lands on the patch's own table row, by arithmetic and not by a
/// branch, which is what makes multimodal §11.3's one-tap cheap path
/// legitimate rather than an approximation.
#[test]
fn the_native_grid_puts_all_the_weight_on_its_own_row() {
    for i in 0..SIDE {
        for j in 0..SIDE {
            let (ids, weights) = interp(i, j, SIDE, SIDE, SIDE);
            let own = (i * SIDE + j) as i32;
            let mut mass = 0.0f32;
            for (tap, weight) in ids.iter().zip(&weights) {
                if *weight > 0.0 {
                    assert_eq!(
                        *tap, own,
                        "patch ({i}, {j}) of a native grid put weight {weight} on table row \
                         {tap}, and its own row is {own}"
                    );
                }
                mass += weight;
            }
            assert!(
                (mass - 1.0).abs() < 1.0e-6,
                "patch ({i}, {j})'s taps carry mass {mass}"
            );
        }
    }
}

/// Every axis tap is inside the table and every row's four weights sum to one —
/// so the gather is a convex combination and cannot move the position
/// embedding's scale.
#[test]
fn every_tap_is_in_range_and_every_rows_weights_sum_to_one() {
    let c = QwenVisionConfig::default();
    for (gh, gw) in [(2u32, 2), (6, 4), (48, 48), (96, 32), (140, 4)] {
        let (ids, weights) = c.pos_embed_taps(gh, gw);
        let rows = (gh * gw) as usize;
        assert_eq!(ids.len(), rows * 4, "four taps per patch row, always");
        assert_eq!(weights.len(), rows * 4);
        for r in 0..rows {
            let mass: f32 = weights[r * 4..r * 4 + 4].iter().sum();
            assert!(
                (mass - 1.0).abs() < 1e-6,
                "{gh}x{gw} row {r} carries tap mass {mass}"
            );
            for &id in &ids[r * 4..r * 4 + 4] {
                assert!(
                    id >= 0 && (id as usize) < SIDE * SIDE,
                    "{gh}x{gw} row {r} gathers table row {id}, and the table has {} rows",
                    SIDE * SIDE
                );
            }
        }
    }
    // `axis_taps`' size == 1 guard: index 0 of a length-1 axis maps to source 0.
    assert_eq!(axis_taps(0, 1, SIDE).1[0], 1.0);
}

/// **THE WHOLE PIPE, ON A REAL PNG.** Bytes this test wrote from the PNG
/// specification (not from `image`'s encoder — see `common`), decoded,
/// resized, patchified, and every stream's length checked against the geometry
/// the same span reports.
#[test]
fn a_real_png_goes_through_the_whole_pipe() {
    let fe = Qwen35Vision::new();
    let c = fe.config;
    let bytes = common::png_rgb(200, 120, common::ramp);
    let span = fe
        .encode_image(&bytes, Budget::Still)
        .expect("a well-formed PNG encodes");

    let (gh, gw) = c.patch_grid(120, 200).expect("servable");
    assert_eq!(
        c.smart_resize(120, 200).expect("servable"),
        (224, 352),
        "the resize policy"
    );
    assert_eq!((gh, gw), (14, 22));

    assert_eq!(span.rows, gh * gw, "one payload row per pre-merge patch");
    assert_eq!(span.patch_grid, media_frontend::Grid::still(gh, gw));
    assert_eq!(
        span.grid,
        media_frontend::Grid::still(gh / 2, gw / 2),
        "the merged grid is what the token rectangle sees"
    );
    assert_eq!(span.token_count, gh * gw / 4);
    assert_eq!(span.position_span, (gw / 2).max(gh / 2));
    assert!(span.uses_mrope, "qwen's trunk rotates on the triple");

    assert_eq!(
        span.payload.len(),
        span.rows as usize * c.patch_width(),
        "the payload is `rows · C·T·P²`"
    );
    assert_eq!(span.positions.len(), span.rows as usize * 2);
    assert_eq!(span.embed_rows.len(), span.rows as usize * 4);
    assert_eq!(span.embed_weights.len(), span.rows as usize * 4);
    assert!(
        span.payload.iter().all(|v| (-1.0..=1.0).contains(v)),
        "normalized pixels live in [-1, 1]"
    );
    // Not a flat image: the ramp survived decode and resize.
    let first = span.payload[0];
    assert!(
        span.payload.iter().any(|v| (v - first).abs() > 1e-3),
        "the decoded image is uniform, so nothing downstream was exercised"
    );
}

/// The delimiters are NAMED, not numbered, and `tokens()` is
/// prefix + pad × token_count + suffix in whatever ids the bound tokenizer
/// hands back (media-door §0, §2).
#[test]
fn the_span_spells_itself_out_of_the_tokenizers_own_ids() {
    let fe = Qwen35Vision::new();
    let d = fe.delimiters();
    assert_eq!(d.prefix, "<|vision_start|>");
    assert_eq!(d.placeholder, "<|image_pad|>");
    assert_eq!(d.suffix, "<|vision_end|>");

    let bytes = common::png_rgb(64, 64, common::ramp);
    let mut span = fe.encode_image(&bytes, Budget::Still).expect("encodes");
    // What the runtime does with `tokenizer.token_to_id` — two arbitrary
    // checkpoint numberings, one of which is not the other.
    span.spell_with(vec![151_652], 151_655, vec![151_653]);
    let toks = span.tokens();
    assert_eq!(toks.len(), 1 + span.token_count as usize + 1);
    assert_eq!(toks[0], 151_652);
    assert_eq!(*toks.last().expect("non-empty"), 151_653);
    assert!(toks[1..toks.len() - 1].iter().all(|&t| t == 151_655));

    let mut renumbered = span.clone();
    renumbered.spell_with(vec![7], 8, vec![9]);
    assert_ne!(span.tokens(), renumbered.tokens(), "the ids moved");
    assert_eq!(
        span.digest(),
        renumbered.digest(),
        "and the span did not — a digest is over the preprocessed span, never over its spelling"
    );
}

/// **THE CACHE STATUTE'S KEY** (media-door §5). Two different images produce
/// identical token lists; the digest is what tells them apart, and it is
/// stable across runs because everything it hashes is deterministic
/// arithmetic over deterministic bytes in a fixed byte order.
#[test]
fn the_digest_is_stable_and_separates_two_images_one_run_cannot() {
    let fe = Qwen35Vision::new();
    let one = fe
        .encode_image(&common::png_rgb(96, 96, common::ramp), Budget::Still)
        .expect("one");
    let again = fe
        .encode_image(&common::png_rgb(96, 96, common::ramp), Budget::Still)
        .expect("again");
    let other = fe
        .encode_image(
            &common::png_rgb(96, 96, |x, y| {
                let mut p = common::ramp(x, y);
                // One pixel of one channel, moved by one.
                if x == 5 && y == 7 {
                    p[1] = p[1].wrapping_add(1);
                }
                p
            }),
            Budget::Still,
        )
        .expect("other");

    assert_eq!(one.digest().len(), 32, "blake3, the workspace's own hash");
    assert_eq!(
        one.digest(),
        again.digest(),
        "two encodings of one image must collide, or a correct cache hit looks like a bug"
    );
    assert_eq!(one.token_count, other.token_count);
    let mut a = one.clone();
    let mut b = other.clone();
    a.spell_with(vec![1], 2, vec![3]);
    b.spell_with(vec![1], 2, vec![3]);
    assert_eq!(
        a.tokens(),
        b.tokens(),
        "the ledger cannot tell two images apart"
    );
    assert_ne!(a.digest(), b.digest(), "and the statute's key must");
}

/// The refusals, by name.
#[test]
fn the_refusals_fire_by_name() {
    let fe = Qwen35Vision::new();
    let empty = fe
        .encode_image(&[], Budget::Still)
        .expect_err("zero bytes are refused");
    assert_eq!(empty.name(), "Decode", "{empty}");

    let garbage = fe
        .encode_image(b"this is not a picture, it is a sentence", Budget::Still)
        .expect_err("prose is refused");
    assert_eq!(garbage.name(), "Decode", "{garbage}");
    assert!(matches!(garbage, Fault::Decode(_)));
}

/// `budget` is ignored here, and that is a fact about qwen rather than an
/// omission: its ceiling is `max_pixels`, and `Processor::for_arch_video`
/// already answered one config for both.
#[test]
fn a_video_frame_is_the_same_preprocessing_as_a_still() {
    let fe = Qwen35Vision::new();
    let bytes = common::png_rgb(80, 60, common::ramp);
    let still: EncodedSpan = fe.encode_image(&bytes, Budget::Still).expect("still");
    let frame: EncodedSpan = fe
        .encode_image(&bytes, Budget::VideoFrame)
        .expect("a frame");
    assert_eq!(still, frame);
}
