//! Default `config.toml` template emitted by `pie config init`. The
//! highest-priority compiled flavor (cuda → portable → dummy) picks
//! which `[model.driver]` block to splice in, so the generated config
//! "just works" without a follow-up edit. Multi-flavor builds always
//! pick the most capable backend.

use crate::driver_ffi::{self, Flavor};

/// Render the default `config.toml` body matching the highest-priority
/// driver flavor compiled into this binary.
pub fn default_config_content() -> String {
    let driver_block = match driver_ffi::default_flavor() {
        #[cfg(feature = "driver-portable")]
        Some(Flavor::Portable) => PORTABLE_DRIVER_BLOCK,
        #[cfg(feature = "driver-cuda")]
        Some(Flavor::Cuda) => CUDA_DRIVER_BLOCK,
        Some(Flavor::Dummy) => DUMMY_DRIVER_BLOCK,
        // default_flavor always returns Some because dummy is linked
        // unconditionally. Keep this fallback for exhaustiveness.
        None => DUMMY_DRIVER_BLOCK,
    };
    format!("{COMMON_PREFIX}\n{driver_block}{COMMON_SUFFIX}")
}

const COMMON_PREFIX: &str = r#"# Generated by `pie config init`. Edit freely.

[server]
host = "127.0.0.1"
port = 8080
verbose = false
registry = "https://registry.pie-project.org/"
python_snapshot = true
# max_concurrent_processes = 64           # global cap on in-flight inferlets

[auth]
enabled = false

[telemetry]
enabled = false
endpoint = "http://localhost:4317"
service_name = "pie"

[runtime]
# Tokio + wasmtime tuning. Defaults are pinned by pie (decoupled from
# upstream wasmtime changes); edit any value to override.
wasm_max_instances = 1000
wasm_max_memory_mb = 4096
wasm_warm_memory_mb = 0
wasm_warm_slots = 100

# Filesystem. allow_fs = true mounts a per-process /scratch dir with full RW.
allow_fs = false

# Network. `network_allowed_hosts` filters wasi:sockets only — wasi:http
# bypasses the per-socket hook (its host stack does its own DNS). Set
# allow_network = false for tight outbound HTTP control.
allow_network = true
network_allowed_hosts = ["*"]

# Uploads
max_upload_mb = 256

[[model]]
name = "default"
hf_repo = "Qwen/Qwen3-0.6B"

[model.scheduler]
batch_policy = "adaptive"
request_timeout_secs = 120
default_endowment_pages = 64
admission_oversubscription_factor = 4.0
restore_pause_at_utilization = 0.85
"#;

#[cfg(feature = "driver-portable")]
const PORTABLE_DRIVER_BLOCK: &str = r#"
[model.driver]
type = "portable"
device = ["auto"]

[model.driver.options]
max_batch_tokens = 10240
max_batch_size = 512
"#;

#[cfg(feature = "driver-cuda")]
const CUDA_DRIVER_BLOCK: &str = r#"
[model.driver]
type = "cuda_native"
device = ["cuda:0"]
tensor_parallel_size = 1
activation_dtype = "bfloat16"

[model.driver.options]
gpu_mem_utilization = 0.85
max_batch_tokens = 10240
max_batch_size = 512
"#;

const DUMMY_DRIVER_BLOCK: &str = r#"
[model.driver]
type = "dummy"
device = ["cpu"]
activation_dtype = "bfloat16"

[model.driver.options]
vocab_size = 151936
arch_name = "qwen3"
"#;

const COMMON_SUFFIX: &str = r#"
# To add a second model, append another [[model]] block with a unique
# name and a non-overlapping device list. The first [[model]] is the
# implicit default for inferlets that don't specify a model name.
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_config_is_parseable() {
        let content = default_config_content();
        let cfg: crate::config::Config = toml::from_str(&content).unwrap();
        cfg.validate().unwrap();
    }
}
