package pie:inferlet;

world imports {
    include pie:core/imports;
    include pie:mcp/imports;
    include pie:zo/imports;
}

world inferlet {
    include pie:core/imports;
    include pie:mcp/imports;
    include pie:zo/imports;
    export pie:core/run;
}