use crate::shared::vocabulary::{Member, Vocab};

pub const VOCAB: Vocab = Vocab(&[
    Member::same("model.layers.{layer}.input_layernorm"),
    Member::same("model.layers.{layer}.linear_attn.A_log"),
    Member::same("model.layers.{layer}.linear_attn.conv1d"),
    Member::same("model.layers.{layer}.linear_attn.dt_bias"),
    Member::same("model.layers.{layer}.linear_attn.in_proj_a"),
    Member::same("model.layers.{layer}.linear_attn.in_proj_b"),
    Member::same("model.layers.{layer}.linear_attn.in_proj_qkv"),
    Member::same("model.layers.{layer}.linear_attn.in_proj_z"),
    Member::same("model.layers.{layer}.linear_attn.norm"),
    Member::same("model.layers.{layer}.linear_attn.out_proj"),
    Member::same("model.layers.{layer}.mlp.down_proj"),
    Member::same("model.layers.{layer}.mlp.experts.{expert}.down_proj"),
    Member::same("model.layers.{layer}.mlp.experts.{expert}.gate_proj"),
    Member::same("model.layers.{layer}.mlp.gate"),
    Member::same("model.layers.{layer}.mlp.gate_proj"),
    Member::same("model.layers.{layer}.mlp.shared_expert.gate_proj"),
    Member::same("model.layers.{layer}.mlp.switch_mlp.down_proj"),
    Member::same("model.layers.{layer}.mlp.switch_mlp.gate_proj"),
    Member::same("model.layers.{layer}.mlp.up_proj"),
    Member::same("model.layers.{layer}.post_attention_layernorm"),
    Member::same("model.layers.{layer}.self_attn.k_norm"),
    Member::same("model.layers.{layer}.self_attn.k_proj"),
    Member::same("model.layers.{layer}.self_attn.o_proj"),
    Member::same("model.layers.{layer}.self_attn.q_norm"),
    Member::same("model.layers.{layer}.self_attn.q_proj"),
    Member::same("model.layers.{layer}.self_attn.v_proj"),
    Member::same("model.embed_tokens"),
    Member::same("lm_head"),
    Member::same("model.norm"),
]);
