use std::ffi::CString;

/// One header, and the name an `#include` spells to reach it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Header {
    /// What `#include "…"` must say, relative to `csrc/src`.
    pub name: &'static str,
    /// The text, carried in the binary by [`include_str!`].
    pub text: &'static str,
}

/// The headers `csrc/` holds, generated by walking it.
mod carried {
    include!(concat!(env!("OUT_DIR"), "/carried.rs"));
}

pub use carried::{LIBRARY, SHIM, UPSTREAM};

/// What every compile in this crate resolves an `#include` against, unless the
const SHIMMED: [Header; SHIM.len() + LIBRARY.len()] =
    join::<{ SHIM.len() + LIBRARY.len() }>(SHIM, LIBRARY);

/// See [`SHIMMED`].
pub const DEVICE_HEADERS: &[Header] = &SHIMMED;

/// [`DEVICE_HEADERS`] plus [`UPSTREAM`] — what a unit compiling upstream
pub const ALL_HEADERS: &[Header] =
    &join::<{ SHIM.len() + LIBRARY.len() + UPSTREAM.len() }>(&SHIMMED, UPSTREAM);

/// `[T] ++ [U] -> [T; N]` at compile time.
const fn join<const N: usize>(left: &[Header], right: &[Header]) -> [Header; N] {
    let mut out = [Header { name: "", text: "" }; N];
    let mut w = 0;
    let mut i = 0;
    while i < left.len() {
        out[w] = left[i];
        w += 1;
        i += 1;
    }
    let mut j = 0;
    while j < right.len() {
        out[w] = right[j];
        w += 1;
        j += 1;
    }
    out
}

/// The compilable unit sources, carried the same way their headers are.
pub mod roots {
    /// `norm`'s six AltUp auxiliary templates.
    pub const NORM_ALTUP_AUX: &str = include_str!("../csrc/src/norm/altup_aux.cuh");
    /// `norm`'s pointwise pair: `residual_add` and `scalar_mul`.
    pub const NORM_ELEMENTWISE: &str = include_str!("../csrc/src/norm/elementwise.cuh");
}

/// The header set as the two parallel arrays `nvrtcCreateProgram` wants,
pub fn as_nvrtc_arrays(headers: &[Header]) -> Result<(Vec<CString>, Vec<CString>), String> {
    let mut texts = Vec::with_capacity(headers.len());
    let mut names = Vec::with_capacity(headers.len());
    for header in headers {
        texts.push(
            CString::new(header.text)
                .map_err(|_| format!("header `{}` contains a NUL", header.name))?,
        );
        names.push(
            CString::new(header.name)
                .map_err(|_| format!("header name `{}` contains a NUL", header.name))?,
        );
    }
    Ok((texts, names))
}

/// Every carried header reachable from `root`, or the first `#include` the set
pub fn reachable(from: &str, root: &str, headers: &[Header]) -> Result<Vec<&'static str>, String> {
    let mut seen: Vec<&'static str> = Vec::new();
    let mut queue: Vec<(&str, &str)> = vec![(from, root)];
    while let Some((at, text)) = queue.pop() {
        for included in quoted_includes(text) {
            let Some(header) = headers.iter().find(|h| h.name == included) else {
                return Err(format!(
                    "`{from}` reaches `{included}` from `{at}`, and the header set it \
                     compiles against does not carry it -- NVRTC resolves against the \
                     set and nothing else, so this compiles nowhere"
                ));
            };
            if !seen.contains(&header.name) {
                seen.push(header.name);
                queue.push((header.name, header.text));
            }
        }
    }
    Ok(seen)
}

/// FNV-1a 64 over every header's name and text, in table order.
#[must_use]
pub fn digest(headers: &[Header]) -> u64 {
    let mut hash = FNV_OFFSET_BASIS;
    for header in headers {
        hash = fold(hash, header.name.as_bytes());
        hash = fold(hash, &[0]);
        hash = fold(hash, header.text.as_bytes());
        hash = fold(hash, &[0]);
    }
    hash
}

/// Every quoted `#include` in `source`, in order of appearance.
#[must_use]
pub fn quoted_includes(source: &str) -> Vec<&str> {
    source
        .lines()
        .filter_map(|line| {
            let rest = line.strip_prefix("#include")?;
            let rest = rest.strip_prefix(|c: char| c == ' ' || c == '\t')?;
            rest.trim_start().strip_prefix('"')?.split('"').next()
        })
        .collect()
}

/// FNV-1a 64 over bytes, the fold [`digest`] is built out of.
pub(crate) fn fnv1a64(bytes: &[u8]) -> u64 {
    fold(FNV_OFFSET_BASIS, bytes)
}

/// The algorithm's offset basis, and the same one
const FNV_OFFSET_BASIS: u64 = 0xcbf2_9ce4_8422_2325;

/// The algorithm's prime.
const FNV_PRIME: u64 = 0x0000_0100_0000_01b3;

/// One more chunk into a running FNV-1a, so a digest over several fields is
fn fold(mut hash: u64, bytes: &[u8]) -> u64 {
    for byte in bytes {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(FNV_PRIME);
    }
    hash
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::jit::Headers;

    /// The set a unit chooses decides what resolves — checked with a header
    #[test]
    fn a_units_header_choice_decides_what_resolves() {
        let upstream = UPSTREAM
            .iter()
            .find(|v| !Headers::Library.set().iter().any(|l| l.name == v.name))
            .expect("the upstream closure carries a header the library does not");
        let root = format!("#include \"{}\"\n", upstream.name);

        let refused = reachable("a/unit", &root, Headers::Library.set())
            .expect_err("the library set does not carry an upstream header");
        assert!(refused.contains(upstream.name), "a refusal names the include: {refused}");

        let resolved = reachable("a/unit", &root, Headers::LibraryAndUpstream.set())
            .expect("the upstream set carries it");
        assert!(resolved.contains(&upstream.name), "and reports what it reached: {resolved:?}");
    }

    /// Reachability is transitive and reports the header it came THROUGH,
    #[test]
    fn an_include_two_headers_deep_is_reached_and_blamed_precisely() {
        let carried = [
            Header { name: "one.cuh", text: "#include \"two.cuh\"\n" },
            Header { name: "two.cuh", text: "#include \"three.cuh\"\n" },
        ];
        let root = "#include \"one.cuh\"\n";

        let why = reachable("a/unit", root, &carried).expect_err("`three.cuh` is not carried");
        assert!(why.contains("`three.cuh`"), "the include that is missing: {why}");
        assert!(why.contains("from `two.cuh`"), "and the header that reaches it: {why}");
        assert!(why.contains("`a/unit`"), "and the unit that would not compile: {why}");

        let full = [carried[0], carried[1], Header { name: "three.cuh", text: "" }];
        assert_eq!(
            reachable("a/unit", root, &full).expect("all three are carried"),
            ["one.cuh", "two.cuh", "three.cuh"]
        );
    }

    /// Every header `csrc/` carries is self-consistent.
    #[test]
    fn every_device_include_resolves() {
        for header in ALL_HEADERS {
            for included in quoted_includes(header.text) {
                assert!(
                    ALL_HEADERS.iter().any(|h| h.name == included),
                    "`{}` includes `{included}`, which the set does not carry",
                    header.name
                );
            }
        }
    }

    /// The set is what a compile is keyed on, so two different sets must not
    #[test]
    fn the_digest_moves_when_any_header_does() {
        let base = digest(DEVICE_HEADERS);
        assert_eq!(base, digest(DEVICE_HEADERS), "and is stable");

        let edited = [Header { name: DEVICE_HEADERS[0].name, text: "// not what it was" }];
        assert_ne!(base, digest(&edited), "text is in the key");

        let renamed = [Header { name: "norm/somewhere_else.cuh", text: DEVICE_HEADERS[0].text }];
        assert_ne!(base, digest(&renamed), "and so is the name it resolves by");

        let split = [Header { name: "a", text: "bc" }, Header { name: "d", text: "e" }];
        let joined = [Header { name: "ab", text: "c" }, Header { name: "d", text: "e" }];
        assert_ne!(digest(&split), digest(&joined));
    }

    #[test]
    fn only_column_zero_quoted_includes_are_directives() {
        let source = "\
#include \"a.cuh\"
  #include \"indented.cuh\"
#include <cuda_bf16.h>
const char* s = \"#include \\\"in_a_string.cuh\\\"\";
#include\t\"tabbed.cuh\"
";
        assert_eq!(quoted_includes(source), vec!["a.cuh", "tabbed.cuh"]);
    }

    /// The arrays handed to NVRTC are the table, in order and complete.
    #[test]
    fn the_nvrtc_arrays_are_the_table() {
        let (texts, names) = as_nvrtc_arrays(DEVICE_HEADERS).expect("no NULs in a source");
        assert_eq!(texts.len(), DEVICE_HEADERS.len());
        assert_eq!(names.len(), DEVICE_HEADERS.len());
        for (at, header) in DEVICE_HEADERS.iter().enumerate() {
            assert_eq!(names[at].to_str().unwrap(), header.name);
            assert_eq!(texts[at].to_str().unwrap(), header.text);
        }
    }
}
